decred/dcrd

txscript/stack_test.go
Remove three tests that exist twice in stack_test.go.
=> Remove duplicate stack tests

dcrjson/dcrdextresults.go, dcrjson/dcrwalletextresults.go, rpcserver.go, rpcserverhelp.go
Instead just return field value in rpc handler
Fixes #33
=> Remove rpc cmd Results that only have 1 field

chaincfg/params.go, cmd/findcheckpoint/findcheckpoint.go
=> Add initial checkpoint.

rpcserver.go
The key to the templatePool map is now MerkleRoot + StakeRoot
together to avoid possible false hits within the map using just the
MerkleRoot.
=> Change templatePool map to be map[[64]byte] instead of [32]byte

rpcserver.go
=> Add getstakeinfo to rpcAskWallet list to return proper error

rpcserverhelp.go
=> Fix some missing rpc help.

dcrjson/walletsvrresults.go, wire/bench_test.go, wire/common.go, wire/common_test.go, wire/internal_test.go, wire/msgalert.go, wire/msgreject.go, wire/msgversion.go
This is required for decred/dcrwallet#65
=> Cherry pick commits required for wallet sync.

cmd/dcrctl/version.go, version.go
Bump the version for the patched release.
=> Bump version for release

blockchain/stake/staketx.go, chainindexer.go, mempool.go
Ticket commitments to a future address were ignored under the
old code. Now they are deserialized from their pkScripts and
stored in the address index of the database. This corrects some
wallet syncing behaviour where usage of addresses failed to
be determined with existsaddress. This has been tested for
correctness with several simnet blockchains.
=> Add lookup of ticket commitments to addrindex

blockchain/stake/ticketdb.go, rpcserverhelp.go
Correct a comment.
Add help text for getticketpoolvalue.
=> Fix minor goclean issues.

dcrjson/dcrwalletextcmds.go
Add commands for new wallet balancetomaintain
=> Add balancetomaintain rpc json parts

.travis.yml
Update go versions used.
Run go install before go clean.
=> Get travis-ci to work again.

rpcserver.go, rpcserverhelp.go
=> Clean up and fix fallthrough on invalid tx types for getrawmempool rpc request

mempool.go
Plucked from this commit in btcd:
https://github.com/btcsuite/btcd/commit/489ba8d31d2c54ec2e1043396bc0e844c6253844
Also fix a bad switch case for testnet.
=> Pull in policy.go changes from btcd to fix issues with fee calc in dcrd

config.go, dcrd.go
Enable the option to change the directory for dcrd.
Example: dcrd -D /dir/dcrd
=> Updated config to allow the ability to change the home directory

doc.go, docs/README.md, docs/configure_peer_server_listen_interfaces.md, docs/configure_rpc_server_listen_interfaces.md, docs/configuring_tor.md, docs/json_rpc_api.md
This pull request only touches documentation files.
This addresses issue #115.
=> Fix rpclisten and listen port references in documentation

mempool.go
The old variables in the memory pool would incorrectly
eliminate transactions send over sendrawtransaction that
had high fees while also always rejecting high priority
transactions. The minimum relay rate has been raised
while the cutoff threshold has been lowered, allow low
fee (1/4 normal fee), high priority transactions.
=> Fix mempool fees variables

mempool.go, policy.go, policy_test.go
=> Cherry pick btcd commit that moves some functions to policy.go

blockmanager.go
A bug could cause the failure to create a template from parent
if a cached block template had a vote spending the same ticket
with a different vote hash as compared to the recently added
block. Now votes are checked by the tickets they spend rather
than the vote hashes.
Fixes #142.
=> Check for hidden votes by ticket hash, not vote hash

database/db.go, database/ldb/operational_test.go, database/ldb/tx.go, database/memdb/memdb.go, docs/json_rpc_api.md, goclean.sh, rpcserver.go
Merge commit removes some changes made by the following commits since they don't apply to Decred:
* e6d5c163d5634a9d4dd2de67ab3c4e46fd3cd1ad
=> Sync upstream through Sep 17, 2015.

txscript/scriptnum_test.go
Upstream commit ce22159fb239f7706253a40d9af24ee045296210.
=>  txscript: Sync upstream makeScriptNum tests.

blockchain/chain.go, blockchain/common_test.go, blockchain/difficulty_test.go, blockchain/example_test.go, blockchain/scriptval.go, blockchain/validate.go, blockmanager.go, cmd/addblock/import.go, cmd/findcheckpoint/findcheckpoint.go, config.go, doc.go, mempool.go, mining.go, sample-dcrd.conf, server.go, txscript/engine.go, txscript/engine_test.go, txscript/example_test.go, txscript/opcode.go, txscript/opcode_test.go, txscript/reference_test.go, txscript/sigcache.go, txscript/sigcache_test.go, txscript/sign_test.go
Upstream commit 0029905d43589ea74d11dd574a92bf45e297e949
=> Integrate a valid ECDSA signature cache.

dcrjson/chainsvrresults.go
Upstream commit f8625369299eda626ea1bab68eeb9e40ad8e04d2
=> dcrjson: Add errors to InfoChainResult

chaincfg/chainhash/hash.go, goclean.sh, rpcserver.go, server.go, wire/common.go
Upstream commit 5a9bac9668e83478005c5273ee432e53e49175f7
=> Correct a few style related issues found by golint.

peer/peer.go
Upstream commits:
- 4a397d51d4e25d0fcf445bb9621fd78528ee863c
- 5c50db535711890e61267dd5147c1fb24a87a5d6
=> peer: Sync upstream fixes and improvements.

mempool.go, policy.go
**NOTE: Most of this commit was already previously cherry-picked**
Upstream commit 3d6afcffe7b758fcb7f65e1ef593c9cbca50f7ab.
=> Move non-mempool specific functions to new file.

peer/peer.go
In case of an error during protocol negotiation in handleVersionMsg,
immediately break out and prevent further processing of OnVersion
listener which generally depends upon peer attributes like NA to be set
during the negotiation. Fixes #579.
=> peer: fix panic due to err in handleVersionMsg

peer/mruinvmap.go, peer/mruinvmap_test.go, peer/peer.go
Upstream commit 1217e00d3977fc655d6db5fba3d2cffc3e65b5ab.
=> peer: Unexport the mru inventory map.

mempool.go, mining.go, policy.go, rpcserver.go
- f41ff545be905bd658084772a5826f4d091f1e2d
- This commit has already been cherry-picked so it is a NOOP
- 8ab565ce21a3b87dd6a24cc37fd45c40bd4af679
=> mempool/mining: Decouple and optimize priority calcs.

cpuminer.go, mempool.go, mining.go, mining/README.md, mining/mining.go, mining/policy.go, rpcserver.go, server.go
Upstream commit ce981f45c26c060048c8bc042fe19b934d12bf37.
=> mining: Create skeleton package.

dcrjson/chainsvrcmds_test.go, txscript/reference_test.go
- 3c2c85888846d405c189b6575a578ea9d8d072d8
- c7e6c1e88f74bb399233f573476d80e964165aee
=> dcrjson/txscript: Merge arm-specific test updates.

dcrjson/chainsvrcmds_test.go, rpcserver.go, txscript/reference_test.go
Upstream commit 16582789c31780d4d5a1b282c2dc6a52aedf41b8.
=> rpcserver: Optimize filteraddr code.

peer/peer.go, server.go, wire/doc.go, wire/message.go, wire/msgsendheaders.go, wire/msgsendheaders_test.go, wire/msgversion.go, wire/protocol.go
Upstream commit ae00fff14ac58b189daa90b74029a1477249f258.
=> wire: Implement sendheaders command

peer/doc.go, peer/example_test.go, peer/peer.go, peer/peer_test.go, server.go, wire/doc.go, wire/message.go, wire/msgsendheaders.go, wire/msgsendheaders_test.go, wire/msgversion.go, wire/protocol.go
Upstream commit 73d353247c2e3ccff1fbe725bdc3580450ea12ac.
=> peer: Consolidate several public methods.

chaincfg/genesis_test.go, chaincfg/params.go, chaincfg/params_test.go
Upstream commit 1d83cd5721fb27457724796b7738bfcc06aa1c54.
=> chaincfg: Consolidate tests into the chaincfg pkg.

txscript/engine.go
Upstream commit 5ff5fc5fa21e9d92a68dd888dbdc7d1eddf26cf7.
=> txscript: Correct comments on alt stack methods.

dcrjson/chainsvrresults.go, rpcserver.go
=> Change Vin field AmountIn to display coins not int64

cmd/dcrctl/config.go, cmd/dcrctl/httpclient.go, config.go
Also, error on an invalid rpc certificate.
Fixes #200
=> Quit when the specified configuration is file not found.

blockchain/stake/doc.go, doc.go, mining/doc.go
=> docs:  Add/update doc.go in a few spots

cmd/dcrctl/terminal.go
=> dcrctl: Clear terminal history

cmd/dcrctl/terminal.go
=> dcrctl: Remove help fallthrough so help will get passed to RPC

README.md
=> docs: Major update to home README

rpcserver.go
=> rpcserver: Account for block votes in coin supply

cmd/dcrctl/terminal.go
=> dcrctl: fix reading from stdin in terminal mode

chaincfg/params.go
=> add another mainnet checkpoint, add initial testnet checkpoints

chaincfg/params.go
=> add more checkpoints for upcoming release

dcrd.go
This is a backport of PR #333  for the release-0.4.0 branch.
=> Backport #333

chaincfg/params.go
=> add more checkpoints for upcoming release (#329)

cmd/dcrctl/config.go
=> Do not error if dcrctl can't find dcrd.conf.

chaincfg/params.go
=> add another checkpoint for mainnet and testnet

mining_test.go
Syncs to btcd commit e15d3008cfd59756db9570da9e47da6831313196.
432ad76 is a NOOP because it was previously cherry-picked in.
=> Merge in btcd commit e15d3008cfd59756db9570da9e47da6831313196

txscript/script.go
Merges in 644570487f379e9856ae4025181ecc6293d86711 from btcd.
=> Merge in btcd commit 644570487f379e9856ae4025181ecc6293d86711

blockchain/chain.go, blockchain/chainio.go
Merges in btcd commit de4fb243899fc988cb3f320bbec9bee95966691b.
=> Merge in btcd commit de4fb243899fc988cb3f320bbec9bee95966691b

wire/bench_test.go
Merges in btcd commit e7ddaa468e5a699a9c21136e3d453ce38034b98a.
=> Merge in btcd commit e7ddaa468e5a699a9c21136e3d453ce38034b98a

wire/bench_test.go
Merges in btcd commit b14032487f67ac140606e7b5f4cd4781243c62c7
=> Merge in btcd commit b14032487f67ac140606e7b5f4cd4781243c62c7

blockmanager.go, server.go
Merges in btcd commit 1b234102147901738bb79b2edf2d803225a36d57.
=> Merge in btcd commit 1b234102147901738bb79b2edf2d803225a36d57

cmd/addblock/addblock.go, cmd/addblock/config.go, cmd/addblock/import.go
Merges in btcd commit dc83f4ee6a127038dc0238600bdc745d239cf8b1.  Adds existsaddress index support to addblock as well.
=> Merge in btcd commit dc83f4ee6a127038dc0238600bdc745d239cf8b1

wire/common.go, wire/msgtx.go, wire/netaddress.go
Merges in btcd commit f68cd7422dd5d0e0d6002647305c1fd663aee77d.
=> Merge in btcd commit f68cd7422dd5d0e0d6002647305c1fd663aee77d

wire/blockheader.go, wire/common.go, wire/msgversion.go, wire/netaddress.go
Merges in btcd commit 5de5b7354ca458d6e7677d6b4629214d3f871b59.
=> Merge in btcd commit 5de5b7354ca458d6e7677d6b4629214d3f871b59

wire/msgaddr.go, wire/msggetblocks.go, wire/msggetdata.go, wire/msggetheaders.go, wire/msgheaders.go, wire/msginv.go, wire/msgmerkleblock.go, wire/msgnotfound.go, wire/msgtx.go
Merges in btcd commit 2adfb3b56acd280e84451e94dd0c06203eef9832.
=> Merge in btcd commit 2adfb3b56acd280e84451e94dd0c06203eef9832

cmd/dcrctl/config.go, config.go, dcrd.go, service_windows.go
=> Reconcile btcd and dcrd auto generated config file semantics

blockchain/error.go
=> Remove unused ErrBIP0030

chaincfg/params.go
=> add more checkpoints for release

glide.lock
=> Update dcr* deps for 0.5.0

blockchain/stake/lottery.go
This corrects the the hash256 deterministic prng generator to properly rollover and avoid repeating values when it has been invoked more than 2^35 + 8 times.
While here, it also removes the unnecessary `seedState` struct field in favor of storing the seed as a `chainhash.Hash` directly and just updating it on rollover.
Finally, it also refactors the seed const to a package level constant to avoid generating a new byte slice (and hence extra garbage) every time a new generator is created.
It should be noted that this does not affect Decred consensus at all because it's impossible to invoke the generator more than 2^35 + 8 times due to other constraints.
=> stake: Correct prng uint32 rollover.

cmd/dcrctl/terminal.go
=> dcrctl: fix output in --terminal mode

blockchain/chain.go, rpcserver.go
Sidechain and orphan blocks were given in previous version of the
software in response to the RPC command getblock, in line with
bitcoind.  Insight relied on this functionality.  It has been
restored in 0.5.0.  Fixes #406.
=> Use correct function to fetch blocks from the blockchain for RPC

blockchain/stake/staketx.go, blockchain/stake/staketx_test.go
A voting version parsing function was added.  Vote versions are
uint32s.
=> Add voting version parsing function

cmd/dcrctl/terminal.go
=> dcrctl:  Set width to max in --terminal

glide.lock
Also includes an update to dcrrpclient
=> Update 3rd party deps in glide

rpcwebsocket.go
I misunderstood an old dcrd comment and thought that all stake
transactions were notified irrespective of whether they were actually
relevant to the wallet or not.  Fix this by only including those that
pass the tx filter for block connected notifications.  Rescanned
blocks already handled this correctly by only including the relevant
stake txs.
=> Notify only relevant stake txs, not all.

blockchain/error.go, blockchain/fullblocktests/generate.go, blockchain/validate.go, blockchain/validate_test.go
Fixes #393 
This was killing me on the inside...
=> ErrBadStakevaseScrVal -> ErrBadStakebaseScrVal

glide.lock
=> Glide update at the beginning of 0.7.0

peer/peer.go
- ff4ada0b0e1ebffa3f9c15cadc96ab0d08a11034
- This commit has already been cherry-picked so it is a NOOP
- 7de7bddba9d9a8b0b7490931e346e8f10d0bdb7f
=> peer: use atomics instead of mutexes

blockchain/chain.go, blockchain/chain_test.go, blockchain/common_test.go, blockchain/example_test.go, blockchain/fullblocks_test.go, blockchain/process.go, blockchain/reorganization_test.go, blockchain/validate_test.go, blockmanager.go, cmd/addblock/import.go
Upstream commit 00ebb9d14d7b6bcd3713e00e63b2b967bf19707c
Also, the merge commit contains the necessary decred-specific alterations.
=> blockchain: Associate time src with chain instance.

blockchain/chain.go
Upstream commit 61a15f6f1bea14cb47aa4d70dd3d38dee5e7c701.
=> blockchain: optimize HaveBlock

dcrd.go, service_windows.go, signal.go
Upstream commit 044a11c9fc4e3e8498428e1652ee061ff5c859e6.
=> dcrd: Simplify shutdown signal handling logic sync.

LICENSE
Upstream commit fb9b640ef2206a067a78fbd472729cdf1f6a6265.
=> license: add title

txscript/scriptbuilder.go, txscript/scriptbuilder_test.go, txscript/sign.go
Upstream commit cee207c64caee6b2471ab73dce0b11c8762346cb.
=> txscript: Expose AddOps on ScriptBuilder.

docs/README.md
Upstream commit 4a5223266c8f50f14dd5db53a195516d2e9f52eb.
=> docs: Add chainhash to README.md

server.go
This slightly optimizes the code which is invoked to provide the current mining state to remote peers.
First, rather than creating copies of all of the hashes into a new slice while limiting them in the `OnGetMiningState` function, just subslice the hashes to the max length when there are too many.
Second, make the slices `[]chainhash.Hash` which has better cache locality and only requires a single allocation as opposed to one per hash.
Finally, convert the `pushMiningState` function to accept `[]chainhash.Hash` slices for the block hashes and vote hashes and use the hashes directly in the slices to build the final wire message.
=> server: Optimize get mining state code.

mempool.go
Vote insertion is an internal mempool operation and thus should not be exposed to callers outside of the package.  It also had an undocumented assumption that the provided tx had already passed `stake.IsSSGen` checks which is yet another reason the function shouldn't be exposed.
=> mempool: Remove exported InsertVote function.

mempool.go, mining.go, server.go
This splits the mining-specific code that deals with sorting blocks according to the number of votes available for it in the `mempool` into `mining.go`.
This is being done for a couple of reasons:
1) Mining-specific code does not belong directly in the `mempool`
2) It is required to be able to split the `mempool` into a separate package which an upcoming upstream sync does
In order to accomplish this, a new function named `VotesForBlocks` has been exposed on the `mempool` and the `SortParentsByVotes` code has been moved to `mining.go` and modified to no longer return errors.  The reasoning for this is the same as the recent change to `VoteHashesForBlock`.  That is to say it is not the responsibility of a sorting function to dictate caller-specific block eligibility logic.
=> mempool: Decouple mining-specific logic.

dcrjson/dcrwalletextcmds.go, rpcserver.go
=> dcrjson: Add rescanwallet JSON-RPC request.

blockchain/internal_test.go, blockchain/validate_test.go
Unit tests for context free block sanity checks.
Unit test for block context for gen block.
Closes #503
=> Add unit tests.

blockchain/internal_test.go, blockchain/validate_test.go
=> Test another failing condition in validate.go

blockchain/validate_test.go
=> Fix output formatting in a unit test.

blockchain/fullblocktests/generate.go
This tweaks the full block test infrastructure to generate the PoS subsidy based upon the block being voted on as opposed to the current one so it matches the consensus rules.
=> fullblocktests: Generate subsidy for voted block.

cmd/dcrctl/version.go, version.go
=> Bump for v0.7.0

blockchain/validate.go
Hope I got this right this time. Let me know if I'm doing something else dumb.
=> Typo correction

glide.lock, glide.yaml
=> Update 3rd party deps at the start of 0.8.0 dev

chaincfg/params.go
=> add checkpoints for 0.8.0 release

glide.lock
=> Update internal glide repos for v0.8.0

chaincfg/params.go
=> Correct the units on the testnet HF description.

blockchain/thresholdstate_test.go
**This requires PR #565**
This adds a few more full block tests to more completely exercise the new threshold state voting functionality.
The following is an overview of the additional tests:
- Cast a majority old version votes that have the same votebits set as those defined in the new version votes in order to ensure the agenda does not incorrectly succeed
- Create a voting period such that there is a majority vote, but quorum is NOT reached and ensure the agenda does not incorrectly succeed
- Create a voting period such that quorum is reached, but there is NOT a majority vote and ensure the agenda does not incorrectly succeed
=> blockchain: Add more fullblock voting tests.

dcrjson/dcrdresults.go, rpcserver.go, rpcserverhelp.go
#568 was committed prior to code review.
=> Fix nits on getstakeversioninfo

blockchain/chaingen/generator.go
The original test generation live ticket pool code was written quickly and _extremely_ inefficiently since it was only intended for a relatively small number of blocks. However, it has proven a useful tool for much longer test chains even though it was incredibly slow to generate them.
As a result, this significantly speeds up generation by replacing the code related to generating the live ticket pool to a more complex version that only handles the changes required by each block along with handling reorgs caused by calling `SetTip` and using cached transaction hashes throughout.
Prior to this commit, the threshold state tests were taking over 10 minutes and they now take 8 seconds on a the same machine.
=> chaingen: Significantly optimize test generation.

blockchain/chaingen/generator.go, blockchain/fullblocksstakeversion_test.go, blockchain/thresholdstate_test.go
**This requires PR #587**
Now that the chaingen code has been optimized, don't skip the fullblock tests when in the short testing mode.
=> blockchain: Always run fullblock tests.

blockchain/chain.go, blockchain/stakeversion.go, blockchain/stakeversion_test.go
The functions that are used to keep stake version and vote versions humming along are relatively expensive due to repeated chain walks. This commit removes the most egregious sinners by memoizing the answer. It should be noted that we can not memoize the walk to the prior interval because that would require one to memoize all blocks up to the prior interval.  This is in practice not a big issue because relatively new `blockNodes` are in memory.  The real savings happen when a block does not need to be loaded from disk.
Here are some figures from a quad core Xeon 2.66GHz:
> stakeversion_test.go:930: running: shallow no cache with 20160 nodes
> stakeversion_test.go:1000:   run time (setup 0) 712.273µs
> stakeversion_test.go:1000:   run time (run 1) 576.898µs
> stakeversion_test.go:1000: …
=> blockchain: Optimize stake and vote lookups.

chainindexer.go, glide.lock, glide.yaml, rpcwebsocket.go, txscript/opcode.go
=> Switch to upstream golang.org/x/crypto

blockchain/chain.go, chaincfg/genesis.go, chaincfg/params.go, chaincfg/premine.go, config.go, params.go, wire/protocol.go
This adds a new testnet2 network with new genesis block, premine address, magic number, etc.
Corrected some testnet related comments while there.
=> Testnet reset

chaincfg/params.go
=> fix StakeBaseSigScript and a comment

cmd/dcrctl/config.go
dcrctl does not require dcrd so it should not keep complaining about
it missing.
Fixes #619
=> dcrctl: Be smarter about automatic configuration.

config.go
Closes #626 
Once we are happy with this I'll do a similar one for dcrwallet.
=> Add warning on startup about old testnet data.

addrmgr/addrmanager.go, addrmgr/addrmanager_test.go, addrmgr/knownaddress_test.go, addrmgr/network_test.go, connmgr/seed.go, peer/peer.go, server.go, wire/netaddress.go
wire: Treat NetAddress more like immutable
addrmgr: Remove unused param from GetAddress()
addrmgr: Fix AddressCache to not include nils which resulted in a panic
=> addrmgr/wire: various fixes from btcd

chaincfg/params.go
=> chaincfg: update checkpoints for 1.0.0 release

mempool/mempool.go
The minimum ticket fee is now handled the same as for all other
transactions and it as well as the relative maximum high fee threshold
can be changed using the application config.
=> mempool: Remove the hardcoded minimum ticket fee.

peer/peer.go, server.go, wire/msgversion.go, wire/protocol.go
=> Bump Protocol Version

config.go, rpcwebsocket.go
=> Concurrently handle websocket client JSON-RPC requests.

dcrjson/dcrwalletextcmds.go, dcrjson/dcrwalletextresults.go, glide.lock, rpcserver.go
This RPC was removed from wallet.
Closes #687.
=> dcrjson: Remove accountfetchaddresses support.

blockmanager.go
=> blockmanager: Fix new tickets notification.

dcrjson/chainsvrcmds.go, dcrjson/chainsvrcmds_test.go, dcrjson/chainsvrresults.go, rpcserver.go, rpcserverhelp.go
=> dcrjson:  getblocksubsidy support.

blockchain/accept.go, blockchain/chain.go, blockchain/chainio.go, blockchain/difficulty_test.go, blockchain/internal_test.go, blockchain/stakeversion_test.go, blockchain/validate.go, blockchain/validate_test.go, blockchain/votebits_test.go
newBlockNode can produce it itself from the passed blockheader.
=> blockchain: drop hash param from newBlockNode()

mempool/mempool.go
Upstream commit a109bea3f17c496a7622bca4e81f2c33015976ce.
The merge commit also contains necessary Decred-specific alterations for other uses of the mutex and reduces a bit of defer usage while here since future upstream commits do the same for other instances.
=> mempool: unexport the mutex

mempool/policy.go
Upstream commit 2ef82e7db35dc8c499fa9091d768dc99bbaff893.
---
This changes the transaction input standardness checks as follows:
- Allow any script in a pay-to-script-hash transaction to be relayed and mined so long as it has no more than 15 signature operations
- Remove the obsolete checks which naively calculated the number of expected inputs in favor of the more accurate `ScriptVerifyCleanStack` and `ScriptVerifySigPushOnly` functionality of the script engine that was added after these checks.
=> mempool: Improve tx input standard checks.

blockchain/chain_test.go, blockchain/chaingen/generator.go, blockchain/subsidy.go, blockchain/validate_test.go, config.go, glide.lock, glide.yaml, mining.go, rpcserver.go, rpcwebsocket.go, txscript/example_test.go
~~NOTE: This PR contains a temporary glide redirect to https://github.com/dnldd/dcrrpcclient/tree/decodeaddress and dnldd/dcrutil@58e046a. This will need to be removed before merging~~
Also, updates the `glide.lock` file to reference the new required dependency versions.
=> Replace DecodeNetworkAddress with DecodeAddress

blocklogger.go
=> blocklogger: Show votes, tickets, & revocations.

dcrjson/chainsvrwscmds.go, dcrjson/chainsvrwscmds_test.go, dcrjson/dcrwalletextcmds.go, dcrjson/dcrwalletextcmds_test.go
thanks to @davecgh for contributing
=> dcrjson: move cmd types

rpcserverhelp.go
=> rpcserverhelp: update TicketFeeInfo help.

chaincfg/params.go
=> chaincfg: update checkpoints for 1.0.7 release

config.go
=> config: Improve blockmaxsize check.

blocklogger.go
Also update order of log from:
transactions, votes, tickets, revokes 
to:
transactions, tickets, votes, revokes
=> Remove STransactions from transactions calculation in logging

blockchain/stake/lottery.go
=> blockchain: cast to int64.

mining_test.go
Fixes #114
thanks to @davecgh for his guidance and edge conditions dataset.
=> mining_test: add edge conditions from btcd.

blockchain/chain_test.go, blockchain/reorganization_test.go, blockchain/validate_test.go
Rather than redefining the `simnet` parameters in the tests, just use the existing `chaincfg` simnet parameters.  Since some of the tests rely on`the modified legacy version, introduce a clone function for the params and simply override the parameters that are different.
This is far preferable to redefining them which is cumbersome to update when the `chaincfg` params add new definitions.
=> blockchain: Modify tests to use chaincfg params.

chaincfg/params.go
=> chaincfg: update checkpoints for 1.1.0 release

peer/peer_test.go
Fixes #857.
Thanks to @davecgh  for the patch and education.
=> peer: fix logic race in peer connection test.

rpcserver.go
These functions are used by the `getrawtransaction` and `searchrawtransactions` RPCs.
Only Vin[0] was being set for stakebase/ssgen transactions in the vin lists created by `createVinList` and `createVinListPrevOut`.  Fix this to allow Vin[1] to be set too.
Also fix the `Stakebase` field of `dcrjson.VinPrevOut` and `dcrjson.Vin` being set incorrectly set to the zero hash instead of the actual hex-encoded signature script of the txin.
Addresses issue https://github.com/decred/dcrd/issues/870
=> rpcserver: fix empty ssgen verbose results

config.go, dcrd.go, doc.go, log.go
=> config: add --nofilelogging option.

Gopkg.lock, bloom/README.md, bloom/example_test.go, bloom/filter.go, bloom/filter_test.go, bloom/merkleblock.go, bloom/merkleblock_test.go, bloom/murmurhash3.go, bloom/murmurhash3_test.go, server.go
Use this new bloom package rather than relying on the bloom package
from the dcrutil repo.
Some minor source code changes have been made to conform to the dcrd
linter requirements.
=> Copy github.com/decred/dcrutil/bloom to bloom package.

Gopkg.lock, Gopkg.toml, rpcserver.go
... since no local changes exist.
=> Use upstream jrick/bitset

blockchain/stake/error.go, blockchain/stake/staketx.go
Needed for [dcrwallet #981](https://github.com/decred/dcrwallet/pull/981)
=> Add IsStakeSubmission

rpcclient/README.md
tiny fix for rpcclient doc to tweaks example url :)
=> rpcclient: tiny fix url for doc

dcrjson/jsonrpcerr.go, rpcserver.go
This adds ErrRPCDuplicateTx for rejected duplicate tx errors.
=> dcrjson: update handleSendRawTransaction error handling.

chaincfg/params.go
* https://mainnet.decred.org/block/000000000000007341d8ae2ea7e41f25cee00e1a70a4a3dc1cb055d14ecb2e11
* https://explorer.dcrdata.org/explorer/block/000000000000007341d8ae2ea7e41f25cee00e1a70a4a3dc1cb055d14ecb2e11
* https://testnet.decred.org/block/0000000000320a623fcc6453986ef13423f455ddf0f788ad1f2bda43858ccb8d
* https://testnet.dcrdata.org/explorer/block/0000000000320a623fcc6453986ef13423f455ddf0f788ad1f2bda43858ccb8d
=> chaincfg: update checkpoints for 1.1.2 release

rpcserver.go
=> rpcserver: skip cert create when RPC is disabled

rpcserver.go
the block size checks,sigops checks and recalculations in
blockTemplateResult were redundant, NewBlockTemplate performs the checks
needed and should be able get the calculations correct without needing
recalculations.
Fixes #495
thanks to @davecgh for his guidance.
=> rpcserver: remove redundant checks in blockTemplateResult.

dcrjson/README.md
Update docs of the where abouts of rpcclient
=> dcrjson: Update README.md.

blockchain/chain.go, blockchain/chainio.go, blockchain/compress.go, blockchain/difficulty.go, blockchain/stakenode.go, blockchain/subsidy.go, blockchain/utxoviewpoint.go
This modifies all files in the `blockchain` package so that function definitions are on the a single line as is the style used in the upstream code as well as throughout its code base.  This helps minimize the differences between them and the upstream code in order to facilitate easier syncs due to less merge conflicts as a result of superfluous changes.
=> blockchain: Make func definition style consistent.

blockchain/stake/lottery.go
This adds initialization vector support to `Hash256PRNG` which is used for determining winning tickets.  This allows callers to cache and reuse the initialization vector for a given seed to avoid recomputation.
It accomplishes this by exporting two new functions named `CalcHash256PRNGIV` and `NewHash256PRNGFromIV` and updating the existing `NewHash256PRNG` function to use the new functions.
It also improves the comment on `NewHash256PRNG` while here.
=> stake: Add Hash256PRNG init vector support.

blockchain/blockindex_test.go
**This requires #990**.
This adds several tests for the `CalcPastMedianTime` function including when there are less than the usual number of blocks which happens near the beginning of the chain.
=> blockchain: Add median time tests.

blockchain/validate.go
This modifies the `checkBlockHeaderSanity` function to accept the header as intended so that it is only performing context-free checks.  Since checking the stake difficulty of all of the ticket purchases necessarily requires the block, that check is moved into `checkBlockSanity`.
Also, while here, improve the comments on the `{c,C}checkProofOfStake` functions.  Note that having comments on an exported function that refer to an unexported one is not very helpful since documentation generation tools don't see unexported funcs.
=> blockchain: Limit header sanity check to header.

blockchain/validate.go
This moves the test for validating the stake difficulty specified by the header matches the calculated difficulty into the `checkBlockHeaderContext` function where it more naturally belongs since it is only dependent on the header and its contextual position within the chain.
Also, while here, it updates the error message to be more consistent with existing error messages and does not incorrectly create a rule error from an internal error in the unlikely case the difficulty fails to be calculated.
=> blockchain: Validate stake diff in header context.

blockchain/validate.go
This changes the validation that the block does not exceed the maximum number of ticket purchases to make use of the value committed to by the header and thus moves the test into `checkBlockHeaderSanity` accordingly.
This is acceptable since the code also validates the header commitment for the number of ticket purchases later and therefore implies correctness.
=> blockchain: Validate max purchases in header sanity.

blockchain/validate.go
This moves the test for validating that the vote bits specified by the header are a specific value before reaching stake validation height into the `checkBlockHeaderSanity` function where it more naturally belongs since it is solely dependent on the header.
=> blockchain: Validate early votebits in header sanity.

blockchain/validate.go
**This requires PR #1012**.
This removes a duplicate check which ensures ticket purchases pay the required amount.  It is already checked by `checkProofOfStake` via `checkBlockSanity`.
=> blockchain: Remove dup ticket purchase value check.

blockchain/chaingen/generator.go, blockchain/validate.go, blockchain/validate_test.go
**This requires PRs #1017 and #1018**.
This moves the checks for validating that votes commit to the parent of the block they are contained in and the vote bits specified by the header match the result of the actual votes included in the block to the `checkBlockSanity` function where they more naturally belong since they do not require access to any previous chain context.
=> blockchain: Vote commitments in block sanity.

blockchain/validate.go
**This requires PR #1034**.
This moves the check for validating that only ticket purchases, votes, and revocations are included in the stake tree to the `checkBlockSanity` function where it more naturally belongs since it does not require access to any previous chain context.
=> blockchain: Allowed stake txns in block sanity.

sampleconfig/sampleconfig.go
=> sampleconfig: Correct comment.

blockchain/fullblocktests/generate.go
This corrects various comment issues introduced with the name refactor as well as a few block names.
=> fullblocktests: Cleanup after refactor.

blockchain/chain.go
~**This requires PR #1083 and #1084**.~ (now merged)
This modifies the `TipGeneration` function to use the new chain tip functionality in order to determine the entire generation of blocks stemming from the current tip as opposed to the children.
=> blockchain: Switch tip generation to chain tips.

blockchain/stakeversion.go
This simplifies, optimizes, and improves the robustness of the voter version calculation as follows:
- Modifies `calcVoterVersion` to make use of the `AncestorNode` function to directly iterate back to the end of the prevoius stake version interval instead of manually adjusting and calling `findStakeVersionPriorNode`.
- Adds an optimization to skip any attempts to count votes before stake validation height since there can't possibly be any votes prior to that point.
- Modifies `calcVoterVersionInterval` to explicitly assert the assumptions at the beginning of the function to prevent invalid behavior instead of only commenting them and then indirectly asserting it via the total number of found votes.
=> blockchain: Simplify voter version calculation.

blockchain/blockindex_test.go, blockchain/common_test.go
This adds code to test the chain tip tracking functionality of the block index.
=> blockchain: Add tests for chain tip tracking.

mempool/mempool.go, mining.go
This replaces the mempool `IsTxTreeValid` function with `IsTxTreeKnownInvalid` instead which more accurately describes its semantics and purpose.
The actual purpose of this function is related to mempool acceptance and building block templates for mining where the assumption is that the previous block's regular transaction tree will be valid and is only invalid specifically if there are enough known votes that vote against it.
This change is desirable because the function provides semantics that are actually opposite to that of the consensus rules where a tree is only valid if it has a majority of yes votes and thus claiming it's valid when that is not actually known for certain yet can easily cause confusion.
=> mempool/mining: Clarify tree validity semantics.

addrmgr/addrmanager.go, addrmgr/network.go, addrmgr/network_test.go
Hide functions which are only used internally.
=> addrmgr: Declutter package API.

blockchain/fullblocktests/generate.go
**This requires PR #1120**.
This adds a few basic revocation tests based on the new `chaingen` revocation infrastructure.
=> fullblocktests: Add some basic revocation tests.

cpuminer.go
This updates the `cpuminer` code for Decred to use the extra data space in the header for the extra nonce space instead of putting it in the coinbase as is required in the upstream code.
=> cpuminer: Use header for extra nonce.

addrmgr/addrmanager.go
Currently the peers file is (re-)written every ten minutes no matter what.
Keep track of changes to the address manager state and write the peers
file only if something changed.
Based on PR #1126.
=> addrmgr: Save peers file only if necessary.

cmd/dcrctl/version.go, version.go
~**Requires PR #1139**.~ (now merged)
=> release: Bump for v1.2.0.

rpcserver.go
=> rpcserver: fix jsonRPCRead data race.

addrmgr/addrmanager.go
The AddressCache() should not propagate addresses of known low quality
to its peers.
Inspired by the Bitcoin Core implementation.
=> addrmgr: Skip low quality addresses for getaddr.

addrmgr/addrmanager.go, addrmgr/addrmanager_test.go
Hide functions which are only used internally.
=> addrmgr: Simplify package API.

dcrjson/chainsvrcmds.go, dcrjson/chainsvrcmds_test.go, rpcclient/rawtransactions.go, rpcserver.go, rpcserverhelp.go
=> dcrjson: Add Expriry field to CreateRawTransactionCmd

blockchain/README.md
=> Fix typo in blockchain readme

blockchain/fullblocktests/generate.go
This PR adds the following block validation rule error tests to fullblocktests:
- `ErrImmatureSpend`
- Create block that tries to spend premine output before maturity in the regular tree.
- Create block that tries to spend premine output before maturity in the stake tree by creating a ticket purchase.
- `ErrRegTxInStakeTree`
- Create block with a malformed outputs order for a ticket purchase.
- Create block with scripts that do not involve p2pkh or p2sh addresses for a ticket purchase.
=> fullblocktests: add additional premine and malformed tests.

txscript/opcode.go
**This builds on top of PR #1205.**
This cleans up the code for handling the substr opcode to explicitly call out its semantics which are likely not otherwise obvious as well as improve its readability.
=> txscript: Cleanup code for the substr opcode.

peer/peer.go
This rearranges some of the function definitions that pertain to initial peer version negotiation and bringup so they are more consistent with the preferred order used throughout the codebase.  In particular, the functions are defined before they're first used and generally as close as possible to the first use when they're defined in the same file.
There are no functional changes.
=> peer: Minor function definition order cleanup.

server.go
This modifies the `OnGetAddr` handler to prevent the server from responding to `getaddr` messages more than once per connection which helps reduce unhelpful traffic and fingerprinting attacks.
=> server: Only respond to getaddr once per conn.

blockchain/chaingen/README.md, blockchain/stake/internal/tickettreap/README.md, rpctest/README.md
* Update blockchain/chaingen/README.md
* Update blockchain/stake/internal/tickettreap/README.md
* Update rpctest/README.md
=> multi: Fix badges in README.

server.go
This modifies the `getcfheaders` handling code to use the recently refactored block locator code that is now available in `blockchain` instead of manually performing the task.
Not only is the code in chain more efficient, it also helps ensure the handling for block locators is consistent.
While here, it also modifies a few cfilter-related comments for consistency and corrects a near bug which was limiting the response to the maximum allowed block headers per message as opposed to the maximum allowed cfilter headers per message.  Since the two constants are currently the same value, there is no functional change in this regard.
=> server: Convert CF code to use new inv discovery.

txscript/error.go
This updates various comments to accurately reflect reality now that several script verification flags have been removed.
=> txscript: Update comments for removal of flags.

dcrjson/chainsvrresults.go, rpcserver.go
Also, update all callers in the repository while here.
=> dcrjson: Make linter happy by renaming Id to ID.

cmd/dcrctl/version.go, version.go
**This PR is rebased on PR #1387.**
=> release: Bump for v1.3.0.

mempool/mempool.go
=> mempool: Correct min relay tx fee comment to DCR.

Gopkg.lock, Gopkg.toml, gcs/gcs.go, gcs/go.mod, gcs/go.sum, go.mod, go.sum
=> gcs: use dchest/siphash

.travis.yml, certgen/certgen.go, rpcserver.go, run_tests.sh, wire/msgheaders_test.go
Also, apply some minor formatting updates as required by the go 1.11 `fmt -s` flag.
=> TravisCI: Update for Go1.11 and module builds.

mining.go, rpcserver.go
this updates the function signatures of `minimumMedianTime` and `medianAdjustedTime` and removes all `chainState` usage in `rpcserver.go` in favour of using `BestState`. 
Port of upstream commit 2274d36 (subset). In preparation of the removal of `chainState`.
=> multi: remove chainState dependency in rpcserver.

mining.go
**This PR requires #1417.**
Port of upstream commit 2274d36 (subset). In preparation of the removal of `chainState`.
=> mining: remove chainState dependency.

blockchain/agendas_test.go
This modifies the test code which deals with testing feature deployments to clone the parameters and modify them such that the deployment being tested never expires.
=> blockchain: Avoid deployment expiration in tests.

mempool/mempool.go
This does some minor cleanup of the code in the `maybeAcceptTransaction` function to use some local bools with more easily readable names for dealing with stake transactions.
It also improves the readability of the double spending exceptions section and avoids some additional if statements.
=> mempool: Stake-related readability improvements.

blockmanager.go
Clients are able to choose between two modes of notification about new blocks via the wire protocol.  The first, and current default, is via inv messages and the second is via direct header announcements.
There is code in the peer package which deals with filtering duplicate inventory announcements via the `QueueInventory` message.  This works as expected for inv-based announcements, however, direct header announcements are not inv messages and hence do not use that code path.
Consequently, the recent addition of the fast relay path which relied on that filtering to avoid sending duplicate announcements resulted in duplicate announcements being sent to peers who requested the header announcements mode.
This resolves the issue by adding some logic directly to the notifications themselves …
=> blockmanager: Avoid duplicate header announcements.

blockchain/validate.go
This simplifies the `CheckConnectBlockTemplate` by making use of the fact that a template may only build off the current tip or the parent of the current tip in order to remove the reorganization detach loop and all code to attach nodes.
This can be done because there can never be any blocks that need to be attached given the aforementioned constraints, and the only two possibilities for the blocks that need to be detached are none in the case the the template is building on the current tip, or the current tip itself in the case the template is building on its parent.
In other words, there will always be 0 nodes to attach and either 0 or 1 node(s) to detach.  Consequently, it is not necessary to include any attach code nor have a detach loop.
=> blockchain: Simplify block template checking.

rpcserver.go
This fixes verify progress calculation for getblockchaininfo.
=> rpcserver: Fix verify progress calculation.

rpcserver.go
=> rpcserver: Fix sendrawtransaction error code.

blockchain/chain.go
This modifies the `forceHeadReorganization` function to remove checks that are now duplicates due to the recently updated conversion of the reorganization logic.
Also, correct the exported comment while here to explain what the function does as opposed to referring to an unexported function that won't show up in the generated documentation.
=> blockchain: Simplify force head reorgs.

rpcserver.go
This simplifies solved block reconstruction by removing the pkScript reassignment and regeneration of the merkle root.
=> rpcserver: update block template reconstruction.

blockchain/validate_test.go
This modifies the legacy sequence lock test code to be more consistent with more recently added tests and pave the way for more easily refactoring out some of the common test logic.
- Use less generic names for the deployment variables and constants to make it more clear precisely which agenda is being activated
- Use the version defined by the constant instead of hard coding it
- Introduce a munge function to replace the block, stake, and vote versions of the test blocks to the appropriate versions
- Update all manual version replacements to use the new munge func
- Update the comments to refer to the agenda instead of the specific version it happens to be for the given network params
=> blockchain: Consistent legacy seq lock tests.

blockchain/validate_test.go
**This requires #1583 and is rebased on top of #1585.**
This refactors the check block template tests in blockchain to use the recently introduced `chaingen` harness.
=> blockchain: Use harness in checkblktemplate tests.

blockchain/common_test.go, blockchain/validate_test.go
**This requires #1583 and is rebased on top of #1587.**
This refactors the legacy sequence lock tests in blockchain to use the recently introduced `chaingen` harness.
In order to simplify the process of activating an agenda which these (and other) tests requires, a new function named `AdvanceFromSVHToActiveAgenda` is also introduced on the `chaingen` harness which, as its names suggests, generates and accepts enough blocks with the appropriate vote bits set to reach one block prior to the specified agenda becoming active.
=> blockchain: Use harness in legacy seqlock tests.

mempool/mempool_test.go
This modifies `CreateVote` in the `mempool` test harness to accept munge functions similar to how `CreateSignedTx`  works.  This allows the test code to more easily mutate the transactions as desired prior to them being signed which provides greater flexibility.
While here, it also sets the block that is being voted on to the current best chain tip of the harness.  While there is not currently anything in the tests that relies on that behavior, it will allow future tests to more easily create votes which involve the block being voted on.
=> mempool: Accept test mungers for vote tx.

mempool/mempool.go, mempool/mempool_test.go
**This requires #1595 and #1596.**
Currently, the memory pool policy is to allow votes which double spend the same ticket (up to a maximum amount) since it is possible that the same ticket is selected in competing branches and thus the double spend must be allowed and will resolve itself depending on which chain is ultimately extended.
A side effect of that is that it also currently accepts votes with different hashes but otherwise both spend the same ticket and vote on the same block.  This can happen when there are multiple wallets casting the vote with different settings such as when one has been upgraded to a new stake version while the others have not or an improperly configured wallet where the vote choices have been set on one, but not the others.
Consequently, this modifies the …
=> mempool: Reject same block vote double spends.

txscript/engine.go, txscript/opcode.go, txscript/scriptbuilder.go, txscript/sighash.go, txscript/sign.go, txscript/sign_test.go, txscript/stack.go, txscript/standard.go
- switch if-else to switch/case for readability
- remove unused params
=> txscript: code cleanup

rpcserver.go, rpcserverhelp.go, rpcwebsocket.go
This updates the code related to the RPC server to use version 2 of the `dcrjson` module.
=> rpcserver: Update for dcrjson/v2.

blockmanager.go
This saves two additional calls to chain.IsCurrent().
=> blockmanager: only check if current once handling inv's

rpcclient/chain.go
This adds the EstimateSmartFee command to the rpc client, so that the
corresponding remote function can be reached.
We'll probably need to discuss whether this should be available only on v2 of the rpcclient module or if we'll wanna backport into a v1 branch.
=> rpcclient: Add EstimateSmartFee

connmgr/connmanager.go, connmgr/connmanager_test.go
This allows package users to use a dial function that receives the full
address structure instead of just the protocol family and address as
strings.
This is required for some use cases in ln. While in btcsuite this was
implemented by changing the function signature of the Dial config
option, this is done here as an extra config option to prevent having to
perform a major version bump in the connmgr module.
=> connmngr: Add DialAddr config option

dcrutil/tx_test.go
This adds tests for NewTxDeep to make sure new MsgTx is deeply copied.
=> dcrutil: Add tests for NewTxDeep.

server.go
=> server: return on outbound peer creation error

config.go
This simplifies and cleans up the initial network information parsing which was recently added in PR #1514 by replacing the networks map and all of the unnecessary error handling that introduced with concrete supported network definitions and directly updating their fields accordingly.
It also avoids a bunch of unnecessary conditional branching by setting the flags to the results of the conditions directly.
Finally, it corrects the logic for determining if interface is limited since that is currently only the case when the other interface has no available listeners.
=> config: Cleanup and simplify network info parsing.

dcrd.go, service_windows.go
The way that shutdown is handled was modified long ago, but it appears that the windows service code was not updated fully for the changes.  In particular, the server instance is no longer used by the service at all. Rather the only information needed is the parsed configuration in order to log the start of day details.
Consequently, this reworks the windows service start of day code to read a buffered channel that receives the parsed configuration instead of the server and modifies the `dcrdMain` function to no longer require the channel to be specified in order to simplify it for eventual context handling.
=> main: Rework windows service sod notification.

cpuminer.go
This modifies the CPU miner to make the speed monitor optional by making use of non-blocking sends to its update channel and then changes GenerateNBlocks, which is used specifically for mining a discrete number of blocks for testing purposes, to avoid launching it.
=> cpuminer: No speed monitor on discrete mining.

rpctest/votingwallet.go
This allows rpctest users to set a custom mining function for the voting
walles. Externally, this will be used to provide a simnet mining
function that generates blocks without triggering a difficulty increase.
=> rpctest: Allow custom miner on voting wallet

docs/README.md, docs/assets/module_hierarchy.gv, docs/assets/module_hierarchy.svg
This updates the `docs/README.md` file, module hierarchy graphviz, and module hierarchy diagram to reflect the new module version.
=> docs: Update for dcrec/edwards v2 module.

blockchain/fullblocktests/generate.go
This adds two new consensus tests to the full block tests for the coinbase nulldata height commitment.  The first new test ensures coinbase transactions with the wrong script version are rejected and the second test ensures data pushes that exceed the maximum allowed number of bytes for the coinbase nulldata push are rejected.
=> fullblocktests: Add coinbase nulldata tests.

blockmanager.go, mining.go, rpcserver.go, rpcwebsocket.go, server.go
This is a port of  [btcd #979](https://github.com/btcsuite/btcd/pull/979/commits/b71d6c30103ce9ad04c4c610f288eb0ad1c2afb7).
=> multi: decouple BlockManager from server. 

chaincfg/params.go
This defines several new functions on the `Params` struct which return some subsidy-related parameters.
The new functions are:
- `BaseSubsidyValue`
- `SubsidyReductionMultiplier`
- `SubsidyReductionDivisor`
- `SubsidyReductionIntervalBlocks`
- `WorkSubsidyProportion`
- `StakeSubsidyProportion`
- `TreasurySubsidyProportion`
This will allow the parameters to be used directly as input to an interface in the future.
=> chaincfg: Add subsidy params accessor funcs.

txscript/data/script_tests.json
Full test suite ran successfully.
=> txscript: Fix typo in script test data.

gcs/gcs.go, gcs/gcs_test.go
This ensures filters properly match search items which happen to hash to zero and adds a test for the condition.  While here, it also rewrites the `MatchAny` function to make it easier to reason about.
This was discovered by the new tests which intentionally added tests with a high false positive rate and random keys.
=> gcs: Correct zero hash filter matches.

gcs/gcs.go, gcs/gcs_test.go
**This is rebased on top of #1853.**
This modifies the code to support an independent false positive rate and Golomb coding bin size.  Among other things, this permits more optimal parameters for minimizing the filter size to be specified.
This capability will be used in the upcoming version 2 filters that will ultimately be included in header commitments.
For a concrete example, the current version 1 filter for block 89341 on mainnet contains 2470 items resulting in a full serialized size of `6,669 bytes`.  In contrast, if the optimal parameters were specified as described by the comments in this commit, with no other changes to the items included in the filter, that same filter would be `6,505 bytes`, which is a size reduction of about `2.46%`.  This might not seem like a significant …
=> gcs: Support independent fp rate and bin size.

blockchain/chainio.go
This refactors the best chain state and block index loading code into separate functions so they are available to upcoming database update code to build version 2 gcs filters.
=> blockchain: Refactor best chain state init.

rpcwebsocket.go
When a transaction is checked for relevance to a websocket client with
a loaded transaction filter, a call to ExtractPkScriptAddrs is not
enough.  Commitments in tickets are encoded in an OP_RETURN output
which require an additional parse of the script to check for a
committed P2PKH or P2SH HASH160.
=> rpcserver: Match tx filter on ticket commitments

blockmanager.go, mining.go
This removes all of the code related to setting and updating cached templates in the block manager since they are no longer used.
It is easy to see this is the case by considering that the only places that set `cachedCurrentTemplate` and `cachedParentTemplate` set them to nil.
=> mining: Remove dead code.

mining.go
This combines the two conditions for the aggressive mining path into a single condition and does a bit of light cleanup to remove the template copies that are no longer necessary due to the removal of the old style template caching.
=> mining: Minor cleanup of aggressive mining path.

mining.go
use a local prng variable
Fixes #1895.
=> mining: fix data race

cpuminer.go
=> cpuminer: fix race.

connmgr/tor.go
=> connmgr: support resolving ipv6 hosts over Tor

mempool/mempool_test.go, txscript/example_test.go, txscript/sign.go, txscript/sign_test.go
=> txscript: Add signature type to KeyClosure API

dcrd.go, server.go
This modifies the lifecycle of the server to use the expected pattern for running subsystems based on contexts in the future.
In particular, this renames the `Start` function to `Run` and arranges for it to block until the provided context is cancelled.  This is more flexible for the caller since it can easily turn blocking code into async code while the reverse is not true.
The new `Run` function ensures the server waits for all goroutines that it starts to shutdown before shutting down itself to help ensure an orderly shutdown.
Finally, this removes the `WaitForShutdown` function from `server` since it is no longer needed.
=> server: Convert lifecycle to context.

blockchain/stakeext.go, dcrd.go
This removes some obsolete todos.
=> multi: resolve todos.

rpcclient/infrastructure.go
This adds periodic pinging to the rpc client to keep the established connection alive.
Closes #1878
=> rpcclient: add automatic pinging.

blockchain/chainio_test.go, blockchain/chainview_test.go, blockchain/scriptval.go, blockchain/sequencelock_test.go, blockchain/stakeversion.go, blockchain/stakeversion_test.go, blockchain/thresholdstate.go, blockchain/validate.go
while here, remove whitespace and replace an always true
comparison
=> blockchain: removed unused params

server.go
This fixes a bug introduced by #1838 where the peer state was not getting updated on a successful
connection because a network address suggestion was not provided.
=> server: Fix peer state update.

rpcserver.go
This gives us logs for debugging possible ping/pong issues.
=> rpcserver: add ping and pong handers.

blockmanager.go
This simplifies the code that updates the latest known block height for peer based on blocks received from them to use the fact the height is in the header.  The previous code was originally from upstream where the height was not available in the header.
=> blockmanager: Simplify dynamic peer height updates.

config.go
Replace deprecated TorLookupIP with TorLookupIPContext
=> config: Use TorLookupIPContext.

dcrutil/wif.go
This adds a PrivKey method to dcrutil.WIF which returns the serialized
private key.
While here and before a stable release of dcrutil/v3 has been tagged,
the method SerializePubKey is renamed to simply PubKey.
SerializePubKey was not an accurate method name, as it described an
action performed rather than the data returned, and this
implementation was returning already-serialized bytes.
A mention in a doc comment to the unexported field ecType (which is
probably a find & replace artifact) is removed.  Because the WIF might
be for a key that is not ECDSA (e.g. ed25519 or schnorr keys), the
ecType field is renamed to scheme.
Fixes #2077.
=> dcrutil: Provide privkey access for WIFs

dcrec/secp256k1/signature.go
**This requires #2072**.
This modifies the signature verification function use the new `ModNScalar` type instead of big ints.
This is work towards eventually using the new more efficient mod n scalar throughout.
The following benchmark shows a before and after comparison of typical signature verification:
```
benchmark            old ns/op    new ns/op    delta
------------------------------------------------------
BenchmarkSigVerify   219346       180815       -17.57%
benchmark            old allocs   new allocs   delta
------------------------------------------------------
BenchmarkSigVerify   57           36           -36.84%
benchmark            old bytes    new bytes    delta
------------------------------------------------------
BenchmarkSigVerify   2818         1697         -39.78% …
```
=> secp256k1: Optimize sig verify with mod n scalar.

dcrec/secp256k1/schnorr/ecdsa.go
This modifies the instances in the `schnorr` package that zero out big ints that use a function to clear the internal memory used by the big int since merely setting it to 0 does not do that.
Spotted by @JoeGruffins while reviewing #2063.
=> schnorr: Zero internal bytes of big ints.

mempool/mempool.go
The `MaybeAcceptDependents` function was added as a part of the logic to track tickets with non-approved inputs separately in a staging pool in PR #1852.  Given it modifies the contents of the `mempool`, it needs to hold a write mutex as opposed to a read mutex as otherwise it can modify the `mempool` out from under readers.
While here, comment the required locking semantics on the other functions that were added as a part of the staging logic as well.
=> mempool: Correct MaybeAcceptDependents mutex.

dcrec/secp256k1/signature.go
This modifies signature verification to perform the final equality check in Jacobian projective space to avoid an extra expensive field inversion by taking advantage of the fact the R component of the signature can be converted to Jacobian projective space and compared directly so long as the two possible cases that arise from R being mod N and the original x coordinate used to create it being mod P.
The following is a before and after comparison of verification of a typical signature:
```
benchmark            old ns/op    new ns/op    delta
-----------------------------------------------------
BenchmarkSigVerify   189505       177147       -6.52%
benchmark            old allocs   new allocs   delta
-----------------------------------------------------
BenchmarkSigVerify   34           34 …
```
=> secp256k1: Avoid inversion in sig verify.

.github/workflows/go.yml, blockchain/stake/staketx.go, blockchain/subsidy.go, dcrec/edwards/threshold.go, dcrec/secp256k1/schnorr/signature.go, rpcserver.go, rpcwebsocket.go
build: bump golangci-lint to 1.24.0
=> multi: remove superfluous fmt.Sprintf

dcrec/secp256k1/schnorr/signature.go, dcrec/secp256k1/schnorr/signature_test.go
**This requires #2150**.
This modifies the signature verification function use the `ModNScalar` and `FieldVal` types instead of big ints.
This is work towards eventually using the specialized types throughout.
The following benchmark shows a before and after comparison of typical signature verification:
```
benchmark            old ns/op    new ns/op    delta
------------------------------------------------------
BenchmarkSigVerify   203206       182142       -10.37%
benchmark            old allocs   new allocs   delta
------------------------------------------------------
BenchmarkSigVerify   45           21           -53.33%
benchmark            old bytes    new bytes    delta
------------------------------------------------------
BenchmarkSigVerify   2066         1041         -49.61% …
```
=> schnorr: Optimize sig verify with specialized types.

hdkeychain/extendedkey.go
**This requires #2156**.
This optimizes the various internal implementations that make use of `secp2561` to use the specialized `ModNScalar` and `JacobianPoint` types instead of `big.Int`s.
The following benchmarks show a before and after comparison:
```
benchmark                 old ns/op     new ns/op   delta
-----------------------------------------------------------
BenchmarkDeriveHardened   3702          3547        -4.19%
BenchmarkDeriveNormal     4053          3587        -11.50%
BenchmarkPrivToPub        94.7          94.0        -0.74%
BenchmarkDeserialize      5825          5797        -0.48%
BenchmarkSerialize        9509          9402        -1.13%
benchmark                 old allocs   new allocs   delta
----------------------------------------------------------- …
```
=> hdkeychain: Use specialized secp256k1 types.

dcrec/secp256k1/ecdsa/signature.go
**This requires #2154  and is rebased on #2158**.
This updates the code to use the recently-added `PutBytesUnchecked` of the `FieldVal` and `ModNScalar` types to serialize directly into larger buffers where possible to avoid the need for additional copies.
=> ecdsa: Use PutBytesUnchecked for serialize.

dcrec/secp256k1/README.md, dcrec/secp256k1/doc.go
**This is rebased on #2165**.
This updates the `README.md` and `doc.go` files to reflect reality after all of the latest changes.
=> secp256k1: Update README.md and doc.go.

README.md
This updates the primary `README.md` for the most recent versions of Go, minimum recommended requirements, and to reflect reality for the latest version of the test script.
=> docs: Update README.md to reflect reality.

connmgr/connmanager_test.go
**This is rebased on  #2188**.
This adds a couple of a tests to the connection manager related to timeout via the configuration option and contexts.
The first test ensures the `Connect` produces the expected results when provided with a context that times out before a dial attempt succeeds.
The second test ensures the dial timeout configuration option works as intended.
=> connmgr: Add timeout tests.

server.go
This bans peers, mostly non-whitelisted peers, for not conforming to the wire protocol.
Work towards #350
=> server: ban peers on wire protocol errors.

connmgr/connmanager.go, connmgr/connmanager_test.go, server.go
**This requires #2192**.
This modifies the lifecycle of the connection manager to use the expected pattern for running subsystems based on contexts.
In particular, this replaces the `Start`, `Stop`, and `Wait` methods with a single method named `Run` and arranges for it to block until the provided context is cancelled.  This is more flexible for the caller since it can easily turn blocking code into async code while the reverse is not true.
The new `Run` method waits for all goroutines that it starts to shutdown before returning to help ensure an orderly shutdown.
Since there are exported methods that send messages to the connection handler goroutine via a channel and that goroutine is stopped during the shutdown process, all sends select across both the channel in question as well as a …
=> connmgr: Convert lifecycle to context.

server.go
This modifies the various aspects that deal with making nodes discoverable and making outbound connections to disable them when running in regression network test mode in the same way it is done for the simulation network test mode.
=> server: Actively prevent regnet network discovery.

rpcclient/chain.go
These methods were accidentally removed from the client type when the
dcrwallet method support was removed from the package.  However, dcrd
also implements verifymessage and a less-featureful version of the
validateaddress method, so the client ought to provide direct support
for these.
Compared to the earlier version of this the validateaddress methods,
these reintroduced methods use dcrd's defined type rather than
depending on the dcrwallet definition.
=> rpcclient: Resurrect validateaddress/verifymessage

rpcserverhandlers_test.go
=> rpcserver: Add handleDecodeScript test.

rpcserverhandlers_test.go
Fixes https://github.com/decred/dcrd/issues/2245
As described in the issue, dropping `s.cfg.Chain.BestSnapshot()` in a handler will cause the associated test to panic in the case that test is not already providing a `mockChain`. This change resolves this, though the test _may_ still need to be updated if the newly added logic in the handler ultimately impacts the output of the handler.
=> rpcserver: Add default configs for tests.

txscript/bench_test.go, txscript/consensus.go, txscript/consensus_test.go, txscript/error.go, txscript/error_test.go, txscript/opcode.go
This removes code that was deprecated since the major version has been bumped since the last release.
=> txscript: Remove deprecated code.

txscript/consensus_test.go
This reworks the tests for `CheckSignatureEncoding` to test for the explicit reason for the failure to ensure that each test is actually
testing the intended condition and be more consistent with the more recent tests.
It also adds a few more tests for some corner cases where signatures will ultimately fail validation due to ECDSA requirements, but are still valid encodings from the standpoint of preventing malleability.
=> txscript: Rework check signature encoding test.

txscript/consensus_test.go
This reworks the tests for `CheckPubKeyEncoding` to test for the explicit reason for the failure to ensure that each test is actually testing the intended condition and be more consistent with the more recent tests.
It also adds several more tests to better ensure proper behavior and includes a couple of corner cases where public keys will ultimately fail validation due to not being on the curve, but are still valid encodings from the standpoint of preventing malleability.
=> txscript: Rework check pubkey encoding test.

rpcclient/infrastructure.go
This modifies the various places the websocket connection is accessed to protect it with a mutex so that it can't race in reconnect scenarios.
While here, it also makes the retry count local to the only goroutine it is accessed from.
Fixes #2259.
=> rpcclient: Protect websocket connection with mutex.

dcrd.go
This modifies the main startup logic to make use of the fact that the server now has its lifecycle tied to the same context that is cancelled when a shutdown signal is received.
The end result is that the separate goroutine it was running in before and associated synchronization logic is no longer necessary.
=> main: Simplify startup logic slightly.

internal/rpcserver/interface.go, internal/rpcserver/rpcserver.go, internal/rpcserver/rpcserverhandlers_test.go, rpcadaptors.go, server.go
This adds the sanity checker interface and update the function signature of `CheckBlockSanity`. Associated tests and mocks updated/added.
=> multi: add SanityChecker interface.

internal/rpcserver/interface.go, internal/rpcserver/rpcserver.go
This adds the rpcserver.CPUMiner interface to facilitate cpu miner related rpc tests.
Work towards #2069 .
=> multi: add rpcserver.CPUMiner. 

connmgr/connmanager_test.go
This modifies the dial timeout test to make use of a channel for the cancellation signal synchronization instead of a sleep to prevent false positive test failures in slower environments such as CI servers.
=> connmgr: Improve dial timeout test synchronization.

docs/json_rpc_api.mediawiki, internal/rpcserver/rpcserverhelp.go, rpcclient/notify.go
This adds documentation for the following ws notifications:
- notifywinningtickets
- notifyspentandmissedtickets
- notifynewtickets
- notifystakedifficulty
Closes https://github.com/decred/dcrd/issues/2295
=> docs: Document additional ws notifications.

config.go, doc.go, server.go
This categorizes the various configuration options in the code to improve readability.
It also updates the doc.go CLI options reference to reflect reality.
=> config: Categorize options in the code.

internal/rpcserver/rpcserverhandlers_test.go
This adds rpc tests for `setgenerate` and `regentemplate`.
=> rpcserver: add setgenerate & regentemplate tests.

peer/README.md, peer/doc.go
=> peer: Update README.md/doc.go to reflect reality.

.github/workflows/go.yml
Update golangci-linter to 1.30.0
=> build: test against go 1.15

rpc/jsonrpc/types/chainsvrcmds.go, rpcclient/extensions.go
Correcting some comment issues, noticed whilst reviewing #2170
=> multi: Fix incorrect RPC comments

connmgr/seed.go
This imposes a limit on the response size from the http seeder such that each returned entry is allowed to have max size of 256 bytes.  Since there is also a limit of 16 entries per response, it amounts to a max overall response size of 4KiB.
=> connmgr: Enforce max http seeder response size.

blockmanager.go, log.go, server.go
This is a backport of #2253 to the 1.5 release branch.
=> [release-v1.5] blockmanager: handle notfound messages and limits.

server.go
This modifies the code that was fairly recently added to ban peers sending messages that do not conform to the wire protocol to only apply when they are not whitelisted.
=> server: Check whitelist before ban on read errs.

README.md
=> docs: Update README CLI suite link to ref latest.

server.go
**This requires #2362**.
This consolidates the logic for handling the disable banning flag as well as whitelisted peers into the `BanPeer` function on the server and updates all of the direct banning from the callbacks accordingly.
This consolidation will help prevent the possibility of banning without properly checking those flags.
=> server: Consolidate ban disable/whitelist logic.

internal/rpcserver/treasury_test.go, rpctest/votingwallet.go
**This is rebased on top of #2351**
_This is part of the treasury decentralization work._
This adds assertions to the existing treasury rpctest to verify that
treasury base transactions have the correct value even when the block
containing them has less than the maximum allowed of vote (SSGen)
transactions.
In order to perform such test, we add the ability for the rpctest's VotingWallet to limit the total number of votes issued for some block.
Note that due to the limited implementation of the existing VotingWallet code, tests making use of this new feature need to be done last for some given rpctest harness, since the chain won't be able to be advanced indefinitely.
This work isn't strictly consensus-related and thus has been extracted from the main treasury PR to ease review by external …
=> multi: Verify treasurybase values in treasury rpctest

blockchain/common_test.go
This adds `AdvanceToHeight` to the `chaingen` harness to allow advancing the chain to an arbitrary height while controlling the number of tickets purchased per block after the first coinbase maturity.
NOTE: This PR was originally intended to add a chain continuity check, but it was modified to only introduce the aforementioned logic in favor of #2398.
=> blockchain: Add chaingen harness AdvanceToHeight.

docs/simnet_environment.mediawiki
This updates the simnet environment documentation for the changes that prevent creating block templates for blocks that would lead to ticket exhaustion.
=> docs: Update simnet env docs for ticket exhaustion.

cmd/gencerts/gencerts.go
This implements a complete rewrite of the gencerts tool, making the
tool suitable not only for generating server certificates, but client
keypairs as well.  The following functionality is added:
* Local hostnames and interfaces are not automatically included in the
certificate.  This allows clients to generate certificates which do
not leak their network interfaces to remote servers.
* The certificate and key names must be explicitly provided on the
command line after all flags.  This allows clients to generate
keypairs with names like "client.pem" and "client.pem.key", rather
than the tool only generating files named "rpc.cert" and "rpc.key".
* The key algorithm may be specified to be any of P-256, P-384, P-521,
or Ed25519.  The default algorithm is P-521, matching the previous
gencerts …
=> gencerts: Rewrite for additional use cases

go.mod, go.sum
This updates all code in the main module to use the latest module versions to pull in the latest updates.
=> main: Update to use all new module versions.

internal/rpcserver/rpcserverhandlers_test.go
This adds test coverage for `handleGetTreasuryBalance`.
```
go test -run="TestHandleGetTreasuryBalance" -coverprofile=cov.out &&
go tool cover -func=cov.out | grep -E "handleGetTreasuryBalance"
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:3080:		handleGetTreasuryBalance	100.0%
```
Part of https://github.com/decred/dcrd/issues/2069.
=> rpcserver: Add handleGetTreasuryBalance tests.

internal/rpcserver/rpcserver.go, internal/rpcserver/rpcserverhandlers_test.go
Work towards #2069 
rpcserver: Add handleGetGenerate and handleGetHashesPerSec tests.
=> rpcserver: Add handleGetGenerate and handleGetHashesPerSec tests.

peer/log.go, peer/peer.go, peer/peer_test.go
- add periods at the end of sentences.
- add missing human-readable InvTypeFilteredBlock conversion
- formatting fixes
=> peer: various cleanups

blockchain/chainio.go, blockchain/upgrade.go
This modifies the database upgrade code in blockchain to properly create the buckets needed to house the decentralized treasury information.
It is done in a such a way that it will correct any upgrades that have already taken place before this code is active.
=> blockchain: Create treasury buckets during upgrade.

internal/rpcserver/rpcserverhandlers_test.go
This adds rpc tests for `ticketsforaddress`.
=> rpcserver: add ticketsforaddress tests.

internal/rpcserver/rpcserverhandlers_test.go
This adds rpc tests for `handleTxFeeInfo`.
=> rpcserver: add handleTxFeeInfo tests.

internal/rpcserver/rpcserverhelp.go
This is a backport of #2452 to the 1.6 release branch.
=> [release-v1.6] rpcserver: Update getrawmempool txtype help.

internal/rpcserver/rpcserverhandlers_test.go
This adds rpc tests for `handleVerifyMessage`.
=> rpcserver: add handleVerifyMessage tests.

internal/rpcserver/interface.go, internal/rpcserver/rpcserver.go, internal/rpcserver/rpcserverhandlers_test.go
**depends on #2405**
This adds rpc tests for `handleSendRawTransaction`.
=> rpcserver: add handleSendRawTransaction tests.

internal/rpcserver/rpcserver.go, internal/rpcserver/rpcserverhandlers_test.go
This adds rpc tests for `handleGetVoteInfo`.
=> rpcserver: add handleGetVoteInfo tests.

blockchain/process.go
The sanity functions, as their comments indicate, are supposed to be context free since they are used on blocks and transactions regardless of their position within the chain.
Unfortunately, the decentralized treasury work ignored that and introduced context to them.  The only current side effect is that blocks created with the new rules, which are naturally orphans to syncing nodes which do not yet have all of those parents, fail the sanity checks which results in stalling the sync process until timeouts occur.
Ultimately all of those context dependent checks need to be moved into the appropriate functions, because future work also depends on those requirements.
However, since that is a non-trivial task, because each one has to be fully examined to ensure there are no later checks which …
=> blockchain: No context dep checks for orphans.

cmd/gencerts/gencerts.go
This commit adds the ability to generate certificates signed by a
local CA cert and key.  The -C and -K flags are used to provide the
filepaths to the certificate and key files, respectively.
For simplicity and security, the issued certificate is not able to act
as an intermediate certificate, and thus cannot sign other
certificates to trust.  More advanced usage is still possible using
external tooling (e.g. openssl), but is not provided by gencerts.
Acting as your own Certificate Authority can reduce configuration
complexity by allowing each of your clients to only trust a single CA
certificate that you control, rather than juggling many different
autogenerated certificates for every different server.
=> gencerts: Add certificate authority capabilities

internal/rpcserver/rpcserver.go, internal/rpcserver/rpcserverhandlers_test.go
This adds rpc tests for `handleGetRawTransaction`.
=> rpcserver: add handleGetRawTransaction tests.

blockchain/stake/lottery.go
This updates ticket lottery errors generated by `findTicketIdxs` to provide more detail.
=> stake: update ticket lottery errors.

internal/netsync/manager.go
This modifies the logic that deals with determining if the sync manager believes the chain is current (aka fully synced) to ensure some edge conditions are handled properly.
For example, it will now update the state after processing each block instead of only after processing a block along with any orphans that it caused to no longer be orphans.
It also now potentially updates the status on every call to the `IsCurrent` in order to ensure it is updated properly for callbacks during block processing.
=> netsync: Improve is current detection.

chaincfg/doc.go
This updates doc.go to remove information that no longer applies and hasn't for quite some time.
=> chaincfg: Update doc.go.

internal/netsync/manager.go, server.go
**This is rebased on #2542**.
This moves the proactive signature cache eviction from the sync manager to the server to more cleanly separate the responsibilities of the server from the sync manager.  The server controls the lifecycle of the signature cache and also now handles notifications from the blockchain when blocks are connected, so the eviction more naturally fits there.
It also removes the `SigCache` entry from the sync manager `Config` struct since it is no longer needed.
=> netsync: Move proactive sigcache evict to server.

internal/rpcserver/interface.go, internal/rpcserver/rpcserver.go, internal/rpcserver/rpcserverhandlers_test.go, internal/rpcserver/rpcserverhelp.go, internal/rpcserver/rpcserverhelp_test.go, internal/rpcserver/rpcwebsocket.go
This adds rpc tests for `handleStop`, `handleHelp`, `handleGetStakeDifficulty` and `handleVersion`.
=> rpcserver: add handleVersion, handleHelp rpc tests.

cmd/gencerts/gencerts.go
This is not useful for Decred in particular, but I do find it useful
for gencerts as a generic certificate/key generation tool.
=> gencerts: Add RSA support (4096 bit keys only)

chaincfg/mainnetparams.go, chaincfg/testnetparams.go
I'm moving my seeds to a new home with a less verbose name.
=> chaincfg: Update seed URL

docs/release-notes/release-notes-1.6.0.md
I'm opening this in preparation for the final release when the release candidate process is done.  I'll keep it up-to-date with any fixes that are backported to the release branch and promote it when the time comes.
=> docs: Add release notes for v1.6.0.

internal/mining/mining.go
This changes the log for head reorg failures to a debug log instead of an error log since it is actually expected to fail reorgs from time to time due to the fact mining is a race to find blocks.
It also cleans up the code slightly while here and adds an additional check to avoid additional work in the case reorgs to other tips fail and the current tip then becomes the best candidate among the eligible parents.
=> mining: No error log on expected head reorg errors.

connmgr/connmanager.go, connmgr/connmanager_test.go
**This is rebased on #2561**.
This adds a new func named `ForEachConnReq` to the connection manager which accepts a closure to call with each connection req known to the connection manager, including pending ones.
A test is also added to ensure proper functionality.
=> connmgr: Add func to iterate conn reqs.

server.go
**This requires #2562**.
This modifies the server code that handles connection requests from the RPC server to prevent duplicate pending connections to the same address (ip/port).
It makes use of the new functionality of the connection manager to iterate all connection requests which including pending requests.
Fixes #641.
Fixes #2558.
=> server: Prevent duplicate pending conns.

server.go
This modifies the server to only notify the sync manager after it has had a chance to process and potentially disconnect it and introduces an additional flag to explicitly track when the sync manager is notified or not instead of relying on the result of version negotiation in order to ensure stable ordering.
Fixes #2581.
=> server: Notify sync mgr later and track ntfn.

server.go
This removes the child context from the server `Run` method since it is no longer needed since all subsystems now support context.
=> server: Remove unneeded child context.

blockmanager.go
This modifies the vote notification logic so that wallets will no longer vote on mainnet blocks once height 534304 has been reached and the block version is prior to 8.
This change is being made to make use of the staking system to force proof-of-work miners who have had well over a month now to upgrade to the latest version so voting on the new consensus changes can commence.
=> [release-v1.6] server: Force PoW upgrade to v8.

server.go
This ports #2597 from the 1.6 release branch to the master branch so that anyone running master will use the same logic.
=> server: Force PoW upgrade to v8.

internal/rpcserver/rpcserverhandlers_test.go
```
go test -run="TestHandleInvalidateBlock" -coverprofile=cov.out && go tool cover -func=cov.out | grep -E "handleInvalidateBlock"
PASS
ok      github.com/decred/dcrd/internal/rpcserver       0.015s
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:3902:            handleInvalidateBlock           100.0%
```
=> rpcserver: Add handleInvalidateBlock test.

internal/rpcserver/rpcserverhandlers_test.go
```
$ go test -run="TestHandleReconsiderBlock" -coverprofile=cov.out && go tool cover -func=cov.out | grep -E "ReconsiderBlock"
PASS
ok      github.com/decred/dcrd/internal/rpcserver       0.021s
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:3976:            handleReconsiderBlock           100.0%
```
=> rpcserver: Add handleReconsiderBlock test.

upnp.go
Fixes #1620
This makes getOurIP return a local IP that is on the same subnet as
the serviceIP used for uPnP.  Verified getOurIP doesn't return a local
IPv6 IP when the serviceIP is IPv4.  Didn't test with IPv6 serviceIP.
Doesn't fix: "the actual attempt to port map later fails because it tries to map the default port despite me having specified a different one in the listener."
=> upnp: More accurate getOurIP.

blockchain/validate.go
This modifies `checkTransactionContext` to accept agenda flags instead of a boolean for whether or not the treasury agenda is active so it is easier to extend  for future consensus votes which would otherwise require a series of boolean parameters.
=> blockchain: Use agenda flags for tx check context.

docs/json_rpc_api.mediawiki, internal/rpcserver/rpcserver.go, internal/rpcserver/rpcserverhelp.go, rpc/jsonrpc/types/chainsvrresults.go
=> rpcserver: Add script version to gettxout.

blockchain/chain.go
This forces the UTXO cache to flush to the database when the chain just latched to current.  This ensures that the full UTXO set is always flushed to the database when the chain becomes current, which allows for fetching up-to-date UTXO set stats.
The behavior before these changes is that the UTXO cache will not be forced to flush to the database until a block is connected AFTER the chain is already latched to current.  Therefore, if you fetch UTXO stats when the chain is current but the next block has not been connected yet, the UTXO stats may not be up to date.
=> blockchain: Flush UtxoCache when latch to current.

Dockerfile.alpine
Alpine 3.10 is EOL, and 3.14 is current
(I have omitted the rest of the checklist because I'm not touching any Go code)
=> contrib: Bump Dockerfile.alpine to alpine:3.14.0.

blockchain/stake/tickets.go, blockchain/stake/tickets_test.go
This adds an `ExpiringNextBlock` method on the `Node` type, which returns the tickets that will expire in the next block.  This allows consumers to determine the tickets that are about to expire when validating or constructing a new block.
This will be used for the automatic ticket revocations agenda since one of the new rules for that agenda is that blocks must contain revocations for expired tickets in the block that they become expired.
=> stake: Add ExpiringNextBlock method to Node.

README.md
This adds some additional text to the section regarding why running a full node is desirable to specifically call out that it is also ideal for providing the most reliable and accurate data about transactions.
=> docs: Add accuracy and reliability to README.md.

blockchain/indexers/indexsubscriber.go
This synchronizes sends and receives for the index subscriber by selecting over the quit channel for the subscriber when calling Notify.
=> indexers: synchronize index subscriber ntfn sends/receives.

server.go
This synchronizes sends and receives for the rebroadcast inventory channel by selecting over the quit channel for the server when sending and closing it when the receiver terminates.
=> server: sync rebroadcast inv sends/receives.

internal/mempool/mempool.go
This consolidates the logic for constructing the agenda flags to use for checking transactions into a separate method versus building them inline in multiple different places.
This makes it easier to add new agendas in the future while keeping the flags consistent.
=> mempool: Consolidate tx check flag construction.

go.mod, go.sum, internal/version/version.go
=> release: Bump for 1.8 release cycle.

internal/staging/primitives/README.md
This updates the primitives module `README.md` to include the recently-added subsidy calculation capabilities.
=> primitives: Update README.md for subsidy calcs.

server.go
This modifies the various peer callbacks in server to ignore the peer parameter and only use the wrapped server peer as an accessor to ensure consistent access.
=> main: Only use server peer accessors.

dcrutil/README.md, dcrutil/txsort/README.md
Update dcrutil/v3 references to v4
=> docs: Update dcrutil/v3 references to v4.

internal/blockchain/chain.go
This resurrects the logic to remove spend journal entries when blocks are disconnected which was no longer being done since the removal of the spend pruner in #2961.
=> blockchain: Remove disconnected spend journal.

blockchain/chainio_test.go, blockchain/error.go, blockchain/upgrade_test.go, blockchain/utxoio_test.go
This is a backport of #2965 to the v4 `blockchain` release branch.
=> [blockchain-v4] blockchain: Address some linter complaints.

internal/rpcserver/rpcwebsocket.go
This modifies the logic that detects when a websocket client has been disconnected to make use of a more efficient atomic int instead of a bool gated by a mutex and uses the atomic as the condition for exiting the input handler versus relying on a less efficient non-blocking select on the quit chan.
It also avoids logging an error when the input handler fails to read a message due to the client being disconnected.  This prevents the spurious "websocket: close 1006 (abnormal closure): unexpected EOF" error messages when websocket clients disconnect.
=> rpcserver: Use atomic for ws client disconnect.

server.go
The existing logic for responding to `getheaders` is based on the old sync model before headers-first syncing was introduced and thus avoids responding whenever the current local chain is not considered to be current.  This existing behavior was important under the the old sync model since it would otherwise lead to unnecessarily downloading a bunch of blocks among other undesirable corner cases, however, it does come with some downsides.
For example, one less than ideal consequence of not responding is that it can lead to peers appearing to be unresponsive and/or stalled rather than merely not having anything interesting yet.
Also, there are a variety of corner cases where a peer might temporarily no longer consider itself current such as after being unable to communicate with the …
=> server: Always respond to getheaders.

chaincfg/README.md, chaincfg/doc.go
This updates the example in `chaincfg/doc.go` and `chaincfg/README.md` to use the latest modules.
=> docs: Update chaincfg examples.

dcrec/secp256k1/privkey.go
The `GeneratePrivateKeyFromRand` function generates a private key with entropy read from an `io.Reader` argument.  If this reader is `nil`, `crypto/rand.Reader` is used instead.
`GeneratePrivateKeyFromRand` is designed to be safer alternative to rolling one's own deterministic PrivKey creation with
`PrivKeyFromBytes`.
=> secp256k1: Add GeneratePrivateKeyFromRand function

blockchain/chaingen/generator.go
This updates the comments detailing the origin of the polynomial coefficients in the ASERT calculation to the more precise values which also matches up with the standalone code.
=> chaingen: More precise ASERT comments.

.github/workflows/go.yml
=> build: Update golangci-lint to v1.53.3.

internal/netsync/manager.go
This modifies the sync manager to immediately request new headers from all peers in the event the block associated with the best target header is rejected.  This allows alternative blocks to be downloaded more quickly without first having to wait for new blocks.
While here, it also allows a couple of blocks of leeway when returning the manager to an unsynced state.
=> netsync: Request new headers on rejected tip.

server.go
This refactors the logic for banning peers out of the peer handler so it is possible to ban peers instantly.
=> server: Make peer banning synchronous.

server.go
**This requires #3299**.
This consolidates the logging for peer banning and adds a reason parameter to help enforce consistent logging as well as make it much less likely that a peer is banned without logging why.
=> server: Consolidate ban reason logging.

mixing/mixclient/client.go
When creating the alternate session failed during a run, the wrong error was
being returned to the caller.
To simplify this logic, don't check the alternate session's error field here,
and just return the alternate session (itself implementing the error type) to
the caller (pairSessions, who calls run).
While here, some additional details are included in the wrapped error returned
when receiving KEs, which will aid in future debugging.
=> mixclient: Improve error returning

peer/log.go
This includes the message hash and the sender's identity in the short human-readable description of peer messages as they are debug logged.
While here and because mixing introduced a new inventory vector type, add it to the inv summary case statement.
=> peer: Add mix message summary strings

mixing/mixclient/client.go
The particular reasons why any peer might be blamed directly from run (rather than during full blame assignment after revealing secrets) was unclear, so include this info in the debug log.
=> mixclient: Log reasons for blaming during run

server.go
This modifies the code that parses provided p2p and rpc listen addresses to support the zone in IPv6 link local addresses.
=> server: Support listening on zoned IPv6 link local.

internal/mempool/mempool.go
If a transaction is rejected because it reference unknown previous transaction outputs and orphans are disallowed, provide the particular outpoints that are missing, not just transaction hashes.
=> mempool: Return missing prev outpoints

internal/netsync/manager.go
This refactors the code that deals with starting synchronization with the sync peer to split out the pieces specific to the initial header sync from the chain data sync.  Along the way it removes some duplicate checks that are no longer necessary.
The primary motivation is to help pave the way for eventually performing parallel block downloads, but it also has the added benefit of making the logic a bit easier to follow, so it is useful on its own.
=> netsync: Split header sync from block sync.

mixing/mixpool/mixpool.go
This allows us to remove an unnecessary log from the wallet (which was only
being done in RPC mode and missing from SPV).
=> mixpool: Debug log accepted messages

server.go
This adds logic to attempt to help maintain at least one mix capable outbound peer to ensure better connectivity among the mix capable peers.
=> server: Prefer min one mix capable outbound peer.

mixing/mixclient/client.go, mixing/mixclient/limits.go
In order to meet the standard tx size requirements on mainnet, peers who contribute too much to the coinjoin transaction size must be excluded from the current run before the pairing is finalized.  Failing to do so will only result in a transaction that fails to publish if all peers continue the mix to completion.
Exclusion is performed by iterating all current PRs in the random order determined by the set of all PRs and the current epoch.  A fake coinjoin transaction which is only meant to measure the expected tx size is added to only if that peer does not overcontribute to the size.  The random peer order is sufficient to prevent this algorithm from being gamed.
Any peers that become excluded will attempt a mix again in the following epoch.  While it could be possible, we do not …
=> mixclient: Respect standard tx size limits

mixing/mixclient/client.go
The two most recent merged pull requests merged cleanly but should have been manually rebased to avoid breaking the build.
=> mixclient: Fix build

run_tests.sh
This reworks the logic in the test run script for determining which modules to test to use the existence of a go.mod file instead of attempting to use the result of go list.
The existing logic is to determine the root module via go list and then test everything that has that as a prefix.  However, that is error prone because indirect dependencies may depend on older versions of modules that are no longer in the repo, but naturally still have the prefix that is specified to test.
Searching for the go.mod files in the repo isn't prone to the aforementioned issue and is generally more robust because it will always be recent as of the current state of the repo and it still has the benefit of dynamically finding all modules in the repo.
=> build: Rework test script to use go.mod files.

contrib/dcr_setup_go_workspace.sh
This adds the new crypto/rand module to the multimod go workspace setup script.
=> contrib: Add crypto/rand to workspace script.

server.go
The current logic attempts to maintain at least one mix capable outbound peer to ensure better connectivity among the mix capable peers.  It works as intended, however, only having a single mix capable peer means there will be delays if that peer goes offline until a replacement is found.  A possible consequence is that any mix clients might potentially get interrupted if that peer goes offline and a replacement isn't found quickly enough.
Attempting to maintain a minimum of three mix capable outbound peers will significantly reduce the likelihood of having periods without any mix capable peers.
This updates the logic accordingly.
```
[DBG] SRVR: Rejecting outbound peer <redacted> with protocol version 9 in favor of a peer with minimum version 10 (have: 0, target: 3)
...
[DBG] SRVR: …
```
=> server: Prefer 3 min mix capable outbound peers.

addrmgr/addrmanager.go, addrmgr/network.go, bech32/bech32_test.go, blockchain/stake/staketx_test.go, blockchain/stake/treasury_test.go, chaincfg/chainhash/hashfuncs_test.go, cmd/gencerts/gencerts.go, connmgr/connmanager_test.go, dcrec/edwards/ciphering.go, dcrec/edwards/ciphering_test.go, dcrjson/jsonerr.go, dcrjson/jsonrpcerr.go, dcrutil/const.go, internal/mempool/mempool.go, internal/mining/mining_harness_test.go, internal/rpcserver/rpcserver.go, internal/rpcserver/rpcwebsocket.go, internal/staging/primitives/subsidy_test.go, mixing/keyagreement.go, mixing/mixclient/limits.go, mixing/mixpool/mixpool.go, networkparams_test.go, rpcclient/chain.go, rpcclient/infrastructure.go, server.go, txscript/engine.go, txscript/scriptnum.go, txscript/stack.go, wire/msgversion.go
A few random fixes found by running some automated linters.
=> multi: Address linter comment complaints.

txscript/stdscript/error.go
=> txscript: Fix minor typo.

server.go
There is no reason that a copy of the inventory message needs to be created
when running in blocksonly mode.
While here, use a switch statement to check for tx and mix messages when we
are running in blocksonly mode.
=> server: Refactor serverPeer OnInv handler

server.go
Future changes will relay inventory to specific peers.  This is a small amount of refactoring to prepare for that change.
=> server: Make per-peer inv relay handler a server method

contrib/devtools/README.md, contrib/devtools/bump_docker.sh
=> contrib: Add script to bump docker image version.

dcrd.go
**This is rebased on #3485**.
This modifies the logic that sets the soft upper memory limit to respect the `GOMEMLIMIT` environment variable when it is set so long as it is set to a value that is higher than the calculated minimum requirement.  This allows system admins to increase the limit if they are comfortable trading off more memory for performance in their environment.  It also provides a way to resolve any potential issues related to the limit in the future should it be necessary in between releases.
=> main: Respect GOMEMLIMIT environment variable.

mixing/mixclient/client.go
An upcoming commit will change Dicemix to select on receiving the context's done channel or the peer result channel.  While this channel is buffered (cap=1), to ensure this does not cause any deadlock if two results are ever sent to the channel, always a non-blocking select to send.
=> mixclient: Use helper func to send peer errors

mixing/mixclient/client.go
When a mix is canceled before it times out or completes (which dcrwallet regularly does for mixed ticketbuying when the ticket price changes), the gen callback (to generate the HASH160 of the address to mix) would error due to the client's context having been canceled.  This resulted in harmless but ugly "context canceled" errors being logged at error level.  Handle these more gracefully by skipping all mixing client activity for local peers that have canceled their requests early.  To an external observer, this should behave no differently than if these clients had fallen off the network.
Requires #3506.
=> mixclient: Don't serve canceled local peers
