docs/assets/module_hierarchy.gv

This converts the module hierarchy graphviz file to use unix line endings so it is consistent with the rest of the code in the repository.

docs: Use unix line ending in mod hierarchy gv.

---

blockchain/chain.go
blockchain/difficulty.go
blockchain/thresholdstate.go
blockchain/validate.go
chaincfg/simnetparams.go
mining.go

**This requires PRs #1480 and #1481**.
This modifies `simnet` to include the latest consensus changes that have been successfully voted into mainnet to date starting from its genesis block.  This means it is no longer necessary to vote those changes in to `simnet` first before making use of them.
The changes entail removing the deployment entries for those votes, updating the mining templates to start from version 5, which matches the current `mainnet` version, and modifying the various sections in `blockchain` which make decisions accordingly.
The `chaincfg` and `blockchain` modules are affected, but since their version has already been bumped since their last release tags, they are not bumped again.

multi: Latest consensus active from simnet genesis.

---

blockchain/chainquery.go
blockchain/go.mod
docs/assets/module_hierarchy.gv
docs/assets/module_hierarchy.svg
mining/go.mod
peer/go.mod
rpcserver.go

This modifies the `ChainTips` function in `blockchain` to return the results using a type defined in the `blockchain` package itself instead of directly returning a `dcrjson` type.  This is preferable since nothing else in the module depends on `dcrjson` and therefore allows the dependency on the `dcrjson` module to be broken.
It also updates the RPC server that makes use of the function to perform the necessary conversions.
Finally, the associated module hierarchy documentation is updated to properly remove the no longer required dependency.
It should be noted that this is a breaking change to the API and thus will need a v2 major version bump of the `blockchain` module to be published before the changes can be externally consumed.

multi: Break blockchain dependency on dcrjson.

---

chaincfg/init.go
chaincfg/init_test.go
chaincfg/params.go

These errors are only used internally and thus should not be exported.
While here, it also removes the completely unused `VoteBitsNotFound` error.
It should be noted that this is a breaking change to the API and thus will need a v2 major version bump of the `chaincfg` module to be published before the changes can be externally consumed.

chaincfg: Unexport internal errors.

---

blockchain/chain.go
blockchain/thresholdstate.go
blockchain/thresholdstate_test.go
blockchain/votebits_test.go
rpcserver.go

This renames the unexported and exported versions of `ThresholdState` to `NextThresholdState` as well as related test helpers. `NextThresholdState` better describes the function because the threshold state being returned is for the block after the provided block hash.

multi: Rename ThresholdState to NextThresholdState.

---

config.go
config_test.go
doc.go
rpcserver_test.go

This cleans up code recently added to support the `--altdnsnames` flag and `DCRD_ALT_DNSNAMES` environment variable to match the project standards, simplify it, and correct some issues with standalone test binaries.
- Gets rid of the setup func which had several issues:
- It was creating a file that was not needed (and without even checking the error)
- Since it was parsing flags and missing with `os.Args` in a func, it was not possible to individual run the test funcs without failure due to the additional flags
- Performs the flag parsing and removal in an `init` func that only runs once when the tests are run (and before `TestMain`)
- Avoids creating empty objects when nil will suffice
- Uses full sentences and periods in the comment and properly spaces them out so they are consistent …

multi: Cleanup recent alt DNS names additions.

---

dcrjson/walletsvrcmds.go
dcrjson/walletsvrresults.go
mining/go.sum
peer/go.sum

related to https://github.com/decred/dcrwallet/issues/1168

dcrjson: add listtickets command

---

blockchain/chain.go
blockchain/notifications.go

This adds `NTChainReorgStarted` and `NTChainReorgDone` notifications to the blockmanager.

multi: Add started and done reorg notifications.

---

blockchain/validate.go
blockchain/validate_test.go

This removes the `CheckWorklessBlockSanity` function since nothing uses it anymore.  It was used for testing templates and unit tests in the past, but the former is now handled by `CheckConnectBlockTemplate` and the latter is handled by the full block tests.
It should be noted that this is a breaking change to the API and thus will need a major version bump of the blockchain module to be published before the next release.

blockchain: Remove unused CheckWorklessBlockSanity.

---

cert_test.go
rpcserver_test.go

Move mistakenly gated cert tests to another file.

main: move cert tests to a separated file

---

blockchain/blockindex.go

This updates the code which deals with marking block nodes modified when setting and clearing status flags to only mark them modified if the status flags actually change.
This is more efficient as it prevents the need to write nodes that haven't actually changed to the database.

blockchain: Only mark nodes modified when modified.

---

blockchain/accept.go
blockchain/blockindex.go
blockchain/chain.go
blockchain/chainio.go
blockchain/stakeext.go
blockchain/stakenode.go

This reworks the stake node handling logic a bit to clean it up, slightly optimize it, and to make it easier to decouple the chain processing and connection code from the download logic in the future.
To accomplish this, the `fetchStakeNode` dependence on the `getReorganizeNodes` function is removed in favor of directly iterating the block nodes in the function as needed.  Not only is this more efficient, it also allows the function to return stake nodes for branches regardless of their validation status.  Currently, this is irrelevant due to the connection and download logic being tightly coupled.  However, it will be necessary in the future when those are separated.
Also, the flushing and pruning logic is modified to no longer rely on the download logic being tightly coupled to the the …

blockchain: Cleanup and optimize stake node logic.

---

rpcserver.go

This adds more detail to configuration errors returned for `GenerateNBlocks`.

rpcserver: Improve GenerateNBlocks error message.

---

blockchain/chain.go
rpcserver.go

When an accepted block is attached to the main chain, potentially
three notifications are emitted: NTBlockConnected,
NTSpentAndMissedTickets, and NTNewTickets.  This change moves
NTBlockConnected to being the first notification, followed by
NTSpentAndMissedTickets and NTNewTickets.
This is important for applications which react to the stake
notifications since they will have already been notified of the most
recently connected block.  For example, dcrwallet uses the
spentandmissedtickets JSON-RPC notification to create revocation
transactions for missed votes.  However, if the missed tickets are
notified before the connected block, a race is possible where the
revocations are rejected as they double spend a vote on what wallet
believes is still the main chain tip block.
This is considered …

blockchain: Notify stake states after connected block

---

server.go

This modifies the code which enforces a maximum number of peers to always allow whitelisted inbound peers even when they would exceed the maximum number of peers to ensure that operators can always allow their own clients.

server: Always allow whitelisted inbound peers.

---

blockchain/chain.go
blockchain/chainio.go
blockchain/indexers/addrindex.go
blockchain/indexers/addrindex_test.go
blockchain/indexers/existsaddrindex.go
blockchain/indexers/manager.go
blockchain/indexers/txindex.go
blockchain/internal/progresslog/blocklogger.go
blockchain/upgrade.go
blockchain/utxoviewpoint.go
blockchain/validate.go
blockchain/validate_test.go
blockmanager.go
mempool/mempool.go
mining.go
mining/mining.go
rpcserver.go
server.go

---
This PR does not yet have database migration code and is completely incompatible with the current v4 database format.  Thus a full chain download is required.  dcrd will exit with error in the case you attempt to run it against an existing v4 database and the new database it creates will be v5, so if you try to run an older software version against the new database, you will get an error message similar to `Unable to start server on [:9108]: the current blockchain database is no longer compatible with this version of the software (5 > 4).`
The migration code will be added via a separate PR.
This is the biggest change to dcrd to date and, as such, will need a significant amount of testing and careful review.
---
This modifies the way the unspent transaction output set is handled to …

blockchain: Reverse utxo set semantics.

---

blockchain/chain.go
blockchain/notifications.go
blockchain/utxoviewpoint.go

**This requires PR #1471.**
This modifies the chain reorganization logic to directly perform the reorg one block at a time with rollback in the case of failure, as opposed to the existing memory-based two-step approach, so that it is more optimized for the typical case, better handles large reorgs, gives the ability to implement better caching strategies, and helps provide a path to decouple the chain processing and connection code from the download logic.  It also removes the cached stxos from the view since the aforementioned changes make them no longer necessary.
A side effect of these changes is that it is no longer possible to know if a reorg will succeed before actually performing it, so the `NTReorganization` notification is now sent after a successful reorg.  The notification …

blockchain: Convert to direct single-step reorgs.

---

blockchain/chain.go
blockchain/chainio.go
blockchain/indexers/addrindex.go
blockchain/indexers/cfindex.go
blockchain/indexers/common.go
blockchain/indexers/existsaddrindex.go
blockchain/indexers/manager.go
blockchain/indexers/txindex.go
blockchain/stake/internal/ticketdb/chainio.go
blockchain/stake/tickets.go
blockchain/upgrade.go

**This requires PR #1471 and #1500**.
As of this PR, the expected behavior is that there is a single migration that takes an hour or two to complete, depending on enabled indexes, after which it will no longer be possible to downgrade.
As the warning above notes, if you try to run an older software version after this migration has completed, you will get an error message similar to `Unable to start server on [:9108]: the current blockchain database is no longer compatible with this version of the software (5 > 4).`
---
This adds code to migrate the database to the new schema required by the recent utxo set semantics reversal changes.
It involves removing the existing utxo set, spend journal, ticket database, various indexes, resetting the best chain tip back to the genesis block, and …

multi: Migration for utxo set semantics reversal.

---

blockchain/upgrade.go

This modifies the version 5 migration code to update the database version atomically with setting a reindex tip and resetting the best chain tip back to the genesis block so the chain can be reindexed.
This is necessary because, unlike the modifications that come before it, storing the current chain tip and resetting it is not idempotent, so lack of atomicity in those updates can lead to failure to recover in unclean shutdown circumstances.
Thanks to @alexlyp for providing the logs which triggered the condition and helping test the resolution.

blockchain: Make version 5 update atomic.

---

rpcserver.go

This bumps the major version of the JSON RPC server to reflect the
breaking change of reordering the reorg and block connected
notifications.  The reorg notification now indicates a successful reorg
was completed rather than initiated.
Ref: dcrd PR https://github.com/decred/dcrd/pull/1500

rpcserver: bump version to 5.0.0

---

dcrec/secp256k1/signature.go

This corrects an ultra rare and nearly impossible to hit edge case where the case of `r == N` in a deterministic signature could lead to an invalid signature being produced versus returning an error as desired.
Credits to @junderw for discovering this in btcsuite/btcd#1347.

secp256k1: Correct edge case in deterministic sign.

---

go.mod
rpcclient/chain.go

This adds support for the `getblockchaininfo` RPC to `rpcclient`.
The main package's required `rpcclient` module version is bumped from v1.0.2 to v1.1.0.

rpcclient: Add GetBlockChainInfo

---

mining.go

This removes a superfluous error check in the `NewBlockTemplate` function.

mining: Remove superfluous error check.

---

mempool/mempool.go

Modify the comment form to from in ` fetchInputUtxos` func.

mempool: Fix typo in fetchInputUtxos comment.

---

dcrutil/block.go
dcrutil/block_test.go

This fixes a bug in dcrutil where `(*Block).BlockHeaderBytes` would incorrectly return a cached byte slice of the serialized block instead of just the header.  This would only happen after the cache had been set, such through a call to `block.Bytes()`, or construction via `NewBlockFromBytes` or `NewBlockFromBlockAndBytes`.
The comments are also changed accordingly and wrapped after 80 columns.
`TestBlock` is updated with a test for `(*Block).BlockHeaderBytes` that follows `(*Block).Bytes`.  When the test is run without the patch for `BlockHeaderBytes`:
```
=== RUN   TestBlock
--- FAIL: TestBlock (0.00s)
/home/jon/github/decred/dcrd/dcrutil/block_test.go:164: BlockHeaderBytes wrong bytes - got ([]uint8) (len=1158 cap=1158) {
00000000  01 00 00 00 50 12 01 19  17 2a 61 04 21 a6 c3 01 …
```

dcrutil: Block does not cache for BlockHeaderBytes

---

blockchain/sequencelock.go
blockchain/validate.go
blockchain/validate_test.go
mempool/mempool.go

The changes to reverse the utxoset semantics also had the side effect of correcting the behavior for sequence locks when inside of a block to the expected behavior instead of the actual current consensus behavior.
In order to avoid that, this modifies the `blockchain` consensus rules to properly preserve the old incorrect behavior of sequence locks within blocks and also updates the `mempool` to to reject transactions accordingly thus providing parity between the two.
The behavior needs to be corrected, but since it constitutes a change to the consensus rules, a vote will be necessary.
A second commit adds tests to ensure the incorrect sequence lock behavior of the current consensus rules is preserved.
In addition, in order to allow similar style tests in the future, this adds a function …

mempool/blockchain: Preserve seqlock behavior.

---

mempool/mempool_test.go

This modifies `CreateSignedTx` in the `mempool` test harness to accept munge functions similar to how `NextBlock` in `chaingen` works and updates the callers accordingly.  This allows the test code to more easily mutate the transactions as desired prior to them being signed which provides greater flexibility.
While here, it also sets the input amount to the proper value in the generated transaction.  While there is not currently anything in the tests that relies on that value being accurate, it is more desirable to create transactions in the test code which are fully valid in case they end up being used where it does matter in future tests.

mempool: Accept test mungers for create signed tx.

---

mempool/mempool_test.go

**This is currently rebased on top of #1576**.
This adds infrastructure to the `mempool` test harness to allow the faked chain to handle sequence lock calculation for use in upcoming sequence lock tests.
In particular, it modifies the existing `CalcSequenceLock` function on the faked chain to perform the full sequence lock calculation versus simply returning a lock that is always valid.
Since by-time sequence lock calculation in `CalcSequenceLock` depends on the ability to calculate the median time for the block before the block that contains the input being spent and the test harness only provides an incomplete faked chain, this introduces a map which tracks the median times per utxo and provides two new functions named `FakeUxtoMedianTime` and `AddFakeUtxoMedianTime` which the tests can …

mempool: Implement test harness seq lock calc.

---

blockchain/fullblocktests/params.go
chaincfg/mainnetparams.go
chaincfg/params.go
chaincfg/regnetparams.go
chaincfg/testnetparams.go
go.mod

This adds a new definition for the upcoming agenda vote to enable the corrected sequence locks behavior as defined by DCP0004.  It does not include any code to make decisions or bump the versions.  It is only the definition.
Also, bump the `chaincfg` module to v1.3.0 so the new definitions are available to consumers.

chaincfg: Introduce agenda for fixlnseqlocks vote.

---

blockchain/agendas_test.go
blockchain/thresholdstate.go
blockchain/validate.go
mempool/mempool.go
mempool/mempool_test.go
mining.go
server.go

**This requires PR #1578.**
This implements the agenda for voting on the sequence lock fixes as defined in DCP0004 (not completed yet -- will be linked here when complete) along with consensus tests and `mempool` acceptance tests to ensure its correctness.
It also modifies the `mempool` to conditionally treat all transactions with enabled sequence locks as non standard until the vote passes at which point the will become standard with the modified semantics enforced.
- Generate new version blocks and reject old version blocks after a super majority has been reached
- New block version on `mainnet` is version 6
- New block version on `testnet` is version 7
- Introduce a convenience function for determining if the vote passed and is now active
- …

multi: Enable vote for DCP0004.

---

blockchain/agendas_test.go
blockchain/common_test.go
blockchain/thresholdstate_test.go
blockchain/validate_test.go

**This requires #1579 and #1580**.
Several of the blockchain tests have similar code to find a specific agenda id for a given version within a given set of chain parameters. This is cumbersome to repeat and also requires hard coding the specific version for an agenda, which can make it more difficult to use different chain parameters since the version often differs between them.
This improves the tests accordingly by introducing common test infrastructure to more easily work with deployments within the tests and refactoring the tests to make use of them.
- Introduce a `findDeployment` function to search for a given agenda within a set of network parameters and return the resulting version and consensus deployment struct itself
- Add a …

blockchain: Add test logic to find deployments.

---

blockchain/common_test.go

**This requires #1581**.
This introduces a new `chaingen` test harness in the `blockchain` test code that is intended to be used to refactor out some of the common code used in the tests that make use of `chaingen` and have a lot of repeated and cumbersome code as well as to simplify creation of future tests which require the ability to create fully valid test chains.
It encapsulates a test instance, a `chaingen` generator instance, and a `blockchain` instance to provide all of their functionality as well as several convenience functions such as tested block acceptance and rejection, expected tip checking, and threshold state checking.
The harness will certainly need to have additional functionality added as the various tests are updated, however this initial implementation should cover …

blockchain: Introduce chaingen test harness.

---

blockchain/chain_test.go

**This requires #1583**.
This refactors the force head reorganization tests in blockchain to use the recently introduced `chaingen` harness.

blockchain: Use harness in force head reorg tests.

---

blockchain/common_test.go
blockchain/thresholdstate_test.go

**This requires #1583 and is rebased on top of #1586.**
This refactors the threshold state tests in blockchain to use the recently introduced `chaingen` harness.
Since these tests also require non-default choices, a new function named `TestThresholdStateChoice` is also introduced on the `chaingen` harness which allows both the state and the choice to be checked.

blockchain: Use harness in threshold state tests.

---

blockchain/agendas_test.go

**This requires #1583 and #1587.**
This refactors the fixed sequence lock tests in blockchain to use the recently introduced `chaingen` harness.

blockchain: Use harness in fixed seqlock tests.

---

cmd/dcrctl/config.go

This makes the version string printed by the `-V`/`--version` flag consistent with `dcrd`.  In particular it will now include the runtime version, OS, and architecture.
Before: `dcrctl version 1.5.0-pre+dev`
After: `dcrctl version 1.5.0-pre+dev (Go version go1.11.5 linux/amd64)`

dcrctl: Make version string consistent.

---

mining.go

The Optimizes to check the height of the next block is greater than the threshold first since it is more likely in the NewBlockTemplate function.

mining: Optimize get the block's votes tx.

---

blockchain/chainio.go

This optimizes to check the traversal position first since it is more likely in `deserializeSpendJournalEntry` func.

blockchain: Optimize skip stakebase input.

---

config.go
doc.go

This removes the long deprecated `--getworkkey` option and associated code.  This realistically should have been done before Decred was even launched as it was deprecated in the upstream code before `dcrd` was ever even started.

config: Remove deprecated getworkkey option.

---

mempool/mempool.go
mempool/mempool_test.go

**This requires #1595**.
This modifies the check which limits the maximum allowed votes double spending the same ticket to exactly the specified constant instead of one more.
It also adds tests for the max vote double spend handling to both ensure they are accepted up until the max, rejected thereafter, and that removing votes allows them to be accepted again.

mempool: Limit max vote double spends exactly.

---

dcrjson/walletsvrresults.go

This adds the active coin type to `dcrjson.WalletInfoResult`.
Since watching-only wallets do not store the coin type keys, the
`CoinType` field is tagged as `"cointype,omitempty"` so that it will be
omitted when the default value of 0 is set, as is the case when the
wallet has an error of kind (dcrwallet/)`errors.WatchingOnly`.
The location of `CoinType` in the struct is chosen in part because it will
not change the size of the struct because of the preceding `bool`s that
leave room in padding for a 32-bit value.
Supporting https://github.com/decred/dcrwallet/pull/1393

dcrjson: add cointype to WalletInfoResult

---

cmd/dcrctl/config.go
cmd/dcrctl/dcrctl.go
cmd/dcrctl/httpclient.go
go.mod
go.sum

This updates `dcrctl` to use version 2 of the `dcrjson` module and to make use of the new separate type definitions provided by wallet so it continues supporting communication with `dcrwallet`.

dcrctl: Update for dcrjson/v2 and wallet types.

---

go.mod
go.sum
rpctest/memwallet.go
rpctest/node.go
rpctest/rpc_harness.go
rpctest/rpc_harness_test.go
rpctest/utils.go

This updates the `rpctest` harness to use version 2 of the `rpcclient` module as well as version 2 of the `dcrjson` module.

rpctest: Update for rpccclient/v2 and dcrjson/v2.

---

txscript/engine.go

This renames the flag that indicates whether or not the script engine is executing a pay-to-script-hash script pair to a name that more accurately describes its behavior.

txscript: Rename p2sh indicator to isP2SH.

---

blockmanager.go
config.go
go.mod
go.sum
log.go
rpcserver.go
server.go

This updates the main module to use version 2 of the mempool module.
The following is a summary of changes:
- Update all imports to use mempool/v2
- Update module requirements to include new module and remove no longer needed old versions
- Add an override for the v2 module so CI is always builds with the latest code
- Update `rpcserver` `getrawmempool` handler to make use of new `mempool` `VerboseTxDescs` instead of the removed `RawMempoolVerbose`
- Update `rpcserver` `getrawmempool` handler to properly return the parameter  provided for the transaction type instead of the type of variable in the case an invalid type is provided
- Update `rpcserver` `getrawmempool` to return the supported transaction types in the error when an invalid type is provided

main: Update for mempool/v2.

---

wire/msgcftypes.go
wire/msgcftypes_test.go

This adds standard wire tests for MsgCFTypes. Things done in these
commit:
- Add standard wire test for MsgCFTypes
- Fix a potential bug at BtcEncode: return an error if the number
of filter types exceed the maximum number of supported filter
types (256)
- Add an extended error checking for checking malformed encoded
data returns correct errors.

wire: Add tests for MsgCFTypes

---

server.go

This changes the behavior of peer disconnection logic, such that
permanent peers are actually removed from the connection manager when
requested, instead of just being disconnected and therefore triggering a
future retry.
Previously, this prevented the addnode [addr] remove from correctly
removing permanent peers. A connection retry attempt would always be
performed.
The easiest way to test this behavior is to run two nodes disconnected from any other public nodes (either in testnet or on a private simnet), connect them via `dcrctl addnode [othernode] add` then disconnect via `dcrctl addnode [othernode] remove`. Without this patch the nodes will reconnect, even though the previous `remove` command should have removed the peer from the permanent list.

server: Remove instead of disconnect node

---

rpcserverhelp.go

Unlike Bitcoin, the getwork JSON-RPC is not deprecated in Decred.  Remove this
language from the command help.

rpcserver: Undeprecate getwork

---

dcrec/secp256k1/doc.go

This updates the link to the document of secp256k1.

dcrec/secp256k1: Update README.md broken link.

---

.travis.yml

Ensures CI will not fail with `./run_tests.sh: Permission denied`

TravisCI: Set ./run_tests.sh executable perms.

---

txscript/error.go
txscript/error_test.go
txscript/opcode.go

This introduces a new error named `ErrCheckSigAltVerify` and modifies the `opcodeCheckSigAltVerify` handler to use the `abstractVerify` function along with the new error.  This makes the handling consistent with all other signature checking verification opcode handlers and ensures the error both can be programmatically detected as well as be uniquely identified as compared to a generic verify failure.

txscript: Consistent checksigaltverify handling.

---

wire/msgaddr.go
wire/msgaddr_test.go

This fixes the calculation of the maximum payload size of `MsgAddr`. The number of address in encoded `MsgAddr` is `varInt` which its size for the maximum size of allowed address is lower than `MaxVarIntPayload`.

wire: Fix maximum payload length of MsgAddr.

---

txscript/opcode.go
txscript/scriptnum.go

As is already well commented in the code, the locktime parameter of the `CHECKLOCKTIMEVERIFY` opcode requires 5 bytes instead of the standard 4 bytes allowed by math opcodes.  This introduces a constant for the value instead of hardcoding 5 to increase readability and potentially allow the value to be exported in the future.

txscript: Introduce constant for max CLTV bytes.

---

txscript/opcode.go
txscript/scriptnum.go

**This is rebased on top of #1650**.
As is already well commented in the code, the sequence number parameter of the `CHECKSEQUENCEVERIFY` opcode requires 5 bytes instead of the standard 4 bytes allowed by math opcodes.  This introduces a constant for the value instead of hardcoding 5 to increase readability and potentially allow the value to be exported in the future.

txscript: Introduce constant for max CSV bytes.

---

dcrd.go

This modifies the `--memprofile` flag to write the memory profile on shutdown as opposed to arbitrarily writing it after 20 minutes.

main: Write memprofile on shutdown.

---

rpctest/rpc_harness_test.go
rpctest/utils.go

This adds new functions for the rpctest package to allow users to check the connection status and disconnect test harnesses.
This is necessary for some outside tests that perform reorgs or other sync operations between nodes.
Given that rpctest is not currently an individual module, this will require a minor bump to the main module.

rpctest: Add new functions

---

blockchain/subsidy.go
blockchain/validate.go

This deprecates the exported `BlockOneCoinbasePaysTokens` function in favor of an unexported variant.  This is being done since it is only intended to be an internal function and thus should not be exported.
However, since unexporting the function is a break to the API, it requires a major version bump to the `blockchain` module.  Therefore, the exported function is retained and simply redefined in terms of the now unexported definition.

blockchain: Deprecate BlockOneCoinbasePaysTokens.

---

blockchain/subsidy.go

This modifies the function which ensures the first block coinbase pays to the outputs required by the chain params to explicitly require script version 0 rather than using the `DefaultScriptVersion` from `txscript` which is subject to change and could therefore easily inadvertently cause an unintentional consensus break.
It also improves the error message while here.

blockchain: Explicit script ver in coinbase checks.

---

chaincfg/params.go

This modifies the registration process to enforce the already implicit assumption that the network address prefix is unique per network so that it is now an explicit requirement.
This is desirable because the address format contains a network identification byte which is used elsewhere in the code to uniquely identify which parameters to use.

chaincfg: Explicit unique net addr prefix.

---

chaincfg/params.go

**This requires #1663**.
This exposes a new function to allow a caller to lookup any registered parameters that are associated with a given network address prefix.

chaincfg: Introduce params lookup by addr prefix.

---

dcrutil/address.go

**This requires #1664**.
This modifies the code that looks up the params by a given network prefix to make use of the new function provided by `chaincfg` in order to ensure that it works with all registered networks as the package was intended.

dcrutil: Lookup params by addr prefix in chaincfg.

---

peer/example_test.go
peer/peer.go
peer/peer_test.go
server.go

**This requires #1670**.
The only way the chain params are used by the peer is to ascertain the network magic to use on the wire (the Net field), so rather than requiring an entire chain params instance, it is desirable to reduce the scope such that the caller only needs to specify the specific value the module peer needs.
To that end, this introduces a new field named Net on the config struct which the caller can optionally specify in the same vain as the chain params could previously optionally be specified.
The ultimate goal is to remove the `chaincfg` dependency altogether, however, since removing the public `ChainParams` field is a breaking API change, the field is deprecated and, in order to maintain API compatibility, some additional semantics around handling of the optionality of …

peer: Deprecate dependency on chaincfg.

---

addrmgr/go.mod
blockchain/go.mod
blockchain/stake/go.mod
certgen/go.mod
chaincfg/chainhash/go.mod
chaincfg/go.mod
connmgr/go.mod
database/go.mod
dcrec/edwards/go.mod
dcrec/go.mod
dcrec/secp256k1/go.mod
dcrjson/go.mod
dcrutil/go.mod
fees/go.mod
gcs/go.mod
go.mod
hdkeychain/go.mod
mempool/go.mod
mining/go.mod
peer/go.mod
rpcclient/go.mod
txscript/go.mod
wire/go.mod

This adds the go 1.11 directive to all of the modules in order to clearly mark they build and work with that version.  Go 1.12 modified the tools such that tidy will automatically add the new version to modules that do not already have a directive and that would prevent builds on Go 1.11 through Go 1.11.3 which is not desirable.

multi: Add go 1.11 directive to all modules.

---

wire/blockheader_test.go

This increase test coverage of BlockHeader.
In following days, I will increase the test coverage of wire. Some test suites need to be refactored to allow for error paths and wrong inputs, I will keep the test cases data but reorganize them and make them more structured this will allow for increase test coverage and easier understanding and covers more samples.
I will keep the PR short and separate for each Message.
After this, I will work with other packages and increase their test coverage and quality.

wire: Add tests for BlockHeader (From)Bytes.

---

hdkeychain/README.md

This updates the `README.md` in `hdkeychain` to account for changes made in Decred, correct the `NewMaster` godoc example link, and format the examples so the description is on the line after the link
for consistency with other packages in the code base.

hdkeychain: Update README.md.

---

bech32/README.md

Also, add spaces to the end of the example links so the description appears on the next line for consistency with other packages in the repo.

bech32: Correct README links.

---

docs/json_rpc_api.mediawiki

Update the RPC docs which state that the allowHighFees argument of sendrawtransaction is not implemented.
Closes #1690

docs: allowHighFees arg has been implemented.

---

chaincfg/params.go

This defines two new functions named `XPrivKeyID` and `XPubKeyID` on the `Params` struct which return the hierarchical deterministic extended private and public key magic version bytes, respectively.
This will allow the parameters to be used directly as input to an interface in the future.

chaincfg: Add extended key accessor funcs.

---

chaincfg/params.go

This renames the recently introduced accessor functions for obtaining the hierarchical deterministic extended private and public key magic version bytes based on feedback.
Ordinarily this would require a major module version bump, however, since a new version with the functions has not been released yet, it is acceptable to rename them without breaking callers.

chaincfg: Rename extended key accessor funcs.

---

wire/msgcfheaders.go
wire/msggetblocks.go
wire/msggetblocks_test.go
wire/msggetcfheaders.go
wire/msggetdata.go
wire/msggetdata_test.go
wire/msggetheaders.go
wire/msggetheaders_test.go
wire/msgheaders.go
wire/msgheaders_test.go
wire/msginv.go
wire/msginv_test.go
wire/msgminingstate.go
wire/msgnotfound.go
wire/msgnotfound_test.go

This makes messages maximum payload length calculations accurate.
In wire messages which contain arrays, the array items counter is variable integer (`varInt`). Since we limit items count in the arrays, the maximum size of these counters is limited, this causes these counters encoded size in all cases be lower than maximum integer encoded size (`MaxVarIntPayload`).
This PR makes this calculation accurate and makes them consistent with the rest of the codebase.

wire: Accurate calculations of maximum length.

---

wire/msgcftypes.go
wire/msgcftypes_test.go

Unlike #1672 which is an improvement this PR is fixing a potential bug, this is why it is in a separate PR

wire: Fix MsgCFTypes maximum payload length.

---

dcrutil/tx.go
dcrutil/tx_test.go

This fixes `NewTxDeepTxIns` implementation. The current implementation of `NewTxDeepTxIns` is wrong and has many issues. This commit fixes this and adds tests for ensuring the API works correctly.

dcrutil: Fix NewTxDeepTxIns implementation.

---

cmd/promptsecret/promptsecret.go

This is useful for dcrctl commands which take multiple secrets, such as
walletpassphrasechange.

promptsecret: Add -n flag to prompt multiple times

---

wire/msggetcftypes_test.go

This adds standard tests for `MsgGetCFTypes` to make sure the API works correctly.

wire: Add tests for MsgGetCFTypes.

---

blockchain/agendas_test.go
blockchain/chain_test.go
blockchain/common_test.go
blockchain/fullblocksstakeversion_test.go
blockchain/thresholdstate_test.go
blockchain/validate_test.go

This introduces two new functions on the `chaingen` harness, named `AcceptBlock` and `RejectBlock`, which allow ensuring a named block is accepted or rejected, respectively, and redefines the existing `Accepted` and `Rejected` functions which only deal with the tip block in terms of the new functions.
It also renames `Accepted` and `Rejected` to `AcceptTipBlock` and `RejectTipBlock`, respectively.
The motivation for this change is to make it easier to test future code which will allow processing of headers and blocks independently as well as processing blocks out of order so long as their headers are already known.

blockchain: Allow named blocks in chaingen harness.

---

blockmanager.go
server.go

Instead of waiting for a second inv to process what the first inv
may have requested, just send it all at once.  This allows dropping
of a request queue for each server peer.

blockmanager: use local var for the request queue

---

config.go
dcrjson/chainsvrresults.go

This adds config helpers for parsing network interface states based on the config parameters set. 
Work towards `getnetworkinfo` implementation.

config: Parse network interfaces.

---

blockmanager.go
mempool/mempool.go
mempool/mempool_test.go
mining.go
rpcserver.go
rpcserver_test.go
server.go

**This PR requires #1417, #1418, #1419, #1420, #1421, #1422 and #1423**
`BgBlkTmplGenerator` represents the background process that generates block templates and notifies all subscribed clients on template regeneration. It generates new templates based on mempool activity for vote and non-vote transactions and the time elapsed since last template regeneration.

multi: add BgBlkTmplGenerator.

---

mining.go

This modifies the code which notifies subscribed clients about a new block template to avoid creating an unnecessary goroutine since the channel is single use and intentionally buffered to ensure the sender can't block.

mining: Remove unnecessary notify goroutine.

---

mining.go

This factors out the code which deals with generating a unique block template key to a separate function, modifies it to only be comprised of the merkle root + timestamp, and renames the associated variables
accordingly.  The separate function is useful because work submission will ultimately need to create the same key.
The rationale for switching to only using the merkle root + timestamp is as follows:
- It is more efficient to use smaller keys
- The combination is guaranteed to be unique for every template so long as there are no more than one per second generated with the exact same transactions (which is already the case with the inclusion of the stake merkle root in the key too)
- There are future plans to combine the stake root and merkle roots into the merkle root field and …

mining: Improve template key handling.

---

dcrd.go
signal.go

**This requires PR #1710 and #1711**.
This converts the signal handling and `dcrdMain` function to use a context with cancellation instead of a separate interrupt channel.  It does not really make much of a difference yet, but the intent is to simplify the various subsystems in future commits by refactoring them to make use of the context versus manually handling start and stop in each subsystem.

main: Convert signal handling to use context.

---

txscript/engine.go
txscript/sigcache.go

This removes a couple of checks for impossible conditions found by the `staticcheck` linter.  In the case of `executeOpcode`, `bytes` are always `>= 0` and, similarly for `SigCache.Add`, `uints` are always `>= 0`.

txscript: Remove checks for impossible conditions.

---

mining.go

This fixes a case where a block with five votes immediately triggers a regen (as it should) but also
schedules another regen in a second.
This was first observed [here](https://github.com/decred/dcrd/pull/1424#pullrequestreview-2208376890)

mining: fix scheduled template regen.

---

mining.go
server.go

This modifies the lifecycle of the background generator to use the expected pattern for running subsystems based on contexts in the future.
In particular, this renames the `Start` function to `Run` and arranges for it to block until the provided context is cancelled.  This is more flexible for the caller since it can easily turn blocking code into async code while the reverse is not true.
Next, the server is modified to ensure it waits for the background template generator to shutdown before shutting down itself to help ensure an orderly shutdown.
While here, it also makes the various lifecycle debug messages more consistent with the rest of the code base.

miner: Improve background generator lifecycle.

---

mining.go

This ensures the vote handling for the new background miner template happens in a goroutine in order to prevent blocking more transactions being added to the `mempool` and the vote itself from being immediately relayed to the rest of the network.
It also prevents a potential deadlock that can occur due to the cycle created by being called under the `mempool` lock and in turn generating a template which itself attempts to grab the `mempool` lock to get the list of transactions.
This really should be handled better overall, but this serves as a quick solution until the rest of the mining updates are made.

mining: Run vote ntfn in a separate goroutine.

---

blockmanager.go
mining.go

This updates `onVoteReceivedHandler` to call `regenTemplate` as a goroutine to prevent blocking on shutdown.

multi: fix onVoteReceivedHandler shutdown.

---

blockchain/chainio.go
blockmanager.go
mining.go
rpcserver.go
run_tests.sh
wire/msgtx.go

```
blockmanager.go:736:14: nilness: tautological condition: non-nil != nil (govet)
if template != nil {
^
mining.go:854:19: nilness: tautological condition: nil == nil (govet)
if curTemplate == nil {
^
rpcserver.go:2949:22: nilness: impossible condition: non-nil == nil (govet)
if expectedPrevHash == nil || !expectedPrevHash.IsEqual(prevHash) {
^
rpcserver.go:3236:41: nilness: nil dereference in dynamic method call (govet)
return nil, rpcInternalError(err.Error(),
^
rpcserver.go:4101:15: nilness: impossible condition: non-nil == nil (govet)
if msgBlock == nil {
^
```

multi: fix recent govet findings

---

wire/msggetcfheaders_test.go

This adds standard tests for `MsgGetCFHeaders` to make sure the API works correctly.

wire: Add tests for MsgGetCFHeaders.

---

run_tests.sh

Race-enabled testing is an order of magnitude slower. This causes issues for pull requests which add more tests, due to elapsed timeouts on the CI infrastructure, and it is more desirable to have a comprehensive test suite running without -race than few tests with it.
To test with -race locally, just run go test -race as usual, or (better) build and run a race-enabled binary.

TravisCI: Disable race detector.

---

wire/msgcfheaders_test.go

This add standard wire tests for `MsgCFHeaders`.

wire: Add tests for MsgCFHeaders.

---

peer/peer.go
peer/peer_test.go

This modifies the `UpdateLastBlockHeight` function to ensure the new height is after the existing height before updating it in order to prevent it from going backwards so it properly matches the intent of the
function which is to report the latest known block height for the peer.
Without this change, the value will properly start out at the latest known block height reported by the peer during version negotiation, however, it will be set to lower values when syncing from the peer due to requesting old blocks and blindly updating the height.
It also adds a test to ensure proper functionality.

peer: Prevent last block height going backwards.

---

blockchain/stake/staketx.go

This sentence read like a directive rather than a definition and all Go types
are statically declared anyways.

stake: Remove unnecessary language in comment.

---

connmgr/connmanager.go
connmgr/connmanager_test.go

This PR brings fixes made in the upstream btcd repo for pending connection management.
In particular, it adds the ability to cancel pending outbound connections by tracking the connection attempts and then allowing a `Remove` call to completely cancel any further attempts to use that connection request.
The upstream commits were adjusted to conform to dcrd's APIs and to not require a major version bump in the connmgr module.

connmgr: Merge upstream fix for pending connections

---

certgen/README.md
certgen/certgen_ed25519.go
certgen/doc.go

This adds the function NewEd25519TLSCertPair which uses Ed25519 keys
rather than ECDSA keys as required by NewTLSCertPair.
Conditional compilation is used to provide the function only on Go 1.13.
Closes #1756.

certgen: Support Ed25519 cert generation on Go 1.13

---

wire/msgcftypes_test.go

This changes a test's name from `*ExtendedErrors` to `*MalformedErrors` to makes it naming convention consistent with the other tests of this type.

wire: Rename extended errors to malformed errors.

---

wire/msgcfilter_test.go

This adds standard tests for `MsgCFilter` to make sure the API
works correctly.

wire: Add tests for MsgCFilter.

---

chaincfg/go.mod
chaincfg/go.sum

This updates the `chaincfg` module to make use of the recently-tagged `dcrec/edwards` v1 module and thereby corrects the dependencies for the `chainec` package within the `chaincfg/v2` module.

chaincfg: Use dcrec/edwards/v1.0.0.

---

chaincfg/go.mod
chaincfg/go.sum

This fixes the minimum required version of the edwards module so that
the chainec package successfully builds.
Fixes #1759

chaincfg: Prepare v1.5.1

---

chaincfg/params.go

This defines several new functions on the `Params` struct which return the magic prefix bytes for addresses.
The new functions are:
- `AddrIDPubKeyV0`
- `AddrIDPubKeyHashECDSAV0`
- `AddrIDPubKeyHashEd25519V0`
- `AddrIDPubKeyHashSchnorrV0`
- `AddrIDScriptHashV0`
This will allow the parameters to be used directly as input to an interface in the future.

chaincfg: Add addr params accessor funcs.

---

txscript/go.mod

This updates the `txscript` dependencies and serves as a base for `txscript/v1.1.0`.
- github.com/decred/dcrd/dcrec/secp256k1@v1.0.2
- github.com/decred/dcrd/dcrutil@v1.3.0
- golang.org/x/crypto@v0.0.0-20190611184440-5c40567a22f8
The full list of updated direct dependencies since the previous `txscripti/v1.0.2` release are as follows:
- github.com/decred/dcrd/chaincfg@v1.5.1
- github.com/decred/dcrd/dcrec@v1.0.0
- github.com/decred/dcrd/dcrec/edwards@v1.0.0
- github.com/decred/dcrd/dcrec/secp256k1@v1.0.2
- github.com/decred/dcrd/dcrutil@v1.3.0
- golang.org/x/crypto@v0.0.0-20190611184440-5c40567a22f8

txscript: Prepare v1.1.0.

---

wire/msgaddr_test.go
wire/msgblock_test.go
wire/msgcfheaders_test.go
wire/msgcftypes_test.go
wire/msgfeefilter_test.go
wire/msggetaddr_test.go
wire/msggetblocks_test.go
wire/msggetcfheaders_test.go
wire/msggetcfilter_test.go
wire/msggetcftypes_test.go
wire/msggetdata_test.go
wire/msggetheaders_test.go
wire/msgheaders_test.go
wire/msginv_test.go
wire/msgmempool_test.go
wire/msgminingstate_test.go
wire/msgnotfound_test.go
wire/msgping_test.go
wire/msgpong_test.go
wire/msgsendheaders_test.go
wire/msgtx_test.go
wire/msgverack_test.go
wire/msgversion_test.go
wire/netaddress_test.go

This adds an additional check to tests ensuring their max payload lengths do not exceed `MaxMessagePayload`.

wire: assert MaxMessagePayload limit in tests.

---

blockmanager.go
mempool/mempool.go
mining.go
rpctest/rpc_harness_test.go
rpctest/votingwallet_test.go
server.go

Currently, block templates that provide work to PoW miners are generated in response to them calling the getwork RPC.  However, unlike in a pure PoW system, in Decred, when a new block is connected, a new block template extending that block can't be generated until the minimum number of required votes for it has been received.  This poses a challenge for PoW miners because they are typically unaware of when votes are received.  Consequently, miners poll `getwork` waiting until they see a new template generated when a new block is connected.
Since only a minimum of 3 votes is required to build a template and new templates are only generated in response to the miners calling `getwork`, as just described, miners often, unfortunately, end up receiving a template that only has 3 votes and …

mining: Overhaul background template generator.

---

blockchain/subsidy.go
blockchain/subsidy_test.go

This betters `CalcBlockSubsidy` by allowing it to calculate the requested block subsidy from a cached
subsidy entry regardless of its proximity to the requested one.

blockchain: update CalcBlockSubsidy.

---

chaincfg/mainnetparams.go
chaincfg/regnetparams.go
chaincfg/simnetparams.go
chaincfg/testnetparams.go
go.mod
go.sum
require.go
run_tests.sh

The current approach of the CI tests of specifying the path to the directory that contains the module only tests version 1 of the module despite there being newer version available.  The same is true for the lints.
This resolves the test portion by obtaining a list of all modules required by the root go.mod file and providing the entire module path, which includes the version, to the go test command instead of the
directory.
Unfortunately, the linter does not recognize full module paths, however it will lint the latest module version from within the module directory itself, so this resolves the linting case by stripping the full module path and version down to the directory and changing into the directory to perform the lint checks.
It also contains two additional commits which correct …

TravisCI: Test and lint latest version modules.

---

dcrjson/chainsvrcmds.go
dcrjson/chainsvrcmds_test.go
dcrjson/helpers.go
rpcserver.go
rpcserverhelp.go

This add an optional version parameter to the `decodescript` rpc. It defaults to version zero if not set.

multi: add optional version arg to decodescript rpc.

---

dcrjson/chainsvrcmds.go
dcrjson/chainsvrcmds_test.go

dcrjson will require a minor bump before the next major.
Unfortunately, the master branch contains a breaking change since the
prior 2.0.0 tag.  This commit reverts that change and prepares the
module for a 2.1.0 release.

dcrjson: Remove API breaking change

---

run_tests.sh

This modifies the script that strips the module version from listed modules for the purposes of changing to the relevant directory to be more portable by adding the -E flag to sed.  This allows it to work properly on Mac as well.
While here, it also switches the sed separator to a comma in the relevant removals to avoid the need to escape the slashes in the path.
Thanks to @jrick for testing and the suggestion to use a comma for the sed separator.

TravisCI: Use more portable module ver stripping.

---

.travis.yml
run_tests.sh

This updates the tests to ensure all modules are downloaded prior to running the linter.  This is necessary in order to support the travis build cache with staged builds on all platforms.

travis: Allow staged builds with build cache.

---

cmd/dcrctl/httpclient.go
config.go
go.mod
go.sum
peer/go.mod
peer/go.sum
peer/peer.go
peer/peer_test.go
rpcclient/go.mod
rpcclient/go.sum
rpcclient/infrastructure.go

This modifies the code to use the Decred fork of the `go-socks` module throughout and updates the affected modules to use the v1.0.0 release of the socks module.

multi: Use decred fork of go-socks.

---

rpc/jsonrpc/types/README.md
rpc/jsonrpc/types/chainsvrresults_test.go
rpc/jsonrpc/types/chainsvrwscmds.go
rpc/jsonrpc/types/chainsvrwsresults.go
rpc/jsonrpc/types/doc.go
rpc/jsonrpc/types/helpers.go

**This PR is rebased on #1792**.
This adds documentation to the recently introduced `rpc/jsonrpc/types` module to make it consistent with other modules in the project.
While here, it also updates the copyright year on the files that were missed during the conversion
from `dcrjson`.

jsonrpc/types: Add README.md and doc.go.

---

go.mod
go.sum
rpctest/memwallet.go
rpctest/node.go
rpctest/rpc_harness.go
rpctest/utils.go
rpctest/votingwallet.go
rpctest/votingwallet_test.go

**This requires PR #1793**.
This updates the `main` module and `rpctest` package (which is part of the `main` module) to use `v3` of the `rpcclient` module.

main: Use rpcclient/v3.

---

chaincfg/params.go

This defines several new functions on the `Params` struct which return some stake-related parameters.
The new functions are:
- `VotesPerBlock`
- `StakeValidationBeginHeight`
- `StakeEnableHeight`
- `TicketExpiryBlocks`
This will allow the parameters to be used directly as input to an interface in the future.

chaincfg: Add stake params accessor funcs.

---

database/ffldb/driver_test.go
database/ffldb/whitebox_test.go
go.mod

This adds an override to the `main` module for `v2` of the `database` module to ensure tests are executed against the latest code in the repository for the `v2` module.
It also modifies the `database` tests to include `v2` in the test database names to ensure they do not conflict with the `v1` module in the case both are being concurrently tested.

main: Add database/v2 override for tests.

---

.travis.yml
blockchain/standalone/README.md
blockchain/standalone/doc.go
blockchain/standalone/error.go
blockchain/standalone/error_test.go
blockchain/standalone/example_test.go
blockchain/standalone/go.mod
blockchain/standalone/go.sum
blockchain/standalone/pow.go
blockchain/standalone/pow_test.go

This implements a new module named `blockchain/standalone` which aims to provide several of the standalone functions currently available in `blockchain` and ultimately replace them in the next major version.
The primary goal of offering these functions via a separate module is to reduce the required dependencies to a minimum as compared to the `blockchain` module.  It will be ideal for applications such as lightweight clients that need to ensure basic security properties hold and calculate appropriate vote subsidies and block explorers.
For example, some things an SPV wallet needs to prove are that the block headers all connect together, that they satisfy the proof of work requirements, and that a given transaction tree is valid for a given header.
The new module currently only provides …

blockchain/standalone: Implement a new module.

---

blockchain/standalone/README.md
blockchain/standalone/bench_test.go
blockchain/standalone/doc.go
blockchain/standalone/go.sum
blockchain/standalone/subsidy.go
blockchain/standalone/subsidy_test.go

**This requires PR #1809**.
This adds a subsidy cache with funcs to calculate subsidies for proof-of-work, votes, and the treasury to the `blockchain/standalone` module.  Since the existing functions in `blockchain` are easy to use     improperly and have poor performance under certain access patterns, rather than copying them over, this provide new implementations of better optimized functions with less potential cases for misuse.
Note that because subsidy generation is consensus critical, great care has been taken to ensure the same semantics are retained under the scenarios which the consensus code invokes the functions, although the semantics of the functions themselves have changed when compared to their existing counterparts when called in circumstances that the consensus code …

blockchain/standalone: Add subsidy calc funcs.

---

blockchain/standalone/README.md
blockchain/standalone/doc.go
blockchain/standalone/merkle_test.go
blockchain/standalone/tx.go
blockchain/standalone/tx_test.go

**This requires PR #1812.**
The copies the standalone `IsCoinBaseTx` function from the `blockchain` module to the `blockchain/standalone` module.
It also updates the documentation and includes comprehensive tests.

blockchain/standalone: Add IsCoinBaseTx.

---

blockchain/stake/staketx.go

There is no reason to perform a bunch of additional checks when there is no possible way a transaction can be vote due to not having at least the minimum required number of outputs for it to possibly be one.

stake: Check minimum req outputs for votes earlier.

---

database/example_test.go
database/ffldb/driver_test.go

This updates v2 test database names to avoid conflicts when multiple database modules are being tested concurrently, continues the work started by #1806.

database: Separate dbs for concurrent db tests.

---

connmgr/go.mod
connmgr/go.sum

This updates the mining module dependencies and serves as a base for `connmgr/v1.1.0`.
- github.com/decred/dcrd/chaincfg@v1.5.2
The full list of updated direct dependencies since the previous `connmgr/v1.0.2` release are as follows:
- github.com/decred/dcrd/chaincfg@v1.5.2

connmgr: Prepare v1.1.0.

---

blockchain/README.md
blockchain/example_test.go

This removes the examples that rely on removed code in the `blockchain/v2` module and serves as a base for `blockchain/v2.0.1`.

blockchain: Prepare v2.0.1.

---

addrmgr/addrmanager.go
addrmgr/network.go
config.go
server.go

This discovers the network address of the daemon through connected outbound peers. The address is advertised to subsequent connecting peers if automatic network address discovery is not disabled.

multi: add automatic network address discovery.

---

blockchain/chainio.go
blockchain/chainio_test.go
blockchain/compress.go

This updates the deserialization logic underneath the decodeSpentTxOut function to be more robust, including the addition of explicit bounds checks to prevent panics.  In at least one case (txVersion parsing), existing bounds checks were incorrect (e.g., testing for impossible conditions).
A minor rearrangement was also done to eliminate one call to the decodeFlagsFullySpent helper.
Although empty scripts are permitted, decodeCompressedTxOut was missing logic to ensure the script version field actually exists (defaulting to 0x00 only via Golang variable initialization).
To support these changes, the TestStxoDecodeErrors test suite was updated to more closely match the updated logic, and to add new tests for error conditions.
According to "go test -coverprofile", coverage for chainio.go …

blockchain: Implement stricter bounds checking.

---

addrmgr/addrmanager.go
docs/json_rpc_api.mediawiki
rpc/jsonrpc/types/chainsvrresults.go
rpcserver.go
rpcserverhelp.go

 multi: add getnetworkinfo rpc. 

---

blockchain/indexers/cfindex.go
gcs/gcs.go
gcs/gcs_test.go

**This requires PR #1843**.
This adds support for empty filters versus being an error along with a full set of tests to ensure the empty filter works as intended.
It is part of the onging process to cleanup and improve the `gcs` module to the quality level required by consensus code for ultimate inclusion in header commitments.

gcs: Support empty filters.

---

gcs/error.go
gcs/error_test.go
gcs/gcs.go
gcs/gcs_test.go

**This requires PRs #1843, #1844, and #1845**.
This updates the error handling in the `gcs` package to be consistent with the rest of the code base to provide a proper error type and error codes that can be programmatically detected.
This is part of the ongoing process to cleanup and improve the `gcs` module to the quality level required by consensus code for ultimate inclusion in header commitments.

gcs: Make error consistent with rest of codebase.

---

blockchain/go.mod
blockchain/go.sum
blockchain/indexers/cfindex.go
gcs/bench_test.go
gcs/blockcf/blockcf.go
gcs/gcs.go
gcs/gcs_test.go
rpcclient/chain.go
server.go

This refactors the primary `gcs` filter logic into an internal struct with a version parameter in in order to pave the way for supporting `v2` filters which will have a different serialization that makes them incompatible with `v1` filters while still retaining the ability to work with `v1` filters in the interim.
The exported type is renamed to `FilterV1` and the new internal struct is embedded so its methods are externally available.
The tests and all callers in the repo have been updated accordingly.

gcs: Add filter version support.

---

rpcserver.go

There's no such thing as an "SHD" script, so fix the error message
to correctly reference a pay-to-script-hash script instead.

rpcserver: Better error message.

---

rpctest/votingwallet.go

A proper error is message logged on the very next line, so there's
no reason to keep this extra Println call.

rpctest: Remove leftover debug print.

---

blockchain/indexers/cfindex.go
gcs/gcs.go
gcs/gcs_test.go
rpcclient/chain.go
server.go

Currently, the filters provide two different serialization formats per version.  The first is the raw filter bytes without the number of items in its data set and is implemented by the `Bytes` and `FromBytesV1` functions.  The second includes that information and is implemented by the `NBytes` and `FromNBytesV1` functions.
In practice, the ability to serialize the filter independently from the number of items in its data set is not very useful since that information is required to be able to query the filter and, unlike the other parameters which are fixed (e.g. false positive rate and key), the number of items varies per filter.  For this reason, all usage in practice calls `NBytes` and `FromNBytesV1`.
Consequently, this simplifies the API for working with filters by standardizing on a …

gcs: Standardize serialization on a single format.

---

gcs/bench_test.go
gcs/gcs.go

**This is rebased on top of #1851**.
This adds a benchmark and optimizes the `Hash` method of gcs filters by making use of the new zero-alloc hashing func available in `crypto/blake256`.
The following is a before and after comparison:
```
benchmark       old ns/op   new ns/op    delta
-------------------------------------------------
BenchmarkHash   1786        1315         -26.37%
benchmark       old allocs  new allocs   delta
-------------------------------------------------
BenchmarkHash   2           0            -100.00%
benchmark       old bytes   new bytes    delta
-------------------------------------------------
BenchmarkHash   176         0            -100.00%
```

gcs: Optimize Hash.

---

rpcserver.go
rpcserverhelp.go
rpcwebsocket.go

`rebroadcastmissed` and `rebroadcastwinners` are websocket rpcs since they broadcast to only websocket clients.

 multi: make rebroadcast winners & missed ws only.

---

peer/peer_test.go

This adds an additional read from the `ok` channel in the peer listener tests to ensure the version message is consumed as well as the `verack` so that the remaining tests line up with the messages that are being tested.

peer: Ensure listener tests sync with messages.

---

blockmanager.go
mining.go

This removes the chain field from the block manager in favour of using the chain field in block manager config.

multi: use chain ref. from blockmanager config.

---

docs/code_contribution_guidelines.md

We already host the whitepaper on decred.org, so no need to link to bitcoin.org.

docs: Link to btc whitepaper on decred.org

---

rpcserver.go
rpcwebsocket.go

This pr is a port of btcd [982](https://github.com/btcsuite/btcd/pull/982).
This modifies all of the RPC code to use the chain parameters that are associated with the RPC server
instead of the global activeNetParams and thus moves one step closer to being able to split the
RPC server out into a separate package.

rpcserver: don't use activeNetParams.

---

mining.go
rpcserver.go

This removes the `UpdateExtraNonce` function which updated an extra nonce in the coinbase transaction and recalculated the merkle root since it is not necessary and wasteful for Decred due to the extra nonce being available the block header.
Further, due to the aforementioned and the fact the template doesn't have a height set, it isn't currently actually being called anyway as can be seen by diffing the decoded output of subsequent `getwork` calls and noting the only thing that is being updated in between full regeneration of new templates is the timestamp as expected.
```diff
$ diff -uNp work1.txt work2.txt
--- work1.txt   2019-09-07 08:18:58.410917100 -0500
+++ work2.txt   2019-09-07 08:19:01.216456300 -0500
@@ -16,7 +16,7 @@
"sbits": 0.00021026,
"height": 98,
"size": 7221,
- …
```

mining: Remove unused extra nonce update code.

---

mining.go

Use the read template.
Fixes #1893

mining: fix data race

---

docs/code_contribution_guidelines.md

This adds a section outlining the process to follow going forward with regards to making breaking changes to modules.

docs: document module breaking changes process.

---

blockmanager.go
go.mod
mempool/error.go
mempool/mempool.go
mempool/mempool_test.go
mempool/policy.go
rpcserver.go

This adds the ErrorCode member to TxRuleError, filling it with
appropriate values throughout the mempool package. This allows clients
of the package to correctly identify error causes with a greater
granularity and respond appropriately.
It also deprecates the RejectCode attribute and ErrToRejectError
functions, to be removed in the next major version update of the
package.
All call sites that inspect mempool errors were updated to use the new
error codes instead of using RejectionCodes. Additional mempool tests
were added to ensure the correct behavior on some relevant cases.
Finally, given the introduction and use of a new public field, the main
module was updated to use an as-of-yet unfinished mempool v3.1.0, which
will include the required functionality.
Close #1900

mempool: Add ErrorCode to returned TxRuleErrors

---

rpcclient/infrastructure.go

Fixes:
```
infrastructure.go:1224:34: bodyclose: response body must be closed (bodyclose)
wsConn, resp, err := dialer.Dial(url, requestHeader)
^
```

rpcclient: close the unused response body

---

gcs/gcs.go
gcs/gcs_test.go

This ensures any empty/nil data elements in the input array to version 2 filter construction are not added to the filter since empty elements do not make sense given how the filters are used.  It also updates the tests to ensure proper behavior.
The single match function already failed attempts to match an empty element as intended, however, prior to this change, it was possible to match an empty item in the multi-item matching path.  This is not desirable since the matching behavior must be consistent in both the single and multi-match cases.

gcs: Prevent empty data elements in v2 filters.

---

dcrec/secp256k1/go.mod
dcrec/secp256k1/go.sum

This updates the `dcrec/secp256k1` module dependencies and serves as a base for `dcrec/secp256k1/v2.0.0`.
The full list of updated direct dependencies since the previous `dcrec/secp256k1/v1.0.2` release are as follows:

secp256k1: Prepare v2.0.0.

---

cpuminer.go

Currently, in order to allow both the normal continuous and discrete CPU mining modes, a non-blocking channel send is used to update the number of hashes per second since the speed monitor is not running or required in discrete mode.
As a result, in the case the total hashes are already being updated by another goroutine, the update will be ignored which can lead to reporting a lower hash rate than is accurate.
In order to better handle the aforementioned case, this modifies the code to introduce a separate struct with its own mutex to be used for tracking the speed stats and uses a unique instance for the continuous and discrete mining modes.  A separate instance is used to ensure the discrete mining mode is unable to interfere with the continuous mode stats.

cpuminer: Improve speed stat tracking.

---

blockchain/fullblocktests/params.go
chaincfg/mainnetparams.go
chaincfg/params.go
chaincfg/regnetparams.go
chaincfg/testnetparams.go
go.mod

This adds a new definition for the upcoming agenda vote to enable header commitments a provide an initial commitment to a version 2 GCS filter as defined by DCP0005.  It does not include any code to make decisions or bump the versions.  It is only the definition.
Also, bump the `chaincfg` module to v2.3.0 so the new definitions are available to consumers.

chaincfg: Introduce agenda for header cmtmts vote.

---

mining.go
rpcserver.go
server.go

This updates the `getwork` RPC to make use of the background template generator infrastructure and removes code that is no longer needed as a result.
This has a lot of benefits, many of which were discussed more in depth in the previous commit that overhauled the background template generator, however  the following is a non-exhaustive overview that highlights the major benefits of the change:
- Requests for updated templates during the normal mining process in between tip changes will now be nearly instant instead of potentially taking several seconds to build the new template on the spot
- When the chain tip changes, requesting a template will now attempt to wait until either all votes have been received or a timeout occurs prior to handing out a template which is beneficial for PoW …

rpcserver/mining: Use bg tpl generator for getwork.

---

docs/json_rpc_api.mediawiki
mining.go
rpc/jsonrpc/types/chainsvrwscmds.go
rpc/jsonrpc/types/chainsvrwscmds_test.go
rpc/jsonrpc/types/chainsvrwsntfns.go
rpcclient/infrastructure.go
rpcclient/notify.go
rpcserverhelp.go
rpcwebsocket.go

multi: add notifywork websocket rpc.

---

wire/go.mod
wire/go.sum

This updates the `wire` module dependencies and serves as a base for `wire/v1.3.0`.
The full list of updated direct dependencies since the previous `wire/v1.2.0` release are as follows:

wire: Prepare v1.3.0.

---

docs/json_rpc_api.mediawiki
mining.go
rpc/jsonrpc/types/chainsvrwsntfns.go
rpcclient/notify.go
rpcserver.go
rpcwebsocket.go

This updates the new RPC websocket `work` notification that is sent when a new template is generated and a websocket client requests updated via `notifywork` to include the reason the template was generated.
The text-based reasons delivered via the `work` notification are:
* `newparent` -- The template builds on a new block as compared to the previous one.
* `newvotes` -- A new vote for the block the template builds on has been received.
* `newtxns` -- New non-vote transactions are available and have potentially been included.
This allows pools that subscribe for work notifications to better choose when to signal workers to throw away all current work and start working on a new template immediately.  In particular, the `newparent` and `newvotes` reasons should trigger workers to …

multi: Add tpl update reason to work ntfns.

---

chaincfg/go.mod
chaincfg/go.sum
go.mod

This updates the `chaincfg` module dependencies and serves as a base for `chaincfg/v2.3.0`.
- github.com/decred/dcrd/wire@v1.3.0
The full list of updated direct dependencies since the previous `chaincfg/v2.2.0` release are as follows:
- github.com/decred/dcrd/dcrec/edwards/v2@v2.0.0
- github.com/decred/dcrd/dcrec/secp256k1/v2@v2.0.0
- github.com/decred/dcrd/wire@v1.3.0

chaincfg: Prepare v2.3.0.

---

dcrjson/go.mod
dcrjson/go.sum

This updates the `dcrjson` module dependencies and serves as a base for `dcrjson/v3.0.1`.
The full list of updated direct dependencies since the previous `dcrjson/v3.0.0` release are as follows:

dcrjson: Prepare v3.0.1.

---

rpc/jsonrpc/types/go.mod
rpc/jsonrpc/types/go.sum

This updates the `rpc/jsonrpc/types` module dependencies and serves as a base for `rpc/jsonrpc/types/v2.0.0`.
- github.com/decred/dcrd/dcrjson@v3.0.1
The full list of updated direct dependencies since the previous `rpc/jsonrpc/types/v1.0.0` release are as follows:
- github.com/decred/dcrd/dcrjson@v3.0.1

rpc/jsonrpc/types: Prepare v2.0.0.

---

blockchain/standalone/go.mod
blockchain/standalone/go.sum

This updates the `blockchain/standalone` module dependencies and serves as a base for `blockchain/standalone/v1.1.0`.
- github.com/decred/dcrd/wire@v1.3.0
The full list of updated direct dependencies since the previous `blockchain/standalone/v1.0.0` release are as follows:
- github.com/decred/dcrd/wire@v1.3.0

blockchain/standalone: Prepare v1.1.0.

---

rpc/jsonrpc/types/go.mod
rpc/jsonrpc/types/go.sum

This updates the `rpc/jsonrpc/types` `v1` module dependencies and serves as a base for `rpc/jsonrpc/types/v1.0.1`.
- github.com/decred/dcrd/dcrjson/v3@v3.0.1
The full list of updated direct dependencies since the previous `rpc/jsonrpc/types/v1.0.0` release are as follows:
- github.com/decred/dcrd/dcrjson/v3@v3.0.1

rpc/jsonrpc/types: Prepare v1.0.1.

---

gcs/gcs.go

This prunes any empty/nil data elements from the input array to `MatchAny` to prevent potential false positive matches of empty data.
The matching code is not used in consensus, so it is safe to modify without a vote and for all filter versions.
The single match function already failed attempts to match an empty element as intended, however, prior to this change, it was possible to match an empty item in the multi-item matching path due to a false positive.  This is not desirable since the matching behavior must be consistent in both the single and multi-match cases.

gcs: Prevent empty data elements fp matches.

---

rpcwebsocket.go

This ensures all templates handed out via work notifications are stored in the `getwork` template pool so that their solved submissions can reconstruct the block.

mining: Store block templates given by notifywork.

---

internal/version/version.go

release: Bump for 1.6 release cycle.

---

rpcadaptors.go
rpcserver.go
rpcwebsocket.go
server.go

This pr depends on  **#1728** and is a port of btcd [981](https://github.com/btcsuite/btcd/pull/981).
This decouples the RPC server from the internal dcrd server to move
closer to being able to split it out into a separate package.
In order to accomplish this, it introduces an rpcserverConfig type and
several new interfaces, named rpcserverPeer, rpcserverConnManager, and
rpcserverBlockManager, which are necessary to break the direct
dependencies on the main server and block manager instances.
It also adds concrete implementations of the new interfaces and uses
them to configure the RPC server.
Ultimately, the RPC server should ideally be decoupled even more such
that all of the types in the configuration struct use interfaces instead
of the concrete types.  Doing this would make the RPC …

rpcserver: decouple from server.

---

rpcserver.go
server.go

This is a port of btcd [984](https://github.com/btcsuite/btcd/pull/984)
This refactors the RPC server to accept and take ownership of already configured listeners and refactors the logic to setup those listeners to the server.  This mirrors the logic used by the connection manager and
is desirable since it is another step closer to being able to split the RPC server code out into a separate package and will make it much easier to internally test since it allows creating mock listeners.

rpcserver: refactor listener logic to server.

---

blockmanager.go
rpcadaptors.go
rpcserver.go
server.go

This is a port of btcd [989](https://github.com/btcsuite/btcd/pull/989)
The purpose is to remove the dependency of blockmanager on serverPeer, which is defined in the main package. Instead, we split out some of the fields from serverPeer into a separate struct called peerSyncState in blockmanager.go. While they are in the same package now, this change makes it easier to move blockManager into its own package along with peerSyncState. The blockManager tracks a map of Peer pointers to the peer state and keeps it updated as peers connect and disconnect.

blockmanager: remove serverPeer from blockmanager completely.

---

rpcserver.go

This makes the `getvoteinfo` RPC handling more consistent with the rest of the handlers and corrects the return error type for unrecognized vote versions.
Fixes #1953.

rpcserver: Cleanup getvoteinfo RPC.

---

blockmanager.go
config.go
go.mod
log.go
mempool/go.mod
rpcserver.go
server.go

Several upcoming changes constitute breaking public API changes to the `mempool` module, therefore, this follows the process for introducing major API breaks which consists of:
- Bump the major version in the go.mod of the affected module if not already done since the last release tag
- Add a replacement to the go.mod in the main module if not already done since the last release tag
- Repeat the process for any other modules the require a new major as a result of consuming the new major(s)

mempool: Start v4 module dev cycle.

---

blockchain/utxoviewpoint.go
mining/policy.go

This introduces a new interface named `PriorityInputser` and updates the functions that currently take a pointer to a `blockchain.UtxoViewpoint` struct to accept the interface instead.
This removes the tight coupling between the two packages at the API boundary and allows callers to easily provide custom values if desired.
It also updates the `blockchain.UtxoViewpoint` struct to implement the interface.

mining: Introduce PriorityInputser interface.

---

blockchain/utxoviewpoint.go
mining/policy.go
mining/policy_test.go

**This requires #1966**.
This changes the overhead value used when calculating transaction priorities for mining to the correct value for Decred transaction sizes and adds tests to ensure the priority calculation produces the expected values.  In order to accomplish this, it introduces a mock priority input source which implements the newly introduced `PriorityInputser` interface.

mining: Correct priority calcs for Decred sizes.

---

addrmgr/addrmanager.go
server.go

This properly associates ports applicable to discovered IPs based on the listeners specified and the network address type of the discovered host. Inbound peers can now corroborate valid suggestions from outbound peers and setups using NAT are now accounted for.

server: improve address discovery.

---

rpcserver.go

This bumps the `rpcserver` version patch to correspond with the recent change to correct the `getvoteinfo` error response when provided a version that does not exist.
Ref #1953.

rpcserver: Bump to 6.1.1.

---

config.go
server.go

This adds a warning when alternative DNS names are specified and the TLS certificate key or cert already exist to make it clear the additional names will NOT be included unless the certificate and key are deleted first.
Closes #1912.

rpcserver: Warn on alt DNS names when certs exist.

---

mempool/log.go
mempool/mempool.go

This implements orphan expiration in the `mempool` such that any orphans that have not had their ancestors materialize within 15 minutes of their initial arrival time will be evicted which in turn will remove any other orphans that attempted to redeem it.
In order to perform the evictions with reasonable efficiency, an opportunistic scan interval of 5 minutes is used.  That is to say that there is not a hard deadline on the scan interval and instead it runs when a new orphan is added to the pool if enough time has passed.
The following is an example of running this code against the main network for around an hour while intentionally generating orphans to test:
```
2019-10-28 01:44:36.272 [DBG] TXMP: Expired 2 orphans (remaining: 46)
2019-10-28 01:49:39.915 [DBG] TXMP: Expired 17 orphans …
```

mempool: Implement orphan expiration.

---

blockchain/chain.go
blockchain/indexers/addrindex.go
blockchain/indexers/cfindex.go
blockchain/indexers/common.go
blockchain/indexers/existsaddrindex.go
blockchain/indexers/manager.go
blockchain/indexers/txindex.go
blockchain/utxoviewpoint.go
cmd/addblock/import.go
server.go

Some indexes require all of the previous output scripts referenced as inputs by the blocks they are indexing.  Currently, the indexing code relies on a concrete `blockchain.UtxoViewpoint` to provide that
information which makes the indexing code more rigid than it needs to be and prevents the possibility of using other sources, such as the spend journal, to provide the necessary scripts.
In addition, the index initialization code also currently requires access to a concrete `blockchain.BlockChain` to query the current chain state which also makes the code more rigid than it should ideally be.
Consequently, this modifies the indexing code to accept a `PrevScripter` interface to remove the tight coupling to a specific type in the former case, and introduces a new `ChainQueryer` interface to …

blockchain: Decouple indexers from blockchain.

---

blockchain/chain.go
blockchain/indexers/common.go
blockchain/indexers/manager.go

**This requires #1968**.
When an index is enabled for the first time (or after having previously been disabled and re-enabled), the index needs to be updated to account for the current state of the main chain.
This poses a problem for indexes that require access to the previous scripts, such as the address index,  since the outputs are no longer in the utxo set due to pruning.  Currently, in order to handle this, the code has to load all of the referenced transactions in order to get access to the output scripts which is extremely inefficient.  The address index is already notoriously time consuming to generate due to the sheer amount of information, but it is only exacerbated by this inefficiency.
However, the necessary information exists in a much more efficient form in the spend …

indexers: Use spend journal for index catchup.

---

config.go
server.go

This is a port of [btcd 1037](https://github.com/btcsuite/btcd/commit/30d4caeac63f368f5164569d96cb0dd754f44222)
The helper function parseListeners has been changed to return a
slice of net.Addrs with Network() returning tcp4 or tcp6 instead of
returning two slices of IPv4 and IPv6 addresses to simplify calling
code. Also improves how local addresses are added to the address
manager when listening on wildcard addresses.
Also splits some newServer logic into new method initListeners.
Network interface parsing has been updated as well.

multi: Simplify logic to bind listeners.

---

cpuminer.go
rpcserver.go

This moves the error check for an attempt to call the generate RPC when on a network that there is virtually no chance of mining a block with the CPU into the RPC server where it more naturally belongs.  The caller of the CPU miner should be the one to determine if it wants to allow
mining or not.  While here, use a more accurate RPC error code of `ErrDifficulty` instead of `ErrInternal`.
This change is a step towards being able to separate the CPU mining code into its own subpackage.

rpcserver: Move error check for generate RPC.

---

chaincfg/params.go
chaincfg/subsidydefinitions.go

The `mustPayout` function is only used when generating the subsidy definitions and thus it should be defined in the same file that is only built during generate.

chaincfg: Gate mustPayout with subsidy generation.

---

docs/json_rpc_api.mediawiki
mining.go
rpc/jsonrpc/types/chainsvrcmds.go
rpcclient/mining.go
rpcserver.go
rpcserverhelp.go

This adds the regentemplate comand to the node, which asks it to
regenerate is block template.
The node now maintains a background template generator, with various
timeouts to enable efficient generation of block templates in a
production setting.
However, external users might want to force a new template to be
generated after new regular transactions have been received but before
the regular regen timeout (currently 30 seconds) has elapsed. This is
true specially for external simnet tests that publish transactions and
rely on them being mined shortly after the node receives them.
The most flexible solution found was to add a new regentemplate command
which rpc clients can issue to force a node to regenerate the latest
template with any new transactions.

multi: Introduce regentemplate command

---

blockmanager.go
internal/rpcserver/interface.go
log.go
mempool/mempool.go
mempool/mempool_test.go
rpcadaptors.go
rpcserver.go
server.go

This removes any remaining orphan transactions that were sent by a peer when it disconnects since it is extremely unlikely that the missing parents will ever materialize from elsewhere.
In order to achieve this, there are three individual commits. The first commit modifies `mempool` to allow a tag to be associated with orphan transactions and uses the peer ID as the tag for each transaction.
The second commit modifies `mempool` to provide a `RemoveOrphansByTag` which, as its name implies, allows callers to remove all orphans associated with a given tag (and also any orphans that depend on the removed orphans, recursively).
The final commit modifies server to invoke the new `RemoveOrphansByTag` function with the peer ID as each peer disconnects.
The following shows the PR is action (IP …

server/mempool: Evict orphans on peer disconnect.

---

config.go
doc.go
mempool/policy.go
mempool/policy_test.go
sampleconfig/sampleconfig.go

**This is rebased on #1982**.
The current max orphan transaction size causes problems with dependent transaction relay due to its artificially small size in relation to the max standard transaction size.
Consequently, this modifies the orphan transaction policy by increasing the max size of each orphan to the same value allowed for standard non-orphan transactions and reducing the default max allowed number of orphans to 100.
From a memory usage standpoint, the worst case max mem usage prior to this change was 5MB plus structure and tracking overhead (1000 max orphans * 5KB max each).  With this, that is raised to 10MB (100 max orphans * 100KB max each) in the worst case.
It is important to note that the values were originally implemented as a naive means to control the size of the orphan …

mempool: Modify default orphan tx policy.

---

blockchain/chain.go
blockchain/chainio.go

This removes the main chain block size instance variable since it is merely set to a constant and is not configurable anyway.  While here, it also moves the prune height calculation outside of the loop and renames the variables related to the main chain block cache to be more consistent with the rest of the code.

blockchain: Remove unconfigurable chain var.

---

rpcserver.go

This is a backport of #1964 to the 1.5 release branch.
It makes the `getvoteinfo` RPC handling more consistent with the rest of the handlers and corrects the return error type for unrecognized vote versions.
It also bumps the rpcserver version patch to correspond with the change.

[release-v1.5] rpcserver: Cleanup getvoteinfo RPC.

---

sampleconfig/sampleconfig.go

This is a backport of #2003 to the 1.5 release branch.

[release-v1.5] sampleconfig: add export dcrctl sample config

---

blockchain/blockindex.go
blockchain/chain.go
blockchain/chainio.go
blockchain/chainio_test.go
blockchain/chainquery.go
blockchain/common_test.go
blockchain/thresholdstate.go
blockchain/upgrade.go

This renames the `KnownValid` and associated status flag of `statusValid` to `HasValidated` and `statusValidated`, respectively in order to better clarify the behavior .
While this distinction doesn't currently make much difference the intention in the future to decouple the block process and download logic at which point the distinction will become more important.

blockchain: Rename KnownValid to HasValidated.

---

blockchain/fullblocktests/generate.go
blockchain/process_test.go

Currently, the full block tests, which are intended to test the consensus rules include some tests that are related to implementation-dependent processing specifics as opposed to consensus rules.  For example, rejection of duplicate blocks, accepting orphan blocks, and handling of reorgs to invalid blocks when processed out of order.
In order to better separate the consensus rules from the processing aspects, this introduces a new test function specifically for testing the process order logic and moves the related tests out of the full
block consensus tests into the new function.

blockchain: Separate processing order tests.

---

blockchain/chain.go
blockchain/go.mod
chaincfg/mainnetparams.go
chaincfg/params.go
chaincfg/regnetparams.go
chaincfg/simnetparams.go
chaincfg/testnetparams.go

This adds a new parameter to the chain parameters to allow a minimum total known cumulative amount of chain work to be specified as of a given point in time and updates the check which determines if the blockchain believes it is current to make use of the value instead of the height of the final checkpoint.  In other words, the chain is not considered synced if the best chain does not yet have the amount of work specified.
This approach is preferred because it easier to maintain, does not rely on trusted known good checkpoints, is valid regardless of the order that blocks are received and processed, and, in general, is a more objective value that can't be invalidated by a chain reorganization.
It also adds initial values for the main and test networks as follows:
> mainnet: …

multi: Introduce initial sync min known chain work.

---

blockchain/chain.go
blockmanager.go
cmd/addblock/import.go

This removes the unused error return from the `HaveBlock` function.

blockchain: Remove unused error from HaveBlock.

---

blockchain/bench_test.go
blockchain/blockindex.go
blockchain/blockindex_test.go
blockchain/chainview.go
blockchain/common_test.go

There are several places when processing blocks and headers that require the ability to traverse the chain to ancestors of a given block such as tallying votes and versions to determine threshold states, finding forks, and calculating PoW difficulty, ticket price, and sequence locks.
Currently most traversal of this type is linear and therefore does not scale well as the chain height grows.  In addition, the ability to quickly locate ancestors, potentially deep in history, will be needed when decoupling the connection code from the download logic as well as several planned future optimizations.
Consequently, this significantly optimizes ancestor traversal by introducing a deterministic skip list and adds tests to ensure proper functionality.
The following is a before and after comparison …

blockchain: Use skip list for ancestor traversal.

---

dcrutil/go.mod
dcrutil/go.sum
go.mod
go.sum
hdkeychain/go.mod
hdkeychain/go.sum

This updates the `main`, `dcrutil`, and `hdkeychain` modules to use the latest `base58` module.
The updated direct dependency is as follows:
- github.com/decred/base58@v1.0.2

multi: Use latest base58 module.

---

blockchain/README.md
blockchain/chain.go
blockchain/chain_test.go
blockchain/common_test.go
blockchain/doc.go
blockchain/error.go
blockchain/error_test.go
blockchain/example_test.go
blockchain/fullblocks_test.go
blockchain/process.go
blockchain/process_test.go
blockchain/validate_test.go
blockmanager.go
cmd/addblock/import.go

This decouples and removes the orphan handling from blockchain in favor of implementing it in the block manager as part of the overall effort to decouple the connection code from the download logic.
The change might not make a ton of sense in isolation, since there is no major functional change, however, decoupling the orphan handling independently helps make the review process easier and alleviates what would otherwise result in additional intermediate code to handle cases that ultimately will no longer exist.
- Introduce blockchain function to more easily determine if an error is a rule error with a given error code
- Move core orphan handling code from blockchain to block manager
- Move data structures used to cache and track …

multi: Decouple orphan handling from blockchain.

---

blockchain/difficulty.go
blockchain/process.go

**This requires PR #2008**.
These checks are no longer necessary since they applied to orphans and blockchain no longer handles orphans.  Further, orphans are currently otherwise limited by the block manager and this is another step towards the overall effort to decouple the connection code from the download logic.  Ultimately, the goal is to remove orphan handling altogether.
Finally, it also has the added benefit of further minimizing the reliance on trusted known good checkpoints.

blockchain: Remove easiest diff checkpoint checks.

---

blockchain/chain.go
blockchain/checkpoints.go
blockchain/difficulty.go
blockchain/process.go
blockchain/validate.go
blockmanager.go
cmd/addblock/import.go
server.go

**This is rebased on PR #2012**.
This modifies blockchain to expose a new field named `Checkpoints` in the `Config` struct which allows the checkpoints to use to be specified by the caller instead of assuming the checkpoint associated with the current chain parameters.  This allows the caller to customize the checkpoints as it sees fit, such as adding custom checkpoints or removing default checkpoints.
In addition, this removes the `DisableCheckpoints` function in favor of the caller simply configuring the chain instance without checkpoints when they're disabled and updates the code to remove the associated flag accordingly.  This produces simpler code and is faster since the mutex that was required to protect the aforementioned flag is no longer required.
Finally, this also paves the way …

blockchain: Make checkpoints configurable.

---

go.mod
go.sum

This update provides dcrctl support for calling the new auditreuse
RPC.

dcrctl: Update dcrwallet RPC types package

---

rpcwebsocket.go

This removes outstanding references of a wsClient quit chan to the
notification maps in notificationHandler() upon client disconnection.
Previously, the left over references caused the wsClient and its
assotiated wsClientFilter struct to not be GCd after a wallet
disconnected from the node, which leaked memory.
This is specially relevant for setups that involve wallets with very
large number of addresses.

rpcwebsocket: Remove client from missed maps

---

rpcwebsocket.go

All sends to channels that are serviced by separate goroutines that can be shutdown via a `quit` channel need to ensure they select across that `quit` channel when sending to the associated channel to ensure they can't end up blocking on the send during shutdown.

rpcwebsocket: Use nonblocking messages and ntfns.

---

bech32/bech32.go
bech32/bech32_test.go
bech32/example_test.go
go.mod
require.go

BIP173 specifically calls out that encoders must always output an all lowercase bech32 string and that the lowercase form is used when determining a character's value for calculating the checksum.
Currently, the implementation does not respect either of those requirements.
This modifies the `Encode` function to convert the provided HRP to lowercase to ensure the requirements are satisfied and adds tests accordingly.

bech32: Ensure HRP is lowercase when encoding.

---

bech32/bech32.go
bech32/bech32_test.go

**This requires PR #2024**.
Since `bech32` itself works with data encoded with 5 bits per byte (aka base32) padded out to the nearest byte boundary, the existing functions for `Encode` and `Decode` accept and return data encoded that way.
However, the most common way to use `bech32` is to encode data that is already encoded with 8 bits per byte (aka base256) without padding which means it is up to the caller to use the `ConvertBits` function properly to convert between the two encodings.
Consequently, this introduces two convenience functions for working directly with base256-encoded data named `EncodeFromBase256` and `DecodeToBase256` along with a full set of tests to ensure they work as expected.

bech32: Add base256 conversion convenience funcs.

---

config.go
doc.go
rpcserver.go
sampleconfig/sampleconfig.go
server.go

**This is rebased on #2022**.
This introduces a new flag named `allowunsyncedmining` which allows checks that prevent unsynchonrized mining to be disabled on `testnet`.  This is an advanced option and should not be used unless you understand exactly why it exists and what it implications it carries.

config: Add flag to allow unsynced testnet mining.

---

blockchain/accept.go
blockchain/chain.go
blockchain/chainio.go
blockchain/checkpoints.go
blockchain/validate.go

**This requires PR #2013**.
This reworks the checkpoint logic in blockchain to greatly simplify it and pave the way to support checkpoints based on only the headers being available.
Previously there was more complex logic that attempted to find the most recent checkpoint that is already available in the downloaded portion of the block chain on demand along with the next checkpoint that is expected.  Instead, the new logic this introduces updates the most recent checkpoint as the blocks are processed as needed and finds the most recent checkpoint once during initialization.
This approach will eventually make it possible to update the most recent checkpoint based on headers alone since it is no longer tightly tied to the active best chain which will be important when decoupling the …

blockchain: Support hdr checkpoints and simplify.

---

txscript/engine.go
txscript/opcode.go

The existing implementation to handle conditional execution makes use of a stack to track the state of each nested conditional.  It is already fairly efficient in terms of execution costs since it only considers the most recent conditional stack entry and makes use of pushing `OpCondSkip` to essentially track the nesting depth in unexecuted branches, however, using a stack is less efficient in terms of memory usage than is actually necessary since there is no need to use a stack at all given that all that is really needed to provide the necessary behavior is the current conditional nesting depth and the depth at which branch execution was disabled (if it has been disabled).
Given the above, this optimizes the `txscript` conditional execution logic by replacing the condition stack with two …

txscript: Optimize conditional execution mem usage.

---

blockchain/go.mod
blockchain/stake/go.mod
database/go.mod
fees/go.mod
gcs/go.mod
go.mod
hdkeychain/go.mod
mempool/go.mod
mining/go.mod
peer/go.mod
rpcclient/go.mod
txscript/go.mod

This modifies the various modules to use a valid prerelease version so they can be used in require statements in consumer code that is also under development.
- github.com/decred/dcrd/blockchain/stake/v3@v3.0.0-20200104000002-54b67d3474fb
- github.com/decred/dcrd/blockchain/v3@v3.0.0-20200104000002-54b67d3474fb
- github.com/decred/dcrd/connmgr/v3@v3.0.0-20200104000002-54b67d3474fb
- github.com/decred/dcrd/dcrutil/v3@v3.0.0-20200104000002-54b67d3474fb
- github.com/decred/dcrd/mempool/v4@v4.0.0-20200104000002-54b67d3474fb
- github.com/decred/dcrd/mining/v3@v3.0.0-20200104000002-54b67d3474fb
- github.com/decred/dcrd/txscript/v3@v3.0.0-20200104000002-54b67d3474fb

multi: Update to prerel module release versions.

---

release/services/rc.d/dcrd

This script removes the default file logging, instead preferring to
write all stdout and stderr (including panic traces) to syslog.

release: Add example OpenBSD rc.d service script

---

chaincfg/mainnetparams.go
chaincfg/params.go
chaincfg/regnetparams.go
chaincfg/simnetparams.go
chaincfg/testnetparams.go
config.go
connmgr/seed.go
server.go

Requires https://github.com/decred/dcrseeder/pull/25

multi: Add HTTP seeder support.

---

mining.go

This fixes a case where`queueRegenEvent` blocks indefinitely (because it's not being read) in `regenHandler` when the template generator is shutting down.

mining: Fix regenHandler shutdown.

---

rpcwebsocket.go

This is a backport of #2027 to the 1.5 release branch.
It removes outstanding references of a `wsClient` `quit` chan to the notification maps in `notificationHandler()` upon client disconnection.
Previously, the left over references caused the `wsClient` and its associated `wsClientFilter` struct to not be GCd after a wallet disconnected from the node, which leaked memory.
This is specially relevant for setups that involve wallets with very large number of addresses.

[release-v1.5] rpcwebsocket: Remove client from missed maps

---

rpcwebsocket.go

This is a backport of #2026 to the 1.5 release branch.
All sends to channels that are serviced by separate goroutines that can be shutdown via a quit channel need to ensure they select across that quit channel when sending to the associated channel to ensure they can't end up blocking on the send during shutdown.

[release-v1.5] rpcwebsocket: Use nonblocking messages and ntfns.

---

go.mod
go.sum

This is a backport of #2018 to the 1.5 release branch.
It provides `dcrctl` support for calling the new `auditreuse` RPC.

[release-v1.5] dcrctl: Update dcrwallet RPC types package

---

internal/version/version.go

Also, per previous discussions, set the clear the `PreRelease` and set the `BuildMetadata` to `release.local` here on the release branch so that anyone building the release branch will end up with version "1.5.1+release.local" indicating it was a local build as opposed to a reproducible release build.

[release-v1.5] release: Bump for 1.5.1.

---

internal/version/version.go

Releases will now use the empty string for the prerelease field and "release.local" for build metadata.  This indicates that the code is for a release, but the release was built from the repo or using go get
without the release build tool.
Development versions will use "pre" for the prerelease and default to no build metadata.
In particular, this will result in the following cases:
- Development builds performed on the master branch will show as "version X.Y.Z-pre" (where either X or Y is one version greater than the current release)
- Builds performed on the release branch without using reproducible build tools will show as "version X.Y.Z+release.local"
- Builds performed on the release branch using reproducible build tools will show as "version X.Y.Z+release"
Consequently, this this …

release: Remove build metadata from master branch.

---

connmgr/connmanager.go
rpcadaptors.go
server.go

NOTE: This is a resubmission of #1842 with the requested changes applied in a separate commit since the author of that PR was not responsive in addressing them for several months.  I've squashed the commits in that PR per standard practice and also updated the commit title to conform to the code contribution guidelines, but otherwise left them unchanged and attributed to the original author to ensure proper credit is given.  Along those lines, I've added a separate commit which applies the requested changes as well as adds the additional code needed to make it work with incompatible changes that have since been made to master in the mean time.
This PR resolves #1725. Currently, if there is a call made by `dcrctl addnode <ip_addr:port> add` to an unresponsive port, the connReq will …

 connmgr: Allow pending outbound conn removal. 

---

dcrec/secp256k1/btcec.go
dcrec/secp256k1/privkey.go
dcrec/secp256k1/pubkey.go
dcrec/secp256k1/schnorr/ecdsa.go
dcrec/secp256k1/schnorr/ecdsa_test.go
dcrec/secp256k1/schnorr/threshold.go
dcrec/secp256k1/schnorr/threshold_test.go
dcrec/secp256k1/signature.go
dcrutil/address.go
txscript/sign.go
txscript/sign_test.go

**This requires #2040.**
This removes several functions that only existed to satisfy the `chainec` interfaces which no longer exist.  It also updates any callers that were directly using functions instead of just directly access the fields or underlying functions accordingly.

secp256k1: Remove unused chainec code.

---

dcrec/secp256k1/bench_test.go
dcrec/secp256k1/btcec_test.go
dcrec/secp256k1/example_test.go
dcrec/secp256k1/privkey.go
dcrec/secp256k1/privkey_test.go
dcrec/secp256k1/pubkey.go
dcrec/secp256k1/schnorr/ecdsa.go
dcrec/secp256k1/schnorr/threshold.go
dcrec/secp256k1/schnorr/threshold_test.go
dcrec/secp256k1/signature.go
dcrec/secp256k1/signature_test.go
txscript/sigcache_test.go
txscript/sign.go

**This requires PR #2042.**
This consists of several commits which improve the code in regards to the signing process by significantly optimizing the deterministic nonce generation by specializing the implementation specifically for secp256k1 and modifying it in such a way that signing can no longer fail in the extremely unlikely event a returned nonce results in an invalid signature.
It has been split into several commits to help ease the review process.
---
The first commit merely reformats the functions to be consistent with the style used in the rest of the code.  It contains no functional changes.
---
The second commit improves the NonceRFC6979 comment which previously indicated it was to generate an ECDSA nonce, but that is not the case.  Instead, it is a method to generate a …

secp256k1: Improve and optimize nonce generation.

---

dcrec/secp256k1/signature.go

**This is rebased on #2045.**
This updates the comments to reflect reality and remove all references to additional curves since the code is tailored specifically to secp256k1 these days.

secp256k1: Correct comments in signature.go.

---

dcrec/secp256k1/bench_test.go
dcrec/secp256k1/signature_test.go

**This is rebased on #2046.**
This tidies up the signature tests to make them more consistent.
- Make signature equality test two different instances in addition to self testing
- Scope the signature tests inside the associated test function
- Use hex to improve readability and reduce definition size
- Rename `TestSignature` to `TestSignatureParsing` to more accurately reflect its purpose
- Add comments

secp256k1: Cleanup signature tests.

---

blockchain/stake/scripttype.go
blockchain/stake/scripttype_test.go
blockchain/stake/staketx.go
blockchain/stake/staketx_test.go
blockchain/validate.go
txscript/standard.go

This removes `GetScriptClass` consensus calls in favour of using script type identification
functions defined in the blockchain package.
Resolves #1626.

multi: replace GetScriptClass consensus calls.

---

dcrd.go
server.go

This updates the rpc listener error message associated with having no usable listeners.

multi: fix rpc listener error.

---

dcrec/secp256k1/bench_test.go
dcrec/secp256k1/curve.go
dcrec/secp256k1/curve_test.go
dcrec/secp256k1/ellipticadaptor.go
dcrec/secp256k1/genstatics.go
dcrec/secp256k1/privkey.go
dcrec/secp256k1/signature.go

**This requires #2056**.
This introduces a new structure for passing around Jacobian coordinates and updates the code to make use of it.
This increases the readability of the code by reducing a lot of extra parameter clutter and makes it more obvious what type of coordinates the functions expect (Jacobian vs affine) as well as which parameters are for passing the results back out.  It also makes the internal code less cumbersome to work with.
The only reason it was originally split into coords was due to early versions of the Go compiler having issues with escape analysis leading to slower performance in performance-critical code.  However, that is no longer the case as can be seen by the benchmarks below which show everything within the margin of error in terms of performance.  A few …

secp256k1: Introduce jacobian point struct.

---

dcrec/secp256k1/signature.go

**This requires PR #2057**.
This implements signature verification directly instead of calling the version in the standard library in order to ultimately be able to break the reliance on big ints it requires and thus allow for optimization specifically for the sec256k1 curve.
It currently is only marginally faster since it still relies on big ints.  However, there is already a 10% reduction in allocations which reduces pressure on the GC during IBD when there are a ton of signature verifications happening.
```
benchmark            old ns/op    new ns/op    delta
-----------------------------------------------------
BenchmarkSigVerify   224238       219603       -2.07%
benchmark            old allocs   new allocs   delta
----------------------------------------------------- …
```

secp256k1: Implement direct signature verification.

---

dcrec/secp256k1/curve.go
dcrec/secp256k1/field.go
dcrec/secp256k1/field_test.go

**This is rebased on #2058.**
This adds a specialized function for testing if a field value is one that is constant time and faster than an equality check along with comprehensive tests for correct functionality.  As the benchmarks below show, it results in a reduction of roughly 2.5% for addition which translates to about a 1% reduction in typical signature verification time.
```
benchmark                         old ns/op     new ns/op     delta
--------------------------------------------------------------------
BenchmarkAddJacobian              580           564           -2.76%
BenchmarkScalarBaseMultJacobian   34629         33885         -2.15%
BenchmarkScalarBaseMultLarge      47468         47021         -0.94%
BenchmarkScalarMult               157832        156503        -0.84% …
```

secp256k1: Add specialized field check for one.

---

docs/json_rpc_api.mediawiki
rpc/jsonrpc/types/chainsvrcmds.go
rpcserver.go
rpcserverhandlers_test.go
rpcserverhelp.go

For createrawsstx explicitly state that all values are in atoms in help
messages and the documentation.
For createrawssrtx explicitly state that all values are in coins in help
messages and the documentation. Remove range loop for only one input.
For createrawtransaction explicitly state that all values are in coins in
help messages and the documentation. Move conversion to atoms above the
check for max amount and check after converting from coins.
Remove bad white spaces from JSON api documentation.

rpcserver: Refactor and updated documents

---

rpcserver.go

Use the passed amounts instead of wire.NullValueIn for inputs to the
transaction.
I'm fairly sure that this should be the passed amounts. With my current knowledge I can't image why it would be wire.NullValueIn. When voting, these amounts decide the ratio to divide up the stakebase.

rpcserver: Correctly assign TxIn amounts

---

rpcserver.go
rpcwebsocket.go
server.go

This updates the `rpcserver` and `wsNotificationManager` lifecycle processes to use a context.
Resolves  #2037

multi: Convert rpcserver lifecycle to context.

---

mempool/mempool.go
mempool/mempool_test.go
server.go

This updates the allowed votes range for `mainnet`, `simnet` and `regnet` to coinbase maturity from tip. Testnet has been exempted due to longer reorgs that have already happened in `testnet's` history.
Resolves #81

mempool: Tighten allowed votes range for mainnet.

---

txscript/engine.go
txscript/script.go
txscript/standard.go

This modifies the consensus critical function which determines if the redeem script of a p2sh or stake-tagged p2sh contains stake opcodes to avoid calling the `GetScriptClass` function which is only intended explicitly for working with standard script forms which only apply in the context of the more restrictive standardness policy rules.
It also renames the function to better indicate its purpose is to specifically check the redeem script as opposed to the entire signature script.
Finally, it removes the now unused `isStakeOutput` function.

txscript: Don't use GetScriptClass in consensus.

---

blockmanager.go
fees/estimator.go
mempool/mempool.go
mempool/mempool_test.go

Closes #1555 
This PR ensures that tickets which spend from not-approved regular transactions are not visible for mining or fee estimation. A regular input is considered "not approved" if it exists in the mempool.
When a ticket is added to the mempool, its inputs are checked for existence in the mempool. If the ticket has mempool inputs, it is tracked separately from other transactions. When the inputs have been mined, the ticket is brought back into the mempool so it is eligible for mining and fee estimation.

mempool: Track tickets with non-approved inputs

---

wire/common.go
wire/error.go
wire/error_test.go
wire/fakemessage_test.go
wire/message.go
wire/message_test.go
wire/msgaddr.go
wire/msgblock.go
wire/msgcfheaders.go
wire/msgcfilter.go
wire/msgcfilterv2.go
wire/msgcftypes.go
wire/msgfeefilter.go
wire/msggetblocks.go
wire/msggetcfheaders.go
wire/msggetcfilter.go
wire/msggetcfilterv2.go
wire/msggetcftypes.go
wire/msggetdata.go
wire/msggetheaders.go
wire/msgheaders.go
wire/msginv.go
wire/msgminingstate.go
wire/msgnotfound.go
wire/msgsendheaders.go
wire/msgtx.go
wire/msgversion.go

This updates the wire error type by clearly defining package errors and updating call sites.
This is work towards  #350.

multi: define wire error types.

---

config.go
doc.go
peer/example_test.go
peer/peer.go
sampleconfig/sampleconfig.go
server.go

This adds `--peeridletimeout` config option and updates peer connections to enforce idle timeouts using the connection's read deadline. Associated tests have also been updated.
This resolves #383.

multi: add peer connection timeout config option.

---

hdkeychain/extendedkey.go

The SerializedPubKey method returns the internal and memoized bytes
representing the compressed serialization of the HD key's secp256k1
public key.  The motivation for providing this method is to avoid an
extra serialization and deserialization through *secp256k1.PublicKey
when creating the pubkey hash.  Wallet profiling revealed that roughly
30% of CPU time deriving child addresses from account branch extended
keys was a result of the extra forced serialization steps.

hdkeychain: Provide SerializedPubKey method

---

go.mod
hdkeychain/example_test.go
hdkeychain/go.mod
rpcclient/go.mod
rpcclient/go.sum
rpcclient/wallet.go
rpctest/memwallet.go

hdkeychain has received breaking changes since the last release (break
occurred in 85f0c09df2), and further releases must use a bumped major
version.  The standard process for introducing major API breaks has
been followed:
- Bump the major version in the go.mod of the affected module if not
already done since the last release tag
- Add a replacement to the go.mod in the main module if not already done
since the last release tag
- Update all imports in the repo to use the new major version as
necessary
- Make necessary modifications to allow all other modules to use the new
version in the same commit
- Repeat the process for any other modules the require a new major as a
result of consuming the new major(s)
Closes #2075.

hdkeychain: Start v3 module dev cycle.

---

hdkeychain/README.md
hdkeychain/example_test.go
hdkeychain/extendedkey.go
hdkeychain/extendedkey_test.go

This removes the `ECPubKey` method in favor of the newly added `SerializedPubKey` method, updates the tests and example to use the new method instead, and finally updates the `README` accordingly as well.
The primary reason for this change is that it removes the secp256k1 type from the public API and is more efficient in practice because the serialized bytes are already available internally and callers are exceedingly likely to just serialize the returned pubkey again, so the current approach  almost always resulted in an additional needless round trip through parsing the public key, which is rather expensive.

hdkeychain: Remove ECPubKey.

---

hdkeychain/extendedkey.go
hdkeychain/extendedkey_test.go
rpctest/memwallet.go

This replace the `ECPrivKey` method with a `SerializedPrivKey` method to be consistent with the newly added `SerializePubKey` method and updates the tests accordingly.
The primary reason for this change is that it removes the `secp256k1` type from the public API and is more efficient in practice because the serialized bytes are already available internally and callers are exceedingly likely to just serialize the returned privkey again, so the current approach  almost always resulted in an additional needless round trip through parsing the private key.

hdkeychain:  ECPrivKey -> SerializedPrivKey.

---

blockchain/go.mod
blockchain/stake/go.mod
database/go.mod
fees/go.mod
gcs/go.mod
go.mod
hdkeychain/go.mod
mempool/go.mod
mining/go.mod
peer/go.mod
rpcclient/go.mod
txscript/go.mod

This modifies all prelease modules to use the latest version so they can be used in require statements in consumer code that is also under development without running into transitive dependency issues.
- github.com/decred/dcrd/blockchain/stake/v3@v3.0.0-20200214194519-928737b3e580
- github.com/decred/dcrd/blockchain/v3@v3.0.0-20200214194519-928737b3e580
- github.com/decred/dcrd/connmgr/v3@v3.0.0-20200214194519-928737b3e580
- github.com/decred/dcrd/dcrutil/v3@v3.0.0-20200214194519-928737b3e580
- github.com/decred/dcrd/mempool/v4@v4.0.0-20200214194519-928737b3e580
- github.com/decred/dcrd/mining/v3@v3.0.0-20200214194519-928737b3e580
- github.com/decred/dcrd/txscript/v3@v3.0.0-20200214194519-928737b3e580

multi: Update all prerel module release versions.

---

hdkeychain/extendedkey.go
hdkeychain/go.mod

This change replaces usage of chainhash (which is intended solely for
transaction and blocks) and dcrutil.Hash160 (used in scripts for
hashing redeem scripts and pubkeys) with direct calls to each hashing
function from dcrd's crypto subpackages.  This improves clarity and
shortens the transitive package imports.  Notably, dcrutil and
everything it depends on is no longer transitively imported when
importing the hdkeychain package.

hdkeychain: Use direct hashes and remove dcrutil dep

---

blockchain/stake/lottery.go
blockchain/stake/lottery_test.go

The comment says this is only exported for test code, but the test
code is able to call the unexported function, and is not used outside
of the package.
stake/v3 is not released yet so a breaking change is permitted here to
remove this API.

stake: Remove exported FindTicketIdxs

---

blockchain/fullblocktests/generate.go
dcrec/secp256k1/ciphering.go
dcrec/secp256k1/ellipticadaptor.go
dcrec/secp256k1/modnscalar.go
dcrec/secp256k1/privkey.go
dcrec/secp256k1/schnorr/ecdsa.go
dcrec/secp256k1/signature.go
dcrec/secp256k1/signature_test.go
mempool/policy_test.go
txscript/sign_test.go

**This requires #2060**.
This modifies the `PrivateKey` type to be opaque and updates the internal implementation of it to use the new `ModNScalar` type instead of a `big.Int`.
It also modifies `NewPrivateKey` to accept the new `ModNScalar` type instead of a `big.Int` and improves the `PrivKeyFromBytes` comment to explicitly call out the semantics that realistically already existed when using the value in calculations.
It is also worth noting that there are still a couple of internal conversions to `big.Int` when dealing with signatures that are required since that code still relies on them for now.  The goal is to eventually update them to use the more efficient specialized types and this change help facilitate that process.

secp256k1: Make private key opaque.

---

dcrec/secp256k1/bench_test.go
dcrec/secp256k1/schnorr/ecdsa.go
dcrec/secp256k1/signature.go

**This requires #2062**.
This modifies the NonceRFC6979 function to return the new `ModNScalar` type instead of a `big.Int` to move closer towards big integer removal in the primary code paths.
While here, this also adds a few more explicit zeros of memory when signing which is good practice when dealing with key material.

secp256k1: Return new scalar from NonceRFC6979.

---

dcrec/secp256k1/bench_test.go
dcrec/secp256k1/curve.go
dcrec/secp256k1/curve_test.go
dcrec/secp256k1/ellipticadaptor.go
dcrec/secp256k1/privkey.go
dcrec/secp256k1/signature.go

**This requires #2063.**
This modifies the internal `scalarMultJacobian` and `scalarBaseMultJacobian` functions to accept the new `ModNScalar` type instead of a raw byte slices and updates the code accordingly.
It also moves the `moduloReduce` function from `curve.go` to `ellipticadaptor.go` since it is only required in the adaptor code now.
This is work towards eventually using the new more efficient mod n scalar throughout.

secp256k1: Use new mod n scalar in ec mults.

---

dcrec/secp256k1/modnscalar.go
dcrec/secp256k1/modnscalar_bench_test.go
dcrec/secp256k1/modnscalar_test.go

**This requires #2064**.
This adds a function to find the modular multiplicative inverse in non-constant time by making use big ints along with the associated tests and benchmarks.
Ideally this will be replaced with an implementation that does not rely on big integers, as well as ultimately have a constant-time implementation. However, this version is being introduced to avoid blocking the ongoing work towards using the new more efficient mod n scalar throughout.

secp256k1: Add non-const inverse for mod n scalar.

---

dcrec/secp256k1/bench_test.go
dcrec/secp256k1/signature.go
dcrec/secp256k1/signature_test.go
txscript/sign.go

This modifies the `Signature` type to be opaque in order to facilitate eventually using the new more efficient mod n scalar.  For now, it makes no other changes beyond making the type opaque.

secp256k1: Make signature opaque.

---

dcrec/secp256k1/bench_test.go
dcrec/secp256k1/signature.go

**This requires PR #2084.**
This modifies the function that produces signatures to use the new `ModNScalar` type instead of big ints and also fleshes out the comments to include a reference to original signing algorithm in GECC, a paraphrased version of it for those without access to the book, and the modifications made so that it is deterministic per RFC6979 and conforms to BIP0062.  It also adds a signing benchmark.
This is work towards eventually using the new more efficient mod n scalar throughout.
While the primary focus of this change is not optimization since signing happens infrequently enough that it is not in a performance hot path, as can be seen from the benchmark below, it does have the effect of making signing a bit faster.
The following benchmark shows a before and after …

secp256k1: Use mod n scalar when signing.

---

dcrec/secp256k1/bench_test.go
dcrec/secp256k1/signature.go
dcrec/secp256k1/signature_test.go

**This requires PR #2085**.
This modifies the function to serialize signatures to use the new `ModNScalar` type instead of big ints and takes the opportunity to clean up the relevant code so that it is more readable and avoid unnecessary extra allocations, improves the comments to reference the DER specification and include the specific details of the format inline, and adds a signature serialization benchmark.
This is work towards eventually using the new more efficient mod n scalar throughout.
While the primary focus of this change is not optimization since signature serialization happens infrequently enough that it is not in a performance hot path, as can be seen from the benchmark below, it does have the effect of making the serialization faster and significantly reducing the number …

secp256k1: Use mod n scalar in sig serialization.

---

dcrec/secp256k1/field.go
dcrec/secp256k1/field_bench_test.go
dcrec/secp256k1/field_test.go

**This is rebased on #2087**.
This introduces the ability to determine if a specialized field value is greater than or equal to the field prime minus the group order in constant time.  It is also significantly faster than performing the calculation via big integers since it would require a conversion from the specialized type in practice.
Comprehensive tests with 100% coverage and benchmarks are included.
For now, this merely introduces the method without modifying any of the code to make use of it, but it will be useful when working with signatures and public key recovery in the future.
The following benchmark shows a comparison between determining the condition via the new specialized method and via generic big ints:
```
benchmark                          old ns/op    new ns/op    delta …
```

secp256k1: Add field func to determine when >= P-N.

---

dcrec/edwards/ecdsa.go
dcrec/edwards/threshold.go

This modifies the instances in the `edwards` package that zero out big ints to use a function to clear the internal memory used by the big int since merely setting it to 0 does not do that.

edwards: Zero internal bytes of big ints.

---

dcrec/secp256k1/signature.go
dcrec/secp256k1/signature_test.go
txscript/sigcache_test.go

**This is rebased on #2095**.
This removes the ability to parse signatures encoded with the more lax Basic Encoding Rules (BER) since they have never been valid on the Decred blockchain and the existing parsing code for them really didn't follow the spec anyway given it enforced additional length restrictions that the BER spec technically allows.

secp256k1: Remove BER signature parsing.

---

dcrec/secp256k1/sigerror.go
dcrec/secp256k1/sigerror_test.go
dcrec/secp256k1/signature.go

**This requires #2105**.
This reworks the DER signature parsing code to use the majority of the implementation code that exists in the consensus scripting engine, updates it to make use of the new specialized mod N scalar, and introduces a new error type and associated error code for signature errors which can be used with the `errors.Is` and `errors.As` interfaces to programmatically detect the failure reason.
It includes full tests for the new signature error infrastructure.
The primary motivation behind using the implementation code from the consensus script engine is that it is already extremely well tested, any signatures that don't conform to it would be rejected by consensus anyway, and the code is easier to follow due to the use of constants and better documentation.

secp256k1: Rework DER signature parsing code.

---

dcrec/secp256k1/go.mod
dcrec/secp256k1/signature_test.go

**This requires #2106**.
This reworks the DER signature parsing tests to ensure 100% test coverage of all branches in the parsing code and also test for the explicit reason for a failure to ensure that each test is actually testing the intended condition.
Compare this to the previous more generic validity testing which only tested that a signature failed to parse as opposed to _why_ it failed to parse.  The result was that some of the tests were not actually testing what they claimed.

secp256k1: Rework DER sig parsing tests.

---

connmgr/dynamicbanscore.go
connmgr/dynamicbanscore_test.go

This allows the stringer for the `DynamicBanScore` type to be used without deadlocking.
This is a port of the same fix in btcd along with improved test coverage.  Credits to Jin for the fix.

connmgr: Fix dynamic ban score stringer deadlock.

---

dcrec/secp256k1/signature.go
dcrec/secp256k1/signature_bench_test.go
dcrec/secp256k1/signature_test.go

**This requires #2106**.
This updates the internal implementation of the `Signature` type to use the new `ModNScalar` type instead of `big.Int`s and modifies `NewSignature` to accept the new `ModNScalar` type accordingly.
Signature parsing and signing operations are now completely free of `big.Int`s.  Verification still relies on them due to their use in public keys.

secp256k1: Use mod n scalar in signature type.

---

dcrec/secp256k1/ciphering.go
dcrec/secp256k1/curve_test.go
dcrec/secp256k1/ellipticadaptor.go
dcrec/secp256k1/pubkey.go
dcrec/secp256k1/schnorr/ecdsa.go
dcrec/secp256k1/signature.go
dcrec/secp256k1/signature_bench_test.go
dcrec/secp256k1/signature_test.go
hdkeychain/extendedkey.go

**This is rebased on #2107**.
This modifies the `PublicKey` type to be opaque in order to facilitate eventually using the new more efficient mod n scalar.  For now, it makes no other changes beyond making the type opaque.

secp256k1: Make public keys opaque.

---

hdkeychain/example_test.go
hdkeychain/extendedkey.go
hdkeychain/extendedkey_test.go

This method never errors now, allowing the API to be simplified
slightly.

hdkeychain: Remove Neuter error return

---

dcrec/secp256k1/privkey.go
dcrec/secp256k1/privkey_test.go

This adds a method to the `PrivateKey` type to clear the memory associated with it so that consumers can explicitly clear key material for enhanced security against memory scraping.  It also adds tests to ensure it works as expected.

secp256k1: Add Zero method to private key.

---

dcrec/secp256k1/schnorr/ecdsa.go
dcrec/secp256k1/schnorr/signature.go
txscript/opcode.go

This removes the `GetR`, `GetS`, and `GetType` methods that were only used to satisfy the `chainec` interface which no longer exists.

schnorr: Remove deprecated chainec methods.

---

dcrec/secp256k1/schnorr/ecdsa.go
dcrec/secp256k1/schnorr/error.go

**This is rebased on #2121**.
There is no reason for the method to exist as the `ErrorCode` field is exported and it also goes against effective Go guidelines in terms of naming.

schnorr: Remove GetCode method from Error type.

---

dcrec/secp256k1/schnorr/ecdsa.go
dcrec/secp256k1/schnorr/ecdsa_test.go
dcrec/secp256k1/schnorr/signature.go
txscript/opcode.go

**This is rebased on #2122**.
This removes the unnecessary generalized `Verify` function in favor of the `Verify` method on the `Signature` to be more consistent with the `secp256k1` package.

schnorr: Remove generalized Verify.

---

dcrec/secp256k1/schnorr/ecdsa.go
dcrec/secp256k1/schnorr/signature.go

**This requires #2123**.
This modifies the `Signature` type to be opaque in order to facilitate eventually using the new more efficient mod n scalar from `secp256k1`.  For now, it makes no other changes beyond making the type opaque.

schnorr: Make signature opaque.

---

dcrec/secp256k1/schnorr/signature_bench_test.go
dcrec/secp256k1/schnorr/signature_test.go

**This requires #2125**.
This moves the code related to benchmarking signing and signature verification to a separate file and modifies them to be more consistent with the code in the secp256k1 package.

schnorr: Cleanup signature benchmarking.

---

dcrec/secp256k1/schnorr/signature.go
dcrec/secp256k1/schnorr/signature_test.go

This removes the `pubNonceX` and `Y` parameters from the internal signing function since they're always called with nil and if the tweaking functionality is desired in the future, it should take a point to operate on instead of individual big ints.

schnorr: Remove unused internal signing params.

---

dcrec/secp256k1/schnorr/signature.go
dcrec/secp256k1/schnorr/signature_test.go

**This requires #2128**.
This modifies the internal `schnorrVerify` function to accept the signature as a type instead of its raw serialized form.  This will ultimately facilitate making it easier to switch over to more efficient types for the r and s components.

schnorr: Accept sig type in internal verify func.

---

dcrec/secp256k1/go.mod
dcrec/secp256k1/schnorr/signature.go
dcrec/secp256k1/schnorr/signature_test.go

**This requires #2129**.
This removes the hash func callback parameter for hashing the commitment data from the internal sign and verify functions in favor of just calling the real hash function directly.
This is being done for several reasons:
- It is not safe to use just any hash function, rather the hash function must have certain properties, so it's safer to make it explicit
- There is only a single hash function, blake256, being used and thus having an extra unneeded parameter is not desirable
- Any modifications to the commitment data invalidate existing signatures, so the internals of the function have to realistically be updated when making any changes anyway

schnorr: Remove internal hash func callback.

---

dcrec/secp256k1/privkey.go

This reduces the number of internal copies of private keys that are made when serializing them and parsing them from bytes in order to help reduce the attack surface.

secp256k1: Reduce privkey copies.

---

dcrec/secp256k1/schnorr/signature.go
txscript/sign_test.go

**This is rebased on #2130**.
This removes the `GenerateKey` function from the `schnorr` package since nothing uses it and it is expected that the caller will use `secp256k1.GeneartePrivateKey` instead since the package works with that type as private keys.

schnorr: Remove unused GenerateKey.

---

dcrec/secp256k1/curve.go
dcrec/secp256k1/signature.go

**This requires #2118**.
This modifies the various EC operations to reduce the overall number of normalizations that are needed by requiring the caller to provide normalized points instead of blindly normalizing the inputs.  It also updates the operations to ensure the result is normalized along with updating the comments to call out the new semantics and updating all of the callers accordingly to ensure the new requirements are met.
This results in less overall normalizations because the caller has more information about whether or not normalization is needed and can therefore avoid it in many cases, particularly when it is using the result that is already normalized as part of a chain of operations.
The following benchmarks show a before and after comparison of the affected operations: …

secp256k1: Reduce EC operation normalizes.

---

dcrec/secp256k1/ellipticadaptor.go

This removes the `q` param from the curve params since it is no longer used due to previous optimizations.

secp256k1: Remove unused q curve param.

---

dcrec/secp256k1/field.go
dcrec/secp256k1/field_test.go
dcrec/secp256k1/signature.go

**This requires #2134**.
This exposes new functions on the `FieldVal` type named `IsOddBit`, `IsOneBit`, and `IsZeroBit` which operates similarly to their counterparts except they return a 0 or 1 instead of a bool.
These are being provided because it is not possible in Go to convert from a bool to numeric value in constant time and many constant-time operations require a numeric value.
Since the type is now exported for external use, consumers would otherwise have no way to perform the conversion.

secp256k1: Expose IsXBit on field val type.

---

dcrec/secp256k1/schnorr/signature.go
dcrec/secp256k1/schnorr/signature_test.go

This removes the bool return from the internal `schnorrVerify` function since it is entirely unnecessary given an error is already returned if the signature fails to verify.  It is also more consistent with the rest
of the code.

schnorr: Remove internal verify func bool ret.

---

chaincfg/go.mod
chaincfg/go.sum

This updates the `go.mod` and `go.sum` files to remove modules that are no longer needed since the removal of `chainec`.

chaincfg: Remove unused modules.

---

dcrec/secp256k1/schnorr/error.go
dcrec/secp256k1/schnorr/error_test.go
dcrec/secp256k1/schnorr/signature.go
dcrec/secp256k1/schnorr/signature_test.go

**This requires #2139 and #2143**.
This consists of two commits which combined add several tests to help ensure the signature verification code works as intended with invalid signatures by crafting signatures that are specifically designed to hit the various failure cases and checking the verification failed for that explicit reason.
The first commit updates the `Error` and `ErrorCode` types to provide support for `errors.Is` and `errors.As` and adds a full set of tests for the error infrastructure so the error handling is more consistent with the rest of the `secp256k1` module.
It also removes the unused `ErrPubKeyOffCurve` error and renames the error creation func to `signatureError` to be more consistent.

schnorr: Add negative tests for sig verification.

---

hdkeychain/extendedkey.go

**This is rebased on #2155**.
This makes use of the `PubKey` method on `secp256k1.PrivateKey` to convert a private key to a public key instead of manually performing the conversion.
This is desirable since `secp256k1` provides the method specifically for this purpose and it also has the benefit of allowing `secp256k1` to perform the task without round tripping through big integers which results in slightly faster derivation.
The following benchmarks show a before and after comparison of the affected operations:
```
benchmark                 old ns/op    new ns/op    delta
----------------------------------------------------------
BenchmarkDeriveHardened   3702         3671         -0.84%
BenchmarkDeriveNormal     4053         3999         -1.33%
benchmark                 old allocs   new …
```

hdkeychain: Use secp256k1 privkey to pubkey method.

---

dcrec/secp256k1/schnorr/error.go
dcrec/secp256k1/schnorr/error_test.go
dcrec/secp256k1/schnorr/primitives.go
dcrec/secp256k1/schnorr/signature.go
dcrec/secp256k1/schnorr/signature_test.go

**This requires #2147**.
This reworks the Schnorr signature parsing code to be more consistent with the ecdsa parsing code and pave the way for eventually being able to remove the reliance on big ints.
It also adds a full set of signature parsing tests that include 100% coverage of all branches in the parsing code and test for the explicit reason for the failure to ensure that each test is actually testing the intended condition.
In particular, the parsing code has been changed as follows:
- Reject signatures that have the r and/or s components out of the allowed ranges for their respective type
- Make use of the specialized mod N scalar and field val types
- Introduce new error codes for signature errors and return them

schnorr: Rework signature parsing.

---

dcrec/secp256k1/ecdsa/README.md
dcrec/secp256k1/schnorr/README.md
dcrec/secp256k1/schnorr/doc.go

**This is rebased on #2148**.
This adds a `README.md` file for the package which includes the custom EC-Schnorr-DCRv0 specification along with the design details and rationale for why its various characteristics were chosen.
It also adds a `doc.go` file to provide package documentation via godoc.

schnorr: Add README.md and doc.go.

---

dcrec/secp256k1/schnorr/error.go
dcrec/secp256k1/schnorr/error_test.go
dcrec/secp256k1/schnorr/signature.go
dcrec/secp256k1/schnorr/signature_bench_test.go
dcrec/secp256k1/schnorr/signature_test.go
txscript/sign.go

**This requires #2149**.
schnorr: Use specialized types when signing.
This modifies the function that produces signatures to use the `ModNScalar` and `FieldVal` types instead of big ints and also fleshes out the comments to include a reference to the signing algorithm specified in `README.md`.
This is work towards eventually using the specialized types throughout.
While the primary focus of this change is not optimization since signing happens infrequently enough that it is not in a performance hot path, as can be seen from the benchmark below, it does have the effect of making signing a bit faster.
The following benchmark shows a before and after comparison of producing a typical signature:
```
benchmark       old ns/op    new ns/op    delta …
```

schnorr: Use specialized types when signing.

---

dcrec/secp256k1/field.go
dcrec/secp256k1/field_test.go
dcrec/secp256k1/modnscalar.go
dcrec/secp256k1/modnscalar_test.go

**This is rebased on #2153**.
This consists of two commits which add a new method named `PutBytesUnchecked to `FieldVal` and `ModNScalar`, respecitvely, which can be used by callers to serialize the types directly into a target byte slice with the caveat that the caller must ensure the target has at least 32 bytes available or it will panic.
This is useful in cases where the caller wishes to write into a larger buffer without having to first serialize into a 32-byte array and copy it.
It also updates the tests to ensure they work as expected.

secp256k1: Add PutBytesUnchecked to some types.

---

dcrec/secp256k1/ecdsa/README.md

ecdsa: Correct README.md documentation links.

---

dcrec/secp256k1/schnorr/signature.go
dcrec/secp256k1/schnorr/signature_bench_test.go

**This requires #2154**.
schnorr: Use PutBytesUnchecked for serialize.
This updates the code to use the recently-added `PutBytesUnchecked` of the `FieldVal` and `ModNScalar` types to serialize directly into larger buffers where possible to avoid the need for additional copies.
The following benchmarks show a before and after comparison of the affected operations:
```
benchmark               old ns/op    new ns/op    delta
--------------------------------------------------------
BenchmarkSign           52682        52284        -0.76%
BenchmarkSigVerify      178050       176977       -0.60%
BenchmarkSigSerialize   87.5         73.3         -16.23%
benchmark               old allocs   new allocs   delta
--------------------------------------------------------
BenchmarkSign           16 …
```

schnorr: Use PutBytesUnchecked for serialize.

---

dcrec/secp256k1/error.go
dcrec/secp256k1/error_test.go
dcrec/secp256k1/go.mod
dcrec/secp256k1/pubkey.go
dcrec/secp256k1/pubkey_test.go
hdkeychain/extendedkey_test.go

**This is rebased on #2159**.
This reworks the tests related to public keys to them more consistent with the rest of the package and improve their coverage to include all of the possible error paths, adds the error infrastructure used throughout the rest of the packages, and updates all of the tests to test for the explicit reason for the failure accordingly.
Finally, it also brings back the hybrid pubkey parsing to match what the function comment claims and corrects the tests accordingly.  The restriction as to which specific types of pubkeys are allowed must be (and is) enforced by the opcode(s) that interpret them as opposed to the lib that implements the more generic specification.
Each commit more thoroughly describes the changes being made to ease review.
The following is an …

secp256k1: Rework pubkey tests.

---

hdkeychain/extendedkey_test.go
hdkeychain/go.mod

hdkeychain: Use errors api and require go 1.13+.

---

dcrec/secp256k1/curve.go
dcrec/secp256k1/pubkey.go
dcrec/secp256k1/pubkey_test.go

**This is rebased on #2161**.
This adds a new method to the `PublicKey` type which can be used to determine if the public key is on the `secp256k1` curve directly.
It also adds tests to ensure proper functionality.

secp256k1: Add IsOnCurve method to PublicKey.

---

dcrec/secp256k1/ciphering.go
dcrec/secp256k1/curve_test.go
dcrec/secp256k1/ecdsa/bench_test.go
dcrec/secp256k1/ecdsa/signature.go
dcrec/secp256k1/ellipticadaptor.go
dcrec/secp256k1/ellipticadaptor_test.go
dcrec/secp256k1/privkey.go
dcrec/secp256k1/pubkey.go
dcrec/secp256k1/pubkey_test.go
dcrec/secp256k1/schnorr/signature.go
dcrec/secp256k1/schnorr/signature_bench_test.go
dcrec/secp256k1/schnorr/signature_test.go
hdkeychain/extendedkey.go

**This requires #2157 and  #2162**.
This updates the internal implementation of the `PublicKey` type to use the `FieldVal` type instead of `big.Int`s and modifies `NewPublicKey` to accept the `FieldVal`s and updates all callers and tests in the repository accordingly.
Public key parsing and serialization are now completely free of `big.Int`s.
Finally, it moves the `X` and `Y` methods to the `ellipticadaptor.go` file since they are only intended to provide interop with the standard library elliptic curve adaptor code.
This reduces the number of allocations needed in the ecdsa compact signature recovery as well as schnorr signature verification and results in a slight speedup for both.
The following benchmarks show the before and after comparison:
```
benchmark                 old ns/op …
```

secp256k1: Use specialized types in public key.

---

dcrec/secp256k1/ciphering.go
dcrec/secp256k1/curve_test.go
dcrec/secp256k1/ecdsa/bench_test.go
dcrec/secp256k1/ecdsa/signature.go
dcrec/secp256k1/ellipticadaptor.go
dcrec/secp256k1/ellipticadaptor_test.go
dcrec/secp256k1/privkey.go
dcrec/secp256k1/pubkey.go
dcrec/secp256k1/pubkey_test.go
dcrec/secp256k1/schnorr/README.md
dcrec/secp256k1/schnorr/example_test.go
dcrec/secp256k1/schnorr/signature.go
dcrec/secp256k1/schnorr/signature_bench_test.go
dcrec/secp256k1/schnorr/signature_test.go
hdkeychain/extendedkey.go

**This is rebased on #2163**.
This adds examples for signing a message and verifying a signature over a message for a public key.

schnorr: Add examples.

---

dcrec/secp256k1/bench_test.go
dcrec/secp256k1/pubkey.go

**This requires #2163**.
This modifies the `ParsePubKey` function to avoid an additional unnecessary check if the point is on the curve in the compressed pubkey case because it necessarily has already determined if that is true via the point decompression from the x coordinate.
Also, prevent x from escaping to the heap for the error print in compressed case while here.
```
benchmark                          old ns/op    new ns/op   delta
------------------------------------------------------------------
BenchmarkParsePubKeyCompressed     11901        11745       -1.31%
BenchmarkParsePubKeyUncompressed   335          325         -2.99%
benchmark                          old allocs   new allocs  delta
------------------------------------------------------------------- …
```

secp256k1: Optimize pubkey parse.

---

README.md

This updates the primary `README.md`.
Added clarifying text to inform new users how dcrd is differentiated from other Decred software.
The purpose is to guide people into the easier software bundles at https://decred.org/downloads, and only continue at dcrd if they truly desire.
Added clarifying text that dcrd does not include wallet functionality by itself.
Again, trying to direct new users to https://decred.org/downloads, but added additional text to guide them into the docs.
*Dependencies:* `GOPATH` and `GOROOT` are handled by default since Go 1.8, but many old Go tutorials direct users to play in dangerous waters. This text should help clarify that users don't need to mess with anything, and only Unix-based users need to mess with their $PATH environment variable.
Further, clarified …

docs: Clarify README.md installation guides.

---

connmgr/connmanager.go

req or Addr are potentially not set when the state machine moves to
handleCancelPending. Ignore this case.
Discussed with @davec

connmgr: Fix potential panic via RPC.

---

peer/peer.go

This modifies the peer initialization code to set a default idle timeout of two minutes if the caller did not specify one.
This is desirable since the default is the zero value otherwise, which results in an immediate disconnection for callers that don't specify a timeout.
It is worth noting that the server code already has a default setting that can be configured via the command-line or a configuration file which is used to configure the peers, so this has no effect on `dcrd`, but it is a nice addition for other consumers of the peer package.

peer: Set a default idle timeout if not specified.

---

README.md

This removes the references to btcd from `README.md` since the code base has diverged so much that there isn't very much in common anymore and thus the text no longer reflected reality.
It also removes some stray trailing spaces while here.

docs: README.md updates.

---

wire/common.go
wire/error.go
wire/error_test.go
wire/message.go
wire/msgreject.go
wire/msgversion.go

This updates the error handling in the `wire` package to be more consistent with the rest of the code base, tightens some of the error handling in message parsing to harden the protocol, and adds tests to ensure the error implementations works correctly with the standard library `errors.Is` and `errors.As` functions introduced in Go 1.13.
In particular, the error code semantics have been changed so the first error starts at 0 instead of treating 0 is a sentinel "no error" value because it goes against Go best practices which designed the errors specifically to avoid the use of sentinel values.  Further, the use of 0 as a sentinel means that there are two different ways to indicate "no error", namely nil and an error code of zero.  Thus callers have to know that they need to check for both …

wire: Improve error handling.

---

wire/msgversion_test.go

The structs were created for testing the `DisableRelayTx = true` case, but they weren't being used. Linter didn't pick up on it because they were being modified.

wire: Test no-relay case in TestVersionWire

---

wire/msgaddr_test.go
wire/msgblock_test.go
wire/msgcfheaders_test.go
wire/msgcfilter_test.go
wire/msgcfilterv2_test.go
wire/msgcftypes_test.go
wire/msgfeefilter_test.go
wire/msggetblocks_test.go
wire/msggetcfheaders.go
wire/msggetcfheaders_test.go
wire/msggetcfilter_test.go
wire/msggetcfilterv2_test.go
wire/msggetdata_test.go
wire/msggetheaders_test.go
wire/msgheaders_test.go
wire/msginv_test.go
wire/msgnotfound_test.go
wire/msgpong_test.go
wire/msgreject_test.go
wire/msgversion_test.go

The error handling in the tests for the `wire` package were recently updated to make use of the new `errors.Is` and `errors.As` standard library functions introduced in Go 1.13, but they were only updated mechanically as opposed to being updated to use the new capabilities of `errors.Is` checking for a specific error code as opposed to just the error type.
Consequently, this updates the tests to remove all of the additional type checking via `errors.As` and instead look for the exact expected error code via `errors.Is`.  This change is desirable since only examining the type of error doesn't prove that the test is actually hitting the specific error it intends too, rather only that it is hitting an error of the same type.
It also corrects a couple of tests and error returns that were …

wire: Use new errors.Is capabilities in tests.

---

dcrd.go
server.go

This removes the `interrupt` channel parameter from the `newServer` function since it is no longer used due to the use of contexts instead.

server: Remove unused interrupt chan param.

---

connmgr/log.go
connmgr/seed.go
connmgr/tor.go

This removes the deprecated functions and types from the `connmgr` package since the major module version has been bumped since the last release.
It consists of three commits for easier review which combined remove the following deprecated items:
- `DisableLog` function
- `LookupFunc` type
- `SeedFromDNS` function
- `TorLookupIP` function

connmgr: Remove deprecated funcs and types.

---

config.go
connmgr/tor.go

**This requires #2187**.
Now that the deprecated non-context version of `TorLookupIP` has been removed, this renames the version that accepts a context to take its place.

connmgr: Rename TorLookupIPContext to TorLookupIP.

---

go.mod
go.sum

This updates the main go.mod direct dependencies to account for the recent `rpcclient` bumps as follows:
- github.com/decred/dcrd/dcrutil/v3@v3.0.0-20200503044000-76f6906e50e5
- github.com/decred/dcrd/rpc/jsonrpc/types/v2@v2.0.1-0.20200503044000-76f6906e50e5
- github.com/gorilla/websocket@v1.4.2

main: Update go.mod for recent rpcclient bumps.

---

connmgr/connmanager.go
server.go

`connmgr.CancelPending` currently returns no error if there is no pending connection to an address.
This undesired behaviour was uncovered by the node removal rpctests as reported by @davecgh:
```
$ (go install && cd rpctest && go test -tags=rpctest -run=TestHarness)
--- FAIL: TestHarness (1.46s)
rpc_harness_test.go:202: removeNode on unconnected peers should return an error
FAIL
exit status 1
FAIL    github.com/decred/dcrd/rpctest  2.677s
```

multi: CancelPending error for no pending conns.

---

docs/code_contribution_guidelines.md

Added clarity about multi-line commit messages, as well as defined rules
regarding linking to other issues or PRs.

docs: Update Code Contribution Guidelines

---

connmgr/connmanager_test.go

**This is rebased on #2189**.
This consists of 9 commits which collectively performs a bunch of housekeeping on the tests in `connmgr` to pave the way for converting the `connmgr` to support a context-based lifecycle.
Each commit further describes the changes made to each test along with the reasoning.

connmgr: Perform some test housekeeping.

---

mining.go

**This is rebased on #2195**.
This modifies the background block template generator to ensure all regen even sends respect the context shutdown state to prevent a potential hang on shutdown when the underlying goroutines go away.

mining: Prevent potential shutdown hang.

---

rpcserver_test.go
rpctest/debug.go
rpctest/memwallet.go
rpctest/node.go
rpctest/rpc_harness.go
rpctest/rpc_harness_test.go
rpctest/utils.go
rpctest/votingwallet_test.go

The rpctest suite is useful however it is impossible to debug in its
current state. This diff adds debug and tracing facilities to the test
that are worth keeping.
It adds two global flags `debug` and `trace` that can be enabled when
additional output is required. In addition, it sends the test object
around so that segregated parts of the code use the same logging
facility. And lastly, it will always print `dcrd` panics to the console.

rpctest: Add debug and trace facility to rpctest.

---

README.md
docs/README.md

When linking to Decred.org, pages should end in / to avoid redirects.
Updated docs to use https://decred.org/community/
Updated docs to use https://decred.org/downloads/

docs: Update links to avoid redirects

---

Dockerfile
Dockerfile.alpine

The docker builds currently fail on `master` due to go 1.13+ now being required. This PR updates `Dockerfile` and `Dockerfile.alpine` to use `golang:1.14`.

docker: Update image to golang:1.14

---

dcrutil/util.go
dcrutil/util_test.go

The API can be used to verify signed messages without the need for an RPC connection.

dcrutil: Add VerifyMessage API

---

blocklogger.go
blocklogger_test.go
blockmanager.go

This PR addresses [Issue #1746 (One last "processed blocks" message is not printed after sync)](https://github.com/decred/dcrd/issues/1746) and adds some test coverage for `blocklogger.go`.
The `logBlockHeight` function currently limits logging to one message every 10 seconds to avoid spamming, but this leads to the referenced issue. The issue of spamming a bunch of messages applies only while syncing, so the approach that I took was to always log the message if we are caught up to the sync height.
Let me know if anyone has a better approach for this, and I can adjust, thanks!
Fixes #1746.

blocklogger: Always log when sync height reached.

---

connmgr/connmanager.go
connmgr/error.go
connmgr/tor.go

This defines the connmgr error types compatible with `errors.Is/As` introduced in go 1.13. This also removes the tor success state from the status error set.

connmgr: define connmgr error types.

---

connmgr/connmanager.go
connmgr/error.go
connmgr/error_test.go
connmgr/tor.go

This continues the work which switched the errors in the `connmgr` package to be compatible with `errors.Is/As` introduced in go 1.13 to make it match the best practices.
- Change the name of the error kind type to `ErrorKind`
- Make error definitions constant
- Add comments to all exported functions and types as required by the code contribution guidelines and various linters
- Add a `MakeError` function to create the errors instead of creating the structs with unnamed fields which goes against standard Go recommendations
- Add full test coverage to ensure the definitions work as intended
This is a followup to #2206.

connmgr: Finish recent connmgr err type additions.

---

blockchain/stakeext.go

Both LiveTickets and MissedTickets were incorrectly tagged as not
concurrent safe. However, as these methods work on an immutable tree on
the tip's stake node, there is no way they will be changed at the time
of reading, as only older nodes are pruned.

stakeext: Fix comments on concurrency.

---

txscript/doc.go
txscript/engine_test.go
txscript/error.go
txscript/error_test.go
txscript/opcode.go
txscript/opcode_test.go
txscript/reference_test.go
txscript/script_test.go
txscript/scriptnum_test.go
txscript/stack_test.go
txscript/standard.go
txscript/standard_test.go
txscript/tokenizer_test.go

This updates the `txscript` package to provide support for the `errors.Is` and `errors.As` functions introduced in Go 1.13 per the recently documented best practices.
- Rename the `ErrorCode` type to `ErrorKind` and make it a string
- Implement the error interface on `ErrorKind`
- Update all error code definitions to the new type
- Remove unused `ErrInternal` definition
- Remove error code string map that is no longer required
- Change the error code field of the `Error` type to `Err`
- Implement `Unwrap` on the `Error` type to support unwrapping via `errors.Is/As`
- Remove the `IsErrorCode` function since it is no longer needed due to `errors.Is`
- Update `IsDERSigError` to cope with the changes
- Modify various comments to refer to error …

txscript: Add support for errors.Is/As.

---

rpcserver.go

The input hex string must be exactly 64 bytes, else an error will be
returned.  The input validation previously checked that the length
following decoding was correct, but was missing a check that the
destination slice was not smaller than half the source's length.
Moving the length check first keeps the existing short source check
while also preventing a panic with a long input string.
Fixes #2212.

rpcserver: Avoid panic during hash decode

---

docs/json_rpc_api.mediawiki
rpcserver.go

Replace `noTxInfoError` with `rpcInternalError` when fetching utxo
entry errors in gettxout cmd handler. `gettxout` should never return
`noTxInfoError` because `gettxout` is about tx outputs not txs.
Update code comment and json-rpc docs to more clearly describe the
semantics of the gettxout method, particularly that JSON null is
returned if the requested txout cannot be found either because it
never existed or because it is spent (and possibly pruned).

rpcserver: Internal err on gettxout utxo fetch err.

---

dcrjson/jsonrpc.go
rpcserver.go
rpcwebsocket.go

This reworks the JSON-RPC unmarshalling logic to correct some error handling cases as well as optimize the normal path.
It accomplishes this as follows:
- Removes the custom, and incorrect, unmarshalling code in favor of just unmarshalling into the `Request` struct directly
- Allows the `Params` to be `nil` (unspecified) per the spec
- Corrects the per-entry batch unmarshal logic such that it first unmarshals into an array of `json.RawMessage` and then unmarshals each individual entry into the `Request` struct
- No longer attempts to process non-batched requests that fail to unmarshal properly
Fixes #2217.

rpcserver: Correct JSON-RPC request unmarshal.

---

rpcserver.go

**This is rebased on #2218**.
This modifies the RPC server handler for `getstakeversioninfo` to limit any provided interval counts to the maximum number of intervals that are actually available for retrieval and improves a couple of error messages while here.
Resolves #2220.

rpcserver: Limit getstakeversioninfo count.

---

blockchain/stakeext.go
blockchain/thresholdstate.go
blockchain/utxoviewpoint.go
internal/rpcserver/interface.go
rpcadaptors.go
rpcserver.go
rpcserverhandlers_test.go
server.go

This creates rpcserver.Chain and rpcserver.UtxoEntry interfaces and
respective rpcChain and rpcUtxoEntry adaptors that implement those
interfaces.
This starts to decouple rpcserver from the concrete BlockChain
implementation and allows for mocking those interfaces when testing
rpcserver handlers.
This addresses https://github.com/decred/dcrd/issues/2069 and adds test coverage for the following rpcserver handlers:
- handleCreateRawSSRtx
- handleCreateRawSStx
- handleDebugLevel
- handleDecodeRawTransaction
- handleExistsExpiredTickets
- handleExistsLiveTicket
- handleExistsLiveTickets
- handleExistsMissedTickets
- handleGetBestBlock
- handleGetBestBlockHash
- handleGetBlockCount
- handleGetChainTips
- handleGetCoinSupply
- handleGetTxOutSetInfo

rpcserver: Create Chain and UtxoEntry interfaces.

---

rpcclient/infrastructure.go

This ensures the `rpcclient` automatically reregisters for work notifications on reconnect if it had previously registered for them.
The infrastructure for the notification was added to the rpcclient in #1410, however, it failed to properly set the flag so it would resend the notification on reconnect.

rpcclient: Reregister work ntfns on reconnect.

---

rpcclient/infrastructure.go

This is a backport of #2228 to the rpcclient-v5 release branch.
It ensures the rpcclient automatically reregisters for work notifications on reconnect if it had previously registered for them.

[rpcclient-v5] rpcclient: Reregister work ntfns on reconnect.

---

blockchain/utxoviewpoint.go
blockchain/utxoviewpoint_test.go

This corrects the construction of the view used by the `mempool` when dealing with disapproved blocks and includes new tests to ensure the various disapproval combinations work as intended.
It does not affect consensus code.

blockchain: Correct mempool view construction.

---

rpcadaptors.go

This corrects the adaptor that converts a concrete `blockchain.UtxoEntry` to the `rpcserver.UtxoEntry` interface that was recently introduced #2211.
In particular, it should not return an instance of the wrapper when either the entry does not exist (is nil) or there was an error.

rpcserver: Correct adaptor for utxo entry fetch.

---

blockchain/indexers/README.md

Really minor, but when reviewing the indexing code, I noticed that the README incorrectly states that the address-ever-seen index requires the transaction-by-hash index.

indexers: Fix existsaddridx description.

---

rpcserver.go
rpcserverhandlers_test.go

This updates handleGetBlockchainInfo to properly return blockchain info
in the case of an empty blockchain where only the genesis block exists.
Also added tests to cover `handleGetBlockchainInfo`.
This can be tested manually with an empty blockchain by running `dcrd` with `--connect=127.0.0.1` (so that it doesn't connect to any peers) and `--datadir=~/some-tmp-dir` to give it an empty database.
Fixes https://github.com/decred/dcrd/issues/2235

rpcserver: Handle genesis in getblockchaininfo.

---

peer/peer.go
server.go

dcrd: Skip known inventory in getblocks requests.

peer: Add IsKnownInventory.

---

txscript/consensus.go
txscript/consensus_test.go

This adds tests for the new `IsStrictNullData` function and also updates the function to take a uint32 since it is going to be used consensus via the upcoming decentralized treasury code and therefore types that vary by architecture can't be used.
Finally, it also renames the `expectedLength` param to `requiredLen` to make it more clear it is a requirement.

txscript: Add tests for new strict null data func.

---

txscript/consensus.go
txscript/opcode.go
txscript/script.go
txscript/scriptbuilder.go
txscript/scriptnum.go
txscript/scriptnum_test.go
txscript/stack.go
txscript/stack_test.go
txscript/standard.go

A persistent source of confusion for maintainers has been distinguishing between consensus code and standardness/policy rules when it comes to the `txscript` package.
One of the main reasons for this is that the package itself contains a mix of consensus code, standardness rules, address to script conversion, and transaction signing code due to the fact that the aforementioned code relies on both the ability to parse scripts, which was not possible to do outside of the package prior to the addition of the tokenizer functionality, and some consensus-specific code that is still not exported.
To help make the distinction more clear, the goal is to ultimately move all non-consensus code out of the `txscript` package.  So, in order to facilitate that goal, this exports various functions and …

txscript: Export various consensus funcs and types.

---

txscript/bench_test.go
txscript/consensus.go
txscript/engine.go

**This requires #2244**.
This modifies the signature encoding check function to use the new `secp256k1.ModNScalar` type for the half order check instead of a big int.
The following benchmark shows a before and after comparison of a typical signature encoding check:
```
benchmark                         old ns/op    new ns/op    delta
-------------------------------------------------------------------
BenchmarkCheckSignatureEncoding   79.0         46.9         -40.63%
benchmark                         old allocs   new allocs   delta
--------------------------------------------------------------------
BenchmarkCheckSignatureEncoding   1            0            -100.00%
benchmark                         old bytes    new bytes    delta …
```

txscript: Optimize sig enc check with mod n scalar.

---

connmgr/connmanager.go
connmgr/connmanager_test.go
server.go

This modifies the connection manager handler for failed connections so that it remains responsive to requests when there are multiple simultaneous failed connections in the retry state and adds a test to ensure proper functionality.
While here it also updates a few formatting nits in the server code and modifies the connection manager test code to use `t.Fatal` instead of `t.Fatalf` when the message has no parameters.

connmgr: Remain responsive with simul failed conns.

---

rpcserverhandlers_test.go

This updates the rpcserver handler tests to use a reasonable default
rpcserverConfig.  This allows for less of a need to provide mocks in
every test and instead only override where necessary.  It also reduces
the likelihood of the tests panicking if code is added to rpcserver
where an assumption of a non-nil value is being made.
This is broken up into a few commits to make it easier to review:
- Rework default configs for tests.
- Update tests to use default configs
- Run tests in parallel.

 rpcserver: Rework default configs for tests.

---

dcrec/secp256k1/field.go
dcrec/secp256k1/field_bench_test.go
dcrec/secp256k1/field_test.go

This updates the field normalization code to better secure against the possibility of non-constant time operations due to branch prediction and adds several tests to ensure the new logic is sound.
The following benchmark results show that this implementation is within the margin of error for it to not be statistically relevant and thus has no performance impact.
```
name             old time/op   new time/op   delta
----------------------------------------------------------------------
FieldNormalize   22.1ns ± 1%   22.1ns ± 1%   ~     (p=0.873 n=5+5)
```
This is primarily based on the work of @bmperrea in btcsuite/btcd#1084 based on questions originally raised by @stevenroose.  However, this differs in that it uses an ever so slightly faster implementation by reversing the comparison …

secp256k1: Harden const time field normalization.

---

fees/estimator.go
internal/rpcserver/interface.go
rpc/jsonrpc/types/chainsvrresults.go
rpcadaptors.go
rpcserver.go
rpcserverhandlers_test.go
server.go

Creates a new interface that fees.Estimator satisfies that can be used
with the rpcserver. Corrects some grammar issues and removes the unused
chainserver result type EstimateSmartFeeResult.

rpcserver: Add handleEstimateSmartFee test.

---

go.mod
rpcserverhandlers_test.go

Because handleEstimateStakeDiff calls chain.EstimateNextStakeDifficulty
up to four times, change testRPCChain.estimateNextStakeDifficulty to a
function so that handlers can specify more complex return values. In
TestHandleExtimateStakeDiff, have the test RPC chain return functions
that return results from a queue, allowing for multiple calls with
varying results.
Use go-spew to print test result equality errors so that values of
pointers are also printed.

rpcserver: Add handleEstimateStakeDiff test.

---

rpcserverhandlers_test.go

This is part of https://github.com/decred/dcrd/issues/2069 and adds tests for the following rpcserver handler functions:
- handleGetTicketPoolValue
- handleGetStakeVersions
- handleGetStakeVersionInfo

rpcserver: Add handleGetStakeVersion tests.

---

rpcserverhandlers_test.go

This adds tests for the missed and live ticket rpcs as well as the validate address rpc.

rpcserver: add missed and live tickets rpc tests.

---

internal/mining/cpuminer/README.md
internal/mining/cpuminer/cpuminer.go
internal/mining/cpuminer/doc.go
internal/mining/cpuminer/log.go
internal/mining/doc.go
internal/mining/mining.go
log.go
rpcserver.go
server.go

**This requires #2275**.
This does the minimum work necessary to refactor the CPU miner code into its own internal package.  The idea is that separating this code into its own package will improve its testability and ultimately be useful to other parts of the codebase such as the various tests which currently effectively have their own stripped-down versions of this code.
The API will certainly need some additional cleanup and changes to make it more usable outside of the specific circumstances it was originally designed to support (namely the generate RPC), however it is better to do that in future commits in order to keep the changeset as small as possible during this refactor.
Overview of the major changes:
- Create the new package
- Move `internal/mining/cpuminer.go` -> …

cpuminer: Refactor code to its own package.

---

config.go
internal/mining/cpuminer/cpuminer.go
internal/mining/cpuminer/log.go
rpcserver.go
rpctest/node.go
server.go

**This requires #2276**.
This significantly reworks the CPU miner to make use of the background block template generator that was introduced in the previous release as well as to convert its lifecycle to use the expected pattern for running subsystems based on contexts.
The switch to using the background block template generator provides all the benefits it offers to miners such as:
- Intelligent vote propagation handling
- Improved handling of chain reorganizations necessary when the current tip is unable to obtain enough votes
- Current state synchronization
- Near elimination of stale templates when new blocks and votes are received
This is particularly important in testing scenarios, such as when using the simulation network, since the difficulty is so low that the code this is …

cpuminer: Rework to use bg template generator.

---

internal/rpcserver/rpcserver.go

**This requires #2288**.
This constructs the RPC API semantic version string from the individual major, minor, and path constants versus requiring updates in both places.  This is something contributors have previously forgotten to update, so it makes sense to avoid the need to do it altogether.

rpcserver: Use func for semver string.

---

internal/rpcserver/rpcserverhandlers_test.go

This adds rpc tests for the `verifychain` and `getdifficulty` rpcs.

rpcserver:  add verifychain & getdifficulty tests.

---

internal/rpcserver/interface.go
internal/rpcserver/rpcserver.go
rpcadaptors.go
server.go

This adds the `BlockTemplater` interface to the `rpcserver` package. Its corresponding adapter has also been added.

multi: add BlockTemplater interface.

---

internal/rpcserver/rpcserver.go
rpcadaptors.go
server.go

This adds an rpc adaptor for cpu miner, handling cases where the underlining miner being passed is nil.

multi: add rpcCPUMiner adaptor.

---

blockchain/chain.go
blockchain/prune.go

Profiling revealed that the number one cause of allocations in blockchain is currently due to stake node pruning, which definitely should not be the case.
Upon closer examination, the culprit is that every single time the stake nodes are pruned the entire ancestry of nodes prior to the prune height, including those that have already been pruned, are appended to the list of nodes to prune.  In practice, this amounts to hundreds of thousands of nodes and thus the slice is resized multiple times (likely around 18 times per run given the current runtime semantics).
This remedies that by ensuring that only the nodes that actually need to be pruned are added to the relevant slice and also preallocating space per a hint that will handle the number of nodes expected to be pruned with a 99% …

blockchain: Optimize stake node pruning.

---

internal/rpcserver/rpcwebsocket.go

This modifies the websocket notification manager to make use of the newer pattern that synchronizes the `Run` `context` with an internal `quit` channel to ensure that any exported functions that communicate with the goroutines can't possibly hang during shutdown.
This was previously done by storing the `context` in the struct (which is generally discouraged) and protecting it by a mutex which means every single notification had to take the mutex.
As can be seen by the diff of this commit, this approach is not only more performant, it's also less code.

rpcserver: Use internal quit chan for ws sync.

---

txscript/sigcache.go

This modifies the signature cache `Exists` method to make use of the new efficient equality testing methods provided by the `secp256k1` types versus indirectly checking their equality via their serializations.
The following benchmark shows a before and after comparison of a typical signature cache exists check:
```
name             old time/op     new time/op     delta
-------------------------------------------------------------------------
SigCacheExists   400ns ± 0%      62ns ± 0%       -84.54%  (p=0.000 n=5+5)
name             old alloc/op    new alloc/op    delta
--------------------------------------------------------------------------
SigCacheExists   256B ± 0%       0B              -100.00%  (p=0.008 n=5+5)
name             old allocs/op   new allocs/op   delta …
```

txscript: Check equality via secp256k1 methods.

---

internal/rpcserver/rpcserver.go

The IDs are assigned in increasing order, so this has the net effect
of peer results returned in the order they were connected.  It also
keeps the order the same across multiple calls.
This matches the behavior of the current pull request implementing
getpeerinfo in dcrwallet.

rpcserver: Sort getpeerinfo results by ID

---

txscript/stack.go
txscript/stack_test.go

Profiling shows that approximately 0.67% of the total allocations are coming from `DropN` even though it should realistically be zero.
The cause is that `DropN` returns an error if it is called with 0 and the code that drops the alternate data stack in between scripts calls it with the depth of the alternate data stack, which is almost always zero.
The call has no observable effect on the result of the script execution in that case since the error is intentionally ignored, there is nothing to be dropped, and is therefore correct semantically, however, it is wasteful to generate and throw away the error.
There really is no good reason for the internal stack implementation to return an error from `DropN` when called with 0 since it equivalent to a NOP.
I have done a careful analysis of all …

txscript: Optimize alt stack drop.

---

txscript/engine.go
txscript/log.go

After recent optimizations, the current next biggest offender of more allocations than would be expected revealed by profiling is due to the trace logging closures for the scripting engine execution.
Once upon a time, there was no way to check the current logging level with the logging infrastructure at the time and thus a logging closure was used to defer the fairly expensive construction of the trace logging information until it was actually invoked (meaning tracing is enabled).
However, those closures come at the cost of allocations, and since script execution is something that happens non-stop during normal operation, those allocations really add up, as the profiling shows.
As some point, the logging infrastructure was changed out, and it is now possible to determine the logging …

txscript: Optimize trace logging.

---

peer/log.go
peer/peer.go

Similar to the recent changes made to `txscript` logging, this updates the `peer` code to take advantage of the ability to determine the logging level when constructing expensive log strings in order to avoid the allocations caused by closures and removes the no longer necessary code related to creating them.

peer: Optimize logging.

---

blockchain/blockindex.go
blockchain/blockindex_test.go
blockchain/chain.go
blockchain/chainquery.go

Part of adding nodes to the block index involves updating the current chain tip in order to be able to efficiently keep track of all known chain tips.
Since there can be multiple tips at a given height, the current code uses a slice for each height to track them.  However, this is wasteful since it is extremely rare for there to be more than one chain tip at the same height.
It is particularly notable at startup since the block index has to load up hundreds of thousands of nodes.
Given that, this modifies the chain tip tracking logic to avoid creating a slice unless it is actually needed by making use of an entry with a static field for the normal case and a dynamic slice for the case when more than 1 tip for the height actually exists.
It also keeps a running sum of the total number of …

blockchain: Optimize chain tip tracking.

---

blockchain/indexers/cfindex.go
config.go
docs/json_rpc_api.mediawiki
internal/rpcserver/interface.go
internal/rpcserver/rpcserver.go
internal/rpcserver/rpcserverhandlers_test.go
internal/rpcserver/rpcserverhelp.go
rpcadaptors.go
server.go

This adds full test coverage for the following rpcserver handlers:
- `handleGetCFilter`
- `handleGetCFilterHeader`
- `handleGetCFilterV2`
```
go test -run="TestHandleGetCFilter" -coverprofile=cov.out &&
go tool cover -func=cov.out | grep -E "handleGetCFilter"
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:2199:		handleGetCFilter		100.0%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:2241:		handleGetCFilterHeader		100.0%
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:2331:		handleGetCFilterV2		100.0%
```
Part of https://github.com/decred/dcrd/issues/2069
Closes #2313.

rpcserver: Add tests for cfilter handlers.

---

blockchain/chain.go
blockchain/upgrade.go

This moves the ` stxosToScriptSource` function from `upgrade.go` to `chain.go` to properly indicate that it is used in more than the upgrade code path.

blockchain: Move stxo source to chain.

---

contrib/README.md
contrib/dcr_tmux_simnet_setup.sh
docs/README.md
docs/simnet_environment.mediawiki

**This requires #2317**.
This adds a script for simplifying `simnet` usage by creating a fresh version of a preconfigured environment each time it is started along with documentation that provides information regarding `simnet`, how to make use of the script and environment, including some basic tasks and common issues, as well as some information about manual configuration.
This script is something that has evolved over the years from one I originally wrote and was later modified by Matheus Degiovani to make use of tmux.  The version provided here also contains some new features and convenience scripts that were written specifically to help newer users and simplify common tasks such as performing a chain reorganization and shutting down the environment.
Some of the documentation is based …

multi: Add simnet documentation and setup script.

---

internal/rpcserver/interface.go
internal/rpcserver/rpcserver.go
internal/rpcserver/rpcserverhandlers_test.go
rpcadaptors.go
server.go

rpcserver: Add handleExistsAddress test.
This removes the ExistsAddrIndex method from the SyncManager interface
and replaces it with a new interface ExistsAddresser that supplies the
two methods used by the rpcserver, ExistsAddress and ExistsAddresses.
rpcserver: Add handleExistsAddresses test.
rpcserver: Add exists upper bounds TODOs.
Although permissioned, the RPC server will allow for checking any number
of values for its various exists commands. It would be reasonable to
limit unreasonable requests that could exhaust dcrd's available memory
and cause node failure. Changes will come with a major RPC version bump.

rpcserver: Add handleExistsAddress(es) tests.

---

contrib/dcr_tmux_simnet_setup.sh

This modifies the `ctl` convenience scripts generated by the the `simnet` environment setup script to respect quoted arguments passed to it.

contrib: Respect quoted args in simnet ctl scripts.

---

contrib/dcr_tmux_simnet_setup.sh

This modifies the `simnet` environment setup script to make use of `winpty` when running under `MSYS2` so that it works properly there.

contrib: Support MSYS2 in simnet setup script.

---

internal/rpcserver/interface.go
internal/rpcserver/rpcserver.go
internal/rpcserver/rpcserverhandlers_test.go
rpcadaptors.go

This adds rpc handler tests for `getwork`.

multi: add getwork tests.

---

blockchain/chainio.go
blockchain/chainio_test.go
blockchain/upgrade.go
blockchain/upgrade_test.go

As of this PR, the expected behavior is that there is a single migration that takes around a minute to complete, after which it will no longer be possible to downgrade.
As the warning above notes, if you try to run an older software version after this migration has completed, you will get an error message similar to `Unable to start server: the current database block index version is no longer compatible with this version of the software (3 > 2)`
---
Originally, some information that is related to vote ticket hashes and revocations was added to the block index because it was needed prior to the full node index being available and also because there was no dynamic loading of the relevant stake node information in various circumstances which meant the information had to be available on the …

blockchain: Remove superfluous blockidx fields.

---

internal/rpcserver/interface.go
internal/rpcserver/rpcserver.go
internal/rpcserver/rpcserverhandlers_test.go
rpcadaptors.go
server.go

rpcserver: Add TxMempooler interface.
In order to allow tests to use mocked mempool transaction data, replace
the RPC server's TxMemPool with an interface that satisfies what is
needed for the server.
rpcserver: Add handleExistsMempoolTxs test.

rpcserver: Add TxMempooler interface and TestHandleExistsMempoolTxs.

---

contrib/dcr_tmux_simnet_setup.sh

The prompts when creating the wallet were changed when the wallet
passphrase was part of the application configuration, which caused the
script to hang.  This fixes the hang by replying to the additional
prompt, and updates the script to pipe input to dcrwallet's stdin to
reply to the prompts, rather than using tmux to send keys.

contrib: Update simnet script for dcrwallet master

---

contrib/README.md
contrib/dcr_tmux_simnet_setup.sh
docs/simnet_environment.mediawiki

This modifies the `dcr_tmux_simnet_setup.sh` script to set the root of all of the nodes to the environment variable `DCR_SIMNET_ROOT` when it is set and fallback to the existing path when it is not as well as to use a variable to consolidate wallet creation answers instead of a file so there are no artifacts left.
It also updates `contrib/README.md` and `docs/simnet_environment.mediawiki` to document the new capability.

contrib: Simnet setup script improvements.

---

contrib/dcr_tmux_simnet_setup.sh

This modifies the `dcr_tmux_simnet_setup.sh` script to update the mining and transfer addresses to account for the change to dcrwallet master which always upgrades the cointype on `simnet`.

contrib: Update simnet script for wallet cointype.

---

Dockerfile
Dockerfile.alpine
README.md

This updates the `README.md` to require Go 1.14/1.15 as well as the docker files to use the `golang:1.15` image.

multi: Update for Go 1.15.

---

blockchain/common_test.go

This adds a function to the common test infrastructure to remove deployments for a given vote ID from parameters for use in testing cases where it is useful to ensure behavior is correct on networks for which an agenda is already active before heights that are not possible to hit when the agenda has to be voted in.
Note that it is intentionally unused at this point, but future commits will make use of it.

blockchain: Add test func to remove deployment.

---

rpcadaptors.go
server.go

This removes a few rpcadaptors that are unnecessary since the underlying
types that server provides satisfies those interfaces themselves.  It
also restructures how nil interfaces are passed to rpcserver.Config to
be more straightforward and a bit less code.

server: Remove unnecessary rpcadaptors.

---

blockmanager.go
server.go
upnp.go

This ensures that all code in the `main` package of root module is not exported since none of it should be accessed outside of the `main` package itself.
While here, it also updates the `NAT ` `discover` func to avoid using named variables which ensures error are not shadowed and eaten.

main: Unexport main package exports.

---

config.go
sampleconfig/README.md
sampleconfig/doc.go
sampleconfig/sampleconfig.go

This modifies the `sampleconfig` package to contain a single function named `FileContents` instead of a constant.
This is being done because changing a constant is technically a major semver breaking change while changing the contents returned by a function is not and the goal is to ultimately make the root module semver compliant.

sampleconfig: Make constant a function instead.

---

internal/mining/cpuminer/cpuminer.go

This modifies the error return from `generate` command when mining is already in progress to properly differentiate between the discrete mining and CPU mining cases.

cpuminer: Improve already discrete mining error.

---

chaincfg/simnetparams.go

This allows simnet nodes to run with --rejectnonstd and still receive
votes and advance the network past SVH.
Previously the simnet used a non-push-only signature script, so this
conflicted with the --rejectnonstd mempool policy.
Note that after this change, a corresponding bump in dcrwallet's go.mod is needed to run simnet setups that advance past SVH. A dcrwallet PR will be provided once a final version of this PR is merged.

chaincfg: Make simnet votes standard txs

---

docs/json_rpc_api.mediawiki
rpc/jsonrpc/types/chainsvrcmds.go
rpc/jsonrpc/types/chainsvrwscmds.go

This consists of two commits.
The first oen moves the `rebroadcastmissed` and `rebroadcastwinners` commands from the regular chain server file to the websocket chain server file so they are only registered as available to websocket clients, and 
The second one updates the `rebroadcastmissed` and `rebroadcastwinners` entries in the JSON-RPC API docs to be properly categorized under the Websocket Methods section and updates them to properly call out the associated notifications they generate.

jsonrpc/types: Register rebroadcast as websocket.

---

blockchain/chainio.go
blockchain/upgrade.go

**This requires PR #2170**.
As of this PR, the expected behavior is that there is a single migration that takes around 5 to 10 minutes to complete after which it will no longer be possible to downgrade.
As the warning above notes, if you try to run an older software version after this migration has completed, you will get an error message similar to `Unable to start server: the current blockchain database is no longer compatible with this version of the software (7 > 6)`
---
This adds code to migrate the database to the new schema required by the decentralized treasury implementation.
It involves updating the utxo set and spend journal entries to account for the change of the position of the fully spent bit within the flags from bit 4 to bit 6.  The process can be interrupted at any point …

blockchain: Decentralized Treasury db migration.

---

blockchain/go.mod

This should fix consumers requiring the blockchain module at dcrd
master.  Previously, this would fail, due to an invalid require on the
released v2.0.0 version of standalone/v2, which has not yet been
released.

blockchain: Update unreleased requires to master

---

internal/mempool/error.go
internal/mempool/mempool.go
internal/mempool/mempool_test.go
internal/mempool/policy.go

**Rebased on top of #2170**
_This is part of the treasury decentralization work._
This PR adds separate tracking for tspends in the mempool and adds unit tests in the mempool package for tspend and tadd handling.
Separately tracking tspends is needed in order to provide them to other nodes during startup, which will be done by a new set of messages introduced in a future PR.
Since this work isn't strictly consensus-related it has been split from the main treasury PR.

mempool: Improve tspend tracking and add tests

---

blockmanager.go
peer/go.mod
peer/go.sum
peer/log.go
peer/peer.go
peer/peer_test.go
server.go
wire/common.go
wire/common_test.go
wire/error.go
wire/error_test.go
wire/message.go
wire/message_test.go
wire/msggetinitstate.go
wire/msggetinitstate_test.go
wire/msginitstate.go
wire/msginitstate_test.go
wire/protocol.go

**Rebased on top of ~#2170~ #2350**
~**Includes #2348**~
_This is part of the treasury decentralization work._
This adds a new pair of messages to the peer protocol named `getinitstate/initstate`. These messages are meant to be used as replacements for the `getminingstate/miningstate` messages.
The new messages are more generic and meant to be used for both the existing mining information (head blocks and votes) and other ephemeral data that nodes of the peer network might need. The initial implementation in dcrd additionally offers and responds with treasury spend transactions.
tpends are special transactions in that they are meant to be long-lived in the mempool and not only miner nodes but also voting wallet nodes need to discover them in a timely manner. Thus we introduce this new set …

multi: Add initialstate peer messages.

---

go.mod

Noticed while rebasing another PR that `go mod tidy` on `master` currently results in a diff.
The CI script checks for this in each module, but not in the main directory, so we can add something there to catch this moving forward. I can look at that separately.

main: go mod tidy.

---

blockchain/treasury.go
docs/json_rpc_api.mediawiki
internal/rpcserver/interface.go
internal/rpcserver/rpcserver.go
internal/rpcserver/rpcserverhandlers_test.go
internal/rpcserver/rpcserverhelp.go
internal/rpcserver/treasury_test.go
rpc/jsonrpc/types/chainsvrcmds.go
rpc/jsonrpc/types/chainsvrcmds_test.go
rpc/jsonrpc/types/chainsvrresults.go
rpcclient/extensions.go

**Rebased on top of #2349**
_This is part of the treasury decentralization work._
closes #2326 
This adds a new RPC message named `gettreasuryspendvotes` and its corresponding server and client implementations.
This command can be used to tally the vote count of treasury spend transactions, for the purposes of tracking both ongoing and mined tspends.
The default parameters for this command (i.e. a future `dcrctl gettreasuryspendvotes`) returns the vote counts for all tspends currently in the node's mempool up to the current mainchain tip.
Clients may specify a block (`dcrctl gettreasuryspendvotes <blockhash>`) to verify the count up to some other previous block and may also specify a set of tspends (`dcrctl gettreasuryspendvotes <blockchash> '[<tspendhash1>, <tspendhash2>, ...]'` to …

multi: Add gettreasuryspendvotes RPC command

---

rpctest/votingwallet.go

Tickets and votes were being issued with tx version 0, which is
non-standard.

rpctest: Make votingwallet txs standard

---

chaincfg/mainnetparams.go
chaincfg/testnetparams.go

This updates the minimum known chain work values for the main and test
networks as follows:
> mainnet: 0x00000000000000000000000000000000000000000013e6909b5a73128d52fc6f
> testnet: 0x000000000000000000000000000000000000000000000000e41955f181d00f59

chaincfg: Update min known chain work for release.

---

dcrjson/cmdparse_test.go
dcrjson/doc.go
dcrjson/help.go
dcrjson/jsonrpc.go
dcrjson/jsonrpcerr.go

This updates the copyright year in the files modified since the previous `dcrjson/v3.0.1` release and serves as a base for `dcrjson/v3.1.0`.

dcrjson: Prepare v3.1.0.

---

docs/README.md
docs/assets/module_hierarchy.gv
docs/assets/module_hierarchy.svg

This updates the `docs/README.md` file, module hierarchy graphviz, and module hierarchy diagram to reflect the new module version.

docs: Update for dcrec/secp256k1/v3 module.

---

internal/rpcserver/rpcserver.go

The standard library HTTP server writes all errors using standard error by default when and error logger is not configured.  Currently, an error logger is not being set which means the errors completely bypass the logging system.
Since the required error logger must be from the standard library logging package and a custom logger is used instead, this creates a shim to forward the log messages from a standard lib logger to the RPC server logger and configures the HTTP server to use it accordingly.

rpcserver: Forward HTTP server err msgs to logger.

---

config.go
config_test.go
dcrd.go

This modifies the initial configuration error handling logic to avoid a bunch of duplicate code and fix some cases that were not logging the errors as expected.
It accomplishes this by consolidating the error reporting in a single place in the caller and introducing a custom error type which signals that the usage message should be suppressed in order to retain the primary behavior the originally was the reason for the prints being in the config function to begin with.
Also, the application name is passed into the function now since it is needed in both places.

config: Consolidate error reporting.

---

blockchain/go.mod
blockchain/go.sum
blockchain/stake/go.mod
blockchain/stake/go.sum
blockchain/standalone/go.mod
blockchain/standalone/go.sum
chaincfg/go.mod
chaincfg/go.sum
database/go.mod
database/go.sum
dcrutil/go.mod
dcrutil/go.sum
docs/README.md
docs/assets/module_hierarchy.gv
docs/assets/module_hierarchy.svg
gcs/go.mod
gcs/go.sum
go.mod
go.sum
hdkeychain/go.sum
peer/go.mod
peer/go.sum
rpcclient/go.mod
rpcclient/go.sum
txscript/go.mod
txscript/go.sum

This updates the `chaincfg` module dependencies and serves as a base for `chaincfg/v3.0.0`.
- github.com/decred/dcrd/wire@v1.4.0
The full list of updated direct dependencies since the previous `chaincfg/v2.3.0` release are as follows:
- github.com/decred/dcrd/wire@v1.4.0
Further, the following dependencies that were previously required in the previous `chaincfg/v2.3.0` release are no longer required:
- github.com/decred/dcrd/dcrec/edwards/v2
- github.com/decred/dcrd/dcrec/secp256k1/v2

chaincfg: Prepare v3.0.0.

---

dcrutil/example_test.go
dcrutil/go.mod
dcrutil/util_test.go

**This is rebased on #2381**.
This consists of two commits which result in removal of the `chaincfg` dependency through the use of mock parameters instead.
The first commit cleans up the tests for verify message and also modifies them to use the available mock parameters to avoid an otherwise unnecessary dep on `chaincfg`.
This second commit modifies the example to make use of mock parameters instead of actual parameters from `chaincfg` in order to avoid the otherwise unnecessary dependency on it.

dcrutil: Remove dependence on chaincfg.

---

blockchain/treasury.go
gcs/blockcf2/blockcf.go

This fixes a few treasury-related comments throughout the codebase.
It also has a commit to fix a possible race in an exported function due to missing RLock call.

multi: Fix treasury comments

---

go.mod
rpc/jsonrpc/types/chainsvrcmds.go
rpc/jsonrpc/types/chainsvrresults.go
rpc/jsonrpc/types/chainsvrwscmds.go
rpc/jsonrpc/types/chainsvrwscmds_test.go
rpc/jsonrpc/types/chainsvrwsntfns.go
rpc/jsonrpc/types/chainsvrwsntfns_test.go
rpc/jsonrpc/types/go.mod
rpc/jsonrpc/types/go.sum
rpcclient/go.mod
rpcclient/go.sum

This updates the `rpc/jsonrpc/types` module dependencies, the copyright year in the files modified since the previous release, and serves as a base for `rpc/jsonrpc/types/v2.1.0`.
- github.com/decred/dcrd/dcrjson@v3.1.0
The full list of updated direct dependencies since the previous `rpc/jsonrpc/types/v2.0.0` release are as follows:
- github.com/decred/dcrd/dcrjson@v3.1.0

rpc/jsonrpc/types: Prepare v2.1.0.

---

docs/json_rpc_api.mediawiki
internal/rpcserver/rpcserver.go
internal/rpcserver/rpcserverhandlers_test.go

This adds a reasonable limit to the maximum number of transactions that can be requested through searchrawtransactions.
10,000 seems like a reasonable max to me, especially given that results can be paginated using the `skip` param, but if anyone is aware of a case where client are expecting to fetch more than 10,000 transactions in one call we can increase this.
Closes https://github.com/decred/dcrd/issues/2372

rpcserver: Add searchrawtransactions count limit.

---

rpcclient/go.mod
rpcclient/go.sum

This should fix consumers requiring the rpcclient module at dcrd
master.  Previously, this would fail, due to various undefined
treasury types, which has not been released.

rpcclient:  Update unreleased requires to master

---

server.go

QueueInventory also has the benefit of skipping known inventory.

dcrd: trickle mempool response to peer.

---

blockchain/standalone/error.go
blockchain/standalone/error_test.go
blockchain/standalone/pow_test.go
blockchain/standalone/treasury.go
blockchain/standalone/treasury_test.go
blockchain/validate.go

This updates the standalone error types to leverage go 1.13 errors.Is/As functionality as well as conform to the error infrastructure best practices outlined in #2181.

multi: update blockchain/standalone error types.

---

blockchain/standalone/tx.go
blockchain/standalone/tx_test.go
blockchain/treasury_test.go

This modifies the `IsCoinBaseTx` function to retain the existing semantics regarding coinbase detection logic once the treasury agenda activates.
Specifically, the existing consensus logic regarding the fast heuristic for detecting whether or not a transaction is likely to be coinbase has no restrictions regarding the number of outputs nor the the lengths of the scripts.
Later, once a coinbase is actually validated by consensus, it is required to have a payout to the treasury as well as a provably-prunable output that identifies the block height.
This means that it is technically possible for a miner to create a coinbase that burns coins if they so choose, even though, in practice, it is exceedingly unlikely.
Since the new treasury spend transaction type looks similar enough to existing …

standalone: Retain coinbase detection semantics.

---

blockchain/standalone/error.go
blockchain/standalone/error_test.go
blockchain/standalone/treasury.go
blockchain/standalone/treasury_test.go
blockchain/treasury.go
blockchain/treasury_test.go
blockchain/validate.go
internal/mempool/mempool.go
internal/mempool/mempool_test.go
internal/mining/mining.go
internal/rpcserver/rpcserver.go

**This requires #2388**.
This existing code for calculating treasury spend window values, namely `CalculateTSpendWindowStart` and `CalculateTSpendWindowEnd`, has a couple of footguns:
- The starting value calculation returns totally invalid values without an error when provided with a expiry that is prior to the first voting window
- Expiry values that are invalid for the start calc are valid for the end calc even though they should not be
As a result, the code for handling the error paths in the rpc server and mining code produces error messages that don't make sense in some cases because they blindly print the start value without checking the error.
To remove the aforementioned footguns and also address the incorrect error messages, the following overview of changes are made:
- Replaces …

standalone: Introduce CalcTSpendWindow.

---

internal/rpcserver/rpcserverhandlers_test.go

This fixes a race that occurs when running TestHandleTSpendVotes test cases in parallel.  It fixes the race by specifying a new *dcrutil.Block per test since *dcrutil.Block can't be safely shared across goroutines.
This was pointed out by @JoeGruffins in https://github.com/decred/dcrd/pull/2390#pullrequestreview-498032154.

rpcserver: Fix race in TestHandleTSpendVotes.

---

blockchain/chaingen/generator.go

This ports the current stake difficulty algorithm (DCP0001) to the generator.
Work towards #2090.

chaingen: implement DCP0001 for generator.

---

internal/mining/mining.go

This removes a now unneeded check for unmineable transactions due to
block disapproval from the template generation code.
Previously this check was meant to ensure that the list of transactions
considered for inclusion in a block template did not include
transactions with an input referencing a regular transaction from a
parent disapproved block.
However this check is redudant due to check executed earlier in the
template building loop that asserts all inputs are valid utxos
according to the PoV of the parent block and taking into account whether
the new block being created will approve or disapprove it.
The check being removed had a bug due to the dcrutil.Tx being duplicated
without also copying the internal tree, which caused transactions to
later fail to be added to the template due to …

mining: Remove unneeded disapproval check

---

blockchain/error.go
blockchain/error_test.go
blockchain/validate.go
blockchain/validate_test.go
internal/mining/error.go
internal/mining/mining.go

This is an alternative approach to #2090 which resolves several of the issues it had and is originally based of an idea mentioned by @matheusd in #2047.
---
This modifies the mining template creation logic to prevent creation of templates that would result in an unrecoverable chain     due to inevitable ticket exhaustion.
It is split into two individual commits as follows:
The first commit adds a new function named `checkTicketExhaustion` to `blockchain` which will return a new rule error if extending a given block with another block that contains a specified number of tickets will result in an unrecoverable chain due to inevitable ticket exhaustion along with tests to ensure proper functionality.
The approach taken is such that it should be easy to use in a future consensus change gated …

multi: Add ticket exhaustion check.

---

blockchain/validate.go

This add the code necessary to reject old block versions once the upgrade process to reach the block versions necessary to start the treasury HFV has a super majority.

blockchain: Reject old block vers for tsry vote.

---

blockchain/validate.go

This converts the series of checks that rejects old block versions once a majority of the network has upgraded to a loop.
When there were only a few this didn't matter, but as the number grows, it is nicer to only need to change the number in a single place.

blockchain: Simplify old block ver upgrade checks.

---

docs/json_rpc_api.mediawiki

This updates the JSON-RPC API documentation examples to use the latest released module versions.
Closes #2231.

docs: Update JSON-RPC API examples.

---

internal/mempool/mempool_test.go
server.go

This updates the server configuration of the `mempool` to allow transactions with the treasury transaction version to ensure they are able to relay properly when/if the treasury agenda becomes active.
It also updates the test configuration to use the constant instead of a hard-coded number.

mempool: Allow treasury txn vers as standard.

---

internal/rpcserver/treasury_test.go

Previously you couldn't run simnet without --rejectnonstd so the rpctest
harness setup was left without this.
This ended up letting a bug slip through that would prevent tadds being
added to mempools and relayed through the network.

rpcserver: Add --rejectnonstd to rpctest

---

blockchain/chain.go
blockchain/chain_test.go
blockchain/common_test.go
blockchain/error.go
blockchain/error_test.go
blockchain/fullblocks_test.go
blockchain/fullblocktests/generate.go
blockchain/validate_test.go
blockmanager.go
cmd/addblock/import.go
internal/mempool/error.go
internal/mempool/error_test.go
internal/mempool/mempool_test.go
internal/mempool/policy_test.go
internal/mining/cpuminer/cpuminer.go
internal/rpcserver/rpcserver.go
internal/rpcserver/rpcserverhandlers_test.go

This updates the blockchain and mempool error types to leverage go 1.13 errors.Is/As functionality as well as confirm to
the error infrastructure best practices.

multi: update blockchain and mempool error types.

---

blockmanager.go
internal/mempool/mempool.go
internal/mempool/mempool_test.go
internal/mining/mining.go
internal/mining/mining_test.go
server.go

Relates to #1556 
This pull request modified the mining prioritization logic to sort transactions by an aggregate fee based on a transaction’s ancestors in the mempool.
Currently, the mining code prioritizes transactions by fee and only includes them in the block template if they have no dependencies. When a transaction is included in the block template, it is removed as a dependency from transactions that depend on it, making those dependent transactions eligible for block template inclusion.
Aggregating ancestor statistics for large graphs of transactions in the mempool may have high computational costs. Performing this aggregation in the block template generator would delay miners requesting a block template since all of the aggregation would need to occur for each transaction, at …

mempool/mining: Implement aggregate fee sorting.

---

blockchain/common_test.go
blockchain/error.go
blockchain/error_test.go
blockchain/fullblocks_test.go
blockchain/validate.go
blockchain/validate_test.go
internal/mempool/mempool_test.go
internal/mempool/policy_test.go

This updates the blockchain and mempool packages for the recent conversion to the new preferred error infrastructure to finish a TODO that was mean to take advantage of it as well as address some other nits such as comments that weren't updated properly and test formatting.

blockchain/mempool: Update for recent err convrsn.

---

internal/mining/mining.go

This updates the block versions created by the mining code to produce the latest versions needed to trigger the treasury HFV.

mining: Update to latest block vers for trsy vote.

---

internal/version/version.go

**This requires #2428**.
This clears the `PreRelease` and sets the `BuildMetadata` to `release.local` on the release branch so that anyone building the release branch will end up with version "1.6.0+release.local" indicating it was a local build as opposed to a reproducible release build.

[release-v1.6] release: Bump for 1.6.0.

---

dcrjson/register.go

This modifies the registration function to return an error as expected in the case the same method type is registered more than once and adds code to return an error when the parameter type is already registered for some other method type.
The current code allowed the same method type to be registered again so long as it had the same parameter type associated with it, which is not desirable since it might have been registered with a different set of flags and the new registration would simply be ignored.

dcrjson: Reject dup method type registrations.

---

internal/rpcserver/rpcserver.go

```
Deprecated: Use websocket.Upgrader instead.
Upgrade does not perform origin checking. 
```
https://pkg.go.dev/github.com/gorilla/websocket#Upgrade

rpcserver: Upgrade is deprecated; switch to Upgrader

---

internal/mining/mining.go

This prevents an issue with the way that children are added to the priority queue when building mining templates.  In particular, it
ensures the child has already had priority item built for it before adding to the prioirty queue since it is possible that the child has not yet been seen under certain circumstances such as when there are complicated transaction graphs of unconfirmed transactions.

mining: Prevent panic in child prio item handling.

---

internal/mining/mining.go

This is a backport of #2434 to the 1.6 release branch.

[release-v1.6] mining: Prevent panic in child prio item handling.

---

docs/json_rpc_api.mediawiki

This addresses several issues with the JSON-RPC API documentation.  It is split into several commits to easy the review process.
- docs: Fix JSON-RPC API gettxoutsetinfo description.
- docs: Add JSON-RPC API getpeerinfo missing fields.
- docs: Fix JSON-RPC API gettreasurybalance fmt.
- docs: Fix JSON-RPC API gettreasuryspendvotes fmt.
- docs: Add JSON-RPC API searchrawtxns req limit. 
Closes #2437
Closes #2438
Closes #2439
Closes #2440
Closes #2442

docs: JSON-RPC API Updates.

---

blockchain/stakeversion.go
internal/mining/bgblktmplgenerator.go
internal/mining/mining.go
server.go

This updates mining to take in the block chain related functions that it requires rather than requiring a blockchain.BlockChain instance.
This allows for alternate implementations to be provided for these functions, such as for testing.
Some of the functions, such as `BlockByHash(hash *chainhash.Hash)`, are only used for the tip and therefore _could_ have been defined as something like `BestBlock()` instead (which would internally call `BestSnapshot` and pass that hash to `BlockByHash`).  I decided against this since mining already has already fetched `blockchain.BestState` in most cases, so it would be a bit less efficient to be calling `BestSnapshot` again within these functions.

mining: Move block chain functions to Config.

---

blockchain/chain.go
blockchain/upgrade.go

This fixes the stxosToScriptSource function so that it takes into
account the new treasury transactions which don't have any inputs
(treasury bases and treasury spends).
Previously, the presence of one of this transactions in the blockchain
would cause a panic during addrindex calculation due to previous scripts
for inputs of those transactions not existing.

blockchain: Fix stxosToScriptSource

---

internal/rpcserver/rpcserver.go
rpc/jsonrpc/types/chainsvrcmds.go

This adds support to querying specifically for tadds when using the
getrawmempool rpc call.
It also adds the missing tspend to the help command when using an
invalid txtype argument to getrawmempool.

multi: Add TAdd support to getrawmempool

---

internal/rpcserver/rpcserverhandlers_test.go

Work towards #2069 
```
$ go test -run="TestHandleGetHeaders" -coverprofile=cov.out && go tool cover -func=cov.out | grep -E "handleGetHeaders"
PASS
coverage: 1.3% of statements
ok      github.com/decred/dcrd/internal/rpcserver       0.017s
github.com/decred/dcrd/internal/rpcserver/rpcserver.go:2347:            handleGetHeaders                95.8%
```
I don't believe it is possible to cause the blockheader serializations to fail.

rpcserver: Add handleGetHeaders test.

---

internal/rpcserver/rpcserverhelp.go

This updates the help for the `getrawmempool` `txtype` parameters to specify the new supported treasury types.

rpcserver: Update getrawmempool txtype help.

---

docs/json_rpc_api.mediawiki

This updates the JSON-RPC API documentation for ` getrawmempool` to make it match reality.  In particular, it removes the incorrect information about dcrd not mining, corrects the description, and adds the optional `txtype` parameter along with a list of supported types.

docs: Update JSON-RPC API getrawmempool.

---

internal/rpcserver/rpcserverhandlers_test.go

This adds rpc tests for `ticketvwap`.

rpcserver: add ticketvwap tests.

---

internal/rpcserver/rpcserverhandlers_test.go

**depends on #2407**
This adds rpc tests for `handleTicketFeeInfo`.

rpcserver: add handleTicketFeeInfo tests.

---

blockchain/upgrade.go

This allows version 5 to 6 database upgrades to work again by implementing code that is independent of the main code and works with the data structures as they existed in the version 5 database.
While here, it also updates some other cases in both older and newer upgrade code to make the upgrades stable even if the primary code changes.
An high-level overview of the key changes is:
- Clear the failed validation status of the v2 block index entries   directly instead of loading the code into the main index, modifying it, and flushing it
- Avoid using the unversioned main funcs related to serializing and deserializing the spend journal
- Implement code to directly create a script source from a v2 spend journal entry
- Reimplement the migration code that initializes the v2 GCS filters to …

blockchain: Make ver 5 to 6 db upgrades work again.

---

blockchain/chain.go
blockchain/error.go
blockchain/error_test.go
blockchain/upgrade.go
blockmanager.go

**This requires #2446**.
This removes all code related to upgrading old databases prior to version 5 and adds code so the main dcrd block loading logic is able to query the blockchain if the database is too old to be upgraded and then automatically handle removing and recreating the database when it is.
In other words, there is no manual intervention required by the user as it will behave the same as if the user had manually removed the database and thus redownload the chain from scratch as normal.
Since the blockchain package is used by other callers and utilities as well, the upgrade path is also updated to detect the situation and return an appropriate error along with additional information informing the caller that the version is no longer supported and the database must be removed. …

blockchain: Handle db upgrade paths for ver < 5.

---

blockchain/chainio.go
blockchain/upgrade.go

**This is rebased on top of #2449**.
As of this PR, the expected behavior is that there is a single migration that takes around 30 seconds to complete after which it will no longer be possible to downgrade.
As the warning above notes, if you try to run an older software version after this migration has completed, you will get an error message similar to `Unable to start server: the current blockchain database is no longer compatible with this version of the software (8 > 7)`
---
Since the next release of the software will include a vote to change the consensus rules, this unmarks all blocks previously marked as having failed validation so they are eligible for validation again under what will likely become new consensus rules.  This ensures clients that did not update prior to new rules …

blockchain: Clear failed block flags for HF.

---

go.mod
go.sum

This updates the 1.6 release to use the latest versions of the following
modules which include fixes for some issues discovered in the initial
release candidate:
- github.com/decred/dcrd/blockchain/v3@v3.0.1
- github.com/decred/dcrd/rpc/jsonrpc/types/v2@v2.2.0
- github.com/decred/dcrd/rpcclient/v6@v6.0.1

[release-v1.6] main: Use backported module updates.

---

internal/rpcserver/rpcserver.go
rpc/jsonrpc/types/chainsvrcmds.go

This is a backport of #2448 to the 1.6 release branch.

[release-v1.6] multi: Add TAdd support to getrawmempool.

---

config.go
doc.go

This modifies the default curve used to generate the RPC certificates to be P-256 instead of P-521.  While I very much prefer the stronger curve, unfortunately, Chromium removed support for P-521 and since that is what electron uses under the hood, Decrediton can no longer connect to dcrd RPC servers using a certificate with P-521.

config: Use the P-256 curve by default for RPC.

---

config.go
doc.go

This is a backport of #2459 to the 1.6 release branch.

[release-v1.6] config: Use the P-256 curve by default for RPC.

---

cmd/gencerts/gencerts.go

This modifies the default curve used to generate the certificates by the `gencerts` utility to be P-256 instead of P-521 to match a recent similar change made to the RPC server automatic generation logic.
Unfortunately, Chromium removed support for P-521 and since that is what electron uses under the hood, Decrediton can no longer connect to dcrd RPC servers using a certificate with P-521.
Thus, given the `gencerts` utility is used in various scenarios which involve interop with the aforementioned software, update it as well.

gencerts: Use the P-256 curve by default.

---

cmd/gencerts/gencerts.go

This is a backport of #2461 to the 1.6 release branch.

[release-v1.6] gencerts: Use the P-256 curve by default.

---

lru/kv.go

This fixes a possible race condition that could happen between the Add()
and Lookup() calls when the cache size was small.
When an entry was found in the cache during a Lookup() call, its value
was feched from the internal list node outside the mutex lock. This
could race with a corresponding Add() call when the node was actually
the LRU node and was about to be overwritten.
This could manifest as a race specially when using caches with a very
small size, since it becomes more likely to perform a lookup on an entry
that is about to be concurrently overwritten.
This fixes the issue by moving the code that extracts the value from the
node to be performed with the lock held.
Here's a test that can usually trigger the race detector on my machine. Run it with `go test -race -run …

lru: Fix lookup race on small caches.

---

internal/rpcserver/interface.go
internal/rpcserver/rpcserver.go
peer/peer.go
rpcadaptors.go

This corrects the `getpeerinfo` RPC handler to avoid a panic when the local address is nil which is the case when a peer is not currently connected.  This can happen for cases such as permanent peers and during process shutdown as peers are disconnected and being cleaned up.
While here, it also updates the comments to specifically call out that the `LocalAddr` method returns `nil` when a peer is not connected to better inform callers they are expected to handle that condition.

rpcserver: Correct getpeerinfo for peers w/o conn.

---

internal/rpcserver/interface.go
internal/rpcserver/rpcserver.go
peer/peer.go
rpcadaptors.go

This is a backport of #2465 to the 1.6 release branch.

[release-v1.6] rpcserver: Correct getpeerinfo for peers w/o conn.

---

gcs/bits_test.go
gcs/error.go
gcs/error_test.go
gcs/gcs_test.go
gcs/go.mod

**depends on #2463**
This updates the gcs error types to leverage go 1.13 errors.Is/As functionality as well as confirm to the error infrastructure best practices outlined in #2181.

gcs: update error types.

---

internal/mempool/mempool.go
internal/mempool/mempool_test.go
internal/mining/mining.go

This change modifies the behavior of the mining view to not track ancestor stats for transactions that have too many unconfirmed ancestors in the mempool. Determining an accurate fee rate of all ancestors for a given transaction or aggregating accurate statistics for descendants of a set of transactions re-entering the mempool has polynomial complexity. Not bounding this problem opens the door to a number complexity attacks. By limiting the number of ancestors a transaction may have before ancestor statistics are no longer tracked, the performance of the block template generator should improve given large chains of unconfirmed transactions.
One example would be a “wide” transaction graph where a single base transaction with many outputs has descendants in the mempool where each redeemer …

mempool: Limit mempool ancestor stats.

---

internal/mempool/mempool.go
internal/mempool/mempool_test.go
internal/mining/interface.go
internal/mining/mining_view.go
internal/mining/tx_desc_graph.go

Requires https://github.com/decred/dcrd/pull/2458
This moves txMiningView and txDescGraph to the mining package. This reduces the coupling between the mempool and mining packages and allows mining tests to use the actual txMiningView and txDescGraph implementations.
---
The more immediate reason I am looking to bring this in is that I am working toward adding a mining test harness. In its current state, most/all of the `txMiningView` and `txDescGraph` functionality would need to be duplicated in the test code.
Summary of the changes (unfortunately, this couldn't really be split into multiple commits since the intermediate steps would be in a non-working state):
- Moved the `txMiningView` type and methods to `mining/mining_view.go`.
- Removed `mining.*` everywhere in this file.
- Moved the …

mining: Move txMiningView from mempool package.

---

internal/mempool/mempool.go
internal/mempool/mempool_test.go
internal/mining/mining.go

This is a backport of #2458 to the 1.6 release branch.

[release-v1.6] mempool: Limit ancestor tracking in mempool.

---

internal/rpcserver/rpcserver.go
internal/rpcserver/rpcserverhandlers_test.go
internal/rpcserver/rpcwebsocket.go

This corrects several of the RPC handlers to base the status of whether or not the decentralized treasury rules are active based on the location of the element in question versus whatever the current tip happens to be.
In particular, the following RPCs are corrected:
- `getblock`
- `getblocksubsidy`
- `getrawtransaction`
- `gettxout`
- `rescan`
- `searchrawtransactions`
- `ticketfeeinfo`
- `txfeeinfo`
While here, it also modifies `searchrawtransactions` to use the height in the header instead of performing another lookup from chain since it is already available there and removes a TODO that no longer applies.

rpcserver: Correct treasury vote status handling.

---

internal/rpcserver/rpcserver.go
internal/rpcserver/rpcserverhandlers_test.go
internal/rpcserver/rpcwebsocket.go

This is a backport of #2469 to the 1.6 release branch.

[release-v1.6] rpcserver: Correct treasury vote status handling.

---

go.mod
rpcclient/go.mod
rpcclient/go.sum

**NOTE: This is rebased on top of `rpcclient/v6.0.1` since master has moved on to the rpcclient/v7 development cycle.**
This updates the `rpcclient` module dependencies and serves as a base for `rpcclient/v6.0.2`.
- github.com/decred/dcrd/rpc/jsonrpc/types/v2@v2.3.0
The full list of updated direct dependencies since the previous `rpcclient/v6.0.1` release are as follows:
- github.com/decred/dcrd/rpc/jsonrpc/types/v2@v2.3.0

rpcclient: Prepare v6.0.2.

---

internal/mining/bgblktmplgenerator.go
internal/mining/bgblktmplgenerator_test.go

This fixes race errors caused by incorrect usage of sync.WaitGroup.
sync.WaitGroup has a restriction when first used on an empty value:
calls to Add() and Wait() must be synchronized, such that the initial
Wait() is not called concurrently to any other Add().
However, the background template generator breaks this premise by
allowing invocations of both Wait() and Add() from different goroutines.
For example, Wait() can be called from an rpcserver handler method while
an Add() is called from an internal goroutine. This causes a potential
race condition.
This can be verified by installing dcrd with `-race`, then running the
TestTreasury test of the internal/rpcserver package.
We fix this issue by switching to a local implementation of the wait
group that retains the same semantics as the …

mining: Switch to custom waitGroup impl

---

go.mod
go.sum
service_windows.go

This switches the module used for windows service management from the
old github.com/btcsuite/winsvc to google.org/x/sys/windows.
The old library generated builds with -race that were unusable in
windows and hasn't received any updates recently.

main: Switch windows service dependency

---

blockchain/upgrade.go

This modifies the upgrade logic in `blockchain` to simplify it, avoid some otherwise unnecessary code duplication, and also make it faster to write upgrade code in the future.
It accomplishes this introducing a couple of new functions described below.
It is also split into several commits which further describe each change to ease the review process.
---
The first new function consolidates the logic for the upgrade code that avoids running a single stage again in the case of interrupted upgrades by accepting a callback and key name to use for tracking.
The net effect is that the individual functions that handle whatever migration is necessary by that stage can focus specifically on that logic and the caller then handles whether or not to apply the stage completion tracking by simply …

blockchain: Upgrade simplification refactor.

---

service_windows.go

This switches the Windows service code to use os.Executable() to
determine the full path to the current executable instead of os.Args[0].
os.Args[0] is not stable across different execution contexts in Windows
(for example, cmd.exe will not return the path).
Originated by a comment in #2479 
Tested installing and removing on mingw, cmd.exe and powershell using the actual bin, a symlink and a hardlink.
In the {sym,hard}link cases, the service is installed pointing to the link itself instead of the link's target. The service runs as expected, but I'm not sure whether we want the default install action to point to the link or to the actual binary. I _think_ the current behaviour is the correct one, but I'm explicitly calling it out in the PR in case this isn't actually  expected.
Also, I …

windows: Switch to os.Executable.

---

internal/rpcserver/rpcserver.go

This commit replaces the SHA256 hash of the HTTP Basic Authorization
header with HMAC-SHA256.  The MAC is performed using a random key read
from the cryptographically random source at server creation.
Storing the authentication details with a MAC unique to each startup
hardens the server against certain classes of memory dumping attacks.
While here, a server field that must be accessed atomically was moved
to the top of the structure, to reduce the likelihood of misaligned
access on architectures where that is forbidden.

rpcserver: Hash auth using random-keyed MAC.

---

blockchain/error.go
blockchain/error_test.go
blockchain/fullblocktests/generate.go
blockchain/process.go
blockchain/stake/staketx.go
blockchain/treasury_test.go
blockchain/validate.go
blockchain/validate_test.go
internal/mempool/mempool.go
rpcadaptors.go

The sanity functions, as their comments indicate, are supposed to be context free since they are used on blocks and transactions regardless of their position within the chain.  Further, the positional functions, as their comments also indicate, are supposed to only rely on the position of the block within the chain and having the headers of all ancestors available, but NOT the full block data of all ancestors available.  These restrictions are important for planned future work which intends to decouple the processing order from the download order.
Unfortunately, the decentralized treasury work ignored the intended purpose and introduced context to both the sanity and positional functions.
This restores the intended restrictions by moving all of the checks that depend on the result of the …

blockchain: No context checks in sanity/positional.

---

internal/mempool/mempool.go
internal/mining/mining.go
internal/mining/mining_harness_test.go
internal/mining/mining_view.go
internal/mining/mining_view_test.go

**This is rebased on https://github.com/decred/dcrd/pull/2480**.
This unexports the TxMiningView methods and fields that don't need to be exposed outside of the mining package and additionally renames the Remove method of the TxMiningView type to RemoveTransaction for naming consistency with the AddTransaction method that it also provides.
I was originally going to create an interface in `mempool` for this but decided against it for a few reasons:
- It leads to an awkward interface usage due to how the mining view is used.
- `mempool` has its own instance of a `TxMiningView` and returns a copy of it when requested by `mining` through the `MiningView` method in `mempool`.
- If `mempool` is updated to use an interface, and the `MiningView` `mempool` method is updated to return that …

mining: Unexport TxMiningView methods.

---

blockchain/chain.go
blockchain/difficulty.go
blockchain/error.go
blockchain/error_test.go
blockchain/headercmt.go
blockchain/stakeext.go
blockchain/thresholdstate.go
blockchain/treasury.go
blockchain/validate.go
internal/rpcserver/interface.go
internal/rpcserver/rpcserver.go
internal/rpcserver/rpcserverhandlers_test.go

**This is rebased on #2481**.
This removes several of the error type definitions from `blockchain` in favor of the context error type wrapping an
error kind that can be detected by `errors.Is`.
This is more in line with the new approach to errors as of the introduction of `errors.Is` and `errors.As` and also has another nice benefit of reducing the amount of code related to errors.
It also updates all callers in the repository to account for the changes.

blockchain: Error type consolidation.

---

blockchain/chain.go
blockchain/chainio.go
blockchain/common_test.go
blockchain/go.mod
blockchain/treasury_test.go

**This is rebased on #2487**.
This changes the main chain block cache to a generic LRU cache for blocks that have been recently seen.  This is useful because it is less dependent on the order the block data is seen and it handles its own pruning with LRU semantics.
This currently doesn't make much difference because the block data is processed in the same order it received, but that will not always be the case, so it is beneficial to have cache semantics which do no rely on the exact order of received blocks.

blockchain: Convert to LRU block cache.

---

blockchain/difficulty.go
blockchain/difficulty_test.go
blockchain/validate.go

**This is rebased on #2488**.
This removes the error returns from `calcNextRequiredDifficulty` and `calcNextRequiredStakeDifficultyV2` since they no longer return any errors.
It also updates all the caller and tests accordingly.

blockchain: Remove unused error returns.

---

internal/rpcserver/rpcserverhandlers_test.go

rpcserver: Add handleGetMempoolInfo test.

---

connmgr/connmanager_test.go

This allows all connmgr tests to pass with 200 successful iterations
when run locally from my OpenBSD laptop with an AMD Ryzen 5 2500U CPU.
While here, return the context error from mockDialer (suggested by
@dajohi).
Closes #2504.

connmgr: Increase test timeouts

---

run_tests.sh

This string is meant to describe the command that was run, not
substitute the output of the command into the error message.
While here, use /bin/sh in the shebang instead of bash, as this script
does not use or need any bashisms.

run_tests.sh: Avoid command substitution.

---

blockmanager.go
internal/rpcserver/interface.go
internal/rpcserver/rpcserver.go
internal/rpcserver/rpcserverhandlers_test.go
internal/rpcserver/rpcwebsocket.go
server.go

The current best state snapshot was updated a long time ago to include the next required stake difficulty.  This updates the RPC server, block manager, and broadcast pruning logic in server to make use of that versus making an explicit call.
It also removes the no longer used method from the `rpcserver.Chain` interface, the block manager infrastructure, and related test code accordingly.

multi: Use best state snapshot next stake diff.

---

blockchain/difficulty.go

**This requires #2493**.
This modifies the ` CalcNextRequiredStakeDifficulty` function to accept a hash instead of using the current chain tip as part of an overall effort to make the blockchain module more explicit and less reliant on the current state.

blockchain: Explicit hash in next stake diff calcs.

---

blockchain/agendas_test.go
blockchain/thresholdstate.go
server.go

This modifies `IsLNAgendaActive` to accept a hash instead of using the current chain tip as part of an overall effort to make the blockchain module more explicit and less reliant on the current state.

blockchain: Explicit hash in LN agenda active func.

---

internal/rpcserver/rpcwebsocket.go

The recent change to use a keyed MAC for authentication only updated the header auth path which results in the correct credentials being rejected via the authenticate command path.
This remedies that by making them match as intended.

rpcserver: Make authenticate match header auth.

---

internal/rpcserver/rpcserver.go
internal/rpcserver/rpcwebsocket.go

The comparisons of the hashed authentication details against the
expected values was constant time, but the checks for whether
successful auth matched the admin or limited privileges was not.
Correct this by performing the bitwise OR of each before comparing.

rpcserver: Check unauthorized access in const time.

---

internal/mempool/mempool.go
internal/mempool/mempool_test.go
server.go

This removes code that was introduced to reject sequence locks from the mempool until the fix sequence lock agenda became active since that agenda is now active and buried deep in the chain and thus there is no longer any reason check for it.
It also reworks the sequence lock acceptance tests to test for the explicit reason for a failure to ensure that each test is actually testing the intended condition and to be more consistent with the rest of the code in preparation for removing the old fix sequence locks rejection code..
It is split into several commits to separate the test reformatting from the actual logic changes to ease review.

mempool: Remove old fix sequence lock rejection.

---

blockdb.go
blockmanager.go
server.go

This decouples the block manager from the global config variable as part of an overall effort to eventually split it into its own package.
It consists of three commits which:
- Remove an unused config field
- Decouples the code related to loading and dumping the block database from the block manager and moves it into a separate file
- Adds configuration parameters used by the block manager to its own config struct versus directly using the global config variable

blockmanager: Decouple from global config var.

---

blockmanager.go
internal/mining/bgblktmplgenerator.go
internal/mining/interface.go
internal/rpcserver/interface.go
internal/rpcserver/rpcserver.go
internal/rpcserver/rpcwebsocket.go

This modifies the RPC server to subscribe to the background block template generator when it is enabled instead of passing a callback through several layers.

multi: Subscribe for work ntfns in rpcserver.

---

internal/rpcserver/rpcwebsocket.go

**This is rebased on #2501**.
This adds code to prune old block templates in the async `notifywork` websocket path to mirror the pruning done via the synchronous `getwork` path.

rpcserver: Prune block templates in websocket path.

---

blockchain/chain.go
internal/rpcserver/interface.go
internal/rpcserver/rpcserver.go
internal/rpcserver/rpcserverhandlers_test.go

This modifies `MaxBlockSize` to accept a hash instead of using the current chain tip as part of an overall effort to make the blockchain module more explicit and less reliant on the current state.

blockchain: Explicit hash in max block size func.

---

blockmanager.go
server.go

**This requires #2497**.
This further decouples the block manager from the server by reworking thelogic that determines whether or not the block manager believes the chain is current (synced) and moving the chain callback code from the block manager to server where it more naturally belongs since it is not directly related to sync, rather it is in response to it.
The logic to determine if the block manager believes the chain is current now uses a flag that is protected by a separate mutex and is updated on the fly versus needing to go through a channel and using the current sync peer.
This also has the benefit of much faster state querying and allowing looser coupling of block processing without the potential of deadlocks.
- Avoid …

multi: Handle chain ntfn callback in server.

---

blockdb.go
blockmanager.go
docs/json_rpc_api.mediawiki
internal/fees/estimator.go
internal/mining/interface.go
internal/netsync/README.md
internal/netsync/doc.go
internal/netsync/interface.go
internal/netsync/log.go
internal/netsync/manager.go
internal/rpcserver/rpcserverhelp.go
internal/rpcserver/rpcwebsocket.go
log.go
rpcadaptors.go
server.go

**This requires #2498 and #2499**.
This does the minimum work necessary to refactor the block manager into its own internal package named `netsync`.  The main motivation is that     separating this code into its own package will improve its testability and more cleanly split the details related to syncing with the network from consensus validation.
The API will certainly need some additional cleanup and changes to make it more usable outside of the specific circumstances it currently supports, however it is better to do that in future commits in order to keep the changeset as small as possible during this refactor.
It has been carefully crafted into a series of individual commits that make each step easier to review as it would be a giant blob of changes that would be very hard to review …

netsync: Split blockmanager into separate package.

---

blockchain/stake/internal/ticketdb/chainio_test.go
blockchain/stake/internal/ticketdb/error.go
blockchain/stake/internal/ticketdb/error_test.go

This updates the ticketdb error types to leverage go 1.13 errors.Is/As functionality as well as conform to the error infrastructure best practices outlined in #2181.

internal/ticketdb: update error types.

---

dcrec/secp256k1/ecdsa/error.go
dcrec/secp256k1/ecdsa/error_test.go

This updates the ECDSA error types to leverage go 1.13 errors.Is/As functionality as well as conform to the error infrastructure best practices outline in #2181.

secp256k1/ecdsa: update error types.

---

dcrec/secp256k1/schnorr/error.go
dcrec/secp256k1/schnorr/error_test.go

This updates the Schnorr error types to leverage go 1.13 errors.Is/As functionality as well as conform to the error infrastructure best practices outlined in #2181.

secp256k1/schnorr: update error types.

---

dcrjson/cmdinfo_test.go
dcrjson/cmdparse_test.go
dcrjson/error.go
dcrjson/error_test.go
dcrjson/help_test.go
dcrjson/jsonerr.go
dcrjson/jsonrpc_test.go
dcrjson/register_test.go
internal/rpcserver/rpcserver.go

This updates the dcrjson error types to leverage go 1.13 errors.Is/As functionality as well as confirm to the error infrastructure best practices outlined in #2181.

dcrjson: update error types.

---

dcrec/secp256k1/error.go
dcrec/secp256k1/error_test.go

This updates the sec256k1 error types to leverage go 1.13 errors.Is/As functionality as well as confirm to the error infrastructure best practices outlined in #2181.

dcrec/secp256k1: update error types.

---

blockchain/stake/error.go
blockchain/stake/error_test.go
blockchain/stake/staketx.go
blockchain/stake/staketx_test.go
blockchain/stake/tickets.go
blockchain/stake/tickets_test.go
blockchain/stake/treasury_test.go

This updates the stake error types to leverage go 1.13 errors.Is/As functionality as well as confirm to the error infrastructure best practices outlined in #2181.

blockchain/stake: update error types.

---

internal/mining/bgblktmplgenerator.go
internal/mining/interface.go
internal/mining/mining.go
internal/mining/mining_harness_test.go
server.go

This reworks the mining template generator slightly to remove the leftover unexported block manager facade interface that was used as part of originally separating the code in a separate internal package.
- Introduces `BgBlkTmplConfig` for the background block template generator to mirror the standard approach used throughout the code
- Removes local fields that are now in the new config struct
- Removes `blockManagerFacade` interface which included:
- `IsCurrent`
- `ForceReorganization`
- Adds `IsCurrent` function to new `BgBlkTmplConfig` struct
- Adds `ForceReorganizion` to `Config`
- Updates all code to account for the changes

mining: Remove leftover block manager facade iface.

---

blockchain/doc.go
dcrec/secp256k1/ecdsa/doc.go
dcrec/secp256k1/ecdsa/error_test.go
dcrec/secp256k1/schnorr/error_test.go
dcrjson/doc.go
gcs/doc.go
internal/mempool/doc.go
internal/mining/error.go
internal/mining/error_test.go
internal/mining/mining.go

This updates the mining error types to leverage go 1.13 errors.Is/As functionality as well as conform to the error infrastructure best practices.

internal/mining: update mining error types.

---

config.go
docs/json_rpc_api.mediawiki
go.mod
internal/rpcserver/rpcserver.go
internal/rpcserver/rpcserverhandlers_test.go
internal/rpcserver/rpcserverhelp.go
internal/rpcserver/rpcwebsocket.go
internal/rpcserver/treasury_test.go
rpc/jsonrpc/types/README.md
rpc/jsonrpc/types/chainsvrcmds.go
rpc/jsonrpc/types/chainsvrcmds_test.go
rpc/jsonrpc/types/chainsvrresults.go
rpc/jsonrpc/types/go.mod
rpcclient/chain.go
rpcclient/extensions.go
rpcclient/go.mod
rpcclient/go.sum
rpcclient/infrastructure.go
rpcclient/mining.go
rpcclient/net.go
rpcclient/notify.go
rpcclient/rawtransactions.go
rpctest/rpc_harness_test.go
rpctest/utils.go
rpctest/votingwallet.go

**This requires https://github.com/decred/dcrd/pull/2516.**
This updates the `gettxout` call to add a required `tree` parameter and remove `version` from the result.  The changes include:
- Starting the v3 module dev cycle for the `rpc/jsonrpc/types`.
- Bumping the RPC API version to 7.0.0.
- Removing `version` from the `gettxout` result.
- It is being removed since upcoming changes will be modifying utxo entries to no longer store the tx version, and (per my understanding) the tx version is not really needed for anything by callers either.
- Adding a required `tree` param to `gettxout`.
- Upcoming changes will be modifying utxo entries to be keyed by an outpoint which includes the `txhash`, `index`, and `tree`, which brought up the question of whether we want the server to check both …

rpcserver: Update gettxout params and result.

---

internal/rpcserver/rpcserver.go
internal/rpcserver/rpcserverhandlers_test.go

This adds tests for `handleGetNetworkHashPS` and `handleGetMiningInfo`.
Because the test blockchain `HeaderByHash` must return different timestamps, use a function for `testRPCChain.headerByHash` that can return varying results.

rpcserver: Add handleGet{NetworkHashPS,MiningInfo} tests.

---

internal/mining/mining.go

This change modifies the block template generator to account for some ancestor statistics not being updated correctly during a reorg, which could lead to some transactions being considered lower priority than expected during block template inclusion. In the interest of keeping the scope of this PR as small and focused as possible, obvious optimizations such as using the cached `txDesc.TxSize` rather than recalculating the tx size multiple times throughout the block template generator have not been applied.

mining: Correct fee calculations during reorgs.

---

internal/mining/mining.go

This is a backport of #2530 to the 1.6 release branch.

[release-v1.6] mining: Correct fee calculations during reorgs. 

---

docs/json_rpc_api.mediawiki

The deprecated `hash1` and `midstate` fields were removed long ago.  This updates the API docs to match that reality.

docs: Update JSON-RPC API getwork to match reality.

---

docs/json_rpc_api.mediawiki
internal/netsync/manager.go
internal/rpcserver/interface.go
internal/rpcserver/rpcserver.go
internal/rpcserver/rpcserverhandlers_test.go
internal/rpcserver/rpcserverhelp.go
internal/rpcserver/rpcwebsocket.go
rpc/jsonrpc/types/chainsvrwscmds.go
rpc/jsonrpc/types/chainsvrwscmds_test.go
rpc/jsonrpc/types/chainsvrwsntfns.go
rpcclient/infrastructure.go
rpcclient/notify.go

This removes support from the RPC server for the `notifystakedifficulty` and related `stakedifficulty` notification.
This is being done because it really is not necessary, as evidenced by the fact that nothing actually uses it, and as further described below.
The only time the stake difficulty can change is when there is a new block that falls on a well defined interval, so all clients already know when it can possibly change and can make use of `getstakedifficulty` at the appropriate times if they really need access to it.
Moreover, since the activation of DCP0001, it became possible to independently calculate the stake difficulty from the headers alone, so SPV clients that don't rely on RPC, such as wallets, already calculate it themselves anyway.
In practice, wallets would be the only …

multi: Remove notifystakedifficulty.

---

internal/mining/mining.go
internal/mining/mining_harness_test.go
internal/netsync/manager.go
server.go

**This requires #2519**.
This removes the `ForceReorganization` method and infrastructure from the `netsync` sync manager as it is no longer needed since the blockchain is safe for concurrent access and the additional `mempool` pruning the version in sync manager currently does is not necessary since all siblings that could be the target of a head reorganization are necessarily at the same height and have the same stake difficulty.
It also removes the `ForceReorganization` method from the `mining.Config` struct in favor of the existing `ForceHeadReorganization` that does the same thing.

multi: Remove unneeded ForceReorganization.

---

blockchain/blockindex_test.go
blockchain/chainio_test.go
blockchain/upgrade_test.go
blockchain/validate.go
blockchain/validate_test.go

This updates the block header positional checks to skip the version check for blocks that are known to violate DCP0005.
Due to a bug that has since been fixed, some blocks were accepted that violated DCP0005 by still being submitted on an old block version (version 6 on mainnet) when the majority of the network had already upgraded to the new version specified by DCP0005 (version 7 on mainnet).
The blocks that violated DCP0005 due to specifying the old version were otherwise valid and are now whitelisted so that they will be accepted when fully syncing the chain without checkpoints.
The logic for the old version checks has since been simplified [in this commit](https://github.com/decred/dcrd/commit/f1e004695ec5d40dc05ee62e741528248ededce6) to take all versions into account with a loop so …

blockchain: Whitelist DCP0005 violations.

---

blockchain/blockindex_test.go
blockchain/chainio_test.go
blockchain/upgrade_test.go
blockchain/validate.go
blockchain/validate_test.go

This is a backport of https://github.com/decred/dcrd/pull/2533 to the 1.6 release branch.

[release-v1.6] blockchain: Whitelist DCP0005 violations.

---

go.mod
go.sum

This updates the 1.6 release to use the latest version of the `blockchain` module which includes a fix for an issue discovered in the initial release candidates:
- github.com/decred/dcrd/blockchain/v3@v3.0.3

[release-v1.6] main: Use backported blockchain module.

---

docs/json_rpc_api.mediawiki
internal/rpcserver/rpcserver.go
internal/rpcserver/rpcserverhandlers_test.go
internal/rpcserver/rpcserverhelp.go
rpc/jsonrpc/types/chainsvrresults.go

This updates `EstimateSmartFee` to return `EstimateSmartFeeResult` and updates associated documentation and tests.
Resolves #2268.

multi: use EstimateSmartFeeResult.

---

chaincfg/mainnetparams.go
chaincfg/testnetparams.go

Adds additional seeders for both mainnet and testnet. This will help to
reduce dependency on the decred.org domain, and gives users some
alternatives if they don't want to use the decred.org seeders for whatever
reason.
FYI: @raedah @chappjc

chaincfg: Add extra seeders.

---

blockchain/difficulty.go
internal/rpcserver/interface.go
internal/rpcserver/rpcserver.go
internal/rpcserver/rpcserverhandlers_test.go

**This requires #2518**.
This modifies `EstimateNextStakeDifficulty` to accept a hash instead of using the current chain tip as part of an overall effort to make the blockchain module more explicit and less reliant on the current state.
It also updates a few comments to match reality while here.

blockchain: Explicit hash in estimate stake diff.

---

internal/netsync/manager.go
internal/rpcserver/interface.go
internal/rpcserver/rpcserverhandlers_test.go
rpcadaptors.go
server.go

**This requires #2518**.
This removes the `TipGeneration` method and infrastructure from the sync manager as it is no longer needed since the `blockchain` is safe for concurrent access.

netsync: Remove unneeded TipGeneration.

---

internal/rpcserver/interface.go
internal/rpcserver/rpcserverhandlers_test.go
rpcadaptors.go

This removes the `LocateBlocks` method and related infrastructure from the rpcserver `SyncManager` interface since it is not used.

rpcserver: Remove unused LocateBlocks iface method.

---

config.go
internal/rpcserver/rpcserver.go
server.go

This adds an alternative method for TLS clients to authenticate to the
server by presenting a client certificate in the TLS handshake.  In
order for dcrd to trust this client, the certificate authority must be
added as a trusted root (by default, in clients.pem in dcrd's
application data directory) as well as setting the config value
authtype=clientcerts.  HTTP POST and websocket clients need not
provide HTTP Basic authentication when client certificates are used.
In future changes, TLS client authentication may be used to limit
access to particular RPCs by various clients, which is possible now
that each client can present their own cryptographic identity.
However, at the moment, enabling TLS client authentication requires it
at the TLS listener level, and therefore breaks the …

rpcserver: Allow TLS client cert authentication

---

internal/netsync/manager.go

This removes the `TicketPoolValue` method from the sync manager since it is no longer called by anything and also not necessary because it is available directly from the chain instance.

netsync: Remove unused TicketPoolValue.

---

internal/netsync/manager.go

Currently the sync manager maintains additional state per peer in a separate data structure which is keyed by the peer.  This additional state is then queried each time it is needed.  This leads to having to refer to the peer and the data associated with it via separate variables which makes the code harder to reason about than if it were all associated directly with the single peer variable.
Given that goal, this modifies the sync manager to introduce a new type named `syncMgrPeer` which embeds a regular peer from the peer package and adds additional information controlled by the sync manager.  The mapping is still maintained as it was before, but each handler now looks up the new combined peer at the top and uses that single instance throughout the handler.
The end result is the code is …

netsync: Embed peers vs separate peer states.

---

internal/netsync/interface.go
internal/netsync/manager.go
server.go

**This requires #2541**.
Now that the sync manager is aware of all peers, this modifies it to update their heights upon seeing the relevant announced blocks directly instead of threading back through the server via a callback that required a goroutine to avoid the otherwise circular lock.

netsync/server: Update peer heights directly.

---

blockchain/common_test.go
blockchain/error.go
blockchain/error_test.go
blockchain/process.go
blockchain/process_test.go
dcrjson/jsonrpcerr.go
docs/json_rpc_api.mediawiki
internal/rpcserver/interface.go
internal/rpcserver/rpcserver.go
internal/rpcserver/rpcserverhandlers_test.go
internal/rpcserver/rpcserverhelp.go
rpc/jsonrpc/types/chainsvrcmds.go

**This requires #2518**.
This adds infrastructure to support invalidating arbitrary blocks as if they had violated a consensus rule as well as reconsidering arbitrary blocks for validation under the current consensus rules and includes comprehensive tests to ensure proper functionality.
It also adds two new rpc commands `invalidateblock` and `reconsiderblock` to expose the new functionality and updates the JSON-RPC API documentation accordingly.
Example use cases this enables:
- Revalidating blocks under new consensus rules 
- Consider the case of old software rejecting blocks due to new consensus rules activating on the network and then upgrading to a new version that supports the new rules
- Possibility of manually generating snapshots of historical state such as live tickets and …

blockchain: Add invalidate/reconsider infrastructure.

---

internal/netsync/manager.go
server.go

**This requires #2537 and #2543**.
This modifies the lifecycle of the sync manager to use the expected pattern for running subsystems based on contexts.
In particular, this replaces the `Start` and `Stop` methods with a single method named Run and arranges for it to block until the provided context is cancelled.  This is more flexible for the caller since it can easily turn blocking code into async code while the reverse is not true.
The new `Run` method waits for all goroutines that it starts to shutdown before returning to help ensure an orderly shutdown.
Since there are exported methods that send messages to the event handler goroutine via a channel and that goroutine is stopped during the shutdown process, all sends select across both the channel in question as well as a quit channel …

netsync: Convert lifecycle to context.

---

blockchain/chainio.go
blockchain/chainio_test.go
blockchain/compress.go
blockchain/compress_test.go
blockchain/error.go
blockchain/error_test.go
blockchain/fullblocktests/generate.go
blockchain/scriptval.go
blockchain/sequencelock.go
blockchain/stakeext.go
blockchain/upgrade.go
blockchain/utxoviewpoint.go
blockchain/utxoviewpoint_test.go
blockchain/validate.go
gcs/blockcf2/blockcf.go
internal/mempool/mempool.go
internal/mempool/mempool_test.go
internal/mempool/policy.go
internal/mining/mining.go
internal/mining/mining_harness_test.go
internal/mining/mining_view_test.go
internal/netsync/manager.go
internal/rpcserver/interface.go
internal/rpcserver/rpcserver.go
internal/rpcserver/rpcserverhandlers_test.go
rpcadaptors.go
server.go

**NOTE: This contains a database migration, so if you plan to test it, please make a copy of your data directory first.**
---
This modifies the utxoset in the database and related `UtxoViewpoint` to store and work with unspent transaction outputs on a per-output basis instead of at a transaction level.  This is a port of https://github.com/btcsuite/btcd/pull/1045 with some significant differences due to the stake tree and transactions in Decred.
The primary motivation is to simplify the code, pave the way for a utxo cache, and generally focus on optimizing runtime performance.
The tradeoff is that this approach does somewhat increase the size of the serialized utxoset since it means that the transaction hash is duplicated for each output as a part of the key and some additional details …

multi: Rework utxoset/view to use outpoints.

---

blockchain/chain.go
blockchain/chainio.go
blockchain/compress.go
blockchain/compress_test.go
blockchain/upgrade.go

**This requires #2540**.
Over the years it has become increasingly obvious that storing multiple versioned formats in the database in an attempt to avoid migrations leads to code that is super hard to reason about and for which it is also difficult to assert correctness.
This is the case because it results in a combinatorial explosion of cases that must be handled.  For example, as soon as you have 3 versions, you're already up to 8 variants you have to handle properly and test, and it only gets exponentially worse with each new version.
Due to this, it is greatly preferred to perform a single migration that handles the conversion logic once.  This allows the rest of the code, especially in the critical paths, to work solely with the latest version and therefore it stays much cleaner, …

blockchain: Remove compression version param.

---

blockchain/chain.go
internal/netsync/manager.go
server.go

**This is rebased on #2547**.
This modifies the way inventory announcements are handled to improve efficiency and readability.
Specifically, it switches to a more explicit approach that handles the specific recognized types (blocks and transactions) independently and now determines if they are needed with unique logic for each type as opposed to the more generic inventory-only based approach.
Next, and probably the most important change overall, is that recently confirmed transactions are now tracked by the server and the logic which determines if a transaction is needed now makes use of those tracked transactions as opposed to the previous rather expensive utxo-based query approach.
The reasoning for this change is that the only time honest nodes notify others about transactions are when …

netsync: Rework inventory announcement handling.

---

blockchain/chain.go
blockchain/upgrade.go

This fixes an issue that was introduced by https://github.com/decred/dcrd/pull/2540:
- blockchain: Fix incorrect decompressScript calls.
- This removes calls to decompressScript on scripts that are already decompressed.  The scripts are already decompressed when loaded for V3 spend journal and utxo set entries.
- blockchain: Fix V3 spend journal migration.
- This fixes an issue with the V3 spend journal migration for a case where the ticket minimal outputs will be incorrectly missing in some migrated entries.
- The issue is that when the utxoset is migrated from V2 to V3, the ticket minimal outputs are only kept for ticket submission outputs (output 0).  Additionally, the V2 spend journal only stores the ticket minimal outputs in the last spent entry.  Therefore, for example, in the case …

blockchain: Fix stxo deserialization for indexing.

---

internal/rpcserver/rpcserver.go
internal/rpcserver/rpcserverhandlers_test.go

This modifies the handler for `getblockchaininfo` to avoid calling the `MaxBlockSize` method with the zero hash which happens when queried at the genesis block because that is not supported and results in an error.

rpcserver: Support getblockchaininfo genesis block.

---

peer/log.go

This modifies the debug message summary for `inv` messages that contain a list with multiple items to include a count of the blocks and transactions as opposed to solely the size of the list.  This is useful information for the new sync model to help confirm there are no blocks in the `inv` messages.

peer: Add inv type summary to debug message.

---

internal/rpcserver/rpcserver.go

This fixes a bug where requesting the treasury spend vote counts on the
exact block where it was mined via the gettreasuryspendvotes rpc call
would fail with "tspend outside window".
Explicitly passing the block where the tspend was mined when that block
was the last possible block that particular tspend could be included in
the blockchain would fail because the votes on that block themselves
aren't counted towards determining tspend elligibility: votes are
tallied only up to its parent.
In essence, the test determining the cutoff height had an off-by-one by
using > instead of >= when a block was explicitly specified in the
request.
Before this fix:
```
$ dcrctl --testnet gettreasuryspendvotes "0000002fb43a19427c2c56764134bd1f4de64a5d5973ff4d38131dfa05431293" …
```

rpcserver: Fix count tspend votes in mined block

---

internal/rpcserver/rpcserver.go

This is a backport of #2565 to the 1.6 release branch.

[release-v1.6] rpcserver: Fix count tspend votes in mined block

---

rpctest/node.go
rpctest/rpc_harness.go
run_tests.sh

Before these changes rpc tests would use whatever dcrd was installed on
the system. For the run_tests script, this bin was prebuilt. Change
every use of the rpc test harness to use an executable from a
predetermined path, and build n node in a temporary path when not
supplied. Remove building from run_tests.sh.
closes #2521

rpctest: Don't use installed node.

---

upnp.go

Fixes #1620
`net.LookupCNAME` resolved to a loopback IP for me (127.0.1.1). The router can't port forward to this IP.
before
```
$ ./dcrd --upnp | grep -E "Successfully bound via UPnP|can't add UPnP port mapping"
-8: [WRN] SRVR: can't add UPnP port mapping: error 500 for AddPortMapping
```
after
```
$ git stash pop
$ go build
$ ./dcrd --upnp | grep -E "Successfully bound via UPnP|can't add UPnP port mapping"
-8: [WRN] SRVR: Successfully bound via UPnP to x.x.x.x:9108
```

upnp: Don't return loopback IPs in getOurIP.

---

bech32/README.md
blockchain/README.md
blockchain/chaingen/README.md
blockchain/fullblocktests/README.md
blockchain/indexers/README.md
blockchain/standalone/README.md
certgen/README.md
chaincfg/README.md
chaincfg/chainhash/README.md
connmgr/README.md
dcrec/secp256k1/README.md
dcrec/secp256k1/ecdsa/README.md
dcrec/secp256k1/schnorr/README.md
dcrjson/README.md
dcrutil/README.md
dcrutil/txsort/README.md
gcs/README.md
hdkeychain/README.md
lru/README.md
peer/README.md
rpc/jsonrpc/types/README.md
rpcclient/README.md
rpcclient/examples/dcrdwebsockets/README.md
rpctest/README.md
sampleconfig/README.md
txscript/README.md
wire/README.md

This updates the installation and updating section of the `README.md` files in the various packages to call out the module they are a part of and instruct the consumer to use the standard go tooling instead of the old, and no longer correct, package-based 'go get -u' instructions.
Closes #2557.

multi: Update README.md files for go modules.
