dcrjson/dcrdextcmds.go
dcrjson/dcrdextresults.go
rpcserver.go
rpcserverhelp.go

This RPC command should be able to hold us over until new db has been added which will allow us to more quickly / less expensively track total coin supply.
This is the current implementation in pseudo code:
1) Get tip block height
2) Iterate over all blocks, get block hash then get block header from that hash.
3) If block 1, add block 1 subsidy as defined in chaincfg/params.go
4) If current block is a "reduction interval", then reduce base subsidy accordingly
5) Calculate PoW, PoS and dev subsidy for current block
6) Add subsidies to running total (only PoW and dev if < Stake Validation Height)

Add getcoinsupply rpc command

---

dcrjson/dcrwalletextcmds.go
dcrjson/dcrwalletextresults.go

This adds the JSON handling for the per ticket manipulation of the
VoteBits field in wallet.

Add JSON RPC handling for per transaction VoteBits manipulation

---

mempool.go
rpcserver.go

Although the address indexer for the memory pool was a part of its
struct, it was not enabled in the daemon. The framework to enable it
by default has been completed and the mempool should now correctly
index transactions by address.

Plug in and enable mempool address indexing

---

blockchain/chain.go
blockmanager.go
dcrjson/dcrdextcmds.go
dcrjson/dcrwalletextcmds.go
dcrjson/dcrwalletextresults.go
rpcserver.go
rpcserverhelp.go

The JSON framework has been modified to enable two new RPC calls,
existsliveticket and getstakeinfo. existsliveticket handling has
been added to the daemon RPC. It checks for the existence of a ticket
in the live ticket stake database given a hash.

Add JSON RPC handlers for getstakeinfo and related functions

---

blockchain/checkpoints.go

This value fits the parameters for Decred better.
Based on the conversation on irc this is the correct value and is needed so we can set a checkpoint soon.

Change CheckpointConfirmations to 4096.

---

blockchain/stake/ticketdb.go

Since this is handled automatically and requires no user
action, it probably should not be an error.

Change ticket db desync from Error to Warn.

---

blockchain/chain.go
blockmanager.go
dcrjson/chainsvrcmds.go
dcrjson/chainsvrcmds_test.go
dcrjson/dcrdextcmds.go
rpcserver.go

getrawmempool has been modified to allow for the selection of specific
transaction types from the mempool. A new RPC call, existslivetickets,
has been added. This call takes a blob of ticket hashes and returns
a blob of bit flags specifying whether or not the tickets exist. This
allows for much faster getstakeinfo calls in the wallet.

Add handling of modified getrawmempool RPC call and existslivetickets

---

dcrjson/dcrwalletextcmds.go
dcrjson/dcrwalletextresults.go

Framework handling the new listscripts JSON RPC command for wallet
has been added. This will allow wallet users to dump the complete list
of redeem scripts from their wallet.

Add JSON RPC handling for listscripts wallet command

---

rpcserver.go

The first pass for the getCoinSupply command did not accurately reduce the work and tax subsidies based on the number of voters.  So the coinsupply was slightly high due to blocks that had less than 5 voters not being properly reduced to match the proper total block reward.  Looks like this reduces current coin supply count by roughly 1507 DCR

Fix coin supply counter to reduce work and tax subsidy based on voters

---

version.go

The internal version was still the 0.0.1-beta release. This makes recognizing updates by an external program almost impossible.

Corrected internal verion to release verion

---

blockmanager.go
mining.go

The checkBlockForHiddenVotes function would corrupt block templates
by incorrectly inserting votes from other blocks. The function has
been rewritten and now correctly regenerates the block template with
the correct number of voters.
Fixes #53.

Bug fix for checkBlockForHiddenVotes corrupting block templates

---

blockmanager.go

This bug was introduced with the fix for checkBlockForHidden votes. One of the
consistency checks fails if the template is uninitialized. The unitialized
pointer is now caught and the function will safely return.

Fix a panic caused by accessing unassigned pointer

---

dcrjson/dcrdextcmds.go
mempool.go
rpcserver.go
rpcserverhelp.go

A new RPC function has been added to the daemon to quickly check for
the existence of transactions in the mempool. It handles raw encoded
hex containing transaction hashes and outputs a raw encoded hex of
bit flags. This makes the output size as small as possible while
speeding up the JSON encoding/decoding of the data.

Add the new RPC function existsmempooltxs

---

dcrjson/dcrwalletextcmds.go

This adds the consolidate command to master, enabling a wallet to
consolidate small UTXOs into a large UTXO.

Add consolidate cmd and response framework to the JSON RPC

---

dcrd.go

The 'stop' command would fail to store the ticket database on close because
the Store() function was never called. This ensures that it is called on
closing.
Fixes #49.

Fix storing the ticket database to disk on close

---

mempool.go

It was easy to spam the mempool with vote transactions that could never be
included in blocks. The original parameter for the number of double spent tickets
in the mempool was lax for simulations, but should be decreased to protect
mainnet daemons.

Reduce likelihood of vote spam

---

mining.go

Many of the checks for the type of stake transaction in the main sorting
loop for mempool transactions of NewBlockTemplate were redundant. Now the
cached data for the transaction type is used instead. An expensive lookup
for a transaction cache was also moved for efficiency.

Optimize mining checks for various stake transactions

---

txscript/standard.go

The required number of inputs for a stake P2SH output were incorrectly
estimated by CalcScriptInfo. Now the sub class for any given output is
also checked for whether or not it is P2SH.

Correct the expected number of inputs for stake P2SH outputs

---

blockchain/chain.go
blockchain/stake/ticketdb.go
blockmanager.go
dcrjson/dcrdextcmds.go
rpcserver.go

The RPC command getticketpoolvalue has been added. Calling the
command will return the current value of all the locked stake from
tickets in the ticket pool.

Add and implement the getticketpoolvalue JSON RPC command

---

mempool.go
txscript/script.go
txscript/script_test.go

This is a cherry pick of the upstream commit 3331d6098ba6b1605bfdaaa2de1becfc77e94d74 and is needed for the upcoming wallet sync.
IsUnspendable takes a public key script and returns whether it is
spendable.
Additionally, hook this into the mempool isDust function, since
unspendable outputs can't be spent.

txscript:  New function IsUnspendable

---

peer.go

The upstream project didn't have timestamps in address messages until a certain protocol version, however that doesn't apply to Decred.  As a result, it looks like the check for it was updated to just hard code it to true.  This was accurate, but there is no point in setting something to
true and then turn around and check if it's true one line later.
Consequently, this just removes the check altogether.

peer: Remove extraneous hasTimestamp check.

---

cmd/checkdevpremine/README.md
cmd/checkdevpremine/config.go
cmd/checkdevpremine/main.go

This introduces a new utility named `checkdevpremine` which can be used to test transactions to determine whether or not they have inputs that trace back to the original developer premine coins.

Introduce a new utility to show dev premine taint.

---

blockchain/chain.go
blockmanager.go
dcrjson/dcrdextcmds.go
dcrjson/dcrdextresults.go
dcrjson/dcrwalletextcmds.go
dcrjson/dcrwalletextresults.go
rpcserver.go
rpcserverhelp.go

New JSON handling has been added for the following wallet commands:
accountaddressindex
accountfetchaddresses
accountsyncaddressindex
getwalletinfo
getmasterpubkey has been modified to take an account argument.
The new daemon command livetickets has been added. This command dumps
the hashes for all the live tickets in the live ticket stake database.

Add new JSON handling for RPC commands and livetickets command

---

.travis.yml

The vet tool moved into the Go source tree as of Go 1.5.  Its previous
location in the x/tools repo was deprecated at that time and has now
been removed.
This commit updates the .travis.yml configuration to avoid fetching vet
from the old location and to simply use the version now available as
part of the standard Go install.
Also, while here, remove the check for changing the tool path since it
is no longer needed.

TravisCI: Remove external go vet reference. (#655)

---

config.go
mining.go
mining_test.go

The mining transaction selection algorithm failed to sort the stake
transactions effectively, as well as failed to sorted by fee for
these transactions. The codebase now defaults to no priority size
spacing in the block, correctly sorts transactions by their stake
importance, and then sub-sorts them by fees.

Fix the mining transaction selection algorithm

---

mining.go

A continue statement was missing which could cause an issue when
attempting to iterate through different eligible blocks on the chain
tip to mine off of. The mining code was also amended to make it return
newly generated work later on in the code if for some reason not
enough voters were found, instead of just returning a nil template.

Properly handle attempting reorganization to an eligible block

---

blockchain/stake/staketx.go
dcrjson/chainsvrresults.go
rpcserver.go
rpcserverhelp.go

Ticket commitments (address and amount) are not properly displayed
by getrawtransaction verbose requests.

Display ticket commitments in getrawtransaction

---

mempool.go

Before you could use dcrctl sendrawtransactions <rawbytes> with a transaction that has unknown inputs, but it would act like it sent sucessfully (no error and return txid).  But, in fact, the tx was reject due to it being an orphan (spending unknown inputs) and it should accurately err out and tell the user of this.

Check to see if missingParents != nil which means isOrphan

---

dcrjson/dcrwalletextcmds.go

The purchaseticket RPC command has been modified to add the new fields
now used by wallet.

Modify the purchaseticket RPC command

---

blockmanager.go
mempool.go
rpcserver.go

If the tx fee/kb are 100x above the minimum (1e6 atoms) and AllowHighFees is false (default), then error and don't allow the tx to be broadcast.
This will not effect any other incoming tx to this node, it is only being checked for sendrawtransaction coming out of that node.
Fixes issue 187 in dcrwallet

Use AllowHighFees in SendRawTransaction cmd to actually check tx fees

---

dcrjson/dcrdextcmds.go
dcrjson/dcrdextresults.go
rpcserver.go
rpcserverhelp.go

The new RPC command ticketfeeinfo has been added. It provides
statistical information about ticket fees per kilobyte for the
mempool, recent blocks, and recent difficulty windows.

Add ticketfeeinfo command

---

blockchain/difficulty.go
blockmanager.go
dcrjson/dcrdextcmds.go
dcrjson/dcrdextresults.go
rpcserver.go
rpcserverhelp.go

The new RPC command estimatestakediff was added. It estimates the
minimum and maximum next stake difficulty. The caller can also
estimate a new difficulty given a passed number of tickets to be
mined in the remaining difficulty period.

Add estimatestakediff RPC command

---

sample-dcrd.conf

closes #116
verified that the rcp server by default only listens on the localhost

fix sample config per issue 116

---

mempool.go

Recreated 907152c commit from btcd
Previously mp.lastUpdated = time.Now() needed to be locked for access.  With the use of atomic.StoreInt64, it allows us to remove the now unneeded lock in LastUpdated which can run without racing in mempool.

mempool: reduce lock contention

---

blockmanager.go
mempool.go
mining.go

The mempool would allow low stake difficulty tickets and then remove
them after the next block was added. This prevents too low difficulty
tickets from being added in the first place. It also refactors some of
the old code in mempool.go, blockmanager.go, and mining.go for
efficiency.
Fixes #153.

Reject too low stake difficulty transactions and cache difficulty

---

blockmanager.go
mempool.go
rpcserver.go
server.go

The mempool would hang when processing orphans occasionally because 
some orphans would be added continuously to the orphan pool. This was 
fixed in btcd previously by changing a list to a map.

mempool: Synchronize btcd commits fixing orphan hang

---

signal.go
signalsigterm.go

When an OS reboots or shuts down, it sends all processes SIGTERM before
sending SIGKILL.  This allows dcrd to do a proper shutdown which most
importantly closes the databases.

dcrd: handle signal SIGTERM (#688)

---

blockchain/stake/ticketdb.go

The ticket database would restore from the genesis block if it failed
the check to see if the tip matched with the database best block. This
corrects the resyncing such that if it finds a matching block for the
ticket database top block in the database, it instead resyncs from that
block instead of the genesis block.

Fix resyncing the ticket database after unexpected shutdown

---

dcrjson/dcrwalletextcmds.go
rpcserver.go
rpcserverhelp.go

The createrawssrtx could not produce correctly formed revocations.
The code has been corrected to call the correct internal API. A
new 'fee' option was added to the JSON command to add a fee to the
revocation.

Fix createrawssrtx command and logic

---

config.go
mempool.go

Very old votes are now rejected from the memory pool by default.
The feature can be disabled with a runtime flag. A redundant
function that determined the transaction type was also removed
from mempool.go.

Reject very old votes from the memory pool

---

txscript/internal_test.go
txscript/script.go
txscript/script_test.go
wire/common.go

Legacy transaction deep copy code mandated by the Bitcoin protocol
caused large amounts of data to be copied needlessly. If the
optimization for SigHashAll is set in chaincfg/params.go, these
extra copies are avoided by directly writing the pkScript and
decorations to a buffer and then hashing to get a witness hash,
while using the cached hash for the prefix.
Fixes #126.

Waste less memory if sighash optimizations are on

---

wire/msgaddr.go

Legacy msgaddr encoding for Bitcoin caused getaddr response
failure when message protocol version was >1. This fixes this
bug.

Remove legacy Bitcoin addr encoding bug

---

config.go
doc.go
peer.go
sample-dcrd.conf
server.go
txscript/script.go
wire/doc.go
wire/msgminingstate.go
wire/msgminingstate_test.go
wire/msgversion.go
wire/protocol.go
wire/protocol_test.go

This sync includes a new service flag named `SFNodeBloom` that a node is required to use to indicate that it supports bloom filtering.  This includes a protocol version bump to `2` and a wire version bump to
`0.1.0`.
dcrd:
The `SFNodeBloom` flag is set by default.  A new configuration option `--nopeerbloomfilters` has been added to to disable bloom filtering.
Also, it corrects an issue with the mining state message where it was using the network protocol version instead of having its own version.

Sync upstream through Sep 28, 2015.

---

wire/protocol.go

This modifies the `wire.ServiceFlag` stringer to use the ordered slice of flags to ensure that the human readable representation of the flags is always in a well defined order.  This is not only useful for humans, but it also allows the output to be deterministically tested.

wire: Use ordered Service Flags.

---

rpcserver.go

**NOTE: Sync from upstream through Sep 30, 2015**
This optimizes the `createVinList` function which is used to generate the JSON list of transaction inputs.  It also makes it more consistent with the `createVinListPrevOut` function.
In particular, it entails the following changes:
- Only do a single coinbase check and return right away instead of checking multiple times inside the loop over the inputs
- Use a pointer for populating the details of each entry to avoid multiple unnecessary array lookups and bounds checks
- Group all fields that populate the entry for better readability

rpcserver: Optimize JSON raw tx input list create.

---

dcrjson/chainsvrresults.go
dcrjson/chainsvrresults_test.go
rpcserver.go
rpcserverhelp.go

The VinPrevOut fields in Decred did not correspond to the
contents of Decred TxIns. This was modified so that these
are included.
Fixes #173.

Fix VinPrevOut fields for Decred

---

dcrd.go

This reduces the target ratio of freshly allocated data to live data to
10% in order to limit excessive overallocations by the garbage collector
during data bursts such as processing complex blocks or rapidly
receiving a lot of large transactions.

main: Limit garbage collection percentage. (#686)

---

mempool.go
mining.go
policy_test.go
rpcserver.go

Use same fee policies across all networks.

---

rpcserver.go

Upstream commit 07406791c9b09beb2b9ca97260017ab1ebe04067
All other commits in the merge have already previously been cherry-picked and therefore are NOOPs.

rpcserver: Correct verifymessage hash generation.

---

config.go
doc.go
mempool.go
mining.go
policy.go
policy_test.go
rpcserver.go
sample-dcrd.conf

Upstream commit a56db22e9be1c5436c952dbee1af582f5b7c8976

config: New option --minrelaytxfee

---

README.md
blockchain/README.md
chaincfg/README.md
database/README.md
dcrec/secp256k1/README.md
dcrjson/README.md
peer/README.md
txscript/README.md
wire/README.md

Upstream commit 3942a116e4a6d15ae50204b6d5b06bd3ecead57f
This merge also includes a few Decred specific modifications and corrects some old `btcjson` references that should have been updated to `dcrjson`.

docs: Make various README.md files consistent.

---

chaincfg/params.go
params.go
server.go

Upstream commits:
- aa0efa1f3ec03b8d0d77e3b1caf55dfb178dbf07
- cb71f278ec1e185408e72acd2ab8f9291ff3ca10
The IPv6 zone handling had already been cherry-picked in the past, so that commit is a NOOP.

chaincfg: Move DNS Seeds to chaincfg.

---

peer/peer_test.go

Upstream commit 21d11e280987c93a1ad376ebecf0789c8c78783a

peer: Fix failing test case due to wrong TimeOffset

---

peer/peer.go
server.go

Cherry-picked various upstream commits that help with issues in the new peer package.  Mainly, a panic (most likely due to out-of-memory) from endless peerDoneHandlers being spawned.
After checking profile routines on master (400+ peerDoneHandler) with this PR (13-16 peerDoneHandler) it appears that the issue should be fixed.
Btcd upstream commits:
-7996eb1f9deee90a070e2d6455c71bd5738192f5
-89af747603fad09130129fa4688eaab53c0abdba
-d0f0a2ac02596ff312987fa1fe75972e5bf9a227
-f41ff545be905bd658084772a5826f4d091f1e2d
-d0cdd53720276ee3499ff56ab1ce7d22601d8d9a

peer/server: various fixes from upstream

---

mempool.go
peer/peer.go

Upstream commits
- 5016675d40c85e1db25fb54fe14c15d9681fd487
- d765c73a419087c637ba03ff79d8d2f21040d70a
The changes in d765c73a419087c637ba03ff79d8d2f21040d70a had previously been cherry-picked, so it's effectively a NOOP.

mempool/peer: Sync upstream comment updates.

---

mempool.go
policy.go
policy_test.go

Upstream commit 58e2762158fbd25134f715171287116167e974d6.
In addition to the normal required changes for syncing, the following changes have been made in order to facilitate integration into Decred:
- Modify the tests to include the new wire fields rather than letting them by set by the default val so they are more explicit
- Update policy tests to check for > 4 nulldata outputs as nonstandard

mempool: Move checkTransactionStandard to policy.

---

dcrjson/chainsvrcmds.go
dcrjson/chainsvrcmds_test.go
dcrjson/chainsvrresults.go
rpcserver.go
rpcserverhelp.go

**This PR codepends on decred/dcrrpcclient#25**
- 365b1bd156bdb9e4972d155ae8c7f939cf786e18
- Previously cherry-picked so it is a NOOP
- b691a222d564e222801d2136489f8758b9154a16
- Reverted because Decred uses a different signature algorithm
- c7eaee60208ba0d3acf5cd541996a3f8841e1187
In addition to the normal required changes for syncing, the following changes have been made in order to facilitate integration into Decred:
- Rework the code which extracts stake submission outputs a bit to be a little more efficient and to better fit with the code being merged

rpcserver: Add filteraddrs param to srt API.

---

peer/peer.go
peer/peer_test.go

- 0c3cf63773370d9c44eb1b47944c951ca0749d5d
- ee8601ecacf43b625eb17e0d801139e83b7d0c04
- Reverted because btcd releases do not apply to dcrd
- 23df5ed2fc06b96b90ae2d8c4ef0eb44182ecc7d
- Reverted because btcd releases do not apply to dcrd
- 6c00d079106efe16ec825c4fd6de9a87ba51b415

peer: Combine stats struct into peer struct.

---

config.go

- d0f0a2ac02596ff312987fa1fe75972e5bf9a227
- This commit has already been cherry-picked so it is a NOOP
- 09874f1e9115b56573168cf2d310357356c9d80a

Fix dropaddrindex flag usage message

---

cpuminer.go
mempool.go
mining.go
rpcserver.go

Upstream commit 2b6a9a56e58efb43eeee86f0be4c6d578a4b3662.
**NOTE: This is only merging in the upstream changes, so while they are useful for Decred as well, this merge commit does fully separate the mempool as upstream does due to the new functionality provided by Decred.**

mempool/mining: Introduce TxSource interface.

---

mempool.go
mining.go
server.go

Upstream commit 83bcfea271da8b0c890ede7ef374c5a74ec5aad7.
In addition to the normal required changes for syncing, the following changes have been made in order to facilitate integration into Decred:
- Configure the NewestSha function to the new mempool config as a closure over the block manager state instead of using the database func directly
- Add a new NextStakeDifficulty callback to the new mempool config for obtaining the next stake difficulty from the block manager and configure it as a closure over the block manager state

mempool: Introduce mempoolConfig.

---

cpuminer.go
mempool.go
mining.go
mining/README.md
mining/mining.go
mining/policy.go
peer/peer.go
rpcserver.go
server.go

Upstream commit 2a7f41cddb9174ee3d72a5a78f90334aa9c99c9f.

peer: Add DisableRelayTx to config.

---

cpuminer.go
mempool.go
mining.go
mining/README.md
mining/mining.go
mining/policy.go
peer/peer.go
rpcserver.go
server.go

- 2f6aeacfab95db5c6afee054f8a118aee5821c97
- This commit has already been independently applied so it is mostly a NOOP except for a comment update
- 542844832e6eccbce6c0650ba5d244562c60e09b
- This commit has already been cherry picked so it is mostly a NOOP
- 4d40a2110a044113e4f19a7fdeb2d2b0c8893269

peer: Rename variable for consistency.

---

peer/peer.go
server.go

Upstream commit 383ed041ec5c4803581e5b6eafa231e62c78dda7.

Use atomic operations instead of mutexes.

---

peer/doc.go
peer/example_test.go
peer/peer.go
peer/peer_test.go
policy_test.go
server.go
wire/doc.go
wire/message.go
wire/msgsendheaders.go
wire/msgsendheaders_test.go
wire/msgversion.go
wire/protocol.go

- d127ad4083a2db4f334f4a47ea02337a6f8a0590
- This commit has already been cherry picked and is a NOOP
- d759d1d3df441bb81972ba9238fc80053af5fa25
- This commit was originally cherry picked from Decred and is a NOOP
- d127ad4083a2db4f334f4a47ea02337a6f8a0590

server: Make consistent use of svr peer stringer.

---

peer/doc.go
peer/example_test.go
peer/peer.go
peer/peer_test.go
policy_test.go
server.go
txscript/opcode.go
wire/doc.go
wire/message.go
wire/msgsendheaders.go
wire/msgsendheaders_test.go
wire/msgversion.go
wire/protocol.go

- d272bfebb74eaaf26214d9b473acf4aa8efb9ae4
- This commit was originally cherry picked from Decred and is a NOOP
- 9abc2c0e19eee22048fa7b070b98e543fea42a60

txscript: Comment improvements and fixes

---

config.go
doc.go
dynamicbanscore.go
dynamicbanscore_test.go
mempool.go
peer/doc.go
peer/example_test.go
peer/peer.go
peer/peer_test.go
policy_test.go
rpcserver.go
sample-dcrd.conf
server.go
txscript/opcode.go
wire/doc.go
wire/message.go
wire/msgsendheaders.go
wire/msgsendheaders_test.go
wire/msgversion.go
wire/protocol.go

- 907152cef9714be35f6e32352268a23dc76bdb9c
- This commit has already been cherry picked from Decred and is a NOOP
- c75fea9c94ed90090b766514e4cd2abce2fb7ae7

Implement banning based on dynamic ban scores

---

blockmanager.go

Upstream commit cab74feb59e5b3aaa20e83a6ea8fdd69e7638c15.

Keep track of recently rejected transactions.

---

blockmanager.go
cpuminer.go
mining.go
rpcserver.go

Upstream commit a3fa06674512523f61a50c67a4a8f315749fcd1e.
Also updates all of the new references for the newly exported fields as part of the merge commit.

mining: Export block template fields.

---

blockmanager.go
cpuminer.go
mining.go
rpcserver.go

Upstream commit 23f59144c7755dd980b52dfaf40676e97d5905a7.

server: Optimize map limiting in block manager.

---

chaincfg/params.go
chaincfg/params_test.go

Upstream commit c7e5d56b58ec07cd0cb0a32fe8d96d6eccd54e4b.

chaincfg: Register networks instead of hard coding.

---

config.go
mempool.go
rpcserver.go
server.go
txscript/engine.go

Upstream commit 123ff368f4cb0c0a9125e5450dfb806b9ec85efc.
NOTE: This does not separate the new Decred-specific mempool policy-related variables into the new policy structure.  That needs to be done as a separate pull request.

mempool: Create and use mempoolPolicy.

---

blockchain/process.go

Add a logger message containing the time it takes to process a block.

Log block processing time in CHAN with debug on

---

rpcserver.go

The median function was not operating on a sorted array, so the result was a random transaction's fee. The modified function sorts the slice, so a copy may be needed, but the callers in ticketfeeinfo do not seem to require the array in the original order.
Note: For length 0 slice, it returns 0.  Is there a more appropriate Amount?
Requires dcrutil.AmountSorter PR https://github.com/decred/dcrutil/pull/12

Fix median of slice of Amounts for ticketfeeinfo.

---

blockmanager.go

The TicketPoolValue value call being routed through the block 
manager caused it to block for extended periods of time, often 
causing slow processing. Now it is handled asynchronously.

Asynchronously call TicketPoolValue to stop block manager blocking

---

blockchain/stake/internal/tickettreap/README.md
blockchain/stake/internal/tickettreap/benchmark_test.go
blockchain/stake/internal/tickettreap/common.go
blockchain/stake/internal/tickettreap/common_test.go
blockchain/stake/internal/tickettreap/doc.go
blockchain/stake/internal/tickettreap/immutable.go
blockchain/stake/internal/tickettreap/immutable_test.go
blockchain/stake/internal/tickettreap/mutable.go
blockchain/stake/internal/tickettreap/mutable_test.go

Ticket voting selection and validation require fast access to a lexicographically sorted list of all available tickets.  The current implementation stores these tickets in bucketized maps which are
unordered.  This means the data has to be sorted every time it is needed in order to select a ticket and validate a block.  On my hardware, the process of removing tickets that have been voted and adding new tickets takes ~27ms with the current implementation.
In order to speed this up, this introduces a new internal package named `tickettreap` that provides a tailored `treap` data structure that is intended to be used for the in-memory live ticket pool when the new database and `blockchain` enhancements have been synced from upstream.  Since it maintains the data in sorted order, it provides a …

stake: New package for fast access to live tickets.

---

server.go

having 3 int32s above the uint64s in the struct
will cause misalignment for some 32-bit architectures.
see https://golang.org/pkg/sync/atomic/#pkg-note-BUG
This aligns bytesReceived and bytesSent.

fix memory allignment for 32-bit architectures (#668)

---

cmd/dcrctl/config.go

This interferes with the installer when it tries to detect if the
required .dirs already exist or not.
Debated with jrick and ay-p.

Don't create .dcrd willy-nilly.

---

cmd/dcrctl/config.go
config.go
config_test.go

This is being cherry-picked from upstream btcd and has been modified to integrate with dcrd by Dave Collins.

Add automatic RPC configuration.

---

cmd/dcrctl/config.go
config.go

The configuration autogenerator currently does not work well
and tries to read the sample file based on where the compiled
source's data directory was. This has been fixed so that the
most common directories where the sample configuration file
might be stored are searched. The configuration file is also
now generated in the correct place in Windows.
Fixes #289.

Attempt to fix the broken paths in config autogen

---

config.go
sample-dcrd.conf

addrindex does not currently work so do not allow it as an option.
The code for it is still currently there, but no longer hooked in
to something users can set.
Closes #282

Remove --addrindex option.

---

rpcserver.go

The coin supply calculation was inaccurate. It has been fixed to
exactly calculate the coin supply based on the history of the
blockchain.

Fix the coin supply calculation

---

server.go

A simple printf shows dozens of AfterFuncs being generated, especially
on testnet where the connectable node count is currently low.  By
resetting the timer, it prevents needless wakeups from filling the
channel.

dcrd:  Do not send a wakeup if not sleeping

---

dcrjson/dcrwalletextcmds.go

Update dcrjson to support address argument added to consolidate in dcrwallet.  Supports https://github.com/decred/dcrwallet/pull/323

dcrjson: Add address argument to consolidate.

---

blockmanager.go

When a main chain block has been reorganized out, the current
template for mining should be dropped because the parent no
longer exists in the main chain. Fixes #324.

Fix a mining bug that occurs during reorgs

---

upgrade.go

Startup would fail if there was no preexisting folder for the
selected blockchain.

Don't fail if no blockchain folder exists

---

blockmanager.go
rpcwebsocket.go

There were two major regression related bugs from merging in the new
database. The first was failure to properly notify transactions in the
stake tree. The second was that the wrong sentinel value was being
used to terminate the rescanning loop, which normally causes
registration for relevant outpoints and addresses. Both bugs are
patched.

Fix merge regression bugs relating to transaction notifications

---

config.go
dcrd.go
ipc.go
rpcserver.go
server.go
service_windows.go
signal.go
signalsigterm.go

Rewrite startup/shutdown logic to simplify shutdown signaling.  All
cleanup is now run from deferred functions in the main function.
Add two new config options to set the read and write ends of a pair of
pipes.  This is used as a simple mechanism for a parent process to
communicate with, observe, and manage the lifetime of a child dcrd
process.  When the RX (read end) pipe is closed, clean shutdown
automatically begins.
Add a new flag --lifetimeevents to create and send lifetime event
notifications over the TX (write end) pipe during bringup and
shutdown.  This allows the parent process to observe which subsystems
are currently starting, running, and stopping.
Fixes #297.
Fixes #298.

Add pipes for parent process IPC.

---

config.go
dcrd.go
ipc.go
rpcserver.go
server.go
service_windows.go
signal.go
signalsigterm.go

This is a backport of PR #311 for the release-0.4.0 branch.

Backport #311

---

blockchain/chain.go
blockchain/reorganization_test.go

A bug in evaluating the correctness of a side chain block caused
forced reorganizations to fail post new database code. This was
corrected and children of the same parent at HEAD should now be
correctly evaluated and able to reorganize to one another without
issue. A test was also added for forced reorganizations.
Fixes #327.

Fix forced reorganizations

---

blockchain/chain.go
blockchain/chainio.go
blockchain/chainio_test.go
blockchain/common.go
blockchain/ticketlookup.go
blockchain/utxoviewpoint.go
blockchain/validate.go
blockchain/validate_test.go
blockmanager.go

A bug prevented STXO data from being written correctly in the event
that a block became invalidated. This could cause failures on testnet
when a block was invalidated. There was also some debug code and a panic
that were in master that have now been removed. A new test has been
added to ensure that STXO data is being properly written, and more
stringent checks for STXO data validity when added or removing blocks
has been added.

Fix a bug with invalidating blocks in new DB and add more sanity checks

---

upgrade.go

Do not error if the old ticket database doesn't exist.
Fixes #345

dcrd:  Fix another upgrade issue.

---

mining_test.go

Contains the following upstream commit:
- 5b14e15
491acd4, 7c17462, and b580cdb were already merged in via cherry-picks as https://github.com/decred/dcrd/commit/b6d426241d2dd01af15425652dc4a878b3559779 https://github.com/decred/dcrd/commit/8e71bcf41a9ed7d33dd9e3d87770d2ede0e3b7b9 https://github.com/decred/dcrd/commit/3740feb6735a648a7f39c87608d8bf55ae5679ec . As such, these commits are NOOPs.

Synchronize to the merging of btcd PR 666

---

blockchain/chainio.go

Merge in 5a1e77bd2dd6f5302a82d3d27b4e3a60526918b1.

Sync to btcd commit '5a1e77bd2dd6f5302a82d3d27b4e3a60526918b1'

---

glide.lock
glide.yaml

This updates the `glide.yaml` to remove the incorrect `seelog` version so it can make use of the latest commit and adds the test import for `testify` used by the `dcrec` package.  Finally it uses `glide update` to update the `glide.lock` file accordingly.
All commits in between the old and newest commits in the lock file have been reviewed.

deps: Update to latest commits.

---

log.go

Merges in b87723cd94ea11c29e22c4372ba4fe96886e7c83 from btcd.
The following commits are NOOPs because they have already been cherry-picked in:
- a1bb291b282433035f63b17773c38fc9e0f103ff
- 474547b211c8f5566d094478318fcfd3c2c838d4

Merge in btcd commit b87723cd94ea11c29e22c4372ba4fe96886e7c83

---

blockchain/chain.go
blockchain/chainio.go
wire/bench_test.go

Merges in btcd commit 27c0f9f8d1af6a44423b03a2e4f03d4a87a1ac40. Generates its own large transaction rather than uses a pregenerated one, saving space and becoming platform independent.

Merge in btcd commit 27c0f9f8d1af6a44423b03a2e4f03d4a87a1ac40

---

dcrec/secp256k1/ciphering.go

Merges up to commit f893558d782396f10c2fe49a8bc73deff4a36d14 from btcd.
1a0e7452f3e7367b30d3d62cab23dcd4e0bb6d8c, 128366734f0307d55bdaca0ed6955054cd3114e1, and 2554caee5919958c0d4b41db8035f0e12ce6f624 are NOOPs because they have already been cherry-picked in.

Merge in btcd commit f893558d782396f10c2fe49a8bc73deff4a36d14

---

txscript/sigcache.go

Merge in btcd commit 7f07fb1093dd80105d36d61c8fb8a16f6e9d9b29, also merging in e8e2167a1af6c20f1f32abb76bd387ee87763bc9.
24e41c843bf5cc363387871b9d8df0598395974c is already cherry-picked and skipped as a NOOP.

Merge in btcd 7f07fb1093dd80105d36d61c8fb8a16f6e9d9b29

---

wire/bench_test.go
wire/msgtx.go

Merges in btcd commit 6229e3583505a82d4514b1efa86f910b78693825.

Merge in btcd commit 6229e3583505a82d4514b1efa86f910b78693825

---

blockchain/indexers/addrindex.go

The offset to index was incorrect when inserting addrindex keys for
blocks that had been invalidated.  Fixes #347.

Fix a bug indexing addrindex when blocks are invalidated

---

blockchain/chain.go
blockmanager.go
mining.go

A bug when updating the chain state during forced reorganizations
was fixed. An assertion was added into the mining code so that it
now errors out if the blockchain and chainState of the block
manager are inconsistent.

Fix a bug for forced reorganizations

---

blockchain/stakenode.go

A bug in the restoration of stake nodes from the disk would prevent the
blockchain from reloading if there was an immediate reorganization
required on start up.  This correctly disconnects the block.

Fix a bug reloading the blockchain

---

dcrjson/dcrdextcmds.go
dcrjson/dcrdextresults.go
rpcserver.go
rpcserverhelp.go

Version the JSON-RPC API with semantic versioning.

---

blockchain/stake/tickets_test.go
blockchain/subsidy.go
blockchain/validate_test.go
chaincfg/params.go
mining.go

Profiling indicated that significant time was being spent validating
coinbase outputs, ensuring that they paid to the development
organization's P2SH tax address.  This check was more inefficient than
necessary for a couple of reasons:
* The tax address was always decoded from a string to a dcrutil.Address.
* The actual script being validated was always parsed for addresses to
check if they matched the tax address.
Neither of these are needed.  To optimize the algorithm, only the
equality of the output script and script version are checked.

Optimize coinbase output tax check.

---

blockmanager.go
cmd/addblock/addblock.go
cmd/addblock/import.go
config.go
server.go

The dumpblockchain function used to serialize a map of block
into gob serialized format, which was used for testing but which
was incompatible with the addblock tool.  The function now dumps
a flat file the the same format required by the addblock tool.
A couple shutdown assertions were added as well, to prevent
potential panics if pointers were nil.  The duration of time
it took to sync the blockchain with addblock is now
reported.

Fix the dumpblockchain function

---

blockchain/indexers/addrindex.go
blockchain/indexers/manager.go
blockchain/indexers/txindex.go
rpcserver.go

If the transaction index was run and never synced before, the first
time run will cause an OOM failure on machines with low RAM. This was
due to the GC never collecting blocks and freeing them after they were
used, because there were references to the block pointers or internal
pointers to the transaction hashes in the database updates. The
pointers to hashes have all been replaced with values to save memory
and allow the GC to free the blocks/transactions as the indexer runs.

Prevent high memory usage when turning txindex on first time

---

blockchain/accept.go
blockchain/chain.go
blockchain/prune.go

The blockchain pruning functions would run at every newly inserted
block node, causing performance degradation. Now the blockchain will
only prune nodes to return the memory to the garbage collector at
prespecified (5 minute) intervals, resulting in much less overhead
when syncing the blockchain.

Add a block pruner that only prunes occassionally

---

blockchain/stake/staketx.go
dcrjson/dcrwalletextcmds.go
dcrjson/parse.go
dcrjson/parse_test.go

The dcrwallet command to set multiple tickets vote bits fields at
the same time has been added.  Functions to encode/decode relevant
hex strings (as passed over JSON) were also added, along with tests.

Add new setticketsvotebits command

---

dcrjson/chainsvrcmds.go
dcrjson/chainsvrresults.go
rpcserver.go
rpcserverhelp.go
server.go

This RPC is essentially a reimplementation of the wire protocol
getheaders and headers messages and is planned on being used by the
wallet to fetch block headers during startup sync.

Add getheaders JSON-RPC extension command.

---

cmd/dcrctl/config.go
config.go

As described in Issue https://github.com/decred/dcrd/issues/105#issuecomment-250304334, `flags.ErrHelp` means that **`err` from `Parse()` the contains auto-generated help message from btcsuite/go-flags**, so we can print it to stdout.
**Clarification:** Only print to stdout when help is explicitly requested, _not_ because of an error.  Exit with code 0 in this case since there is no error.
Just opinions, but... http://stackoverflow.com/q/2199624/2778484

Output of --help/-h should go to os.Stdout rather than os.Stderr

---

dcrjson/chainsvrwscmds.go
dcrjson/chainsvrwscmds_test.go
dcrjson/chainsvrwsntfns.go
dcrjson/chainsvrwsntfns_test.go
dcrjson/chainsvrwsresults.go
glide.lock
rpcserver.go
rpcserverhelp.go
rpcwebsocket.go

Change the block connected and disconnected notifications to include
the entire block header.
Do not notify the previous block's regular tree transactions if the
newly attached block voted to approve them.  Instead, notify the
regular transactions from the newly attached block.  It is up to the
client to check the vote bits in the header to decide how to handle
the previous block's regular transactions.
Every websocket client now has an associated transaction filter that
is used to determine whether or not a processed transaction is (or
might be) relevant to the client.  A new RPC, loadtxfilter, has been
added to load, reload, or add to this filter.
Redo the entire rescan RPC to scan over previously-processed blocks
using the same transaction filter (rather than specifying which
addresses …

Use same notification for mined transactions and blocks.

---

blockchain/accept.go

checkCoinbaseUniqueHeight had a check to ensure the block had
transactions.  This check is already done beforehand by
checkBlockSanity.

blockchain: remove redundant check

---

blockchain/error.go
blockchain/validate_test.go

This function had several issues:
- It is completely unnecessary since the `ErrorCode` field is   intentionally exported so it is accessible
- It goes against effective Go naming guidelines which specifically  state getters should not be named `GetFoo`
- The comment on it regarding implementing the error interface was incorrect

blockchain: Remove unnecessary RuleError.GetCode.

---

peer/example_test.go
peer/peer.go
peer/peer_test.go
server.go

- 5cbd1f85bf217f59d3465ff8a471883600795ea0
- 777ccdade39c7b483410585d5e65e88db304f156
- f3d759d78307298c06b1cffaeb5af48a978f55af
- 1ffc3dc18d95b7b0aaf841dc46bd363f546ceb8d
Also the merge commit updates the code to use the correct Decred protocol versions and contains a few style-related changes.

peer: Extract protocol negotiation from main read and write loops

---

blockchain/fullblocktests/generate.go
blockchain/stake/staketx.go
blockchain/validate.go
mempool.go
mining.go
rpcserver.go
rpcwebsocket.go
wire/msgblock_test.go
wire/msgtx.go
wire/msgtx_test.go

This exports the transaction tree constants from the `wire` package instead of from `dcrutil`.  The tree is a fundamental part of a transaction and therefore its definitions belong in `wire` alongside the other constants that are also related to fundamental transaction fields.
Further, the `wire` package most definitely should not depend on `dcrutil` since that would create a cyclic import cycle.

wire: Export transaction tree constants.

---

blockchain/common_test.go
blockchain/difficulty.go
blockchain/fullblocktests/generate.go
blockchain/fullblocktests/params.go
blockchain/stake/tickets_test.go
blockchain/subsidy.go
blockchain/subsidy_test.go
blockchain/validate.go
blockchain/validate_test.go
chaincfg/params.go
cpuminer.go
mempool.go
mining.go
rpcserver.go

Upstream commit a7b35d9f9e24f8cebf3dc30cf083668700690095.
Also, the merge commit contains necessary decred-specific alterations.  It also has the side effect of correcting a couple of min reduction bugs even though they can't currently ever be hit due to the min reduction interval flag being disabled for all networks.

multi: Upstream parameter abstraction sync

---

README.md
server.go

- 05ab7141d3b268e1479853a2f79e219d2db36428
- Reverted because Travis is already at a more recent version
- 87b3756c8c7a1ae14b90aea51d452c2d72815511

server: Remove superfluous check in OnMemPool.

---

mempool.go

This optimizes the vote map by making better use of Go's slice properties.  In particular, instead of creating a slice with empty entries and iterating to find the next empty entry, just create the slice with a cap
and append entries as needed.  This allows the code simply take the `len` of the slice and range over it without needing additional code to deal with nil entries.
While here, it also makes a few comments and returns more consistent with the rest of the code base.

mempool: Optimize the votes map slices.

---

mempool.go
mining.go
server.go

This renames the `GetVoteHashesForBlock` on the `mempool` type to `VoteHashesForBlock` so it is named according to Effective Go guidelines as required by the project's code contribution guidelines and removes
the error return and paths from the function.
The error has been removed since the function should not be assuming how the caller wishes to use the data.  Consequently, now when there are no votes for a given block hash, the function simply returns a nil slice to reflect that.  The caller can then decide if the lack of vote hashes for a block is an error or not.
Also, the error path regarding an unset vote hash in the metadata is an impossible condition because the `mempool` has full control over the vote insertion and thus will never insert vote metadata without it.
Fixes #481.

mempool: Rename GetVoteHashesForBlock & remove err.

---

blockchain/stake/staketx.go

stake: Convert TxType constants to enum syntax.

---

blockchain/chain.go
blockchain/fullblocktests/params.go
blockchain/stake/tickets_test.go
blockchain/validate.go
blockchain/validate_test.go
chaincfg/params.go
mining.go

This reverts to the correct upstream majority version code which properly detects when certain thresholds of the network have been updated in order to determine when to start rejecting old version blocks and enforcing the rules in the new version block.
Fixes #489.

multi: Restore correct upstream majority version code.

---

rpcserver.go

This modifies the RPC server `blockTemplateResult` function to return RPC errors as expected instead of using `mempool` and `blockchain` errors.
In addition to being more correct, it also helps pave the way for mempool separation since its internal error funcs will no longer be available to abuse as this code was doing.

rpcserver: Return RPC errors from block template.

---

blockmanager.go
config.go
log.go
mempool/README.md
mempool/error.go
mempool/log.go
mempool/mempool.go
mempool/policy.go
mempool/policy_test.go
mining.go
rpcserver.go
server.go

Upstream commit 7fac099bee3a9f48512a8cb389b7d53e0c392c1b.
Also, the merge commit contains the necessary decred-specific alterations, adds a new policy parameter for `AllowOldVotes` to keep with the spirit of the merged commit, modifies the `RawMempoolVerbose` to accept an optional filter type to retain that functionality, and various other cleanup intended to bring the code bases more in line with one another.

mempool: Refactor mempool code to its own package.

---

blockchain/fullblocktests/params.go
blockchain/stake/tickets_test.go
blockchain/validate_test.go

This updates the various definitions of the simnet params used exclusively in the tests to match their definitions used by the actual simnet parameters defined in `chaincfg`.
While it would certainly be easier to simply use the params defined in `chaincfg`, that also would not allow the tests to detect them being inadvertently changed.

blockchain: Make params used in tests match.

---

blockchain/fullblocktests/generate.go

This modifies the full block consensus tests to only purchase tickets until the target pool size is reached during the initial creation of the blocks needed to reach stake validation height.
This helps make the code a little more flexible since it will allow many more blocks to be created without spiking the ticket price as would happen prior to this change.
For a little intuition, once stake validation height is reached the tests intentionally purchase the same number of tickets as are voting on each block in order to achieve a steady state, so if the number of
tickets in the pool are already higher than the target pool size prior to reaching that steady state, the ticket price would keep rising until the outputs used to purchase the tickets no longer had enough funds
available to …

fullblocktests: Limit tickets to target pool size.

---

blockchain/chain.go
blockchain/difficulty.go
blockchain/stakeext.go
blockchain/validate.go
dcrjson/dcrdextcmds.go
dcrjson/dcrdextcmds_test.go
dcrjson/dcrdextresults.go
rpcserver.go
rpcserverhelp.go

Implement dcrctl getstakeversions command.  This PR also expands the findNode command to search arbitrary depths but maintains backwards compat by implementing the prior 2800 depth max constant.
Example: dcrctl getstakeversions $(dcrctl getbestblockhash) 10
returns the last 10 stake/voter versions stats. 
Fixes #521

Implement stake voter version interrogation command.

---

blockchain/error.go
blockchain/stakeversion.go
blockchain/stakeversion_test.go
blockchain/validate.go
chaincfg/params.go
mining.go

this PR implements the mechanism for stake voters to influence the future of the network.  It does that by looking at set intervals (SVI) past stake validation height (SVH).  The initial interval starts therefore at SVH+SVI.  At subsequent intervals (SVH+N*SVI) reevaluate the versions.
Once 75% of the votes cast in a SVI have a particular version the stake version is flipped to said version (on an interval).  Once Stake Version reaches particular version it means that the daemon understands the new rules as of that version.
Consensus rule changes are as follows:
1. Reject version 2 blocks once a majority of the network has upgraded.
2. Enforce the stake version in the header once a majority of the network has upgraded to version 3 blocks.
Voter and Stake majorities are defined as 75% …

Implement softfork mechanism.

---

blockchain/difficulty.go

This variable should never be changed and the code will run faster and avoid errors as a const.
It makes it read a little ugly because it's not in with the rest of them, but I don't think it's a problem.

Change maxShift from var to const

---

blockchain/validate_test.go

Ensure the rejection of blocks resulting in large serializations.

Add one more consensus test

---

blocklogger.go

This is very trivial, not sure if I should even do a PR, but here it is.
I noticed this in the dcrd log:
18:18:38 2017-01-14 [INF] BMGR: Processed 1 block in the last 15.21s (1 transaction, 6 stake transaction, height 98443, 2017-01-14 18:18:31 +0100 CET)
It turns out that whenever there is "1 transaction", the "stake transaction" part is also singular, because of comparison on the wrong variable.

blocklogger: fix singular case for stake transactions

---

blockchain/chain.go
dcrjson/dcrdextresults.go
rpcserver.go
rpcserverhelp.go

Add header.Version to the getstakeversions command.  Even though that information can be obtained separately it would require a bunch of RPC chatter which is suboptimal.
Fixes #555

Add block version to getstakeversions

---

blockchain/validate.go

This removes a couple of checks that are completely impossible to hit.
These are impossible to hit because there is a maximum protocol limit of 1MiB and the absolute minimum possible transaction size that will successfully deserialize with no inputs and no outputs is 15 bytes
(which is itself an invalid transaction anyways), which means a maximum of 66,666 of these invalid transactions could fit into a 1MiB block. Since the check is comparing against 393,216 on mainnet and 1,000,000 on testnet and simnet, it can easily be seen it simply isn't possible to hit.
Technically, if it were possible to hit these conditions, changing them would be a hard fork, however, since they're impossible to hit, this is effectively a noop change in regards to consensus.

blockchain: Remove impossible condition checks.

---

blockchain/chaingen/generator.go
blockchain/thresholdstate_test.go

**This requires PR #542**
This adds a series of full block tests which exercise the new voting functionality exposed via PoS votebits and a threshold state machine.  As with other full block tests, these involve generating a completely
valid chain starting with genesis block and methodically reaching various thresholds.
To achieve this, the tests creates two stake version 4 test dummy deployments that are carried out at the same time to also ensure voting on multiple agendas concurrently works as intended.  The first agenda is voted in via a majority yes vote while the second is rejected via a majority no vote.
The following is an overview of the progression of the tests:
- Generate enough block to reach one block before the first stake version interval using v3 blocks and v3 votes in …

blockchain: Add fullblock tests for voting.

---

blockchain/accept.go
blockchain/chain.go
blockchain/chaingen/generator.go
blockchain/fullblocktests/generate.go
blockchain/fullblocktests/params.go
blockchain/stake/tickets_test.go
blockchain/thresholdstate.go
blockchain/thresholdstate_test.go
blockchain/validate.go
blockchain/validate_test.go
blockchain/votebits_test.go
chaincfg/params.go
mining.go
rpcserver.go
wire/msgblock.go
wire/msgblock_test.go
wire/msgmerkleblock.go
wire/msgmerkleblock_test.go
wire/msgtx.go
wire/msgtx_test.go
wire/protocol.go

**This requires PR #542**
This implements a new voting agenda for the testnet and simnet networks for increasing the maximum block size from 1MiB to 1.25MB.
- Bump the maximum protocol block size limit to 1.25MB
- Bump the protocol version to 4
- Add wire tests for v3 protocol sizes and update tests for latest
- Update all wire values that are defined in terms of the max block size to respect the protocol version
- Update the `MaxSigOpsPerBlock` constant to maintain existing value regardless of the raised max protocol block size
- Decouple the maximum tx size from the block size by creating a chain parameter for it with the current sizes so it is not a part of the hard fork vote
- Add definition for new version 4 stake vote along with agenda to …

multi: Implement block size hard fork demo voting.

---

dcrjson/dcrdcmds.go
dcrjson/dcrdresults.go
rpcserver.go
rpcserverhelp.go

We need a "better" getstakeversions command that returns cooked values instead of just raw data.

Add new getstakeversioninfo command

---

.travis.yml
README.md
dcrjson/chainsvrcmds_test.go
dcrjson/cmdparse_test.go
dcrjson/help_test.go

Go 1.8 is out and by policy we only support the latest two Go releases.

Add Go 1.8 support, remove 1.6.

---

cmd/dcrctl/version.go
version.go

By default, put 'dev' in the prerelease field.
For release builds we can add 'release' with the build scripts.
Update comment for current (post 1.5) usage on ldflags -X while there.
Closes #516

Differentian dev and release in -V

---

blockchain/accept.go
blockchain/chain.go
blockchain/chainio.go
blockchain/internal_test.go
blockchain/stakeversion.go
blockchain/stakeversion_test.go
blockchain/validate.go
blockchain/validate_test.go
blockchain/votebits_test.go

In order to keep the HF work as separate as possible, a new array was introduced in blockNode that keeps track of the version:bits tuple.  With the HF work completed, we can now get rid of the voterVersion array and reuse the tuple in the stake version code.
This PR is purely mechanical.
Fixes #576

Don't keep double vote information in blockNode

---

blockchain/accept.go
blockchain/chain.go
blockchain/chainio.go
blockchain/internal_test.go
blockchain/stakeversion.go
blockchain/stakeversion_test.go
blockchain/thresholdstate.go
blockchain/votebits.go
blockchain/votebits_test.go
dcrjson/dcrdresults.go
rpcserver.go
rpcserverhelp.go

We still return only the voteversion information but we have voteversion:bits available.  So return that instead so that we can get all version/vote/bits raw data in addition to the cooked values we already have.
Fixes #585

Tupleize version:bits

---

goclean.sh

This modifies the `goclean.sh` script that is executed on Travis to only run the tests once.
While it is nice to see coverage reports in the log, unfortunately it appears that both the -race and -cover flags can't be used together, and the tests have grown in complexity such that they are starting to get close to TravisCI time limits.

TravisCI: Only run tests once.

---

blockchain/chainio.go
blockchain/stakeversion_test.go
blockchain/votebits_test.go

This modifies all invocations of `newBlockNode` in the tests to use the already existing `zeroHash` instance and `nil` for all unused fields versus creating an empty object for them.  This is more consistent with existing code and avoids needlessly creating objects.

blockchain: Make node creation in tests consistent.

---

blockchain/chaingen/generator.go

The go compiler treats the `math.MaxUint32` constant as an integer in the error print which causes a compile error.  This casts the constant to avoid that thus allows the code to compile on 32-bit architectures.
Fixes #604

chaingen: Allow 32-bit compile.

---

dcrjson/chainsvrresults.go
rpcserver.go
rpcwebsocket.go

Make GetBlockHeaderVerboseResult and GetBlockVerboseResult return
Confirmations as -1 when we are dealing with an orphan block.
Fixes #546

rpcserver: Confirmations -1 when a block is orphan

---

blockchain/stakeversion_test.go
blockchain/thresholdstate.go
blockchain/votebits_test.go

Modify threshold state to use the stake version that will be used in the
next block. That removes a full interval before voting can start and it
makes all voting intervals consistent.
Fixes #595
Requires #596

blockchain: use next block stake version.

---

blockchain/votebits.go
blockchain/votebits_test.go

Add a test where the expiration time is roughly at the half of the
voting window.  We do that by spoofing the ExpireTime to be half of the
required RCI window.  The synthetics use a second per block time stamp
so we simply set ExpireTime to RCI/2 seconds.
Fixes #601
Requires #599

blockchain: add expiration test during voting.

---

chaincfg/init.go
chaincfg/init_test.go
chaincfg/params.go

Unfortunately, agendas require some assumptions.  In order to prevent bad agendas to be allowed in the code base we need an agenda validator.  This validator shall be called every time dcrd is loaded and straight up panic.  This will not adversely impact the user experience but will force developers to properly design dcrd agendas.
Fixes: #606
Requires: #602
These are the required tests to ensure vote integrity:

chaincfg: strictly enforce agenda assumptions.

---

chaincfg/params.go

The test network should allow any scripts and transaction types that are valid according to consensus rules as opposed to the more strict standardness rules that apply to mainnet.  This allows new script forms and types to be tested before they go to mainnet.
Also, this is the same setting as the previous test network.

chaincfg: Allow non-std transactions on testnet2.

---

.travis.yml
goclean.sh

The linters take quite a while to run in the TravisCI environment which causes the deadline to be exceeded.
While here, also increase the allowed deadline for the remaining linters to 10 minutes and also update Travis to use a new Ubuntu distribution.

TravisCI: Remove a couple of linters.

---

txscript/sign_test.go

This updates the script signing test code to use a single chain params variable instead of repeatedly referring to a specific network.  This makes it much easier to change in the future such as future testnet resets.

txscript: Update signing tests to use params var.

---

server.go
wire/msgminingstate.go

If there are more vote hashes than wire.MaxMSBlocksAtHeadPerMsg, send
the max instead of none.  Also, add a missing error check for safety.

server: send some vote hashes

---

blockchain/chain.go
rpcserver.go

This adds bounds check for the RPC parameters for the `getstakeversions` command to both the handler and the chain function itself which provides the data.
Also, while here simplify the for loop in `GetStakeVersions` to check `prevNode` in the for loops condition instead of in a separate if block, return more appropriate error types for RPC parameter type errors, and
make use a naked type cast of the command to be consistent with all of the other handlers.
Fixes #635

rpcserver/chain: Bounds check getstakeversions.

---

rpcserver.go

This modifies the `rpcserver.go` file to make the function definitions consistent with one another.  Not only is this good for consistency, but it also makes the upstream syncs easier since there are less merge
conflicts due to superfluous changes.

rpcserver: Make function definitions consistent.

---

wire/msgversion.go
wire/msgversion_test.go

Upstream commit 763f731c5c97ab2f659f0c7dd3e6a8f48c723daa.
This updates wire to enforce a limit of 256 instead of the existing 2000 to coincide with the upstream btcd project, and consequently includes a wire version bump to 0.2.1 in the merge commit.

wire: Lower MaxUserAgentLen to 256.

---

cpuminer.go
dcrec/secp256k1/signature.go
goclean.sh
mining.go
rpcserver.go

While here, readd gosimple and unconvert

gometalinter:  use --vendor to skip ./vendor/

---

config.go
connmgr/README.md
connmgr/connmanager.go
connmgr/connmanager_test.go
connmgr/doc.go
connmgr/dynamicbanscore.go
connmgr/dynamicbanscore_test.go
connmgr/log.go
connmgr/seed.go
connmgr/tor.go
docs/README.md
log.go
peer/example_test.go
peer/peer.go
peer/peer_test.go
server.go

This is a port of a series of commits from btcd which introduce and refine package `connmgr` which contains connection management related functionality.
The following is an overview of the features the package provides:
- Maintain fixed number of outbound connections
- Basic handling of inbound connections
- Optional connect-only mode
- Retry persistent connections with increasing back-off
- Source peers from DNS seeds
- Use Tor to resolve DNS
- Dynamic ban scores
- Test coverage
In addition, dcrd has been refactored to make use of the new package by extending the connection manager to work with the server to source and maintain peer connections. The following is a broad overview of the changes to integrate the package:
- Simplify peer state by removing pending and retry peers
- Refactor …

connmgr: Refactor connection management into pkg 

---

release/services/smf/dcrd.xml
release/services/systemd/dcrd.service

This adds example service files to run dcrd as a system service for systemd and
illumos SMF.
Waiting on an rc.d before this is merged...
Closes #561.

Add example service files.

---

.gitignore
cmd/promptsecret/promptsecret.go

promptsecret is used to read a secret from stdin without echoing and
write it to stdout.

Add new tool, promptsecret

---

glide.lock
glide.yaml

Pull in dcrrpcclient and dcrutil changes for better memory allocation.
Add ssh/terminal used by cmd/promptsecret

glide: sync

---

rpcserver.go
rpcwebsocket.go

Ensure that all errors return an RPC error.  Try to match the type as
well.  Also some miscellaneous clean ups.
Fixes #498

rpcserver: always reply with an RPC error.

---

dcrjson/dcrwalletextcmds.go
dcrjson/walletsvrresults.go

Add generate vote for https://github.com/decred/dcrwallet/issues/646.
balancetomaintain and ticketmaxprice were removed already but these pieces were missed.

dcrjson: add generatevote and remove some unused pieces

---

mempool/policy.go
mempool/policy_test.go

This lowers the default minimum relay fee to 0.001 DCR/Kb from its previous value of 0.01 DCR/Kb.
It should be noted that this is only a default node policy change and as such does not affect the consensus rules in any way.

policy: Lower default relay fee to 0.001/kB.

---

mempool/mempool.go

When the minimum relay fee was modified from 0.01 to 0.001 DCR/kB this
value was not changed, causing the new high fee threshold to be 0.1
DCR/kB.  After discussion, we want to keep the same default high fee
threshold as before, especially as this value is used to limit
unintended high fees for ticket purchases.

Increase the high fee multiplier to keep same threshold.

---

blockchain/chainio.go
blockchain/fullblocktests/params.go
blockchain/stake/tickets_test.go
blockchain/thresholdstate.go
blockchain/thresholdstate_test.go
blockchain/validate_test.go
blockchain/votebits.go
blockchain/votebits_test.go
chaincfg/init.go
chaincfg/init_test.go
chaincfg/params.go
dcrjson/dcrdresults.go
rpcserver.go
rpcserverhelp.go

This renames the `chaincfg` parameter for the vote choice which represents an abstaining vote to be named `IsAbstain` instead of `IsIgnore` since that more accurately describes its intent and behavior.
It also updates the RPC server choice result field for `isignore` to be named `isabstain` to match.
Finally, it renames other internal variables which make use of the choice to include the word abstain as well for clarity.
Closes #655.

multi: Rename vote choice IsIgnore to IsAbstain.

---

blockchain/difficulty_test.go

This removes dead code from the `difficulty_test.go` file in the `blockchain` package.

blockchain: Remove dead code from diff tests.

---

rpcserver.go

More dependencies on the global config in main isn't great but the
actual value in the mempool policy isn't exported at this time.

rpcserver: Use a real value for fee estimates.

---

blockchain/difficulty.go
blockchain/difficulty_test.go
blockchain/fullblocktests/params.go
blockchain/stake/tickets_test.go
blockchain/validate.go
blockchain/validate_test.go
blockmanager.go
chaincfg/params.go
mining.go
rpcserver.go

This implements a new stake difficulty algorithm along with a voting agenda for all networks to change and a comprehensive set of tests.  It also implements estimation using the new algorithm for the `estimatestakediff` RPC.
- Add new agenda to vote on changing the stake difficulty algorithm to all networks
- The version on mainnet is version 4
- The version on testnet and simnet is version 5
- Modifies the stake difficulty calculation function to calculate the difficulty based on the result of the vote
- Modifies the stake difficulty estimation function to calculate the difficulty based on the result of the vote
- Makes the stake difficulty estimation function concurrent safe
- Calls it directly from the RPC server instead of going through …

multi: Implement stake difficulty change and vote.

---

chaincfg/params.go

This adds a new agenda to mainnet which allows the stake holders to vote on whether or not they want the developers to begin work on integrating lightning network support.
Closes #597

chaincfg: Add agenda for LN support vote.

---

wire/blockheader.go

This corrects the comment for the `MaxBlockHeaderPayload` variable to match reality, removes an extraneous `TODO` that has already been done, and makes the `readBlockHeader` and `writeBlockHeader` functions use a style consistent with the rest of the code.

wire: Cleanup blockheader.go.

---

rpcserver.go

Only the first parameter to the `rpcInternalError` function is returned to RPC clients, so any errors that originate in the handlers need to be passed as the first parameter.
The second context parameter is to allow additional context to be added to errors coming from underlying calls.  There is no additional context for errors generated by the RPC handlers themselves.

rpcserver: Return handler errors to RPC client.

---

rpcserver.go

This disables the `getblocktemplate` RPC handler since it does not at all work as intended.  Fixing it is going to be a larger effort, so just disable it until it can be properly implemented.

rpcserver: Disable getblocktemplate.

---

rpcwebsocket.go

rpcserver: Always read wsclient filter with mutex held.

---

log.go

I've found this helps with general tracing/review of time critical functions.

log: Use millisecond time resolution.

---

blockchain/stakeext.go
dcrjson/dcrdcmds.go
rpcserver.go
rpcserverhelp.go

This RPC works identically to the existsexpiredtickets RPC but checks
for missed rather than expired tickets.
Closes #697.

rpcserver: Add existsmissedtickets RPC.

---

dcrec/edwards/const.go
dcrec/edwards/curve.go
dcrec/edwards/ecdsa.go
dcrec/edwards/primitives.go
dcrec/edwards/privkey.go
glide.lock
glide.yaml

set to the version decred/ed25519 had been synced with.

glide: move to upstream agl/ed25519

---

dcrec/secp256k1/bench_test.go
dcrec/secp256k1/btcec.go
dcrec/secp256k1/btcec_test.go
dcrec/secp256k1/field.go
dcrec/secp256k1/field_test.go
dcrec/secp256k1/precompute.go
dcrec/secp256k1/pubkey.go
dcrec/secp256k1/pubkey_test.go
dcrec/secp256k1/signature.go
dcrec/secp256k1/signature_test.go

**This PR depends on #722**
This unexports various functions, structs, and constants that were exported for some reason when porting this from the upstream project when they really should not have been since they deal with package internals.
While here, correct a few other minor differences that were introduced between the package and the upstream code and correct a few comments that appear to have had a blanket find/replace applied to them incorrectly.

secp256k1: Unexport idents that do not need to be.

---

dcrec/secp256k1/bench_test.go
dcrec/secp256k1/btcec.go
dcrec/secp256k1/btcec_test.go
dcrec/secp256k1/field.go
dcrec/secp256k1/field_test.go

This modifies the normalize function of the internal field value to both optimize it and address an issue where the reduction could lead to an incorrect result with a small range of values along with some tests to ensure the behavior is correct.
It also contains contributions from @jimmysong to optimize NAF to avoid returning the unneeded bit when there is not a carry and adds a bunch of unit tests.
The following benchmark shows the relative speedups as a result of the optimization on my system.  In particular, the changes result in approximately a 14% speedup in Normalize, which ultimately translates to a 2% speedup in signature verifies.
```
benchmark                        old ns/op     new ns/op     delta
-------------------------------------------------------------------- …
```

secp256k1: Optimize normalize and NAF, correct normalize, and add tests. 

---

cmd/dcrctl/config.go
cmd/dcrctl/httpclient.go

This option lets dcrctl print the raw json it both
sends and receives for commands.
Inspired by the similar option in dcrtime.
Closes #727

Add -j/json option to dcrctl.

---

blockchain/chain.go
blockmanager.go
dcrec/edwards/ecdsa.go
mining.go

... not the entire block header.

chainstate only needs the previous block hash

---

rpcserver.go

When the includemempool parameter is set to true, transactions in the mempool
should be additionally considered.  However, the previous code used a buggy
implementation which would return an error if this parameter was set and the
transaction was not found in the mempool, without ever querying a mined utxo.
Fixes #658.

rpcserver: Fix gettxout includemempool handling.

---

config.go

This allows levels to be specified by their shorthand versions (CRIT
vs CRITICAL, for example), works with any capitalization, and adds
support for handling the OFF level (previously the least verbose log
level that could be set was CRITICAL).
Fixes #740.

Use btclog for determining valid log levels.

---

dcrec/secp256k1/README.md
docs/README.md
docs/code_contribution_guidelines.md
docs/configuring_tor.md
docs/json_rpc_api.md

The github markdown interpreter has been changed such that it no longer allows spaces in between the brackets and parenthesis of links and now requires a newline in between anchors and other formatting.  This
updates all of the markdown files accordingly.
While here, it also corrects a couple of inconsistencies in some of the `README.md` files and correct some previous merge conflicts.
Fixes #743 and includes changes missed by #711.

multi: Update markdown files for GFM changes.

---

cmd/dcrctl/config.go
cmd/dcrctl/sample-dcrctl.conf

This option allows one to specify a different option for the wallet
rpc server it will connect to.  This is primarily meant to be used in
the config file so that a single dcrctl.conf may be used in the
situation where the wallet is on one host and dcrd is on another host.
Closes #735

dcrctl: Add --walletrpcserver option.

---

blockchain/indexers/addrindex.go
blockchain/indexers/common.go
blockchain/indexers/existsaddrindex.go
blockchain/indexers/manager.go
blockchain/indexers/txindex.go

This modifies all files in the indexers package to minimize the differences between them and the upstream code in order to facilitate easier syncs due to less merge conflicts as a result of superfluous changes.
While here, it also corrects a few comments that were not updated properly for the changes in Decred.

indexers: Minimize differences with upstream code.

---

blockchain/chain.go
blockchain/indexers/addrindex.go
blockchain/indexers/txindex.go

This modifies the code to permit a reorganization that includes block one.  Even though this will never happen on the main network since it's buried so deep, it is entirely possible for the first block to be
reorged away on test chains.
Not only is it more technically accurate to permit a reorg of the first block, so long as the new one satisfies all of consensus rules, it also facilitates upcoming test code which relies on that capability.
It should be noted that this is technically a hard fork, however, it only applies to the first block and so it would now require a reorg of over 150,000 blocks which is completely infeasible.

chain/indexers: Allow reorg of block one.

---

blockchain/chaingen/generator.go
rpctest/README.md
rpctest/doc.go
rpctest/memwallet.go
rpctest/node.go
rpctest/rpc_harness.go
rpctest/rpc_harness_test.go
rpctest/utils.go

Upstream commit b86df0ba9194659fddf1e4e8930b67b5791eff49.
The merge commit contains necessary Decred-specific alterations and also removes the code that is related to generating and submitting a new block.
While the block generation functionality is useful, the specific method used in the upstream code will not work in Decred because of the additional state needed for voting and the fact the difficulty adjustment period is much more frequent which prevents just using the pow limit.
Future commits can remedy this situation by making use of block templates provided by the daemon and allowing the rpc test code to modify the template accordingly.

rpctest: Upstream create new rpctest package sync.

---

rpcserver_test.go

Upstream commit 2d86fbfacee9bef2745a2fb29efc8e7760f1cc5d

rpcserver: Upstream sync to add basic RPC tests.

---

rpctest/rpc_harness_test.go

- c3d5371615c4869e3f899a355421089318976944
- Reverted since Travis is already at a more recent version
- 7c4b169faa134b6716f574cff87d2e4340fba57b
- Reverted since this is already done via the Decred docker setup
- 47ced81d440595b0bbe6c355236ac306e107c259
- Reverted since it has already been fixed by connmanager sync
- 6cf60b5fae5cd076c863892038840a2327e345ce
Also, the merge commit contains the necessary Decred-specific alterations.
----
This corrects several issues with the new rpctest package.
The following is an overview of the issues that have been corrected:
- The JoinNodes code was incorrect for both mempool and blocks.
- For mempool it was only checking the first node against itself
- For blocks it was only testing the height instead of hash …

rpctest: Correct several issues in tests and joins.

---

rpcserver_test.go

Upstream commit bfe2ba41910873aa84bc896ae09ca0dad97e5ddd.
---
This adds a `defer` statement at the top of  `TestRpcServer` which will attempt a `recover` which tears down all active harnesses in the event that one of the tests causes a panic in the main goroutine.
Before this commit, if a buggy test caused a panic while all integration tests were being executed, then any active harnesses would fail to be properly torn down. This would cause the running btcd processes to be leaked, possibly interfering with future test runs until the process was manually killed. This commit fixes such behavior.
In order to aide in debugging, when a test panics, the test number is printed out along with a full stack-trace from the start of the test to the panic point.

rpctest: prevent process leak due to panics.

---

blockchain/chain.go
blockchain/chainio.go

Upstream commit c57c18c8e2e9c43b5cc81b04e5f84b23ccf95661.
---
This adds a new field to the best chain state snapshot for the calculated past median time as returned by the `calcPastMedianTime` function.  This is useful since it provides fast access to it without having to acquire the chain lock which is needed to recalculate it.
This will ultimately allow the associated exported function to be removed since it only exists to be able to calculate this exact value, however this commit only introduces the new field in order to keep the changes minimal.

blockchain: Add median time to state snapshot.

---

mempool/mempool.go
server.go

Upstream commit 641182b2ade8fe31ffa3698c2ab758ef3851d16c.
In addition, the merge commit also adds two more functions to the config, named `BlockByHash` and `BestHash`, along with an additional field for the `SubsidyCache` in order to maintain the spirit of the upstream commit breaking the dependency on a specific chain instance.
---
This modifies the config for the new `mempool` package such that it takes a callback function to obtain the best chain height instead of requiring a fully initialized `blockchain.BlockChain` instance.
This will make it much easier to test the `mempool` since the tests will be able to provide their own height function to test various functionality without having create and manipulate full blocks and chain instances.

mempool: Break dependency on chain instance.

---

blockchain/utxoviewpoint.go
mempool/mempool.go
mempool/mempool_test.go

Upstream commit 15bace88dc95887139d877aca092f9c41b5d63fe.
In addition to the necessary Decred-specific alterations to the existing upstream code, the merge commit also introduces several new functions on the fake chain instance to handle the additional capabilities needed by the Decred mempool such as the `NextStakeDifficulty`, `BlockByHash`, and `BestHash` functions along with a `SubsidyCache` instance.
---
This adds a basic test harness infrastructure for the mempool package which aims to make writing tests for it much easier.
The harness provides functionality for creating and signing transactions as well as a fake chain that provides utxos for use in generating valid transactions and allows an arbitrary chain height to be set.  In order to simplify transaction creation, a single …

mempool: Add basic test harness infrastructure.

---

config.go
doc.go
mempool/mempool.go
rpcserver_test.go
sample-dcrd.conf
server.go

This contains the following upstream commits:
- dc5486a579f7992c09c6f6cf2970f3e4fe7b8b53
- 815ded348ec5aa2d0dbe7cfbc1468616e3508252
- c6d50b7abfe5f43c60718398e12606d219725a57
The merge commit also includes the contains necessary Decred-specific alterations.
---
This PR adds two new cli flags: one for accepting non-std transactions, and the other for rejecting non-std transactions.
The two flag are rejected when used concurrently. Config parsing is set up such that, the desired policy expressed via the config always overrides the policy set by default for a particular chain.
The `mempool`'s `Policy` config has been modified to add a new `RelayNonStd` bool which is checked when validating transactions rather than the policy as dicated by the current `ChainParams` instance. 
Finally, the …

config: introduce new flags to accept/reject non-std transactions 

---

rpcserver_test.go
rpctest/rpc_harness_test.go

This contains the following upstream commits:
- 5e93b1664e4a57aa997b77c6e4a8a90b4c90dd98
- This commit originated from downstream so it is a NOOP
- 0ddd10add60683ce24cafcc1d9b38832ad1920ef
- This commit has been reverted since it has already been done.
- fb90c334dffc6c91843d8d36ac31e7f7eb6c7594
---
This modifies the rpctest harness to call the TearDown function in the SetUp error path. This ensures any resources, such as temp directories, that were created during setup before whatever the failure that caused the error are properly cleaned up.

rpctest: Cleanup resources on failed setup.

---

blockchain/scriptval_test.go
rpctest/rpc_harness.go
rpctest/rpc_harness_test.go
rpctest/utils.go

This contains the following upstream commits:
- c20db1cf148ce3b06d6a97c24172d1d034995dbb
- This is commented out in the Decred tests, so merged with the commented code
- daac24626e01996e925c3f55d371d460b25e4c6d
- This has been reverted since the Decred build system is different and it therefore does not apply
- 7cf9ec81909f69c267f4cb130bc1bbe04ff488b0
---
This modifies the ports that are selected for use for the p2p and rpc ports to start with a port that is based on the process id instead of a hard-coded value.  The chosen ports are incremented for each running instance similar to the previous code except the p2p and rpc ports and now split into ranges instead of being 2 apart.
This is being done because the previous code only worked for a single process which means it prevented the …

rpctest: Use ports based on the process id.

---

config.go
doc.go
sample-dcrd.conf
server.go

The whitelist option is used to specify networks that will not be
banned.
Fixes #351

config: Add --whitelist option

---

mempool/policy.go
mempool/policy_test.go

This updates the comments in the `isDust` function to match the current default relay fee of 1e5 and the correct tx size values.  It's nice to have the most recent values as a reference in the comments.
Also, while here, add a couple of tests just below and above the dust point for the current default relay fee.

mempool: Update comments for dust calcs.

---

glide.lock
rpctest/rpc_harness_test.go

Upstream commit 5ec83d23f382ae80d5235cfc29b5f88b2af3b713.
The merge commit modifies the dependency hash updates in `glide.lock` to the correct commits.

rpctest/deps: Update dependencies and API.

---

rpcserver_test.go
rpctest/rpc_harness_test.go
run_tests.sh

Contains upstream commits:
- 99165eb5580b0cb3af1401a9dd641af867852300
- This is a NOOP since it was already done in Decred when porting the `rpctest` framework
- 754c4fbe0cc528f7d7edd309d40db9aa873c7fe6
The merge commit also ports the necessary changes to run the tests in the new Decred build setup.
---
This adds a new build tag named `rpctest` which must be set in order for `rpctest`-based tests to be executed.  The new build tag is also added to the `run_tests.sh` script which is executed by Travis during continuous integration builds.
This change is being made because the `rpctest` framework requires additional careful user configuration to ensure the version of `dcrd` under test can be programmatically launched from the system path with
all of the necessary ports open whereas all of …

rpctest: Gate rpctest-based behind a build tag.

---

blockchain/accept.go
blockchain/chain.go
blockchain/example_test.go
blockchain/process.go
cmd/addblock/import.go

- 42a4366ba8b170de11c471fdfb1f3eede9642a0f
- This is a NOOP since it has already previously been applied
- 77913ad2e8d62e8760aa66519eed3e2ec810da31
Most of the changes related to this merge have already previously been applied, so this primarily just minimizes the differences versus upstream.

blockchain: Sync main chain flag on ProcessBlock.

---

peer/peer.go
server.go

Upstream commit 8965d888931238fd17b3ea9ae70216f1c3ce6e6a.
---
This makes the enforcement of the bloom filter service bit much more strict.  In particular, it does the following:
- Moves the enforcement of the bloom filter service bit out of the `peer` package and into the server so the server can ban as necessary
- Disconnect peers that send filter commands when the server is configured to disable them regardless of the protocol version
- Bans peers that are a high enough protocol version that they are supposed to observe the service bit is disabled, but ignore it and send filter commands regardless.
As an added bonus, this fixes the old logic which had a bug in that it was examining the _remote_ peer's supported services in order to choose whether or not to disconnect instead of the …

peer: Strictly enforce bloom filter service bit.

---

mempool/mempool_test.go

Upstream commit e88f2d7bf413c9e9b7f05ffe3d30f0e5ca36f803.
The merge commit also contains the Decred-specific updates.
---
This adds a test to the mempool for ensuring that orphans are evicted when exceeding the max orphan policy setting as expected.

mempool: Add test for max orphan entry eviction.

---

blockchain/chain.go
blockmanager.go
mining.go

Upstream commit 1cba5c8fc0e39f9e65c5d0bb6f4750dfd1e3f02a.
---
This removes the exported `CalcPastTimeMedian` function from the `blockchain` package as it is no longer needed since the information is now available via the `BestState` snapshot.
Also, update the only known caller of this, which is the chain state in block manager, to use the snapshot instead.

blockchain: Remove exported CalcPastTimeMedian func.

---

blockchain/common_test.go
blockchain/fullblocktests/README.md
blockchain/fullblocktests/generate.go

Upstream commit f21410e47c5ae0a14849c54f7b8076f5c2f874e9.
These tests have already been synced via a separate commit, so this primarily just minimizes a few differences and picks up the `README.md` for the `fullblocktests` package.
The merge commit modifies the paths in the `README.md`  for Decred accordingly.

fullblocktests: Sync upstream block validation.

---

glide.lock
txscript/sign_test.go
txscript/standard.go
txscript/standard_test.go

~~This requires PR decred/dcrutil#55~~.
Decred's consensus rules require address generation to use a compressed pubkey format, this was hacked
into `btcutil.NewAddressSecpPubKey`. This commit removes the hack and provides `btcutil.NewAddressSecpPubKeyCompressed` to enforce the consensus prerequisite

txscript: Force extracted addrs to compressed.

---

peer/peer.go
peer/peer_test.go
wire/doc.go
wire/message.go
wire/msgfeefilter.go
wire/msgfeefilter_test.go
wire/msgversion.go
wire/protocol.go

This contains the following upstream commits:
- ca4e9b82d639837e4d7b2071c9c32c0e54f49a4c
- 9935fe5dba371df20afa0af30eb4488d13d44931
- d009185a56930ee32e8415c55956f1000f59213d
The merge commit modifies the protocol versions and the wire default user agent version accordingly along with other minor changes in terms of copyright dates and comment changes.
---
feefilter is used to request the receiving peer does not announce any transactions below the specified minimum fee rate.
NOTE: This only implements the new message type in the `wire` and `peer` packages.  Further PRs will be needed to `dcrd` itself to implement and respond to the message.

wire/peer: Implement feefilter p2p message.

---

dcrec/secp256k1/field.go
dcrec/secp256k1/field_test.go

This contains upstream commits:
- a52eb04aaabfb7f6ec03b8cdab8a432b58fd3862
- This has already been previously applied so is a NOOP other than a couple of comment updates.
- 294b5d46da4ea05bc0df80e4a6b5f46c6ca9c8cb
---
This adds new tests to the `TestNormalize`, `TestMul`, and `TestAdd2` test test some additional edge conditions.

secp256k1: Add regression tests for field.go.

---

blockchain/chain.go
mempool/mempool.go
peer/mruinvmap.go
peer/mrunoncemap.go
peer/peer.go
rpcwebsocket.go
server.go

Upstream commit b1621332cc6d5860f58a7526088569e92af05ae0.
---
Defers are nice for readability but they do add overhead.  This gets rid of defers where it is just as easy as not to use one.

multi: Optimize by removing defers

---

txscript/data/tx_invalid.json

This removes the tests related to max money checks since `txscript` does not do sanity checking on the monetary amounts as that is done by the consensus rules in `blockchain`.
While here, update `dcrscript` -> `txscript` in the comments to reflect reality.
As an aside, the existing tests were invalid anyways since the signatures were invalid and thus the tests were failing for the wrong reason.

txscript: Remove max money from json test data.

---

rpctest/node.go
rpctest/rpc_harness.go

logs and data directories are subdirs
of the harness dir, the node dcrd 
process is also run in the working dir
which is the harness dir
thanks to @davecgh for contributing

rpctest: Store logs and data in same path

---

txscript/reference_test.go

This cleans up the reference test file to remove references to bitcoin since it no longer applies to decred and remove a TODO that was recently completed.

txscript: Cleanup reference test code.

---

glide.lock
wire/msgtx.go

This is no longer needed since the tests that used it were updated. It really should have never been in the production code anyways. Code only needed by tests should be in the associated test package.

wire: Remove legacy transaction decoding.

---

mempool/mempool.go
mempool/mempool_test.go
mempool/policy.go
mempool/policy_test.go
server.go
wire/msgtx.go

This removes the function `IsSupportedMsgTxVersion` function from `wire` since that is a policy decision and does not belong in `wire`.
It also updates the mempool standard transaction checks to be more inline with the upstream code such that the maximum supported transaction version is specified via a field in the mempool policy
configuration struct.
Finally, it adds a new test to the standard transaction tests to ensure transactions that are not serialized with the full seriaization type are considered nonstandard.

mempool/wire: Don't make policy decisions in wire.

---

config.go
sampleconfig.go

This improves the default config file creation process so that it will only create a default config file when the user has not overridden the config file path.
It also now works properly when a different `appdata` path is provided in that it will still create a default config file in that new path if one doesn't already exist, but only if the user did not also override the config file path.
Finally, instead of copying a separate sample config file from the filesystem, which didn't work properly under several scenarios such as when it wasn't already available or the `appdata` directory was changed, the code now specifies the entire sample config as a string in the source code.  This means it will work as intended under all scenarios.
Fixes #533.

config: Improve config file handling.

---

blockchain/chainio.go
blockchain/chainio_test.go
blockchain/fullblocktests/params.go
blockchain/stake/staketx_test.go
blockchain/stake/tickets_test.go
blockchain/utxoviewpoint.go
blockchain/validate_test.go
chaincfg/genesis.go
mempool/policy.go
mempool/policy_test.go
rpcserver.go
txscript/engine_test.go
txscript/script_test.go
txscript/sign_test.go
wire/bench_test.go
wire/blockheader.go
wire/blockheader_test.go
wire/msgblock.go
wire/msgblock_test.go
wire/msgtx.go
wire/msgtx_test.go

Decred's serialized format for transactions split the 32-bit version field into two 16-bit components such that the upper bits are used to encode a serialization type and the lower 16 bits are the actual
transaction version.
Unfortunately, when this was done, the in-memory transaction struct was not also updated to hide this complexity, which means that callers currently have to understand and take special care when dealing with the version field of the transaction.
Since the main purpose of the wire package is precisely to hide these details, this remedies the situation by introducing a new field on the in-memory transaction struct named `SerType` which houses the serialization type and changes the Version field back to having the desired semantics of actually being the real transaction …

multi: Separate tx serialization type from version.

---

mempool/policy.go

The old code ran dust checks on regular, vote, and revocation
transactions, while ignoring any dust checking on ticket purchases.
This change also removes the dust checking for votes and revocations
as these are required for the network to run and should not be
rejected just to minimize dust.  The output amounts for these votes
and revocations are determined by consensus rules so standard checks
must be relaxed on them.
If there were to be any dust checks performed on stake transactions,
it should only be done on the commitment amounts in ticket purchases.
By calculating the output amounts that a revocation would require
creating, the mempool could determine if the revocation outputs would
be considered dust with the current policy and reject the ticket
purchase.
Fixes #805.

Only perform standard dust checks on regular transactions.

---

blockchain/chain.go

getstakeversions asserts the hash provided exists on chain before
proceeding to find the node.
Fixes #527

blockchain: Improve getstakeversions efficiency.

---

config.go
database/cmd/dbtool/globalconfig.go
database/cmd/dbtool/insecureimport.go
database/ffldb/driver_test.go
wire/msgversion.go

As per https://github.com/golang/go/wiki/CodeReviewComments#error-strings,
error strings should not be capitalized
- Replace Capitalized by lower cases
- Also, at some places, made a judgement call and added a prefix

multi: Error descriptions should be lowercase.

---

rpcserver.go

This fixes a possible panic when attempting to issue createrawssrtx with a txid that is not found.

rpcserver: check whether ticketUtx was found

---

config.go
sampleconfig/README.md
sampleconfig/doc.go
sampleconfig/sampleconfig.go

This adds a `readme` and `doc.go` for the `sampleconfig` package so it is consistent with all of the other packages.
While here, it also changes the exported value to a constant and removes
the unused `sampleConfigFilename` constant.

sampleconfig: Add package README and doc.go.

---

cmd/addblock/config.go
cmd/checkdevpremine/config.go
cmd/dcrctl/config.go
cmd/findcheckpoint/config.go
cmd/gencerts/gencerts.go
config.go
database/cmd/dbtool/main.go
glide.lock
glide.yaml

glide: use jessevdk/go-flags for consistency.

---

addrmgr/addrmanager.go
blockchain/chainio.go
blockchain/fullblocktests/generate.go
cmd/addblock/config.go
cmd/addblock/import.go
cmd/dcrctl/config.go
cmd/findcheckpoint/config.go
config.go
connmgr/connmanager.go
cpuminer.go
database/cmd/dbtool/globalconfig.go
database/ffldb/driver_test.go
database/ffldb/interface_test.go
txscript/stack_test.go
upnp.go

Fixes #363
Functions fmt.Error(), errors.New() are inspected.
Files under the dcrd/vendor directory are ignored.

multi: Error descriptions are in lower case.

---

blockchain/stake/tickets_test.go

Rather than redefining the simnet parameters in the tests, just use the existing `chaincfg` simnet parameters.  This is acceptable because there are now full block consensus tests that have their own definitions and ensure the consensus handling for tickets is correct.
Further, if these tests really wanted to have their own versions, they should instead start with the definition in chain params, make a copy, and change whatever they require that is different versus redefining them which makes them cumbersome to update.

stake: Modify ticket tests to use chaincfg params.

---

blockchain/difficulty_test.go
blockchain/stakeversion_test.go
blockchain/votebits_test.go

This modifies the `newFakeChain` and `newFakeNode` functions to be easier to work with and then updates the various tests that use them to significantly simply them.  It also removes the `genesisBlockNode` function since it is no longer necessary due to the changes other changes.
While here, it also improves the comments on the tests to better describe what is being tested.

blockchain: Cleanup various tests.

---

config.go
dcrd.go
doc.go
sampleconfig/sampleconfig.go

extend --profile cmd line option to allow interface to be specified

---

run_tests.sh

For a clean install, gometalinter can return non-zero, or gometalinter
may not run at all if it is not present.
In these cases, the content of stdout is zero bytes, and the script
continues when it should error out.
This error can easily occur when initially setting up the dev project
and one has not installed gometalinter or unconvert.  (This is not
a problem for docker testing, as these are preinstalled.)
Also updated README.md to describe the testing dependencies.

Ensure 'run_tests.sh local' fails correctly when gometalinter errors.

---

blockchain/fullblocktests/params.go
chaincfg/params.go

This adds a new definition for the upcoming agenda vote to enable the lnfeatures as defined by DCP0002 and DCP0003.  It does not include any code to make decisions or bump the versions.  It is only the definition.

chaincfg: Introduce agenda for v5 lnfeatures vote.

---

rpcserver.go

rpcserver: return rule error on rejected raw tx

---

mempool/mempool.go
mempool/mempool_test.go
mempool/policy.go
mining.go
server.go
txscript/opcode_test.go
txscript/standard.go

This modifies the way standard verification flags are handled so that it is possible to selectively enable them based on the result of agenda votes.
First, it moves the `StandardVerifyFlags` constant from the `txscript` package to the `mempool/policy` code and renames it to `BaseStandardVerifyFlags`.  As the TODO in the comment of the moved constant indicated, these flags are policy related and thus really belong in policy.  Ideally there would be a completely separate policy package, but since the policy code currently lives in `mempool/policy.go`, the constant has been moved there.
Next, it introduces a new function named `standardScriptVerifyFlags`, which accepts the chain as an argument and, for now, just returns the `BaseStandardVerifyFlags` along with a `nil` error.  This will allow …

multi: Abstract standard verification flags.

---

blockchain/accept.go
blockchain/chain.go
blockchain/prune.go

This removes the memory block node (header) pruning.  It should be noted that this does not apply to stake node pruning.
This is being done for two primary reasons:
- The goal is to ultimately have all block nodes in memory in the same way the upstream code has done since it provides significant   optimization and code simplification opportunities
- Upcoming code that deals with calculating sequence locks on inputs far in the past requires the ability to quickly calculate the median time for arbitrarily old nodes and consequently pruning the memory block nodes could lead to significant performance implications under those conditions

chain: Remove memory block node pruning.

---

mempool/mempool.go
mempool/mempool_test.go
mempool/policy.go
mempool/policy_test.go
server.go

This modifies the mempool transaction finality checks to use the past median time instead of the adjusted network time.  This ensures the standardness rules match the upcoming consensus rules which reject transactions that are not after the median time of the last several blocks.  Without this change, it is possible for transactions which can never make it into a block to be admitted to the mempool thereby wasting memory.
- Introduce a new callback to the mempool config named `PastMedianTime`  for obtaining the median time for the current best chain so it can remain decoupled from the chain
- Update the tx finality standardness check to use the callback
- Remove the now unused `TimeSource` mempool config parameter
- Update the mempool test …

mempool: Use median time for tx finality checks.

---

wire/common.go

Fixes #357
```
benchmark: BenchmarkDecodeHeaders
old ns/op     new ns/op     delta
-----------------------------------
4517561       3335930       -26.16%
old allocs    new allocs    delta
-----------------------------------
12002         2             -99.98%
old bytes     new bytes     delta
-----------------------------------
561793        417792        -25.63%
```

wire: Decrease num allocs when decoding headers.

---

blockchain/accept.go
blockchain/agendas_test.go
blockchain/stakeversion_test.go
blockchain/thresholdstate.go
blockchain/validate.go
mining.go
server.go

**This requires PR #864**.
This implements the agenda for voting on the LN features as defined in [DCP0002](https://github.com/decred/dcps/blob/master/dcp-0002/dcp-0002.mediawiki) and [DCP0003](https://github.com/decred/dcps/blob/master/dcp-0003/dcp-0003.mediawiki) along with consensus tests to ensure its correctness.
- Generate new version blocks and reject old version blocks after a super majority has been reached
- New block version on `mainnet` is version 5
- New block version on `testnet` is version 6
- Introduce a convenience function for determining if the vote passed and is now active
- Introduce a new function for getting the consensus script verification flags and setting the appropriate flags to enforce the new consensus semantics in …

multi: Enable vote for DCP0002 and DCP0003.

---

.gitignore

This syncs the `.gitignore` file with the upstream `btcd` project since it shouldn't have been completely changed to begin with.  While here, it also adds the Decred-specific binaries.

Improve gitignore.

---

rpcclient/README.md

This information no longer applies since the `rpcclient` was merged into dcrd proper.

rpcclient: Remove docker info from README.md.

---

dcrutil/hdkeychain/example_test.go

This works around the issue with `go vet` via `gometalinter` as described in alecthomas/gometalinter#351 by showing the example at the package level instead of on the function itself.

hdkeychain: Work around go vet issue with examples.

---

bloom/example_test.go

The missing import is preventing `go test` from completing.

bloom: Add missing import to examples.

---

rpcserver.go

This checks the error for UpdateBlockTime.

rpcserver: check for error in getwork request.

---

rpcserver.go

Hello.
When a miner (malicious) submit the orphan block to dcrd, it will cause nil pointer deference.
Please review this PR, many thanks:)

rpcserver: nil pointer dereference when submit orphan block

---

bloom/README.md

The link in the dcrd/bloom/README.md page led to a 'Not Found' page on
GoDoc. The link has now been changed. Fixes issue #921.

bloom: Fix link in README.

---

rpcserver.go

rpcserver: skip generating certs when nolisten set

---

addrmgr/addrmanager.go
addrmgr/knownaddress.go
peer/peer.go

Following are 3 instances of data race as per report from race detector:
```
================================================================
1
================================================================
WARNING: DATA RACE
Write at 0x00c4299e4eb8 by goroutine 70:
github.com/decred/dcrd/addrmgr.(*AddrManager).Attempt()
/Users/maicalal/go/src/github.com/decred/dcrd/addrmgr/addrmanager.go:828 +0x112
main.(*server).outboundPeerConnected()
/Users/maicalal/go/src/github.com/decred/dcrd/server.go:1678 +0x656
main.(*server).(main.outboundPeerConnected)-fm()
/Users/maicalal/go/src/github.com/decred/dcrd/server.go:2535 +0x5f
Previous read at 0x00c4299e4eb8 by goroutine 49:
main.newServer.func6()
/Users/maicalal/go/src/github.com/decred/dcrd/addrmgr/knownaddress.go:34 +0x473 …
```

multi: Handle detected data race conditions 

---

dcrjson/chainsvrresults.go
peer/peer.go
rpcserver.go
rpcserverhelp.go

- [3b5bb9f](https://github.com/btcsuite/btcd/commit/3b5bb9fd43eaab2dc902c47b4900b8161b77330a)
- NOOP, no concept of a`preciousblock` in decred.
- [07e1e30](https://github.com/btcsuite/btcd/commit/07e1e308f1469b56ad3b8d7d3dc02466673e0deb)

rpc: Add localaddr and relaytxes to getpeerinfo

---

txscript/standard.go
txscript/standard_test.go

- [b60e354](https://github.com/btcsuite/btcd/commit/b60e3547d2602b23fedf191d44377f3084f65a9a)
---
This corrects the `isNullData` standard transaction type test to work properly with canonically-encoded data pushes.  In particular, single byte data pushes that are small integers (0-16) are converted to the
equivalent numeric opcodes when canonically encoded and the code failed to detect them properly.
It also adds several tests to ensure that both canonical and non-canonical nulldata scripts are recognized properly and modifies the test failure print to include the script that failed.
This does not affect consensus since it is just a standardness check.

txscript: Correct nulldata standardness check.

---

README.md

Hello! Following the readme I get an error with the suggested command for running the tests in a docker container with a previous version of Go, it happens to be 1.7, not the current previous one:
```
$ ./run_tests.sh 1.7
[...]
server.go:1282:11:warning: Until not declared by package time (gosimple)
server.go:1282:11:warning: Until not declared by package time (gosimple)
server.go:1282:11:warning: Until not declared by package time (unconvert)
server.go:1282:11:warning: Until not declared by package time (unconvert)
+ '[' 0 '!=' 0 ']'
+ go install . ./cmd/...
./server.go:1282: undefined: time.Until
```
Not sure if this is intended, I've proposed changes for suggesting the previous, supported version of Go, in this case 1.8, which gives some warnings but doesn't fail.
Cheers!

update go version for example test run in readme

---

rpcclient/infrastructure.go

[go1.10 fixes a bug](https://go-review.googlesource.com/c/go/+/82135) in encoding/json that allowed it to allocate an unexported field, but `(*rpcclient.Client).handleMessage` relied on this behaviour to unmarshal into `inMessage`.  Address the go1.10 fix by allocating the unexported pointer types (`rawResponse` and `rawNotification`).
There may be other uses of `json.Unmarshal` that rely on the pre-go1.10 behaviour that we should look out for.

rpcclient: json unmarshal into unexported embedded pointer

---

rpctest/node.go
rpctest/rpc_harness.go

This pr contains the following upstream commits:
- [59a3fc2](https://github.com/btcsuite/btcd/commit/59a3fc2f661a332d386e68f5f8ef3bf1d6d5a02a)
- NOOP
- [49cbaf2](https://github.com/btcsuite/btcd/commit/49cbaf23dd94d2eb6a44eac3cc24e98f9a582aa5)
- does not apply to dcrd
- [da04285](https://github.com/btcsuite/btcd/commit/da04285e0d65bd85078908bfd8d1d4c81c11435e)
---
This modifies the rpctest framework to start btcd with the appropriate
network flags depending on the provided parameters.
Previously, it always started btcd with --simnet even if other
parameters, such as those for the regression test network, were
provided.

rpctest: Choose flags based on provided params.

---

chaincfg/params.go

Switched the testnet seeder on netpurgatory to .com instead
of .org so it matches the mainnet one.
I'm consolidating/reorganizing some servers and domains so I'd like to move my testnet seeder to the same domain as my mainnet one.

Rename one of the testnet seeders.

---

txscript/script.go
txscript/script_test.go

This modifies the exported `CalcSignatureHash` function to accept a script as bytes instead of an array of parsed opcodes which are not available to callers outside of the package.
While here, it also adds a proper comment for the exported function since it is intended for more than testing as the previous comment claimed.
Finally, it updates the tests to use a valid script instead of the previous impossible to achieve constructed series of parsed opcodes.

txscript: Allow external signature hash calc.

---

txscript/standard.go
txscript/standard_test.go

- [d0a9c03](https://github.com/btcsuite/btcd/commit/d0a9c03844a4a7f4c27e24fdc856333d17ec2f6f)
- NOOP
- [b77654f](https://github.com/btcsuite/btcd/commit/b77654f8d4dc593d15bcfe5cfc8783606745fb69)
- [0731f2d](https://github.com/btcsuite/btcd/commit/0731f2ddc979708df658492bd947addaa79e114c)
- Updated scripts used for `just right` and `too big`
---
This modifies the recently-added NullDataScript function in several
ways in an effort to make them more consistent with the tests in the
rest of the code base and improve/correct the logic:
- Use the hexToBytes and mustParseShortForm functions
- Consistently format the test errors
- Replace the valid bool flag with an expected error and test against it
- Ensure the returned script type is the …

 txscript: Cleanup and improve NullDataScript tests.

---

blockchain/fullblocktests/generate.go
chaincfg/chainec/secp256k1.go
chaincfg/chainec/secschnorr.go
dcrec/secp256k1/btcec_test.go
dcrec/secp256k1/ciphering.go
dcrec/secp256k1/ciphering_test.go
dcrec/secp256k1/example_test.go
dcrec/secp256k1/privkey.go
dcrec/secp256k1/privkey_test.go
dcrec/secp256k1/pubkey.go
dcrec/secp256k1/pubkey_test.go
dcrec/secp256k1/schnorr/ecdsa.go
dcrec/secp256k1/schnorr/ecdsa_test.go
dcrec/secp256k1/schnorr/pubkey.go
dcrec/secp256k1/schnorr/threshold.go
dcrec/secp256k1/schnorr/threshold_test.go
dcrec/secp256k1/signature.go
dcrec/secp256k1/signature_test.go
mempool/mempool_test.go

This simplifies sec256k1 & schnorr related func signatures by removing the koblitz curve param. The secp256k1 curve is used implicitly instead.
This is work towards #923.

sec256k1: update func signatures.

---

txscript/standard.go
txscript/standard_test.go

This update removes `NullDataScript` in favour of `GenerateProvablyPruneableOut` as well as enforcing `MaxDataCarrierSize` for it. The null data test func is renamed and repurposed to use GenerateProvablyPruneableOut as well.
resolves #952

txscript: enforce MaxDataCarrierSize for GenerateProvablyPruneableOut

---

.travis.yml

Closes #957.
GOVERSION wasn't being set in the environment so travis was testing Go 1.9 twice.

travis: set GOVERSION environment properly

---

blockchain/fullblocktests/doc.go
docs/README.md

This PR consists of the following upstream commit:
- [69fca4d](https://github.com/btcsuite/btcd/commit/69fca4d9b1f0fd8f9b2f5380822e8f8d952c1796)
- NOOP
- [bff2ba7](https://github.com/btcsuite/btcd/commit/bff2ba70fd23c9e360ec6da3780842c773175e62)
- NOOP
- [9634a8c](https://github.com/btcsuite/btcd/commit/9634a8cb0d3278c0261df979694a0e93ea042dae)
- [b8df516](https://github.com/btcsuite/btcd/commit/b8df516b4b267acf2de46be593a9d948d1d2c420)

docs: Add fullblocktests entry and minor consistency updates

---

blockchain/stake/internal/tickettreap/common.go
run_tests.sh

This adds a directive to instruct `gometalinter` to ignore a false positive produced by vet.  The code in question intentionally makes use of the property vet is warning about.

stake: Override false positive vet error.

---

sampleconfig/sampleconfig.go

This updates the minimum relay fee in the sample config file to match the actual default.  Note that it's commented anyways, so this does not result in any logical change.  However, the file aims to have the defaults commented out by default, so it makes sense to update the value accordingly.

sampleconfig: Update min relay fee.

---

addrmgr/doc.go
bloom/doc.go
limits/doc.go
mempool/doc.go

Just some small documentation improvements.

docs: document packages and fix typo

---

rpcserver.go

rpcserver: assert network for validateaddress rpc.

---

docs/json_rpc_api.md

- adjust links and example code to reflect that rpcclient is now part of the main dcrd repo
- `wire.NewShaHashFromStr` has been moved to `chainhash.NewHashFromStr`
- use mainnet port and genesis block hash
The prototype of the notification handlers `OnBlockConnected` and `OnBlockDisconnected` changed.
Any ideas how to process the `blockHeader` byte slice to make the output more meaningful?

docs: rpclient is now part of main dcrd repo, fix code examples

---

rpcserver.go

This modifies the `sendrawtransaction` handler to avoid adding stake transactions to the rebroadcast logic since they should not be perpetually rebroadcast without special handling to remove them under certain circumstances other than showing up in a block.
This is particularly applicable to votes which are only valid for a specific block and are time sensitive, but it also applies to ticket purchases which are only valid for the duration of a stake difficulty interval, and revocations which could be invalidated in a reorg due to the associated missed or expired ticket being resurrected in a reorg.

rpcserver: Do not rebroadcast stake transactions.

---

.travis.yml
blockchain/stake/internal/tickettreap/common.go
run_tests.sh
sampleconfig/sampleconfig.go

- [bca9877](https://github.com/decred/dcrd/commit/bca9877796e9590adca69818e3049fbcff9a08af)
- NOOP
- [a09d052](https://github.com/decred/dcrd/commit/a09d052f96f5dc19d014e2ee8243ca87520882b8)
- NOOP
- [0d508e6](https://github.com/decred/dcrd/commit/0d508e652258c10230c22651de1ce2c395f695d4)
- NOOP
- [f161d6b](https://github.com/decred/dcrd/commit/f161d6b69e9adb97a04e51c28f26eb614f9f01a2)
---
DNSSeed defines a DNS Seed with a hostname and whether it supports
filtering by service flag bits.

chaincfg: Introduce new type DNSSeed 

---

blockchain/validate.go
rpcserver.go

This modifies the `CheckProofOfWork` function to accept a block header instead of an entire block since there is no reason to force the caller to have access to a full block when only the header is required.

blockchain: Accept header in CheckProofOfWork.

---

blockchain/accept.go
blockchain/agendas_test.go
blockchain/chain.go
blockchain/chainio.go
blockchain/difficulty_test.go
blockchain/internal_test.go
blockchain/stake/staketx.go
blockchain/stakeversion_test.go
blockchain/validate.go
blockchain/validate_test.go
blockchain/votebits_test.go
blockmanager.go

First try at improving #913.
This adds a new function `FindSpentTicketsInBlock` that extracts all spent and revoked tickets, plus the vote bits of a given block and uses that function instead of the individual functions when loading a new node into the blockchain.
This improves startup time a bit, as the `isSSGen`, `isSSRtx`, and `determineTxType` are somewhat slow, as they need to decode the output script of the transactions. Looping over the transactions once and doing a single test is faster.
The first commit adds a couple of instrumentation lines (to be removed before final merge).
Numbers for my computer:
```
| variation     | mainnet | testnet |
| with patch    |   23.7s |   42.6s |
| without patch |   35.9s |  118.0s |
```

blockchain: Switch to FindSpentTicketsInBlock.

---

rpctest/rpc_harness.go
service_windows.go

This simplifies the code based on the recommendations of the `gosimple` lint tool.

multi: Simplify code per gosimple linter.

---

blockchain/chain.go
blockchain/stake/tickets.go
blockchain/stake/tickets_test.go
blockchain/stakenode.go
blockchain/upgrade.go

**NOTE: This requires PR #986**
This modifies the stake package to accept an initialization vector for the node connection and disconnection code so that the caller can provide a cached value versus the data having to be recomputed.  All tests in the stake package have been updated for the changes.
It also updates the `blockchain` package to calculate the iv for the block header and cache the value with each block node and updates the callers into the modified stake package functions to use the cached values.

blockchain/stake: Use Hash256PRNG init vector.

---

blockchain/chain.go
blockchain/chainio.go
blockchain/difficulty.go
blockchain/difficulty_test.go
blockchain/internal_test.go
blockchain/sequencelock_test.go
blockchain/stakeversion.go
blockchain/stakeversion_test.go
blockchain/subsidy.go
blockchain/timesorter.go
blockchain/timesorter_test.go
blockchain/utxoviewpoint.go
blockchain/validate.go
blockchain/votebits.go
blockchain/votebits_test.go

**NOTE: This requires #986 and #987**.
This modifies the block node structure to include only the specifically used fields, some of which in a more compact format, as opposed to copying the entire header and updates all code and tests accordingly.
Not only is this a more efficient approach that helps pave the way for future optimizations, it is also consistent with the upstream code which helps minimize the differences to facilitate easier syncs due to less merge conflicts.
In particular, since the merkle and stake roots, number of revocations, size, nonce, and extradata fields aren't used currently, they are no longer copied into the block node.  Also, the block node already had a height field, which is also in the header, so this change also removes that duplication.
Another change is …

blockchain: Don't store full header in block node.

---

blockchain/blockindex_test.go
blockchain/chain.go
blockchain/chainio.go
blockchain/difficulty.go
blockchain/difficulty_test.go
blockchain/internal_test.go
blockchain/sequencelock_test.go
blockchain/stakeversion.go
blockchain/stakeversion_test.go
blockchain/subsidy.go
blockchain/timesorter.go
blockchain/timesorter_test.go
blockchain/utxoviewpoint.go
blockchain/validate.go
blockchain/votebits.go
blockchain/votebits_test.go
rpcserver.go
server.go

**This requires #986, #987, and #988**.
This modifies the block node structure to include extra fields needed to be able to reconstruct the block header from a node, and exposes a new function from chain to fetch the block headers which takes advantage of the new functionality to reconstruct the headers from memory when possible.  Finally, it updates both the p2p and RPC servers to make use of the new function.
This is useful since many of the block header fields need to be kept in order to form the block index anyways and storing the extra fields means the database does not have to be consulted when headers are requested if the associated node is still in memory.

blockchain: Reconstruct headers from block nodes.

---

dcrjson/dcrwalletextcmds.go

Considering that there is no method for getseed and also that your seed should be saved at wallet creation it seems best to get rid of getseed type and instance function.

dcrwalletextcmds: remove getseed

---

blockchain/accept.go
blockchain/indexers/addrindex.go
blockchain/indexers/existsaddrindex.go
blockchain/indexers/manager.go
blockchain/sequencelock.go
blockchain/stake/staketx.go
blockchain/stake/staketx_test.go
blockchain/stakenode.go
blockchain/subsidy.go
blockchain/upgrade.go
blockchain/utxoviewpoint.go
blockchain/validate.go
blockmanager.go
cmd/checkdevpremine/checkdevpremine.go
mining.go
rpcserver.go

This modifies the `IsSStx`, `IsSSGen`, and `IsSSRtx` functions to only return a `bool` and introduces `CheckSStx`, `CheckSSGen`, and `CheckSSRtx` to return the actual error as needed by consensus.
This is being done because "is" functions are much nicer to use when they don't return an error and the callers that use them almost never care why they aren't of the type, they just want to determine if they are.  In the few cases where the caller does care, they can use of the new check functions.
While here, also update the comments to call out what the more common names for the transaction types are and to add comments to the test functions for consistency.
Finally, it updates all callers in the repo accordingly.

stake/multi: Don't return errors for IsX functions.

---

blockchain/chain.go
blockchain/chainio.go
blockchain/stakeversion_test.go

The current serialized "block index" is actually a main chain index, so this renames the related functions to correctly denote it's a main chain index and updates the comments accordingly.
This is being done since future work intends to actually serialize the entire block index and renaming this now will make the introduction of full block index code more clear.

blockchain: Rename block index to main chain index.

---

blockchain/accept.go
blockchain/blockindex.go
blockchain/blockindex_test.go
blockchain/blocklocator.go
blockchain/chain.go
blockchain/chainio.go
blockchain/difficulty.go
blockchain/difficulty_test.go
blockchain/process.go
blockchain/sequencelock.go
blockchain/sequencelock_test.go
blockchain/stakeext.go
blockchain/stakenode.go
blockchain/stakeversion.go
blockchain/stakeversion_test.go
blockchain/thresholdstate.go
blockchain/validate.go
blockchain/votebits_test.go

**This requires #989**.
This refactors the block index logic into a separate struct and introduces an individual lock for it so it can be queried independent of the chain lock.
It also modifies the `newBlockNode` function to accept nil for the ticket spend information parameter and updates all of the test code that doesn't require it to use nil.

blockchain: Refactor main block index logic.

---

blockchain/chain.go
blockchain/chainio.go
blockchain/fullblocks_test.go
blockchain/upgrade.go
blockmanager.go
cmd/findcheckpoint/findcheckpoint.go
mining.go
rpcserver.go
server.go

**This requires #990**
This modifies the `BestState` struct in the `blockchain` package to store hashes directly instead of pointers to them and updates callers to deal with the API change in the exported `BestState` struct.
In general, the preferred approach for hashes moving forward is to store hash values in complex data structures, particularly those that will be used for cache entries, and accept pointers to hashes in arguments to functions.
Some of the reasoning behind making this change is:
- It is generally preferred to avoid storing pointers to data in cache objects since doing so can easily lead to storing interior pointers into other structs that then can't be GC'd
- Keeping the hash values directly in the structs provides better cache locality

blockchain: Use hash values in structs.

---

blockchain/chainio.go

This removes the `DumpBlockChain` which is leftover from earlier development.  It will still be in commit history if it's ever needed again, but it doesn't belong in production code.

blockchain: Remove unused dump function.

---

blockchain/chain.go

This generalizes and optimizes the reorganize chain function to take advantage of the linear structure of the nodes being attached and detached in order to avoid reloading the parent blocks as well as allow it to rewind the chain in the case no attach nodes are provided or extend the chain in the case no detach nodes are provided.
It also adds several assertions to ensure the assumptions about the state hold and generally cleans up the function for code consistency.

blockchain: Generalize and optimize chain reorg.

---

blockchain/accept.go
blockchain/chain.go
blockchain/validate.go

**This requires PR #997**.
This modifies the block connection code paths to accept the parent block in addition to the block as a parameter versus loading it on demand in the called functions.  This makes the dependency more explicit and also ensures it doesn't potentially get loaded multiple times in the reorg case.

blockchain: Pass parent block in connection code.

---

blockchain/accept.go
blockchain/chain.go
blockchain/chainio.go
blockchain/stakenode.go
blockchain/utxoviewpoint.go
blockchain/validate.go
rpcserver.go
server.go

**This requires #998**.
This makes the semantics of block fetching much more explicit by introducing a new function named `fetchMainChainBlockByHash` which only attempts to the load a block from the main chain block cache and then falls back to the database.  While currently only blocks in the main chain are in the database, the intention is for future commits to allow the database to house side chain blocks as well, so having clearly defined semantics will help make that transition easier to verify.
While here, it also renames `{f,F}etchBlockFromHash` to `{f,F}etchBlockByHash` to be consistent with the naming used by the other existing functions and updates the comments to better describe the function semantics.

blockchain: Explicit block fetch semantics.

---

blockchain/chain.go

This corrects the generalized reorg logic in `reorganizeChain` for the case when there are only nodes being detached since the fork block would be nil in that case.
It should be noted that nothing currently calls this code under that scenario so this case would never be hit, but that could change in the future, so the logic needs to account for it.

blockchain: Use next detach block in reorg chain.

---

blockchain/validate.go
blockchain/validate_test.go

This moves the test for validating the number of votes specified by the header is at least the required minimum into the `checkBlockHeaderSanity` function where it more naturally belongs since it is solely dependent on information the header.
Also, remove the redundant check for the same condition from `checkBlockSanity` since it has now already been checked according to the value the header commits to and therefore validating the header commitment for the number of votes implies correctness.

blockchain: Validate num votes in header sanity.

---

blockchain/validate.go

This changes the validation that the block does not exceed the maximum number of votes to make use of the value committed to by the header and thus moves the test into `checkBlockHeaderSanity` accordingly.
This is acceptable since the code also validates the header commitment for the number of votes later and therefore implies correctness.

blockchain: Validate max votes in header sanity.

---

blockchain/validate.go

This changes the validation that the block does not contain any votes or revocations before stake enabled height and stake validation height to make use of the values committed to by the header and thus moves the test into `checkBlockHeaderSanity` accordingly.
It also combines the two checks to only check before stake validation height since that always comes after stake enabled height and adds an assertion to ensure that optimization assumption holds.
This is acceptable since the code also validates the header commitments for the number of votes and revocations later and therefore implies correctness.

blockchain: No votes/revocations in header sanity.

---

blockchain/accept.go
blockchain/validate.go

This moves the test for validating the block height specified by the header matches the height it actually connects to the chain into the `checkBlockHeaderContext` function where it more naturally belongs since it is only dependent on the header and its contextual position within the chain.

blockchain: Validate block height in header context.

---

blockchain/validate.go

**This requires PRs #1008, #1009, #1010, and #1011**.
This cleans up the `checkBlockSanity` and make it more consistent with the rest of the code base.
- Use the local variable throughout
- Check the header values against the expected value instead of the reverse
- Make the errors more consistent and verbose in some cases
- Use an int64 for the type so consensus doesn't different between computer architecture
- Correct and add some comments

blockchain: Block sanity cleanup and consistency.

---

blockchain/validate.go
blockchain/validate_test.go

**This requires #1013**.
This moves the check for validating that there are only ticket purchases included in blocks before stake validation height to `checkBlockSanity` where is more naturally belongs since it does not require access to any previous chain context.

blockchain: Only tickets before SVH in block sanity.

---

blockchain/accept.go
blockchain/upgrade.go

This moves the `ticketsSpentInBlock` and `ticketsRevokedInBlock` functions to the `upgrade.go` file since they are only used in the upgrade code.

blockchain: Move upgrade-only code to upgrade.go.

---

blockchain/stake/staketx.go
blockchain/stake/staketx_test.go
blockchain/validate.go
mempool/mempool.go
mining.go

This modifies the `SSGenBlockVotedOn` function to directly copy the hash the vote commits to into a statically sized array versus calling the hash function and thus can remove the potential runtime error.
This is preferred because the code will fail to compile if the size of `chainhash.HashSize` is every changed which is desirable because it would mean the assumptions the code makes would be invalidated.
It also updates all callers in the repository accordingly.

stake: Static assert of vote commitment.

---

blockchain/error.go
blockchain/validate_test.go

This removes the `ErrUnparseableSSGen` error code since it is no longer used.

blockchain: Remove unused error code.

---

blockchain/chain.go
blockchain/reorganization_test.go
blockchain/validate.go
blockchain/validate_test.go
mining.go

**This requires PR #1014**.
This modifies the exported `CheckConnectBlock` function to call the `checkBlockSanity` and `checkBlockContext` functions to ensure all validation rules are enforced from the mining code.
Since both the mining code and tests typically work with unsolved blocks, this also introduces a new parameter on `CheckConnectBlock` to pass behavior flags which allows the caller to skip the proof of work check.
It also modifies `forceHeadReorganization` to call `checkBlockContext` for the same reason.
Finally, all tests and call sites are updated with the appropriate flags and various tests are updated for the changes accordingly.

blockchain/mining: Full checks in CCB.

---

blockchain/validate.go

**This requires #1017**.
This moves the test for validating the pool size specified by the header matches the calculated size into the `checkBlockHeaderContext` function where it more naturally belongs since it is only dependent on the header and its contextual position within the chain.

blockchain: Validate pool size in header context.

---

blockchain/error.go
blockchain/fullblocktests/generate.go
blockchain/validate.go

This modifies the `checkBlockHeaderSanity` function to include an additional check which ensures the final state is zero prior to stake validation height.
It should be noted that this is technically a hard fork since before this change it was possible to use any value for the final state prior to stake validation height.  However, no blocks on mainnet nor testnet ever used non-zero final states for blocks in that range and they are buried behind checkpoints in the minimum required version of the software due to the previous consensus votes, so it isn't possible to trigger a reorg that would fork old nodes off the network anyways, so it is safe to retroactively apply this check.
It also adds tests for the new consensus check which ensures the final state is zero prior to stake validation …

blockchain: Validate early final state is zero.

---

blockchain/validate.go

This moves the test for validating the final state specified by the header matches the calculated final state into the `checkBlockHeaderContext` function where it more naturally belongs since it is only dependent on the header and its contextual position within the chain.

blockchain: Validate final state in header context.

---

blockchain/validate.go

This moves the check for validating that the number of revocations does not exceed the maximum allowed to the `checkBlockSanity` function where it more naturally belongs since it does not require access to any previous chain context.
It should be noted that this check previously used `math.MaxUint8` and was rather implicitly limited by the fact the header uses a `uint8` for the field, so this makes the requirement more explicit by defining a constant.

blockchain: Max revocations in block sanity.

---

blockchain/validate.go

This moves the test for validating the votes in the block are eligible votes per the results of the ticket lottery into the `checkBlockContext` function where it more naturally belongs since it is only dependent on the block and its contextual position within the chain.
While here, it also refactors the check into a separate function named `checkAllowedVotes` to improve readability.

blockchain: Validate allowed votes in block context.

---

blockchain/validate.go

This moves the test for validating the revocations in the block are actually eligible to be revoked per the results of the ticket lottery into the `checkBlockContext` function where it more naturally belongs since it is only dependent on the block and its contextual position within the chain.
While here, it also refactors the check into a separate function named `checkAllowedRevocations` to improve readability.  Also, since this was the final check in the `CheckBlockStakeSanity` function, that entire function has been removed along with its call site.

blockchain: Validate allowed revokes in blk contxt.

---

blockchain/blockindex.go
blockchain/chain.go
blockchain/stake/tickets.go
blockchain/stakenode.go
blockchain/upgrade.go

This renames the fields dealing with the hashes of tickets that have been voted on from `ticketsSpent` to `ticketsVoted` to more accurately differentiate them from revocations which also technically spend tickets.

blockchain/stake: Rename tix spent to tix voted.

---

txscript/standard.go

This allows redeeming parties to audit the secret size and ensure it
will be usable once revealed.

Require atomic swap contracts to specify the secret size.

---

blockchain/accept.go
blockchain/chain.go
blockchain/process.go
blockchain/validate.go

This modifies the `blockchain` code to store all blocks that have passed proof-of-work and contextual validity tests in the database even if they may ultimately fail to connect.
This eliminates the need to store those blocks in memory, allows them to be available as orphans later even if they were never part of the main chain, and helps pave the way toward being able to separate the download logic from the connection logic.
Note that it also updates the `blockExists` function since the code base is currently in the process of changing over to decouple download and connection logic, but not all of the necessary parts are updated yet, to ensure blocks that are in the database, but do not have an associated main chain block index entry, are treated as if they do not exist for the purposes of …

blockchain: Store side chain blocks in database.

---

blockchain/chainio.go

Prior to this commit, the chain data structures were initialized in two separate places depending on whether or not the database state had already been created.
This simplifies that logic so that the initialization of the data structures happens in a single place.
In order to accomplish this, the logic has been split into three phases:
1) Query to determine the current state of the database
2) Optionally initialize the database by creating all buckets and populating it with the genesis block and associated state if it has not already been done
3) Initialize the data structures using the data loaded from the database

blockchain: Simplify initial chain state.

---

blockchain/chainio.go
blockchain/chainio_test.go
blockchain/internal/dbnamespace/dbnamespace.go
blockchain/upgrade.go

**This requires PR #1045**.
This modifies the database versioning to use separate keys within the version bucket for each component in order to simplify upgrade logic.
Having a single key for the various versions of the database components makes it difficult to use because the version isn't known until the data is read, however, modifying the format necessarily means the version is needed before that point to know which format to read.
While here, it uses a `uint64` to store the date instead of a `uint32` so the timestamp continues to work past 2106.
Also, it removes the upgrade started logic since it should be possible to stop in the middle of an upgrade and resume later.  Forcing a completely new database to be created because an upgrade was stopped in the middle is not ideal.

blockchain: Rework database versioning.

---

blockchain/chain.go
blockchain/chainio.go
blockchain/upgrade.go

**This require PRs #1045 and #1047**.
This modifies the database upgrade logic to avoid needing the chain and moves it earlier in the initialization process just after the initial database creation (if needed), but prior the final struct instance population from the database.
It is much simpler logic to have an already upgraded database prior to populating the initial chain state so all of the initial setup happens in one place.

blockchain: Don't require chain for db upgrades.

---

blockchain/chain.go
blockchain/chainio.go
blockchain/indexers/addrindex.go
blockchain/indexers/common.go
blockchain/indexers/existsaddrindex.go
blockchain/indexers/manager.go
blockchain/indexers/txindex.go
blockchain/upgrade.go
blockmanager.go
dcrd.go
server.go

**This requires PR #1051**.
This propagates the interrupt channel through to `blockchain` and the `indexers` so that it is possible to interrupt long-running operations such as catching up indexes.

blockchain/indexers: Allow interrupts.

---

blockchain/chainio.go

This removes the legacy version details from the database to ensure that loading older versions of the software after the database has been upgraded fails as desired.
This is important because otherwise, the database could actually be using a new version that has been upgraded via the new scheme, but old software would still see this old information and believe the database was still on that older version.

blockchain: Remove old version information.

---

blockchain/accept.go

This modifies the code in `maybeAcceptBlock` to return an error if there is no previous entry in the block index for a given block indicating it is either an orphan or the genesis block.
The function should never be called in either circumstance since the genesis block is valid by definition and orphans are handled prior to calling the function.

blockchain: Do not accept orphans/genesis block.

---

blockchain/accept.go
blockchain/blockindex.go
blockchain/blockindex_test.go
blockchain/chainio.go
blockchain/difficulty.go
blockchain/difficulty_test.go
blockchain/internal_test.go
blockchain/stakeversion_test.go
blockchain/validate.go
blockchain/validate_test.go

~**This requires PR #1057**.~ (now merged)
This consists of two commits to simplify the construction logic for block nodes.
The first separates the logic for populating the stake information in a block node from the construction of the node in order to better delineate the difference between the two and to pave the way for that information to be stored separately in the database versus needing to load full blocks to retrieve it.
The second modifies the `newBlockNode` function to accept the `parent` as an argument to automatically connect the newly created node.  When it is not `nil`, the work sum will automatically be summed and the parent of the new node will be set accordingly.  This simplifies the block node construction a bit and allows some redundant code to be removed.  It also …

blockchain: Simplify blocknode construction.

---

dcrjson/walletsvrresults.go

This adds a collection of summary total fields to the GetBalanceResult
struct which allows providing a summary of totals for all wallet
accounts when using `getbalance "*"`.

dcrjson: include summary totals in GetBalanceResult.

---

blockchain/blockindex.go
blockchain/stakenode.go

This provides a function to calculate the lottery initialization vector for a node on demand versus calculating it at node creation time and storing the result.
This is being done because it saves an additional 32 bytes in the block node structure and the ultimate goal is to move towards having all block nodes in memory to greatly simplify and optimize the code.  Since there will be a lot of nodes in memory, these extra bytes can add up to significant savings.

blockchain: Calculate the lottery IV on demand.

---

blockchain/error.go
blockchain/error_test.go

This adds missing error entries to the tests and also adds an additional check to ensure that all possibilities are tested to prevent drift in the future.

blockchain: Correct error stringer tests.

---

blockchain/accept.go
blockchain/blockindex.go
blockchain/chain.go

This simplifies and consolidates the logic for adding and removing nodes to and from the block index by moving the initial add into `maybeAcceptBlock` just after the node is created, adding the child
connection logic to the `AddNode` function, and introducing a `RemoveNode` function that is called in dry run mode which undoes the aforementioned changes.
In addition to being simpler logic to follow, it helps make it clear that all blocks which are written to the database end up with a block index entry, even if they ultimately fail to connect.

blockchain: Simplify add/remove node logic.

---

cmd/checkdevpremine/config.go
cmd/dcrctl/config.go
cmd/gencerts/gencerts.go
config.go
sampleconfig/sampleconfig.go

This fixes the behavior of expanding ~ on Windows and macOS, as well
as adding support for ~otheruser to expand to the home directory of
otheruser.
Modify the default sample config to reflect the change in the meaning
of ~ on Windows, and the unintended meaning of ~ on macOS.  Include
defaults for all 3 of the major operating system classes since
uncommenting the default Unix option on macOS or Windows would change
the blockchain data directory to a non-default location.
Fixes #1040.

Expand ~ to correct home directory on all OSes.

---

blockchain/chain.go

This modifies the `forceHeadReorganization` function to lookup the child node directly from the index instead of looping through all of the children looking for it.

blockchain: Lookup child in force head reorg.

---

blockchain/blockindex.go
blockchain/chainio.go
blockchain/chainio_test.go
blockchain/upgrade.go

This modifies the newly added block index serialization code to use a separate structure as opposed to working with block nodes directly.
This approach is more desirable because it provides better separation and more robust code against changes to the block node structure itself and it avoids complications dealing with non-serialized fields such as
parent and child pointers.

blockchain: Refactor block idx entry serialization.

---

blockchain/chain.go

This modifies `GetStakeVersions` to limit the requested count based on the height of the requested block instead of the entire height of the chain.

blockchain: Limit GetStakeVersions count.

---

blockchain/validate_test.go

This removes a couple of checks that are already tested via the dynamic full block tests and thus do not need to be tested again.

blockchain: Remove superfluous test checks.

---

blockchain/accept.go
blockchain/chain.go
blockchain/process.go
rpcserver.go

This switches block template proposal checks over to use `CheckConnectBlock` now that all of the core checks needed for block templates is included there, and, more importantly, removes the the `BFDryRun` flag since it was only used to test block template proposals and it is much simpler to allow the main chain processing paths to run without the complication of selectively processing code for dry run behavior.

blockchain: Remove dry run flag.

---

blockchain/chaingen/generator.go
blockchain/fullblocktests/README.md
blockchain/fullblocktests/generate.go
blockchain/validate_test.go

This PR  adds`AssertTipBlockStakeRoot` helper and moves the following block rejection cases into fullblocktests.
- `ErrVotesOnWrongBlock` 
- Attempt to add block with tickets voting on wrong block
- `ErrIncongruentVotebit` 
- Attempt to add block with incorrect votebits set
- Everyone votes yea, but block header says nay
- Everyone votes nay, but block header says yea
- 3x nay 2x yea, but block header says yea
- 2x nay 3x yea, but block header says nay
- `ErrBadMerkleRoot`
- Create block with an invalid stake root
- `ErrWrongBlockSize`
- Create block with an invalid block size
- `ErrBadCoinbaseAmountIn`
- Create block with an invalid subsidy for coinbase output
- `ErrBadStakebaseAmountIn`
- Create block with an invalid subsidy for a stakebase input
- `ErrRevocationsMismatch`
- Create …

blockchain: move block validation rule tests into fullblocktests (1 of x).

---

blockchain/stakeversion.go
blockchain/stakeversion_test.go

This removes the `calcStakeVersionByNode` in favor of just using `calcStakeVersion` directly since the latter already takes the node and the former is a simple pass through with no additional handling.

blockchain: Remove redundant stake ver calc func.

---

blockchain/chaingen/generator.go
blockchain/fullblocktests/generate.go

This modifies the `chaingen` test harness to error when a duplicate block name is provided to `NextBlock` to help prevent misuse.
It also corrects a couple of comment typos.

chaingen: Prevent dup block names in NextBlock.

---

blockchain/validate_test.go

This removes some tests from `validate_test.go` that are already tested by the dynamic full blocks tests.

blockchain: Remove duplicate val tests.

---

blockchain/chaingen/generator.go
blockchain/fullblocktests/generate.go

This exports the `VoteCommitmentScript` function from the `chaingen` package so callers can make use of it to create new vote commitment scripts and improves the test which checks for votes on the wrong block by creating a new commitment script and testing 3 different scenarios:
- Ticket that commits to the parent of the correct block to ensure that the code under test is not just failing due to a hash that doesn't exist
- Ticket that commits to the correct block hash and wrong block height
- Ticket the commits to the correct block height and wrong block hash

fullblocktests: Improve vote on wrong block tests.

---

blockchain/chaingen/generator.go
blockchain/fullblocktests/generate.go

This adds a new exported function named `IsSolved` to the `chaingen` package which allows consumers
to easily check if a block is solved according to the target difficulty specified by the bits in its header and updates `fullblocktests` to use it.

multi: Simplify invalid proof of work tests

---

blockchain/chain.go
blockmanager.go
mining.go
rpcserver.go
server.go

This replaces the `GetGeneration` function which allowed getting the entire generation (all children stemming from the same parent) of an arbitrary bock with `TipGeneration` which only returns the same information for the tip block.
This is being done because the function is only used for mining purposes to get the generation of the current tip.  The code is simplified by reducing its scope to its actual purpose as an initial benefit.  It also provides much better optimization opportunities later.

blockchain: Reduce GetGeneration to TipGeneration.

---

blockchain/blockindex.go
blockchain/chain.go
blockchain/chainio.go

This adds logic to keep track of all known chain tips.  Currently, this will only work with chain tips that have been seen since the daemon was loaded, however, when moving to the full block index in memory, it will end up tracking all chain tips in the block index.
Also, note that nothing makes use of the functionality as of this commit yet.  It will be useful in the future to allow things such as removal of the more expensive per-node children tracking, mining code improvements, and enhanced fork-related interrogation ability.

blockchain: Add chain tip tracking.

---

blockchain/chaingen/generator.go

This modifies the `CreatePremineBlock` in `chaingen` to accept mungers similar to `NextBlock`.

chaingen: Accept mungers for create premine block.

---

blockchain/blockindex.go
blockchain/chain.go
blockchain/chainio.go

This simplifies the recently added chain tip tracking by allowing the block index to handle it when a node is added to it.
This is possible since the block index does not support nodes that do not connect to an existing node (with the exception of the genesis block), and thus all new nodes are either extending an existing chain or are on a side chain, but in either case, are a new chain tip.  In the case the node is extending a chain, the parent is no longer a tip so it can be removed.

blockchain: Simplify chain tip tracking.

---

blockchain/chaingen/generator.go
blockchain/fullblocktests/generate.go
blockchain/validate_test.go

This PR moves the following block validation rule tests to
fullblocktests.
- `ErrBlockOneOutputs`
- Create a premine block with one premine output removed.
- Create a premine block with a bad spend script.
- Create a premine block with an incorrect pay to amount.
- `ErrVotesMismatch`
- Create block with a header that commits to more votes than the block
actually contains.
- `ErrIncongruentVotebit`
- Attempt to add block with incorrect votebits set.
- 4x Voters, 2x Nay 2x Yea, but block header says Yea
- 3x Voters, 2x Nay 1x Yea, but block header says Yea
- 3x Voters, 1x Nay 2x Yea, but block header says Nay
- `ErrSStxCommitment`
- Attempt to add block with a bad ticket purchase commitment.
- `ErrSSGenPayeeOuts`
- Attempt to add a block with a bad vote payee output.
- Attempt to add a …

blockchain: move block validation rule tests into fullblocktests (2/x).

---

blockchain/chain.go
blockchain/chainio.go

This modifies the startup logic to cache the tip and parent blocks in the main chain block cache at initialization time which is desirable because all of the transactions which come in to the mempool need access to the these blocks to construct their utxo views due to the potential for invalidation of the outputs in the previous block through voting.
Without caching them, the blocks end up being loaded from the database again every time a new transaction enters the mempool until the blocks eventually get cached when a new block is connected which is majorly inefficient.

blockchain: Cache tip and parent at init.

---

blockchain/chainquery.go
dcrjson/chainsvrresults.go
docs/json_rpc_api.md
rpcserver.go
rpcserverhelp.go

This implements the `getchaintips` JSON-RPC and updates the associated JSON-RPC API documentation accordingly.
It should be noted that until the entire block index is loaded into memory, the chain tips tracking currently only works with tips that have been seen since the daemon was started.

multi: Implement getchaintips JSON-RPC.

---

blockchain/chain.go
blockmanager.go
mining.go

This modifies the mining code to request the desired blocks from chain by hash as opposed to using a separate function to get the top block and removes the now unused plumbing through block manager.
Not only is this faster because it avoids the need to go through block manager, it is also more robust since it does not rely on the tip of the chain not having changing for correctness.
Finally, it removes the `blockchain.GetTopBlock` function since nothing else made use of it.

multi: Simplify and optimize mining tip block retrieval.

---

rpcserver.go
version.go

This adds the dcrd version info as an additional key to the JSON-RPC getversion response to accompany the existing RPC API version information and bumps the JSON-RPC minor version to account for the backwards-compatible change.
Also, it corrects the semver build handling. The semver spec allow the build portion to contain multiple identifiers separated by periods, however, the current code is stripping periods.

rpcserver: Add dcrd version info to getversion RPC.

---

README.md

- Capitalize Go.
- No text lines longer than 80 characters.

Adjust README.md for new Go version

---

docs/code_contribution_guidelines.md

Also some cleanups:
- Use proper punctuation.
- Use nicer link for Bitcoin white paper.
- Remove white spaces at the end of lines.
- Format paragraph.
Depends on PR #1106.

docs: document how to use go test -coverprofile

---

addrmgr/addrmanager.go
addrmgr/addrmanager_test.go
addrmgr/doc.go
addrmgr/network.go

Make sure the peers.json file is actually written and read in unit test.
Also some minor edits:
- Capitalize Tor.
- Capitalize JSON.
- Proper capitalization at the beginning of a sentence.
This PR increases the test coverage for the `addrmgr` package from 70.1% to 78.9%.

addrmgr: Improve test coverage.

---

rpcserverhelp.go

The `getblockheader` RPC with a `verbose` parameter of `false` returns the serialized header not its hash.

rpcserver: Correct getblockheader result text.

---

sampleconfig/sampleconfig.go
server.go
wire/protocol.go

This renames the `BIP0111Version` constant to `NodeBloomVersion` to better describe its purpose.
Closes #196.

multi: Rename BIP0111Version to NodeBloomVersion.

---

mining.go

This prevents the ability for duplicate transactions to be added to the mining priority heap when a transaction spends multiple outputs from the same input transaction by converting the dependency tracking to use a map keyed by the transaction hash instead of a linked list.
Work towards #709.

mining: Fix duplicate txns in the prio heap.

---

mining.go

**This requires PR #1108**.
This fixes a bug where a transaction would lose reference to other transactions dependent on it when being considered for inclusion in a new block template. The issue only occurs when the transaction being considered triggers a change of priority queue ordering to ordering by fee. It results in none of the dependent transactions being considered for inclusion in the new block template.
Work towards #709.

mining: Stop transactions losing their dependants.

---

mempool/mempool.go
mempool/policy.go
mining.go
mining/policy.go

This moves the priority-related code from the `mempool` package to the mining package and also exports a new constant named `UnminedHeight` which takes the place of the old unexported `mempoolHeight`.
Even though the mempool makes use of the priority code to make decisions about what it will accept, priority really has to do with mining since it influences which transactions will end up into a block.  This change also has the side effect of being a step towards enabling separation of the mining code into its own package which, as previously mentioned, needs access to the priority calculation code as well.
Finally, the `mempoolHeight` variable was poorly named since what it really represents is a transaction that has not been mined into a block yet.  Renaming the variable to more …

mining/mempool: Move priority code to mining pkg.

---

mempool/mempool.go

- [0e71867](https://github.com/btcsuite/btcd/commit/0e71867dfea2749357d3731381efd2c47b47a6a6)
---
This optimizes the way in which the mempool oprhan map is limited in the
same way the server block manager maps were previously optimized.
Previously the code would read a cryptographically random value large
enough to construct a hash, find the first entry larger than that value,
and evict it.
That approach is quite inefficient and could easily become a
bottleneck when processing transactions due to the need to read from a
source such as /dev/urandom and all of the subsequent hash comparisons.
Luckily, strong cryptographic randomness is not needed here. The primary
intent of limiting the maps is to control memory usage with a secondary
concern …

mempool: Optimize orphan map limiting.

---

cpuminer.go
mining.go
rpcwebsocket.go

This modifies all files in the main package so that function definitions are on the a single line as is the style used in the upstream code as well as throughout its code base.  This helps minimize the differences between them and the upstream code in order to facilitate easier syncs due to less merge conflicts as a result of superfluous changes.

main: Make func definition style consistent.

---

blockmanager.go
cpuminer.go
mining.go
rpcserver.go

**This requires PR #1114**.
The current code creates block templates with coinbase transactions that have 4 uint64 extra nonces, but only ever uses one of them.  Rather than wasting the extra space, this modifies the code so it only uses a single uint64 extra nonce.
It should be noted that realistically there isn't even a real need for an extra nonce in the coinbase at all because there is extra space in the header specifically for that purpose and miners can't modify the coinbase via `getwork` anyways.
However, it is still necessary to insert for the current code in order to ensure every block template has a unique merkle root since that is what is used to uniquely identify the block template.

mining: Use single uint64 coinbase extra nonce.

---

mempool/mempool.go
mining.go
mining/mining.go
server.go

**This requires PR #1118**.
This finishes separating the mining code from the `mempool` that was partially done in commit 9031d8574e857b5deefad4793ad5ba7eec6a72e3 by extending the `TxSource` interface to include the new functionality required by Decred.
The following is an overview of the changes to accomplish this:
- Move the `VoteTx` struct out of the `mempool` package in the mining package and rename it to `VoteDesc` instead to signify it is a vote descriptor and be consistent with the naming of `TxDesc`
- Update `mempool` to use the new `mining.VoteDesc` struct
- Rename `CheckIfTxsExist` to `HaveAllTransactions` to be more consistent with `HaveTransaction` in the `TxSource` interface as it now lives alongside it
- Add `VoteHashesForBlock`, `VotesForBlocks`, and `IsTxTreeKnownInvalid` …

mempool/mining: TxSource separation.

---

blockchain/difficulty.go
blockchain/difficulty_test.go

Currently, the stake difficulty estimation function for algorithm defined in [DCP0001](https://github.com/decred/dcps/blob/master/dcp-0001/dcp-0001.mediawiki) only works with `mainnet` due to a limitation of only working when the interval size is less than or equal to the ticket maturity.
This generalizes the function to work with all values of interval size and ticket maturity and adds a full suite of tests using the `testnet` parameters to ensure proper functionality.
Of particular note is the case when the current height is before the ticket maturity floor since that means some of the tickets being estimated will mature during the interval and that there can be no non-estimated immature tickets.
This also implies that, unlike when the ticket maturity is greater than or equal to the …

blockchain: Support testnet stake diff estimation.

---

blockchain/chaingen/generator.go

This adds infrastructure to track missed votes and automatically generate revocations for them along with a new assertion helper named `AssertTipNumRevocations` which, as it name suggests, allows the caller to
assert the header commits to the specified number of revocations.
This will be useful for porting the rest of the block validation tests to the `fullblocktests` framework.

chaingen: Add revocation generation infrastructure.

---

mining.go

This corrects the code to create a new template when first starting up with aggressive mining enable before votes on the most recent block are known.
First, the code is expecting the current best block, not its parent, and second, the coinbase script should match what is created in the normal path as well.

mining: Correct initial template generation.

---

addrmgr/addrmanager.go

Document internal structure of AddrManager.
Also use internal PRNG everywhere.

addrmgr: Improve documentation.

---

addrmgr/addrmanager.go

Overwriting the peers file immediately might lead to a situation where
the old file is lost and the new file could not be written completely.
Write to a temporary peers file instead and then move it into place with
os.Rename (which should be atomic).

addrmgr: Make writing of peers file safer.

---

version.go

This changes the `appPreRelease` definition from a constant to a variable so it can be set via the linker when creating release candidates.

main: Allow semver prerel via linker flags.

---

addrmgr/addrmanager.go
addrmgr/addrmanager_test.go
addrmgr/doc.go

Add unit test to ensure the removal of corrupt peers files.
Also fix some typos.
Increases test coverage from 78.4% to 79.5%.

addrmgr: Test removal of corrupt peers file.

---

addrmgr/addrmanager.go

Address a TODO in the code. The rest of the code is sufficiently
different to justify code duplication.

addrmgr: Factor out common code.

---

addrmgr/knownaddress.go

Caching the result of time.Now() increases performance by around 50%
in the happy case (measured for last return statement).

addrmgr: Improve isBad() performance.

---

chaincfg/params.go

This adds checkpoints for both the main and test networks as follows:
- Add mainnet checkpoint at height 214672.
- Add testnet checkpoint at height 249802.

chaincfg: Add checkpoints for upcoming release.

---

docs/README.md

dcrrpclient and dcrjson have been merged into dcrd.
Adjust links accordingly.

docs: Fix links for internal packages.

---

blockchain/utxoviewpoint.go

This modifies the connectTransactions`` function to only fetch the stake inputs once instead of for every stake transaction in the tree.

blockchain: Only fetch inputs once in connect txns.

---

blockchain/indexers/addrindex.go
blockchain/indexers/common.go
blockchain/indexers/existsaddrindex.go
blockchain/indexers/manager.go
blockchain/indexers/txindex.go
database/error.go

Indexes may now optionally provide their own implementation for
dropping the index, with a fallback to simply removing the index
bucket and metadata if not implemented.
Using an interface and dynamically dispatching to the correct drop
implementation also allowed removing a special case for deletion of
the transaction index from the common drop code.

indexers: Provide interface for index removal.

---

Gopkg.lock
dcrjson/walletsvrcmds.go
dcrjson/walletsvrcmds_test.go
dcrjson/walletsvrresults.go
rpcserver.go

Changes needed for [decred/dcrwallet#1037]
`dcrjson/walletsvrcmds.go`
`dcrjson/walletsvrcmds_test.go`
`dcrjson/walletsvrresults.go`
`rpcserver.go`

dcrjson: Add VerifySeedCmd.

---

txscript/script.go
txscript/script_test.go
txscript/sighash.go
txscript/sighash_test.go

This moves the logic to calculate the signature hash and the associated test to separate files.  Since there will ultimately be a new signature algorithm, it makes sense to separate all logic related to signature hashes for better code organization.
It contains no functional changes.

txscript: Move sig hash logic to separate file.

---

hdkeychain/example_test.go
hdkeychain/extendedkey.go
hdkeychain/extendedkey_test.go

This reverts changes to the `String` function on `ExtendedKey` to match the upstream code so that it satisfies the `fmt.Stringer` interface as intended.
For an additional bit of context, the condition was never intended to be an error to begin with because it's perfectly acceptable to work with zeroed keys and there is even a `Zero` function which serves precisely that purpose.

hdkeychain: Satisfy fmt.Stringer interface.

---

wire/msgtx.go
wire/msgtx_test.go

**This build on top of PR #1179**.
This removes the `TxSerializeWitnessSigning` serialization type since it is no longer required due to implementing it directly in the signature hash calculation function.  It also removes all related tests.
Although this is technically a change to the wire protocol, the protocol version is not being bumped because nothing ever sends messages using this serialization type as it only applied for calculating signature hashes and really should not have ever been in the wire package to begin with.

wire: Remove TxSerializeWitnessSigning.

---

rpcserver.go

This PR has the following upstream commits:
- [9799f0e](https://github.com/btcsuite/btcd/commit/9799f0e547c59ff7090bfd0a718ff345334adbb4)
- [6b8a249](https://github.com/btcsuite/btcd/commit/6b8a24918e53e3c928df3eef0fd06f1c94e7e1cd)
- NOOP
---
In order to avoid compatibility issues with software relying on 
Core's behavior, terminate HTTP POST JSON-RPC responses with a newline.

rpcserver: Improve JSON-RPC compatibility

---

addrmgr/addrmanager.go
addrmgr/addrmanager_test.go

Test for codepath that adds the same address twice and is supposed to update the timestamp.
Requires PR #1136.

addrmgr: Test timestamp update during AddAddress()

---

blockchain/chain_test.go
blockchain/error.go
blockchain/error_test.go
blockchain/validate.go
blockchain/validate_test.go
mining.go
rpcserver.go

~**This requires PRs #1076, #1077, #1084, and #1085**.~ (now merged)
This removes the `CheckConnectBlock` function in favor of a new function named `CheckConnectBlockTemplate` which more accurately reflects its purpose of testing block template proposals and uses this fact to be more restrictive about the allowed inputs and to avoid performing the proof of work check.
In particular, the provided block template must only build from the current tip or its parent or an error is returned.
All mining code has been updated to call the new function accordingly.
Finally, it also adds a full suite of tests for the new function using the `chaingen` framework in order to ensure proper functionality.

blockchain: CheckConnectBlockTemplate with tests.

---

cmd/dcrctl/config.go
cmd/gencerts/gencerts.go
config.go

This corrects an issue introduced by commit c6f9474348e8eb1488ae3d6cbcca461f0bb80c79 which resulted in empty paths that were cleaned and expanded being transformed into "." instead of having no effect as intended.

multi: Correct clean and expand path handling.

---

cmd/dcrctl/httpclient.go

dcrctl: Fix --skipverify failing if rpc.cert not found.

---

blockchain/accept.go
txscript/consensus.go
txscript/consensus_test.go
txscript/standard.go

Standardness rules are not the same as consensus rules and it is important to keep clear separation between them, because standardness rules can and do change, while the consensus rules must not change without a specific vote, and even then, the old rules must be kept around for validation of all blocks prior to any changes introduced by a successful vote.
Prior to this commit, the `blockchain` code which enforces the consensus rule that requires the second output of the coinbase transaction to contain the height of the block in a provably pruneable nulldata script push was relying on code in `txscript/standard.go`, which, as the name of the file suggests, is specifically intended for code related to standardness checks.
This introduces a new function in the `txscript` package named …

multi: Break coinbase dep on standardness rules.

---

blockchain/chaingen/generator.go
blockchain/fullblocktests/generate.go

Previously fullblocktests entries required in-depth knowledge of the stake tree in order to retrieve the prevailing ticket price. `ticketPrice := b.STransactions[5].TxOut[0].Value`. `CalcNextReqStakeDifficulty(b)` reduces this to a func call.

blockchain: utilize CalcNextReqStakeDifficulty in fullblocktests.

---

mempool/mempool_test.go

- [6035525](https://github.com/btcsuite/btcd/commit/60355258a79e9acfef7bb8436e7673f105c826f2)
---
This introduces a new pool membership test function to the mempool
testing infrastructure and refactors the tests to make use of it.
It is useful since it is common logic that is not only needed in the
existing tests, but will be needed by most mempool-related tests.

mempool: Refactor pool membership test logic.

---

blockchain/validate.go
mempool/mempool.go

The `CheckTransactionInputs` function, as it name suggested, is only intended to perform validation that requires the inputs to transactions.
Consequently, this moves the check for validating the transactions in the block are not expired into the `checkBlockContext` function where it more naturally belongs since it is only dependent on the block and its contextual position within the chain.
Since this check is also needed by the `mempool`, it refactors the check into separate functions named `IsExpired` and `IsExpiredTx`, which work with both `dcrutil` transactions and raw `wire` transactions, respectively, and updates `mempool` to perform the necessary check by making use of them.

blockchain: Validate tx expiry in block context.

---

mempool/mempool.go

This modifies the pruning code to make use of the newly available function in `blockchain` to test if a transaction is expired.
While here, it makes the comments on the functions more consistent with others and moves the unexported definition before the exported function from which it is used.

mempool: Use blockchain for tx expiry check.

---

txscript/engine.go

This removes the `ScriptStrictMultiSig` flag from the `txscript` package since it is not used or needed by Decred.
The flag is a holdover from the upstream code which was used to address a bug that does not exist in Decred.

txscript: Remove unused strict multisig flag.

---

docs/json_rpc_api.md

This modifies the example for connecting to the dcrd RPC server from node.js to work with node.js v8.11.1 LTS and v10.0.1 along with calling out the tested version and requirement for the additional `ecdhCurve`
parameter on v8.11.1 LTS.

docs: Update node.js example for v8.11.1 LTS.

---

hdkeychain/bench_test.go
hdkeychain/extendedkey.go
rpctest/memwallet.go

The `chainec` package is scheduled to be removed. This PR replaces `chainec` function calls within the `hdkeychain` package with the underlining `secp256k1` types and fields which breaks its dependence on a package soon to be removed. `memwallet`, a member of `rpctest` which calls `hdkeychain` functions is also updated.
This is work towards #1191

multi: use secp256k1 types and fields directly.

---

dcrec/edwards/privkey.go
dcrec/secp256k1/privkey.go

PubKey() returns the corresponding public key of the referenced private
key. This is preferred to Public() which returns the X and Y values
of the public key instead. Public() is scheduled to be removed after
the imposed chainec interface restrictions are removed.

dcrec: add Pubkey func to secp256k1 and edwards elliptic curves.

---

blockchain/compress.go

This PR replaces chainec function calls within the blockchain package with the underlining secp256k1 functions. This is in preparation for removing the chainec package.
This is work towards #1191

blockchain: use secp256k1 functions directly.

---

mempool/policy_test.go

This PR replaces chainec function calls within the mempool package
with the underlining secp256k1 functions. This is in preparation for
removing the chainec package.
This is work towards #1191

mempool: use secp256k1 functions directly.

---

Gopkg.lock
Gopkg.toml
addrmgr/log.go
blockchain/indexers/log.go
blockchain/internal/progresslog/blocklogger.go
blockchain/log.go
blockchain/stake/log.go
blocklogger.go
cmd/addblock/addblock.go
config.go
connmgr/log.go
database/cmd/dbtool/main.go
database/driver.go
database/ffldb/driver.go
database/log.go
go.mod
go.modverify
log.go
mempool/log.go
peer/doc.go
peer/log.go
rpcclient/log.go
txscript/log.go

This modifies all packages within the repository to the use the Decred fork of `btclog` which has been renamed to `slog` and updates the dependency files accordingly.

multi: Replace btclog with slog.

---

Gopkg.lock
Gopkg.toml
go.mod
go.modverify
rpcclient/infrastructure.go
rpcserver.go
rpcwebsocket.go

This change is being made since no local changes exist and dependencies are pinned unlike when it was originally vendored.

rpc: Use upstream gorilla/websocket.

---

Gopkg.lock
Gopkg.toml
go.mod
go.modverify

**This PR builds on #1218.**
Also, while here, constrain slog in Gopkg.toml to 1.0.0 and update the associated lock file accordingly.

build: Update some vgo dependencies to use tags.

---

dcrjson/dcrwalletextcmds.go

this is corresponding dcrd PR for task
https://github.com/decred/dcrwallet/issues/990
https://github.com/decred/dcrwallet/pull/1137

dcrjson: Implement xpub import from other wallet and use for address generation

---

chaincfg/chainhash/go.mod
chaincfg/chainhash/go.modverify

This adds module support for the versioned go toolchain to the `chainhash` package.
It does not update the travis build environment or README since it is
experimental at this point.

chainhash: Define vgo module.

---

wire/go.mod
wire/go.modverify

Now that `chainhash` has been defined, update the `wire` module to only depend on it instead of the entire `dcrd` module.

wire: Refine vgo deps.

---

addrmgr/go.mod
addrmgr/go.modverify

Now that `wire` has been defined, update the `addrmgr` module to only depend on it instead of the entire `dcrd` module.  Also, since there is no longer a dep on the entire `dcrd` module to pick it up transitively, add the `slog` dep as well.

addrmrg: Refine vgo deps.

---

chaincfg/go.mod
chaincfg/go.modverify

Now that `wire` has been defined, update the `chaincfg` module to only depend on it instead of the entire `dcrd` module.  The `chainhash` dependency is handled transitively via `wire`.

chaincfg: Refine vgo deps.

---

mempool/mempool.go
mempool/policy.go
mempool/policy_test.go
sampleconfig/sampleconfig.go

This lowers the default minimum relay fee to 0.0001 DCR/Kb from its previous value of 0.001 DCR/Kb and increases the high fee multiplier to keep the same default high fee threshold of 1 DCR/kB.
In order to keep the comments accurate, it also updates the comments in the `isDust` function and the sample config file to match the new default relay fee as it's nice to have the most recent values as a reference in the comments.
Finally, it updates the tests for the expected new values as a result of the reduced default relay fee and adds add a couple of dust tests just below and above the dust point for the new reduced default relay fee.
It should be noted that this is only a default node policy change and as such does not affect the consensus rules in any way.

policy: Lower default relay fee to 0.0001/kB.

---

dcrjson/dcrwalletextcmds.go
rpcclient/wallet.go

The SplitTx parameter for PurchaseTicketCmd specifies the minimum
number of inputs needed to use a split transaction for a ticket
purchase. The parameter options are 1 and 2. Ticket purchase inputs
less than the set SplitTx value are used directly in the transaction.

multi: Change NoSplitTransaction param to SplitTx.

---

rpcclient/wallet.go

This avoids a dcrjson marshaling bug referenced in [dcrrpcclient 89](https://github.com/decred/dcrrpcclient/pull/89) and [dcrwallet 963](https://github.com/decred/dcrwallet/pull/963).
Thanks to @chappjc for pointing it out.

rpcclient: pass default value for NewPurchaseTicketCmd's comment param.

---

blockchain/accept.go
blockchain/chain.go
blockchain/chain_test.go
blockchain/example_test.go
blockchain/fullblocks_test.go
blockchain/fullblocksstakeversion_test.go
blockchain/notifications.go
blockchain/process.go
blockchain/thresholdstate_test.go
blockchain/validate_test.go
blockmanager.go
cmd/addblock/import.go

This modifies the `ProcessBlock` function in the `blockchain` package to return the fork length for the connected block and updates all callers and tests accordingly.  Several of the internal functions which `ProcessBlock` calls are also updated in order to bubble the necessary information back up so it can be returned.  It does not make any behavioral changes.
This is being done to better expose information about the position of the block within the chain to callers without them having to make additional queries.

multi: Return fork len from ProcessBlock.

---

blockchain/accept.go
blockchain/notifications.go
blockmanager.go

This modifies the logic which sends winning ticket notifications to RPC clients to consider the reorganization depth and refuse to send the notifications for blocks on side chains that would ultimately result in a reorg of 6 or more blocks.
Also, the code used to send the notifications was needlessly repeated in multiple places since any blocks accepted via `ProcessBlock` also result in an accepted notification and therefore the RPC notification only
needs to be sent from there.

multi: No winning ticket ntfns for big reorg depth.

---

docs/json_rpc_api.md

The 'txaccepted' method is currently showing an out of date paramater within the json_rpc_api. The first parameter is currently set to 'TxSha', however it should be set to either 'TxID' or 'TxHash' as per https://github.com/decred/dcrd/blob/ed7c45a3e114a4d09976aa5e7ed195412660bbae/dcrjson/chainsvrwsntfns.go

docs: Update parameters for 'txaccepted' method in json_rpc_api.md.

---

dcrjson/dcrwalletextcmds.go
rpcclient/wallet.go

This renames the SplitTx field to TicketChange since it better describes
the feature being opted into. The field type was also changed to a bool
pointer.

multi: modify PurchaseTicketCmd.

---

blockchain/chain.go
blockchain/validate.go

This modifies the code to panic under unrecoverable conditions which will very likely lead to worse things happening such as writing incorrect information to the database versus return an assertion error.
We generally prefer to avoid using panics in packages since it largely takes control away from the caller (although they can use recover to catch them) and they are often misused as a substitute for proper error
handling.  However, the particular cases this changes really need to be panics because they apply to algorithmic invariants that if violated can lead to consensus failure, corrupted state, and other disastrous
outcomes.
Note that there are still some other cases in the package that return assert errors, but they either really should be returning a different error as they are not …

blockchain: Panic on fatal assertions.

---

blockchain/accept.go
blockchain/blockindex.go
blockchain/blockindex_test.go
blockchain/blocklocator.go
blockchain/chain.go
blockchain/chainio.go
blockchain/difficulty.go
blockchain/process.go
blockchain/sequencelock.go
blockchain/sequencelock_test.go
blockchain/stakeext.go
blockchain/stakenode.go
blockchain/stakeversion.go
blockchain/stakeversion_test.go
blockchain/thresholdstate.go
blockchain/utxoviewpoint.go
blockchain/validate.go

This reworks the block index code such that it loads all of the headers in the main chain at startup and constructs the full block index accordingly.
Since the full index from the current best tip all the way back to the genesis block is now guaranteed to be in memory, this also removes all code related to dynamically loading the nodes and updates some of the logic to take advantage of the fact traversing the block index can no longer potentially fail.  There are also many more optimizations and simplifications that can be made in the future as a result of this.
Due to removing all of the extra overhead of tracking the dynamic state, and ensuring the block node structs are aligned to eliminate extra padding, the end result of a fully populated block index now takes quite a bit less memory …

blockchain: Convert to full block index in mem.

---

blockchain/chain.go
blockchain/checkpoints.go
blockchain/process.go
blockchain/validate.go

**This requires PR #1229**.
This modifies the code that determines the most recently known checkpoint to take advantage of recent changes which make the entire block index available in memory by only storing a reference to the specific node in the index that represents the latest known checkpoint.
Previously, the entire block was stored and new checkpoints required loading it from the database.

blockchain: Optimize checkpoint handling.

---

blockchain/blocklocator.go

**This requires PRs #1229 and #1230.**
This significantly optimizes and simplifies the generation of block locators by making use of the fact that all block nodes are now in memory and therefore it is no longer necessary to consult the database for the hashes or worry about issues related to dynamic loading of nodes.
Also, it slightly modifies the algorithm so that the doubling doesn't start for one additional iteration in order to mirror the upstream code.  Due to the way block locators are used, this does not change any semantics in terms of requesting and locating blocks.
Finally, the semantics of `BlockLocatorFromHash` have been changed to return a locator for the current tip in the case the hash is unknown.  This is preferable since only including the passed block hash, when it isn't …

blockchain: Optimize block locator generation.

---

blockchain/chain.go
blockchain/chain_test.go
blockchain/chainio.go
blockchain/common_test.go
rpcserver.go
server.go

**This requires PRs #1229, #1230, and #1237.**
This refactors the code that locates blocks (inventory discovery) out of `server` and into `blockchain` where it can make use of the fact that all block nodes are now in memory and more easily be tested.  As an aside, it really belongs in blockchain anyways since it's purely dealing with the block index and best chain.
In order to do this reasonably efficiently, a new memory-only height to block node mapping for the main chain is introduced to allow efficient forward traversal of the main chain.  This is ultimately intended to be replaced by a chain view.
Since the network will be moving to header-based semantics, this also provides an additional optimization to allow headers to be located directly versus needing to first discover the hashes …

multi: Refactor and optimize inv discovery.

---

blockchain/chainio_test.go
blockchain/validate_test.go

This cleans up and corrects the spend journal tests which deal with a live blockchain.
First, it updates the params used in the test to the legacy values so the blocks actually connect to the main chain instead of being added as orphans.
Second, it checks the return value from `ProcessBlock` for whether or not the block is on the main chain and fails if it is not to ensure it actually is on the main chain.
Finally, it moves the core logic which checks the number of spend outputs matches the serialized spend journal directly into the test instead of calling a separate `DoStxoTest` function on the `blockchain` instance for that purpose and removes that now unused function.

blockchain: Improve spend journal tests.

---

peer/peer.go
peer/peer_test.go

**This relies on PR #1247**.
This removes an impossible to hit duplicate version check and adds a test to ensure the behavior is correct.
Previously, the check was necessary because the handler was a part of the input handler loop, however, the initial negotiation logic was refactored some time ago to be synchronous and thus it is no longer possible to receive a second version message in the refactored code path.

peer: Remove superfluous dup version check.

---

addrmgr/addrmanager.go

This modifies the `savePeers` function in the `addrmgr` package to lock the mutex before checking if saving is needed because the flag is accessed from multiple goroutines.

addrmgr: Fix race in save peers.

---

peer/peer.go
server.go

**This requires PR #1248**.
This modifies the negotiation logic to ensure the callback has the opportunity to see the message before the peer is disconnected and improves the error handling when reading the remote version message.
It also has the side effect of ensuring the protocol version is negotiated before sending reject messages with the exception of the first message not being a version message since negotiation is not possible in that case.
This is being changed because it is useful for the server to see the message regardless in order to have the opportunity to things such as update the address manager and reject peers that don't have desired services.

peer: Rework version negotiation.

---

peer/example_test.go
peer/peer.go
peer/peer_test.go
server.go

**This requires PR #1250.**
This modifies the `OnVersion` callback to allow a reject message to be returned in which case the message will be sent to the peer and the peer will be disconnected.

peer: Allow OnVersion callback to reject peer.

---

server.go

**This requires PR #1251.**
This modifies the server connection code to reject outbound peers that do not offer full node services.

server: Reject outbound conns to non-full nodes.

---

peer/peer.go

**This requires PR #1250 and is currently rebased on top of #1252.**
This modifies the peer code which deals with advertising service flags via the net address fields of the version message as follows:
- For outgoing connections:
- Set the local netaddress services to what the local peer supports
- Set the remote netaddress services to 0 to indicate no services as they are still unknown
- For incoming connections:
- Set the local netaddress services to what the local peer supports
- Set the remote netaddress services to the what was advertised by the remote peer in its version message

peer: Improve net address service adverts.

---

addrmgr/addrmanager.go
server.go

Date:   Sun Jun 3 03:29:22 2018 -0500
This consists of two commits.
The first commit exposes a new method named `SetServices` to the address manager which can be used to update the services for a known address.
The second updates server to add code which updates the address manager services for a known     address to the services advertised by peers when they are connected to via an outbound connection.  It is only done for outbound connections to help prevent malicious behavior from inbound connections.

multi: Update addrmgr services on outbound conns.

---

server.go

**This requires PR #1254**.
This modifies the `OnVersion` handler for server peers to use a local variable for the inbound status of the peer in order to avoid grabbing the mutex multiple times.
While here, it also does some light cleanup.  There are no functional changes.

server: Use local inbound var in version handler.

---

server.go

**This requires PR #1255**.
This changes the server peers `OnVersion` handler to only advertise the server as a viable target for inbound connections when the server believes it is close the best known tip.

server: Only advertise local addr when current.

---

server.go

**This requires #1256**.
This modifies the `OnVersion` handler for server peers to use a local variable for the remote address of the peer in order to avoid grabbing the mutex multiple times.
There are no functional changes.

server: Use local addr var in version handler.

---

Dockerfile-1.10
Dockerfile-1.9

- github.com/decred/dcrctl and github.com/decred/dcrrpcclient
do not exist anymore.
- glide isn't used anymore.

travis: simplify Docker files

---

txscript/data/script_invalid.json
txscript/data/script_valid.json
txscript/opcode.go

This cleans up the code for handling the left opcode to explicitly call out its semantics which are likely not otherwise obvious as well as improve its readability.
It also adds several tests to the reference script tests which exercise the semantics of the left opcode including both positive and negative tests.

txscript: Cleanup and add tests for left opcode.

---

txscript/data/script_invalid.json
txscript/data/script_valid.json
txscript/opcode.go

**This is rebased on top of #1281.**
This cleans up the code for handling the right opcode to explicitly call out its semantics which are likely not otherwise obvious as well as improve its readability.
It also adds several tests to the reference script tests which exercise the semantics of the right opcode including both positive and negative tests.

txscript: Cleanup and add tests for right opcode.

---

txscript/data/script_invalid.json
txscript/data/script_valid.json
txscript/opcode.go

**This is rebased on top of #1282**.
This cleans up the code for handling the cat opcode to more closely match the style used by the rest of the code and improves its test coverage by adding several tests to the reference script tests which exercise its semantics including both positive and negative tests.

txscript: Cleanup and add tests for the cat opcode.

---

blockchain/stake/tickets.go
blockchain/stake/tickets_test.go

`MissedByBlock` includes both missed (a winner with no vote) and expired. It also includes revocations of either miss or expire.
`ExpiredByBlock` gives only tickets that expired, and only the actual expiry, not the revocation of an expired ticket.

stake: add ExpiredByBlock

---

server.go

This moves the function definition for `enforceNodeCFFlag` so it are more consistent with the preferred order used throughout the codebase.  In particular, the functions are defined before they're first used and
generally as close as possible to the first use when they're defined in the same file.
While moving, it also reformats the code to match the same spacing as the other CF functions for consistency.
There are no functional changes.

server: Minor function definition order cleanup.

---

dcrjson/walletsvrcmds.go
rpcclient/wallet.go

This reverts the split_tx/ticket_change addition to PurchaseTickeCmd. From a discussion had with raedah and jrick on purchasing tickets we concluded that change created by direct ticket purchases will adhere to coinbase maturity before becoming available for spending. We will not be circumventing this by not setting the expiry for sstxchange.
The only ideal scenario currently for purchasing tickets directly is with inputs equal to the stake difficulty plus the fee.

multi: revert TicketChange addition to PurchaseTicketCmd

---

blockchain/blockindex_test.go
blockchain/chain.go
rpcserver.go

This optimizes the `FetchHeader` function to make use of the fact that all block nodes are now in memory and therefore it is no longer necessary to consult the database for them.
It also renames the function to `HeaderByHash` so it is consistent with other similar functions such as `HeaderByHeight`, `BlockByHash`, and `BlockByHeight` and updates all callers in the repo accordingly.
This speeds up fetching all of the headers in the chain by roughly 3x to 4x for a chain height of 246,000 headers.  Longer chains will benefit more.
For example, here is some timing information before and after this commit plus the full block index in memory commit for 246,000 headers:
7200 RPM HDD:
-------------
Previous fetch time: ~15.76s
New fetch time: ~4.17s
SSD:
----
Previous fetch time: ~12.63s
New …

blockchain: Optimize exported header access.

---

server.go

This reverts a change made in 4f6ed9afdbf4eed86055a5122780f405b48010d2
which resulted in a headers response to not be created for a
getheaders request if there were no more discovered headers.  This was
a deviation from the previous behavior of queueing a headers message
with an empty vector of headers.
This was a protocol change without a protocol bump, so the behavior
must be reverted.
I also cross referenced the Bitcoin Core source code and, just like
the now-restored behavior, headers messages were always sent even when
no new headers were discovered.  I don't see any reason why Decred
should deviate from this behavior.

server: Always reply to getheaders with headers

---

txscript/data/script_invalid.json
txscript/data/script_valid.json
txscript/opcode.go

This cleans up the code for handling the div opcode to explicitly call out its semantics which are likely not otherwise obvious as well as improve its readability.
It also adds several tests to the reference script tests which exercise the semantics of the div opcode including both positive and negative tests.

txscript: Cleanup and add tests for div opcode.

---

txscript/data/script_invalid.json
txscript/data/script_valid.json
txscript/opcode.go

This cleans up the code for handling the mod opcode to explicitly call out its semantics which are likely not otherwise obvious as well as improve its readability.
It also adds several tests to the reference script tests which exercise the semantics of the div opcode including both positive and negative tests.

txscript: Cleanup and add tests for mod opcode.

---

rpcclient/infrastructure.go
rpcclient/infrastructure_test.go

This implements fmt.Stringer by returning the URL of the RPC server
that the client makes requests to.
Since the client config is not exported by Client, this is now the
only way to return the scheme, host, and endpoint the server.

rpcclient: Implement fmt.Stringer for Client

---

networkparams_test.go

Network PoW limit has two different representations of the same difficulty value. See example at the `chaincfg/mainnetparams.go`:
```
PowLimit:         mainPowLimit,// big int
PowLimitBits:     0x1d00ffff,  //conceptually the same
//value, but in an obscure form
```
This test ensures they properly match.
Genesis block difficulty should be within the network PoW limit. See `chaincfg/genesis.go`:
```
var genesisBlock = wire.MsgBlock{
Header: wire.BlockHeader{
...
Bits:         0x1b01ffff, // Is this a valid value?
...
},
}
```

main: verify network pow limits

---

blockchain/validate_test.go
rpcserver.go
rpctest/memwallet.go
txscript/example_test.go
txscript/reference_test.go
txscript/sign_test.go
wire/msgtx.go
wire/msgtx_test.go

This adds the valueIn parameter to wire.NewTxIn. Call sites and associated tests have also been updated.
Resolves #1279

multi: add valueIn parameter to wire.NewTxIn.

---

txscript/sighash.go
txscript/sign_test.go

**This is currently rebase on #1308**.
This removes the `SigHashOld` definition from the `txscript` package since it both has never been used in Decred and it has also always been invalid to use due to the fact that strict encoding has always been
active and required by consensus in Decred.

txscript: Remove unused old sig hash type.

---

addrmgr/addrmanager.go
addrmgr/knownaddress.go
server.go

A node that has never been successfully connected should not be
announced.

addrmgr: skip never-successful addresses

---

txscript/script.go
txscript/standard.go

This slightly cleans up the handling for pay-to-script-hash scripts and related stake opcode checking as follows:
- Move the `isScriptHash` and `isAnyKindOfScriptHash` functions to `script.go` since they are required by consensus and therefore do not belong in `standard.go` which is reserved for standardness only rules
- Introduce a new function named `isStakeOpcode` and use it throughout versus repeating the specific logic in multiple places
- Use the stake opcode constants instead of magic numbers in the aforementioned new function
- Introduce a new function named `isStakeScriptHash` which specifically determines if a script is of the special stake p2sh form
- Update `isAnyKindOfScriptHash` to make use of the original `isScriptHash` function instead of repeating the logic and the newly …

txscript: Cleanup P2SH and stake opcode handling.

---

txscript/consensus.go
txscript/data/script_valid.json
txscript/doc.go
txscript/engine.go
txscript/engine_test.go
txscript/error.go
txscript/error_test.go
txscript/opcode.go
txscript/opcode_test.go
txscript/reference_test.go
txscript/script.go
txscript/script_test.go
txscript/scriptbuilder.go
txscript/scriptbuilder_test.go
txscript/scriptnum.go
txscript/scriptnum_test.go
txscript/sighash.go
txscript/stack.go
txscript/stack_test.go
txscript/standard.go
txscript/standard_test.go

**This requires PRs #1315 and #1318**.
This converts the majority of script errors from generic errors created via `errors.New` and `fmt.Errorf` to use a concrete type that implements the error interface with an error code and description.
This allows callers to programmatically detect the type of error via type assertions and an error code while still allowing the errors to provide more context.
For example, instead of just having an error the reads "disabled opcode" as would happen prior to these changes when a disabled opcode is encountered, the error will now read "attempt to execute disabled opcode OP_FOO".
While it was previously possible to programmatically detect many errors due to them being exported, they provided no additional context and there were also various instances that …

txscript: Significantly improve errors.

---

blockchain/agendas_test.go
blockchain/validate.go
mempool/policy.go
txscript/data/script_tests.json
txscript/engine.go
txscript/engine_test.go
txscript/error.go
txscript/error_test.go
txscript/example_test.go
txscript/opcode_test.go
txscript/reference_test.go
txscript/sign_test.go

**This requires PR #1320**.
This removes the `ScriptBip16` flag from the `txscript` package, changes the default semantics to always enforce its behavior, and updates all callers in the repository accordingly.
This change is being made to simplify the script engine code since the flag has always been active and required by consensus in Decred, so there is no need to require a flag to conditionally toggle it.
Also, since it is no longer possible to invoke the script engine without the flag with the clean stack flag, it removes the now unused `ErrInvalidFlags` error and associated tests.
It should be noted that the test removed from `script_tests.json` specifically dealt with ensuring a signature script that contained non-data-pushing opcodes was successful when neither the `ScriptBip16` or …

txscript: Remove pay-to-script-hash flag.

---

blockchain/agendas_test.go
blockchain/validate.go
mempool/policy.go
txscript/data/script_tests.json
txscript/engine.go
txscript/engine_test.go
txscript/example_test.go
txscript/opcode_test.go
txscript/reference_test.go
txscript/sign_test.go

**This is rebased on PR #1322**.
This removes the `ScriptVerifyDERSignatures` flag from the `txscript` package, changes the default semantics to always enforce its behavior and updates all callers in the repository accordingly.
This change is being made to simplify the script engine code since the flag has always been active and required by consensus in Decred, so there is no need to require a flag to conditionally toggle it.
It should be noted that the tests removed from `script_tests.json` specifically dealt with ensuring non-DER-compliant signatures were handled properly when the `ScriptVerifyDERSignatures` flag was not set.  Therefore, they are no longer necessary.
Finally, the `DERSIG` indicator to enable the flag in the test data has been retained for now in order to keep the logic …

txscript: Remove DER signature verification flag.

---

txscript/data/script_tests.json
txscript/reference_test.go

**This requires PR #1323**.
This removes the `DERSIG` script verify flag from the various reference test data since it is now a noop due to the corresponding flag being removed from the script engine.

txscript: Remove DERSIG flag from test data.

---

txscript/opcode.go
txscript/scriptnum.go
txscript/scriptnum_test.go
txscript/stack.go
txscript/standard.go

**This requires #1326 and is rebased on #1327**.
This removes the flag to require minimal encoding when create script numbers since since all callers now call the function with true due to the recent removal of the minimal data script verification flag from the script engine and updates the tests accordingly.

txscript: Remove script num require minimal flag.

---

txscript/opcode.go
txscript/stack.go
txscript/stack_test.go

**This requires PR #1328**.
This modifies the `PeekInt` function of the stack to accept a maximum script number length to mirror `PopInt` for consistency.  It also updates the two callers `CLTV` and `CSV`) which were manually performing the same task with 5 bytes due to `PeekInt` enforcing 4-byte script nums to use the modified version accordingly.
It also adds some stack tests for 5-byte encodings on both `PopInt` and `PeekInt`.

txscript: Make PeekInt consistent with PopInt.

---

blockchain/chain.go
blockchain/chainio.go
mining.go
rpcserver.go
server.go

This modifies the `BlockByHash` function to return blocks regardless of whether or not the block is on a side chain and removes the `FetchBlockByHash` function since this change makes it redundant.
This is being changed to simplify the API and because there are no current cases where calls into chain to retrieve a block need to be limited to the main chain and if the need should ever arise, the caller can simply make use of the `MainChainHasBlock` function to verify.

blockchain: Combine block by hash functions.

---

dcrjson/walletsvrresults.go

This change makes the following fields omitempty so they can be
ignored by SPV wallets:
* poolsize
* allmempooltix
* live
* proportionlive
* missed
* proportionmissed
* expired
As a side-effect, non-SPV wallets will also omit these fields from the
result if the value is zero.
The following counts remain:
* ownmempooltix
* immature
* voted
* revoked
And two new fields have been added to allow SPV wallets to provide a
fuller picture of the wallet's ticket state counts:
* unspent
* unspentexpired
The `unspent` field describes the number of tickets that have gone
live and have not been spent by a vote or revocation.  The
`unspentexpired` field describes the number of unspent tickets that
must certainly be revoked as they have not been spent by a vote and
have passed the expiry period.  These …

dcrjson: Ready GetStakeInfoResult for SPV wallets.

---

blockchain/fullblocktests/params.go
chaincfg/mainnetparams.go
chaincfg/params.go
chaincfg/simnetparams.go
chaincfg/testnetparams.go

Use the coin type numbers defined in SLIP0044:
https://github.com/satoshilabs/slips/blob/master/slip-0044.md
They are not going to change and dcrwallet already uses them.

multi: Switch default coin types to SLIP0044.

---

chaincfg/chainec/secp256k1.go
dcrec/secp256k1/example_test.go
dcrec/secp256k1/signature.go
dcrec/secp256k1/signature_test.go
txscript/opcode.go
txscript/sigcache_test.go

**This requires PR #1304**.
This removes the unused curve parameter from the `ParseSignature` and `ParseDERSignature` functions of the `secp256k1` package and updates all callers in the repository accordingly.

multi: Remove unused secp256k1 sig parse parameter.

---

blockmanager.go
rpcserver.go
server.go

multi: add specialized rebroadcast handling for stake txs.

---

blockchain/accept.go
blockchain/chain.go
blockchain/chainio.go
blockchain/chainquery.go
blockchain/checkpoints.go
blockchain/indexers/manager.go
blockchain/stakenode.go
blockchain/upgrade.go
blockchain/utxoviewpoint.go
blockchain/validate.go
blockchain/validate_test.go
rpcserver.go

This refactors the code that relies on the database main chain index to use the in-memory block index now that the full index is in memory.
This is a major optimization for several functions because they no longer have to first consult the database (which is incredibly slow in many cases due to the way `leveldb` splits all of the information across files) to perform lookups and determine if blocks are in the main chain.
It should also be noted that even though the main chain index is no longer used as of this commit, the code which writes the main chain index entries to the database in `connectBlock`, `disconnectBlock`, and
`createChainState` have not been removed because, once that is done, it will no longer be possible to downgrade and thus those changes must be performed along with a …

blockchain: Refactor db main chain idx to blk idx.

---

blockchain/chain.go
blockchain/chainio.go
blockchain/internal/dbnamespace/dbnamespace.go
blockchain/upgrade.go

**This PR requires #1332**.
This removes the main chain index from the database as well as all code related to reading and writing it (other than those in the upgrade paths) since it is no longer used and bumps the database version since it is not possible to downgrade after the main chain index has been removed.
---
As of this PR, the expected behavior is that there is a single migration that takes a couple of seconds to complete after which it will no longer be possible to downgrade.
As the warning above notes, if you try to run an older software version after this migration has completed, you will get an error message similar to `Unable to start server on [:9108]: the current blockchain database is no longer compatible with this version of the software (4 > 3).`
---
This is work …

blockchain: Remove main chain index from db.

---

blockchain/blockindex_test.go
blockchain/chainview.go
blockchain/chainview_test.go
blockchain/common_test.go

**This PR is rebased on #1334**.
This implements a new type in the blockchain package that takes advantage of the fact that all block nodes are now in memory to provide a flat view of a specific chain of blocks (a specific branch of the overall block tree) from a given tip all the way back to the genesis block along with several convenience functions such as efficiently comparing two views, quickly finding the fork point (if any) between two views, and O(1) lookup of the node at a specific height.
The view is not currently used, but the intent is that the code will be refactored to make use of these views to simplify and optimize several areas such as best chain selection and reorg logic and finding successor nodes.  They will also greatly simplify the process of disconnecting the …

blockchain: Implement new chain view.

---

chaincfg/chainhash/hashfuncs.go
chaincfg/chainhash/hashfuncs_test.go

Removed some duplicate code by having HashH use HashB rather than duplicating its functionality.

chainhash: Remove dup code from hash funcs.

---

blockchain/chainview.go
blockchain/chainview_test.go

**This requires PR #1337**.
This exposes the ability to more efficiently create a block locator from a chain view for a given block node by using their ability to do O(1) lookups.
It also adds tests to ensure the behavior is correct.

blockchain: Faster chain view block locator.

---

chaincfg/chainhash/go.modverify
chaincfg/chainhash/go.sum

This updates the `chainhash` build module for the changes in the upcoming go1.11 release.

chainhash: Update go build module support.

---

wire/go.mod
wire/go.modverify
wire/go.sum

This updates the `wire` build module for the changes in the upcoming go1.11 release and to depend on the latest `chainhash` module version.

wire: Update go build module support.

---

addrmgr/go.mod
addrmgr/go.modverify
addrmgr/go.sum

This updates the `addrmgr` build module for the changes in the upcoming go1.11 release and to depend on the latest `chainhash` and `wire` module versions.

addrmgr: Update go build module support.

---

chaincfg/go.mod
chaincfg/go.modverify
chaincfg/go.sum

This updates the `chaincfg` build module for the changes in the upcoming go1.11 release and to depend on the latest `chainhash` and `wire` module versions.

chaincfg: Update go build module support.

---

dcrec/secp256k1/go.mod
dcrec/secp256k1/go.sum

Now that the `chainhash` module has been defined, update the `secp256k1` module to only depend on it instead of the entire `dcrd` module.

secp256k1: Refine go build module support.

---

blockchain/validate.go

This modifies the `checkConnectBlock` function to remove the check which tests if the block is the genesis block and returns an error since it is no longer necessary due to other changes in the code since the function was originally written.
In particular, the genesis block is valid by definition as the root of the chain, so it does not make sense to try to connect it to a chain that doesn't exist yet.

blockchain: Remove unnecessary genesis block check.

---

blockchain/chainview_test.go
blockmanager.go
mempool/mempool.go
mempool/mempool_test.go

This modifies the `mempool` to handle pruning of expired transactions in a self-contained way so that the caller is not responsible for worrying about the specific semantics of height and expiration interplay and updates all callers in the repository accordingly.
It also adds a test which ensures the behavior is correct by creating a series of transactions with expirations, adding them just before the point at which they will expire, and then advancing the chain so that each transaction expires and thus should be pruned.

mempool: Make expiry pruning self contained.

---

blockchain/chain.go
blockchain/chain_test.go
blockchain/error.go
blockchain/error_test.go

This optimizes the chain reorganization logic by making use of the block index status flags for known valid and invalid blocks.
In particular, validation is now skipped for blocks that are either already known valid or invalid.  When validating blocks, the result is stored into the block index for the block accordingly, and in the case of blocks that fail validation, all of the descendants of the invalid block are marked as having an invalid ancestor.
It also introduces a new error named `ErrKnownInvalidBlock` which is returned in the case a forced reorg is attempted to an invalid block and adds a test to ensure it works as intended.

blockchain: Optimize reorg to use known status.

---

blockchain/accept.go
blockchain/blockindex.go
blockchain/chain.go
blockchain/stakenode.go
blockchain/validate.go

**This PR depends on #1367.**
This modifies the block index to support tracking modified nodes and flushing them to the database.  This ensures that validation states set on arbitrary nodes are persisted to the database and helps pave the way towards supporting decoupling the chain processing logic from the download logic.
In the immediate term, as of this commit, side chains which encounter an invalid block will no longer potentially have to be revalidated to discover they are invalid after restart.
A few comments are also improved while here.

blockchain: Make block index flushable.

---

dcrjson/walletsvrcmds.go
dcrjson/walletsvrresults.go
rpcclient/wallet.go
rpcserver.go

related to https://github.com/decred/dcrwallet/pull/1195

dcrjson: add fundrawtransaction command

---

addrmgr/go.mod
blockchain/go.mod
blockchain/go.sum
blockchain/stake/go.mod
blockchain/stake/go.sum
chaincfg/go.mod
connmgr/go.mod
database/go.mod
database/go.sum
dcrutil/go.mod
gcs/go.mod
gcs/go.sum
go.mod
go.sum
hdkeychain/go.mod
mempool/go.mod
mempool/go.sum
mining/go.mod
mining/go.sum
peer/go.mod
peer/go.sum
rpcclient/go.mod
rpcclient/go.sum
txscript/go.mod

This bumps the various module versions as follows:
- github.com/decred/dcrd/addrmgr@v1.0.2
- github.com/decred/dcrd/wire@v1.1.0
- github.com/decred/dcrd/chaincfg@v1.1.1
- github.com/decred/dcrd/connmgr@v1.0.1
- github.com/decred/dcrd/dcrutil@v1.1.1
- github.com/decred/dcrd/database@v1.0.1
- github.com/decred/dcrd/hdkeychain@v1.1.0
- github.com/decred/dcrd/txscript@v1.0.1
- github.com/decred/dcrd/blockchain/stake@v1.0.1
- github.com/decred/dcrd/gcs@v1.0.1
- github.com/decred/dcrd/blockchain@v1.0.1
- github.com/decred/dcrd/mining@v1.0.1
- github.com/decred/dcrd/mempool@v1.0.1
- github.com/decred/dcrd/peer@v1.0.1
- github.com/decred/dcrd/rpcclient@v1.0.1
It also updates all of the dependencies for every module accordingly and adds a few missing overrides for transitive dependencies.

release: Bump module versions and deps.

---

blockchain/common_test.go
blockchain/stake/internal/ticketdb/chainio_test.go
blockchain/stake/tickets_test.go

This modifies the various tests that create temporary databases to make use of `ioutil.TempDir` instead of a relative directory path.  This allows the tests to be run from any path without failure.

multi: Use temp directories for database tests.

---

blockchain/chain_test.go
blockchain/fullblocks_test.go
blockchain/validate_test.go

This modifies the `fullblocktests` that create a temporary database to make use of `ioutil.TempDir` instead of a relative directory path.  This allows the tests to be run from any path without failure.

blockchain: Use temp dirs for fullblocks test.

---

database/ffldb/interface_test.go

This updates the interface tests in `database/ffldb`to reference the block tests within the same module as opposed to escaping the module to find it in the blockchain module.
This should have been a part of the previous commit that performs the same, but was missed.

database: Use module-scoped data in iface tests.

---

peer/peer.go
server.go

This adds a new parameter named `UserAgentComments` to the peer `Config` struct so that callers may specify additional comments to add to the user agent string.
It also updates the server to include the prelease portion of the semantic version as a comment when creating peers.

peer: Add support for specifying ua comments.

---

cmd/dcrctl/version.go
go.mod
version.go

This marks the start of a new release process as compared to previous releases.
Instead of bumping the version just before a release and releasing from the master branch, as has been done up to this point, the minor (or major when necessary) will now be bumped on the master branch at the beginning of a release cycle.  In addition, the pre-release portion of the semantic version is now the string "pre" to help make it more obvious that the master branch represents a pre-release build of work leading up to the next release.
When a new release is prepared, a new release branch will be created that has a naming scheme of "release-vX.Y", where X is the major and Y is the minor.  Any additional commits needed to prepare the release leading up to a release candidate will be cherry-picked to the …

release: Bump for 1.4 release cycle.

---

blockchain/chain.go
blockchain/chainio.go

This adds `PrevHash, NextPoolSize, NextStakeDiff, NextWinningTickets, MissedTickets and NextFinalState` fields to `BestState`.
Port of upstream commit c57c18c. In preparation of the removal of `chainState`.

blockchain: update BestState.

---

mempool/mempool.go

This improves trace logs related to transaction removal from the
mempool. During some debugging, they were found to be slightly
misleading in their current form.

mempool: tweak trace logs

---

blockmanager.go

Current code results in transactions from invalidated blocks being
removed from the mempool instead of remaining there to be mined in a
future block.
The new version ensures that transactions are *only* removed once they
are in a block voted as valid.
This only applies to regular transactions, since stake transactions are
not affected by the validity bits.
Original fix provided by @davecgh

blockmanager: handle txs in invalid blocks

---

dcrec/edwards/ciphering.go
dcrec/edwards/ciphering_test.go
dcrec/edwards/curve.go
dcrec/edwards/ecdsa.go
dcrec/edwards/primitives.go
dcrec/edwards/privkey.go
dcrec/edwards/pubkey.go
dcrec/edwards/signature.go
dcrec/edwards/threshold.go

This makes the style of the function definitions in the `dcrcec/edwards` package more consistent with the code throughout the rest of the code base.
Also, move the nil check for pubkey parsing to the top of the function before any more work is done.

dcrec: Make function defs more consistent.

---

blockchain/chain.go

This corrects the `NextPoolSize` field that was recently added to the best state when a block is disconnected to calculate the next pool size relative to the previous block since it will become the new best state.

blockchain: Correct best pool size on disconnect.

---

peer/peer.go

peer: Protect handlePongMsg with p.statsMtx

---

blockchain/indexers/existsaddrindex.go

This removes the implementation of the `NeedsInputser` interface on the exists address index since not implementing the interface is the same as implementing it and returning false.
This is desirable because not only is it less code, it is consistent with the transaction index.

indexers: Remove unneeded existsaddrindex iface.

---

blockchain/indexers/existsaddrindex.go

This modifies the functions in the exists address index to use the `internalBucket` interface instead of directly taking a `database.Bucket` interface.  This allows tests to mock the data the source and is consistent with the address index.

indexers: Use testable bucket for existsaddrindex.

---

blockchain/blockindex.go
blockchain/chain.go
blockchain/common_test.go
blockchain/stakeversion.go
blockchain/thresholdstate.go

This modifies the code in `blockchain` to make less assumptions about the availability of the block data by checking the status flags to determine whether or not it is available.
While currently there aren't actually ever any nodes in the block index that don't have the full block data available, that will not always be true in the future.

blockchain: Reduce block availability assumptions.

---

rpcserver.go

This modifies the `createrawsstx` handler to accept pay-to-script-hash addresses for the voting address since they are also valid.

rpcserver: Allow scripthash addrs in createrawsstx.

---

blockchain/accept.go
blockchain/notifications.go
blockmanager.go
go.mod
peer/peer.go
server.go

This PR consists of several commits which ultimately immediately relays blocks that intend to extend the main chain to the rest of the network directly after they have passed all sanity and contextual checks rather than waiting for the more expensive connection code to complete.
This is acceptable because blocks that pass all of the aforementioned checks and then fail to connect are quite rare since it takes a significant amount of work to create a block which satisfies the proof of work requirement as well as all other checks up to that point.
The first commit adds a new function to `peer` named `QueueInventoryImmediate` which allows an inventory vector to be queued for immediate send versus the standard trickling batched inventory queue method while still respecting the functionality …

multi: Fast relay checked tip blocks.

---

txscript/data/script_tests.json

This also moves some dangling tests to their respective opcode groupings.
Work towards #1331.

txscript: group numeric encoding tests with their opcodes.

---

cpuminer.go
mining.go
server.go

**This PR requires #1417 and #1418.**
Port of upstream commit 2274d36 (subset). In preparation of the
removal of chainState.

multi: remove chainState deps in server & cpuminer.

---

blockmanager.go
cpuminer.go
mining.go
server.go

**This PR requires #1417, #1418 and #1419.**
Port of upstream commit 2274d36 (subset).

blockmanager: remove block manager chain state.

---

blockmanager.go
cpuminer.go
mempool/mempool.go
mining.go
mining/mining.go
server.go

**This PR requires #1417, #1418, #1419 and #1420.**
Port of upstream commit a18f883.

multi: move MinHighPriority into mining package.

---

cpuminer.go
mining.go
rpcserver.go
server.go

**This PR requires #1417, #1418, #1419, #1420 and #1421**
Port of upstream commit 74fe2a4. In preparation of moving all
mining related code into the mining package.

multi: add BlkTmplGenerator.

---

README.md
docs/README.md

This revamps the main `README.md` file in an attempt to provide a more user-friendly introduction to the software and why someone would want to run it and also updates the `docs/README.md` to remove some sections that do not apply to Decred and update some others to reflect reality.
It also adds minimum recommended specifications for `dcrd` to the main `README.md` and updates the build instruction for module-aware builds and the recent changes the `run_test.sh` script.
Finally, it updates the contact information to point to the decred.org/community page.

docs: Revamp main README.md and update docs.

---

blockchain/agendas_test.go
dcrjson/walletsvrcmds.go
rpcserver.go
rpcserverhelp.go

This removes the handler for the `createrawssgen` RPC and deprecates the associated `dcrjson` structures.
This is being done because it doesn't make any sense for votes to be created over the RPC interface.  In order for voting on the previous block to have any semblance of relevance, the software producing the
vote clearly must have code to deserialize and understand the relevant data structures.

rpcserver: Remove createrawssgen RPC.

---

cpuminer.go
mining.go
rpcserver.go

This moves the `UpdateBlockTime` function to the recently introduced `BlkTmplGenerator` type in order to break its dependence on the block manager.

multi: Move update blk time to blk templ generator.

---

mempool/mempool.go

This removes the standardness check to reject transactions with a lock time greater than a maxint32 because the requirement for the check was due to legacy Bitcoin reasons that have never applied to Decred.

mempool: Remove potential negative locktime check.

---

blockchain/validate.go
mempool/mempool.go
mempool/mempool_test.go

**This relies on #1456.**
This removes a redundant check for validating that votes and revocations are not in a block before they are allowed from `CheckTransactionInputs` since it has nothing to do with validation of transaction inputs and it's an impossible condition to hit in the block validation path because the same check is done much earlier in the validation process.
It should also be noted that the checks this removes are also more permissive than they need to be because the first vote is not allowed until stake validation height, which is after stake enabled height. There is no effect on consensus because, as previously mentioned, the more restrictive checks earlier in the process prevent these checks from ever being exercised.
However, the `mempool` previously relied on this …

multi: No stake height checks in check tx inputs.

---

blockchain/validate.go

This separates all of the validation checks in `CheckTransactionInputs` related to each allowed type of stake transaction into separate functions dedicated to each type.
It also renames the utxo view parameter to `CheckTransactionInputs` to be consistent with the name used in other functions throughout the package.
It does not perform any additional cleanup beyond the separation and does not have any functional changes.

blockchain: Separate tx input stake checks.

---

blockchain/fullblocktests/generate.go
blockchain/validate.go

**This requires PR #1452**.
This moves the check for validating that output scripts in non-stake transactions do not contain any of the opcodes only allowed in the stake tree to the `CheckTransactionSanity` function where it more naturally belongs since it does not require access to transaction inputs as its location in `CheckTransactionInputs` would otherwise indicate.
It should be noted that the check just before the one being moved in this change is removed because it checked that specific patterns involving stake opcodes where not being used in non-stake transactions which is a strict subset of the more general check which ensures there are no stake opcodes at all in the output scripts.
Also, to improve efficiency, the check is added to the existing loop which already iterates the …

blockchain: Ensure no stake opcodes in tx sanity.

---

README.md

Fix obvious copy/paste error in readme.

[README] Use correct binary name

---

blockchain/accept.go
blockchain/validate.go

This moves the `IsFinalizedTransaction` function from `accept.go` to `validate.go` where it more naturally belongs as it is a validation function.  This is also evidenced by only being called from validation functions as well.

blockchain: Move finalized tx func to validation.

---

blockchain/accept.go
blockchain/validate.go

**This requires #1465**.
This moves the `checkCoinbaseUniqueHeight` function from `accept.go` to `validate.go` where it more naturally belongs as it is a validation function.  This is also evidenced by only being called from validation functions as well.

blockchain: Move unique coinbase func to validate.

---

go.mod
rpcclient/chain.go

This adds support for the getchaintips node RPC to rpcclient,
adding asynchronous and blocking functions to rpcclient.Client.

rpcclient: support getchaintips RPC

---

.gitignore
networkparams_test.go

Ensures address encoding magics and `params.NetworkAddressPrefix` are consistent with each other. This test will light red when a new network is started with incorrect values.
Also there is a minor fix of *pointers for two other tests in this file.

main: add address encoding magic constants test

---

.github/pull_request_template.md

This adds a pull request template which provides a checklist and links to the code contribution guidelines to help contributors ensure they are adhering to project standards.

docs: Add github pull request template.

---

blockchain/chaingen/generator.go

This modifies the test chain generator infrastructure that automatically tracks missed votes and generates revocations for them to only generate a single revocation and properly handle reorgs by removing revoked tickets from the pool of missed tickets when a block is connected and adding back any revoked tickets to the pool of missed tickets when a block that contains them is disconnected.
In addition, it modifies the handling of stake ticket purchases such that the associated ticket purchases are created after the munge functions run to ensure all changes are accurately account for.  In particular, the indexes of the ticket purchase transactions within the block can change if the munger adds or removes transactions before them.
This allows the large reorg tests to work as intended again.

chaingen: Only revoke missed tickets once.

---

blockchain/chaingen/generator.go
blockchain/chainio.go
blockchain/fullblocktests/generate.go

**This requires PR #1484**.
This adds some tests to ensure blocks that disapprove the regular transaction tree of the parent as follows:
- Attempt to spend an output from a disapproved tree in the block that disapproves it is rejected
- Reorg to a side chain that contains two consecutive blocks that disapprove their parents is accepted without error
- Reorg back to the original chain which causes the disapproving blocks to be removed is accepted without error
While here, it adds a new function named `AssertTipDisapprovesPrevious` which, as its name suggests, allows the caller to assert the vote bits in the header disapprove of the previous block.

chaingen/fullblocktests: Add disapproval tests.

---

run_tests.sh

This modifies the code in `run_tests.sh` which obtains the stripped list of modules to test based on the output of the go list command to work with MacOS as well.  It seems that `sed` on MacOS does not like the "or" regexp syntax, so this modifies it to perform each branch separately.

build: Support MacOS sed for obtaining module list.

---

dcrjson/walletsvrcmds.go
dcrjson/walletsvrresults.go

Required changes to implement BIP175 decred/dcrwallet#1132 into Decred.  Allows two new RPC methods (1) getcontracthashes and (2) getpaytocontractaddress.  This loose coupling allows users to grab just the contract(s) hash if needed and a contract P2PKH.

dcrjson: Add pay to contract hash support.

---

blockchain/chain.go
blockchain/thresholdstate.go
blockmanager.go
dcrjson/chainsvrresults.go
docs/json_rpc_api.md
rpcserver.go
rpcserverhelp.go

This resolves #1475.
Thanks to @davecgh for his help & @matheusd for testing/review.

multi: Add getblockchaininfo rpc.

---

blockchain/chain.go
blockchain/difficulty.go
blockchain/go.mod
blockchain/stakeversion_test.go
blockchain/thresholdstate.go
blockmanager.go
chaincfg/genesis.go
chaincfg/genesis_test.go
chaincfg/go.mod
chaincfg/init.go
chaincfg/params.go
chaincfg/premine.go
chaincfg/register_test.go
chaincfg/regnetparams.go
config.go
dcrutil/address.go
dcrutil/go.mod
dcrutil/wif_test.go
doc.go
go.mod
hdkeychain/extendedkey_test.go
hdkeychain/go.mod
networkparams_test.go
params.go
rpctest/rpc_harness.go
wire/doc.go
wire/protocol.go

This resurrects the regression test network that was removed before initial launch although it really should not have been.  The simulation test network and the regression test network do not serve the same purpose.  Specifically, the regression test network is intended for unit tests, RPC server tests, and consensus tests.  On the other hand, the simulation test network is intended for private use within a group of individuals doing simulation testing and full integration tests between different applications such as wallets, voting service providers, mining pools, block explorers, and other services that build on Decred.
Keeping the concerns separate will allow the simulation test network to be modified in ways such as activating consensus changes that have been successfully voted into …

multi: Resurrect regression network.
